### ISSUE TITLE
Support for the ‚lesser known countries’

### ISSUE THREAD

**Issue by TichyProgs** [SciTools/cartopy#1001]
Could I get borderlines for i.e. Poland’s ‚countys’? Where can I get list of the supported countries for that kind of features?  I’d like to make them visibl for a choropleth kinda map.

sorry if I’m asking about something that is in documentation. I guess I wasn’t able to find it

**Comment by pelson** [comment]
Hi @TichyProgs. 

Cartopy deals with shapefiles in a generic way. If you can point it at a shapefile with the information, cartopy can plot it on a map.

A quick google turns up the following:

 * https://www.eea.europa.eu/data-and-maps/data/eea-reference-grids-2/gis-files/poland-shapefile
 * https://www.citypopulation.de/Poland.html

Please note: I have no knowledge of these sites, and cannot guarantee their authenticity and/or correctness

Once you have the shapefiles, you should be able to do something like:

 * https://ocefpaf.github.io/python4oceanographers/blog/2015/02/02/cartopy_folium_shapefile/
 * https://modelingguru.nasa.gov/docs/DOC-2602
 * https://gis.stackexchange.com/questions/187867/cartopy-plotting-shapefiles

These kind of questions are probably best asked at StackOverflow (using the cartopy tag), this is inevitably a popular question to have about cartopy.

Hope this helps, and please do consider posting your solution as a Q & A on StackOverflow!

Thanks,

@pelson

**Comment by CGelo** [comment]
Hi @pelson,
thanks for the answer, that's exactly what I wanted to know/receive. In future I'd ask this kind of questions os stackoverflow as you propose I think but it's new for me to use packages that are still under active GitHub development if you know what I mean (i.e. matplotlib is already well established)

I'll try to find a suiting me solution in next few days and I'll post it as Q&A on SO as you asked me to do

Cheers,
@TichyProgs

**Comment by TichyProgs** [comment]
Hi @pelson,
thanks for the answer, that's exactly what I wanted to know/receive. In future I'd ask this kind of questions os stackoverflow as you propose I think but it's new for me to use packages that are still under active GitHub development if you know what I mean (i.e. matplotlib is already well established)

I'll try to find a suiting me solution in next few days and I'll post it as Q&A on SO as you asked me to do

Cheers,
@TichyProgs
