### ISSUE TITLE
Doc: add example of plt.subplots to the GeoAxes docs

### ISSUE THREAD

**Issue by pelson** [SciTools/cartopy#1005]
We show how to use ``plt.axes`` and ``plt.subplot``. We should also show how to use ``plt.subplots``.

**Comment by pelson** [comment]
Also, in that code, we should use ``plt`` not ``pyplot`` as the import name (and perhaps show it being imported if necessary).

**Comment by QuLogic** [comment]
> Also, in that code, we should use `plt` not `pyplot` as the import name (and perhaps show it being imported if necessary).

I don't see this anymore.

**Comment by dopplershift** [comment]
Removal of `pyplot.` in #1178 .

**Comment by acertainelijah** [comment]
Has there been an update with `plt.subplots`?

This will greatly assist in my py3 scripts updating Basemap to Cartopy.

**Comment by greglucas** [comment]
I think this issue was getting at the need to demonstrate that the keyword argument `subplot_kw` is required when using `plt.subplots`, which isn't listed in the docs anywhere.

```python
fig, ax = plt.subplots(subplot_kw={'projection': ccrs.PlateCarree()})
```
