### ISSUE TITLE
Doc: gallery code links don't need to be underlined

### ISSUE THREAD

**Issue by pelson** [SciTools/cartopy#1006]
As an example, https://2-5282596-gh.circle-artifacts.com/0/root/project/docs/build/html/gallery/miscellanea/star_shaped_boundary.html#sphx-glr-gallery-miscellanea-star-shaped-boundary-py has all of the functions that have links underlined. This adds visual noise that distracts from the message.

We want to keep the links, but define the CSS to avoid the underlining.

**Comment by dopplershift** [comment]
We fixed this in MetPy by putting `theme_override.css` in `docs/_static`:

https://github.com/Unidata/MetPy/blob/d66e868e10cb74dfa397f012849f0c6aa01a6416/docs/_static/theme_override.css#L1-L8

It's not pretty, but it's better than the underline.

**Comment by pelson** [comment]
The following will do the trick.

```
+pre a {
+    // Prevent code examples showing underlines.
+    text-decoration: none !important;
+}
+
```


I'll make a PR with it later on.
