### ISSUE TITLE
Unknown exception on ax.set_extent

### ISSUE THREAD

**Issue by julietbravo** [SciTools/cartopy#1012]
If I run the code attached below, it crashes on the `ax.set_extent()` line with the following error:

**Error:**

    Unknown exception thrown
    Unknown exception thrown
    Unknown exception thrown
    Unknown exception thrown
    Unknown exception thrown
    Unknown exception thrown
    Unknown exception thrown
    Unknown exception thrown
    Invalid argument (must be a Polygon)
    Geometry must be a Point or LineString
    Assertion failed: (0 != cs), function GEOSCoordSeq_getSize_r, file geos_ts_c.cpp, line 3991.
    Abort trap: 6

**Code:**

    import matplotlib.pylab as pl
    import cartopy
    import cartopy.crs as ccrs
    
    projection = ccrs.LambertConformal(central_longitude=4.9, central_latitude=52)
    ax = pl.subplot(111, projection=projection)
    ax.set_extent([-8, 17, 42, 60], ccrs.PlateCarree())

**System:**
Python 3.6.3 (on Mac OS 10.12), Cartopy 0.15.1 (from Homebrew), GEOS 3.6.2

**Comment by dopplershift** [comment]
How did you install CartoPy? How is shapely installed?

**Comment by julietbravo** [comment]
After finding this: https://github.com/SciTools/cartopy/issues/738, I tried:

    pip3 uninstall shapely
    pip3 uninstall cartopy
    pip3 install shapely cartopy --no-binary shapely --no-binary cartopy

Which also works for me.

**Comment by dopplershift** [comment]
I kinda figured it was something like that. Closing in favor of one of the many other bugs related to conflicts between Shapely/GEOS.
