### ISSUE TITLE
Day/night terminator

### ISSUE THREAD

**Issue by ctjacobs** [SciTools/cartopy#1038]
It would be nice to have a day/night terminator available in Cartopy, like the one in Basemap: https://github.com/matplotlib/basemap/blob/master/examples/daynight.py

Are there any plans to port this across?

**Comment by QuLogic** [comment]
It's not builtin, but there's an example of how to do it in [the Aurora example](http://scitools.org.uk/cartopy/docs/latest/gallery/aurora_forecast.html).

**Comment by ctjacobs** [comment]
Thank you, that's very helpful.
