### ISSUE TITLE
Displaying tiles in gray scale

### ISSUE THREAD

**Issue by stefanomattia** [SciTools/cartopy#1046]
### Description
I'm trying to display tiles via Cartopy's img_tiles module in gray scale. That's because I would like to overlay color-coded satellite data and I would prefer a background as little distracting as possible.

The various tiles providers as documented in the source code allow the use of a desired_tile_form during initialization. The documentation is not entirely clear about the possible values one could assign to that parameter (only "RGB" is mentioned), but digging a bit in the code I see that it is passed to img.convert, which is a PIL.image method.

Now the PIL documentation says:

> The current version supports all possible conversions between “L”, “RGB” and “CMYK.” The matrix argument only supports “L” and “RGB”.
> 
> When translating a color image to black and white (mode “L”), the library uses the ITU-R 601-2 luma transform: [...]

So it would appear that using the "L" mode would turn the image in black and white, however that doesn't really seem to work in my case. It's more of a green-tinted gray-scale conversion instead.

#### Code to reproduce

```
import matplotlib.pyplot as plt    
import cartopy.crs as ccrs
import cartopy.io.img_tiles as cimgt

# standard RGB
figure, ax = plt.subplots(figsize=(15, 10))
request = cimgt.StamenTerrain()
ax = plt.axes(projection=request.crs)
ax.set_extent([94, 102, 0, 6])
ax.add_image(request, 8)
plt.show()

# (not working) black and white
figure, ax = plt.subplots(figsize=(15, 10))
request = cimgt.StamenTerrain(desired_tile_form="L")
ax = plt.axes(projection=request.crs)
ax.set_extent([94, 102, 0, 6])
ax.add_image(request, 8)
plt.show()
```
(see [original](https://i.stack.imgur.com/8KZIb.png_) and ["converted"](https://i.stack.imgur.com/uIPZi.png) images)

Digging into the matplotlib documentation, the issue might be related to the colormap (or lack thereof) used.

In fact, when I try to display my images inline in a Jupyter notebook, the following commands behave differently:
```
# shows a green-tinted gray scale converted image, just like using desired_tile_form="L" with cartopy
imshow(np.asarray(img.convert('L')))

# shows a gray scale image (desired output)
imshow(np.asarray(img.convert('L')), cmap=cm.Greys_r)
```

Is there a way to sneak `cmap=cm.Greys_r` in somewhere?
<details>
 <summary>Full environment definition</summary>

### Operating system
MacOS 10.13.3

### Cartopy version
0.16.0

### conda list
# packages in environment at /Users/stefano/anaconda3:
#
# Name                    Version                   Build  Channel
_license                  1.1                      py36_1
alabaster                 0.7.10                   py36_0
anaconda                  custom           py36ha4fed55_0
anaconda-client           1.6.3                    py36_0
anaconda-navigator        1.6.2                    py36_0
anaconda-project          0.6.0                    py36_0
appnope                   0.1.0                    py36_0
appscript                 1.0.1                    py36_0
asn1crypto                0.22.0                   py36_0
astroid                   1.4.9                    py36_0
astropy                   1.3.2               np112py36_0
autopep8                  1.3.2                     <pip>
babel                     2.4.0                    py36_0
backports                 1.0                      py36_0
beautifulsoup4            4.6.0                    py36_0
bitarray                  0.8.1                    py36_0
blaze                     0.10.1                   py36_0
bleach                    1.5.0                    py36_0
bokeh                     0.12.5                   py36_1
boto                      2.46.1                   py36_0
bottleneck                1.2.1               np112py36_0
ca-certificates           2017.08.26           ha1e5d58_0
cartopy                   0.16.0           py36he7b4726_0
certifi                   2018.1.18                py36_0
cffi                      1.10.0                   py36_0
chardet                   3.0.3                    py36_0
click                     6.7                      py36_0
cloudpickle               0.2.2                    py36_0
clyent                    1.2.2                    py36_0
colorama                  0.3.9                    py36_0
colorlover                0.2.1                     <pip>
conda                     4.4.11                   py36_0
conda-env                 2.6.0                h36134e3_0
contextlib2               0.5.5                    py36_0
cryptography              1.8.1                    py36_0
cufflinks                 0.12.1                    <pip>
curl                      7.49.0                        1
cycler                    0.10.0                   py36_0
cython                    0.25.2                   py36_0
cytoolz                   0.8.2                    py36_0
dask                      0.14.3                   py36_1
datashape                 0.5.4                    py36_0
decorator                 4.0.11                   py36_0
distributed               1.16.3                   py36_0
docutils                  0.13.1                   py36_0
entrypoints               0.2.2                    py36_1
et_xmlfile                1.0.1                    py36_0
fastcache                 1.0.2                    py36_1
flask                     0.12.2                   py36_0
flask-cors                3.0.2                    py36_0
freetype                  2.5.5                         2
geos                      3.6.2                h5470d99_2
get_terminal_size         1.0.0                    py36_0
gevent                    1.2.1                    py36_0
greenlet                  0.4.12                   py36_0
h5py                      2.7.0               np112py36_0
hdf4                      4.2.12                        1
hdf5                      1.8.17                        1
heapdict                  1.0.0                    py36_1
html5lib                  0.999                    py36_0
icu                       54.1                          0
idna                      2.5                      py36_0
imagesize                 0.7.1                    py36_0
ipykernel                 4.6.1                    py36_0
ipython                   5.3.0                    py36_0
ipython_genutils          0.2.0                    py36_0
ipywidgets                6.0.0                    py36_0
isort                     4.2.5                    py36_0
itsdangerous              0.24                     py36_0
jbig                      2.1                           0
jdcal                     1.3                      py36_0
jedi                      0.10.2                   py36_2
jinja2                    2.9.6                    py36_0
jpeg                      9b                            0
jsonschema                2.6.0                    py36_0
jupyter                   1.0.0                    py36_3
jupyter_client            5.0.1                    py36_0
jupyter_console           5.1.0                    py36_0
jupyter_core              4.3.0                    py36_0
lazy-object-proxy         1.2.2                    py36_0
libcxx                    4.0.1                h579ed51_0
libcxxabi                 4.0.1                hebd6815_0
libiconv                  1.14                          0
libnetcdf                 4.4.1                         1
libpng                    1.6.27                        0
libtiff                   4.0.6                         3
libxml2                   2.9.4                         0
libxslt                   1.1.29                        0
llvmlite                  0.18.0                   py36_0
locket                    0.2.0                    py36_1
logzero                   1.3.1                     <pip>
lxml                      3.7.3                    py36_0
markupsafe                0.23                     py36_2
matplotlib                2.0.2               np112py36_0
mistune                   0.7.4                    py36_0
mkl                       2017.0.1                      0
mkl-service               1.1.2                    py36_3
mpmath                    0.19                     py36_1
msgpack-python            0.4.8                    py36_0
multipledispatch          0.4.9                    py36_0
navigator-updater         0.1.0                    py36_0
nbconvert                 5.1.1                    py36_0
nbformat                  4.3.0                    py36_0
netcdf4                   1.2.4               np112py36_1
networkx                  1.11                     py36_0
nltk                      3.2.3                    py36_0
nose                      1.3.7                    py36_1
notebook                  5.0.0                    py36_0
numba                     0.33.0              np112py36_0
numexpr                   2.6.2               np112py36_0
numpy                     1.12.1                   py36_0
numpydoc                  0.6.0                    py36_0
odo                       0.5.0                    py36_1
olefile                   0.44                     py36_0
openpyxl                  2.4.7                    py36_0
openssl                   1.0.2n               hdbc3d79_0
owslib                    0.15.0           py36hf35f654_0
packaging                 16.8                     py36_0
pandas                    0.20.1              np112py36_0
pandocfilters             1.4.1                    py36_0
partd                     0.3.8                    py36_0
path.py                   10.3.1                   py36_0
pathlib2                  2.2.1                    py36_0
patsy                     0.4.1                    py36_0
pep8                      1.7.0                    py36_0
pexpect                   4.2.1                    py36_0
pickleshare               0.7.4                    py36_0
pillow                    4.1.1                    py36_0
pip                       9.0.1                    py36_1
plotly                    2.0.11                   py36_0
ply                       3.10                     py36_0
proj4                     4.9.3                h3f1bf9d_7
prompt_toolkit            1.0.14                   py36_0
psutil                    5.2.2                    py36_0
ptyprocess                0.5.1                    py36_0
py                        1.4.33                   py36_0
pycodestyle               2.3.1                     <pip>
pycosat                   0.6.3            py36hee92d8f_0
pycparser                 2.17                     py36_0
pycrypto                  2.6.1                    py36_6
pyepsg                    0.3.2            py36hba2fa79_0
pyflakes                  1.5.0                    py36_0
pygments                  2.2.0                    py36_0
pylint                    1.6.4                    py36_1
pyodbc                    4.0.16                   py36_0
pyopenssl                 17.0.0                   py36_0
pyparsing                 2.1.4                    py36_0
pyproj                    1.9.5.1                  py36_0
pyqt                      5.6.0                    py36_1
pyshp                     1.2.12           py36h78922a7_0
pytables                  3.3.0               np112py36_0
pytest                    3.0.7                    py36_0
python                    3.6.1                         2
python-dateutil           2.6.0                    py36_0
python.app                1.2                      py36_4
pytz                      2017.2                   py36_0
pywavelets                0.5.2               np112py36_0
pyyaml                    3.12                     py36_0
pyzmq                     16.0.2                   py36_0
qt                        5.6.2                         2
qtawesome                 0.4.4                    py36_0
qtconsole                 4.3.0                    py36_0
qtpy                      1.2.1                    py36_0
readline                  6.2                           2
requests                  2.14.2                   py36_0
rope                      0.9.4                    py36_1
ruamel_yaml               0.11.14                  py36_1
scikit-image              0.13.0              np112py36_0
scikit-learn              0.18.1              np112py36_1
scipy                     0.19.0              np112py36_0
seaborn                   0.8.1            py36h595ecd9_0
setuptools                38.4.0                   py36_0
shapely                   1.6.2            py36hed20685_0
simplegeneric             0.8.1                    py36_1
singledispatch            3.4.0.3                  py36_0
sip                       4.18                     py36_0
six                       1.10.0                   py36_0
snowballstemmer           1.2.1                    py36_0
sortedcollections         0.5.3                    py36_0
sortedcontainers          1.5.7                    py36_0
sphinx                    1.5.6                    py36_0
spyder                    3.1.4                    py36_0
sqlalchemy                1.1.9                    py36_0
sqlite                    3.13.0                        0
statsmodels               0.8.0               np112py36_0
sympy                     1.0                      py36_0
tblib                     1.3.2                    py36_0
terminado                 0.6                      py36_0
testpath                  0.3                      py36_0
tk                        8.5.18                        0
toolz                     0.8.2                    py36_0
tornado                   4.5.1                    py36_0
traitlets                 4.3.2                    py36_0
unicodecsv                0.14.1                   py36_0
unixodbc                  2.3.4                         0
wcwidth                   0.1.7                    py36_0
werkzeug                  0.12.2                   py36_0
wheel                     0.29.0                   py36_0
widgetsnbextension        2.0.0                    py36_0
wrapt                     1.10.10                  py36_0
xarray                    0.10.0           py36h9a76c0b_0
xlrd                      1.0.0                    py36_0
xlsxwriter                0.9.6                    py36_0
xlwings                   0.10.4                   py36_0
xlwt                      1.2.0                    py36_0
xz                        5.2.2                         1
yaml                      0.1.6                         0
zict                      0.1.2                    py36_0
zlib                      1.2.8                         3

```
```

### pip list

```
```

</details>

**Comment by stefanomattia** [comment]
It turns out there is indeed an easy way to pass the right cmap, directly into the `add_image` method, e.g.:
```
ax.add_image(request, 8, cmap='gray')
```
I will therefore close this issue, as I think it's only indirectly related to Cartopy.

**Comment by IGOR-06** [comment]
I tried with cmap and I was not allowed by add_image not to include cmap
