### ISSUE TITLE
EPSG:3857 CRS Mistmatch with WMTS Definition

### ISSUE THREAD

**Issue by acrosby** [SciTools/cartopy#1049]
### Description

I have a requirement to use a commercial WMTS as a basemap for some plots. I get the following mismatch with projections below, but technically it seems like it should be supported but there is a projection description syntax issue. Is there a quick and dirty way to get this to work? (I can't share the WMTS endpoint, but the error should be descriptive enough..., and unfortunately this code has to run on windows using an Anaconda install)

#### Code to reproduce

```python
import cartopy.crs as ccrs
from owslib.wmts import WebMapTileService
ax = plt.subpot(projection=ccrs.epsg('3857'))
ax.add_wmts(WebMapTileService(server),  layer_name="World_Imagery")
```

#### Traceback 

```python
    ax.add_wmts(server, layer_name="World_Imagery")
  File "C:\Users\user\AppData\Local\Continuum\Anaconda\lib\site-packages\cartopy\mpl\geoaxes.py", line 1879, in add_wmts
    return self.add_raster(wmts, **kwargs)
  File "C:\Users\user\AppData\Local\Continuum\Anaconda\lib\site-packages\cartopy\mpl\geoaxes.py", line 991, in add_raster
    raster_source.validate_projection(self.projection)
  File "C:\Users\user\AppData\Local\Continuum\Anaconda\lib\site-packages\cartopy\io\ogc_clients.py", line 436, in validate_projection
    self._matrix_set_name(projection)
  File "C:\Users\user\AppData\Local\Continuum\Anaconda\lib\site-packages\cartopy\io\ogc_clients.py", line 431, in _matrix_set_name
    raise ValueError(msg)
ValueError: Unable to find tile matrix for projection.
    Projection: _EPSGProjection(3857)
    Available tile CRS URNs:
        urn:ogc:def:crs:EPSG:6.18:3:3857
```

<details>
 <summary>Full environment definition</summary>

### Operating system
Win 7

### Cartopy version
Cartopy==0.15.0
OWSLib==0.16.0

</details>

**Comment by acrosby** [comment]
If I monkey patch like this, I get an error much further down in owslib in `buildTileResource`, which may be an issue with the service itself (although it works in QGIS). Is this reasonable? Is there something else I might need to change?

```python
import cartopy.io.ogc_clients as ogcc
ogcc._URN_TO_CRS['urn:ogc:def:crs:EPSG:6.18:3:3857'] = crs.GOOGLE_MERCATOR
ogcc.METERS_PER_UNIT['urn:ogc:def:crs:EPSG:6.18:3:3857'] = 1
```

**Comment by acrosby** [comment]
@pelson Is this something you can look into, or should I bang away and try to get something running and submit a PR?

**Comment by pelson** [comment]
> @pelson Is this something you can look into, or should I bang away and try to get something running and submit a PR?

I'm really glad you've been able to get your teeth into the code. It could really do with extra eyes 👀, and looks like there have been 2 positive PRs come out of it. 👍

**Comment by acrosby** [comment]
I'm going to close this since the PR has been merged. Feel free to open in the future.

**Comment by raphaelquast** [comment]
@acrosby

Hello,

I'm currently trying to do a very similar thing than you did last year... I want to add a wmts-layer with epsg 3857 in a windows-anaconda environment...
I'm using `cartopy v.0.17.0` (so all changes in here are already included) but it's still failing with the same error... i.e.:

Do you have any idea how I could get it running?
Thanks!

```python
import matplotlib.pyplot as plt
from owslib.wmts import WebMapTileService

URL = 'https://www.basemap.at/wmts/1.0.0/WMTSCapabilities.xml'
layer = 'geolandbasemap'
wmts = WebMapTileService(URL)

ax = plt.subplot(projection=ccrs.epsg('3857'))
ax.add_wmts(wmts, layer)

>>> ValueError: Unable to find tile matrix for projection.
    Projection: _EPSGProjection(3857)
    Available tile CRS URNs:
        urn:ogc:def:crs:EPSG:6.18.3:3857
```

**Comment by raphaelquast** [comment]
... found it :-)     #1313

**Comment by xpbliss** [comment]
solve it?
