### ISSUE TITLE
contourf with add_image (tiles) does not work

### ISSUE THREAD

**Issue by gnlynx** [SciTools/cartopy#1058]
### Description
I would like to put tilers from Stamen as a background of my map, and put on it some data using contourf function. To add tilers I used:
```
from cartopy.io.img_tiles import StamenTerrain
tiler = StamenTerrain(desired_tile_form='RGBA')
self.ax.add_image(tiler, 10, interpolation='bicubic', zorder=1)
```
after that I would like to add contourf plot but... the script hangs after running.
If I do it in reverse order (first contourf function and then add_image) than script is running correctly but only contourf is drawn, without tiles.  
Interestingly, add_image function works fine without contourf. 

Do you have any idea how to resolve this problem?
Thanks,

<details>
 <summary>Full environment definition</summary>

### Operating system
Unix

### Cartopy version
0.15

</details>

**Comment by gnlynx** [comment]
I solved the problem.  
I missed set_extent before add_image. However, it only works if the order is as follows:  
set_extent,  
add_image,  
contourf.  
If add_image is after contourf only contourf plot is visible.

**Comment by pelson** [comment]
Thanks for the update.

zorder should be all that is needed. There is no fundamental assumption in cartopy that contours are above images.
