### ISSUE TITLE
Missing ISO_A3 codes

### ISSUE THREAD

**Issue by TizianoGC** [SciTools/cartopy#1059]
Hi,
I'm using the natural_earth shapefile in Cartopy 0.16.0.
I noticed that certain countries (ATC, CYN, FRA, IOA, KAS, KOS, NOR, SOL) have "-99" instead of the corresponding ISO Alpha-3 code.
Are you planning to solve this bug any time soon?

Thanks!

**Comment by QuLogic** [comment]
Cartopy does not ship any Natural Earth shapefiles directly. You should report any problems to [the Natural Earth people](http://www.naturalearthdata.com/) on [their GitHub](https://github.com/nvkelso/natural-earth-vector) (there seem to be many existing issues discussing ISO codes.)
