### ISSUE TITLE
Bounding limit in polar stereographic plots

### ISSUE THREAD

**Issue by ajheaps** [SciTools/cartopy#1065]
### Description
Is there a way to set a bounding limit in polar stereographic plots so that the plot is circular rather than square?  

It's important for clarity of presentation that we see only the hemisphere we are interested in and not parts of the other hemisphere which are distracting. The call I currently make in Basemap uses the boundinglat attribute to set this but I cannot see an equivalent in Cartopy. 

The round plots I'd like to achieve in Cartopy are shown on the cf-plot web page http://ajheaps.github.io/cf-plot/polar.html

#### Code to reproduce

```
import matplotlib.pyplot as plt
import cartopy.crs as ccrs

plt.figure(figsize=(3, 3))
ax = plt.axes(projection=ccrs.NorthPolarStereo())
ax.set_extent((-180, 180, 0, 90), crs=ccrs.PlateCarree())

ax.coastlines(resolution='110m')
ax.gridlines()

plt.show()

```

<details>
 <summary>Full environment definition</summary>

### Cartopy version 0.16

</details>

**Comment by ajdawson** [comment]
Like this example in the cartopy documentation?
 http://scitools.org.uk/cartopy/docs/latest/gallery/always_circular_stereo.html#custom-boundary-shape

**Comment by ajheaps** [comment]
Yes, exactly that.  Thank-you!
I'd spent an hour looking around but had missed the all important gallery page...
