### ISSUE TITLE
Remove "future np.array_split will retain the shape of arrays" type warnings

### ISSUE THREAD

**Issue by pelson** [SciTools/cartopy#1067]
### Description
Lots of numpy warnings about ``array_split``. Let's fix the behaviour.

```
  /home/travis/miniconda/envs/test-environment/lib/python3.5/site-packages/numpy/lib/shape_base.py:431: FutureWarning: in the future np.array_split will retain the shape of arrays with a zero size, instead of replacing them by `array([])`, which always has a shape of (0,).

```

#### Code to reproduce

The cartopy unit-tests. See example output at: https://travis-ci.org/SciTools/cartopy/jobs/374947492

**Comment by QuLogic** [comment]
I think this must be something in our dependencies. I don't see the warning on the Latest builds.
