### ISSUE TITLE
The width and height of the map in the projection unit.

### ISSUE THREAD

**Issue by ahmedshaaban1** [SciTools/cartopy#1074]
### Description

Basemap has a width and height arguments in the basemap function [http://basemaptutorial.readthedocs.io/en/latest/basemap.html](url) that control the height and width of the map in the projection unit. Based on my knowledge there are no similar capabilities in Cartopy. 
I am suggesting adding such feature to the Cartopy. 

I already asked a question on StackOverflow about this issue and people suggest changing the projection might change the enlarge the image [https://stackoverflow.com/questions/50311704/cartopy-width-and-height](url)

#### Code to reproduce

```

```

#### Traceback 

```

```

<details>
 <summary>Full environment definition</summary>

### conda list

```
```

### pip list

```
```

</details>

**Comment by ahmedshaaban1** [comment]
Can you enlarge that image without changing ax.set_extent().

**Comment by dopplershift** [comment]
Use `fig = plt.figure(figsize=(fig_width_inches, fig_height_inches))`

**Comment by ahmedshaaban1** [comment]
Thanks, but this will increase the white space only around the map without increasing the figures itself.  See (https://stackoverflow.com/questions/50311704/cartopy-width-and-height).

**Comment by dopplershift** [comment]
That’s not correct:

![3e29ccaa-194b-452f-9c8b-11c852c71d20](https://user-images.githubusercontent.com/221526/40580296-d895b07a-60f8-11e8-83df-835ae5cd3130.png)

Now, what might be confusing is that CartoPy will ensure that the aspect ratio (the ratio of height and width) of the axis will match the aspect ratio of the extent of the plot (i.e. it makes sure 1 kilometer in y is the same size as 1 kilometer in x, in projected space). If you create a figure with a size that does not have the proper aspect ratio, you will end up with extra white space. But I can say with complete certainty that setting `figsize` is not just adding unused white space; I use it all the time to make bigger images.

**Comment by ahmedshaaban1** [comment]
Thanks alot, you answer inspired me with one way to enlarge maps that is really difficult to enlarge. For example, I tried a lot to enlarge tropical channel maps as the following (8000x2000) with dpi=100: 
![test](https://user-images.githubusercontent.com/15742456/40596998-a2683b2a-620c-11e8-846d-e90d0b25d1fa.png)

Yet, the major problem is that the figure size is needed to exceed the screen size if we really need to enlarge the figure so as to keep the scale ratio correct. Yet, upon saving the figure, Matplotlib save what is already exposed on the screen. If the figure is rendered on the screen, then it cannot exceed the size of the screen, so whatever the size is, it cannot exceed the monitor size.  To overcome that, I added the following few lines to cancel showing an image so that savefig is able to save the figure with the actual given size. 
```python 
import matplotlib    
matplotlib.use('agg')
plt.ioff()
```
Here is the complete code
```python 
import cartopy.crs as ccrs 
import cartopy.feature as cfeature
import matplotlib.pyplot as plt

import matplotlib
matplotlib.use('agg')
plt.ioff()

def main():
    fig = plt.figure(figsize=(20*4,5*4))
  #  ax = fig.add_subplot(1, 1, 1, projection=ccrs.Mercator())
    ax = fig.add_subplot(1, 1, 1, projection=ccrs.LambertCylindrical())

    ax.set_extent([-180, 180, -20, 20],crs=ccrs.LambertCylindrical())

    ax.add_feature(cfeature.LAND)
    ax.add_feature(cfeature.OCEAN)
    ax.add_feature(cfeature.COASTLINE)
    ax.add_feature(cfeature.BORDERS, linestyle=':')
    ax.add_feature(cfeature.LAKES, alpha=0.5)
    ax.add_feature(cfeature.RIVERS)
    plt.savefig('test.png',dpi=100)
    
if __name__ == '__main__':
    main()
```

Thanks for your help and ideas.

**Comment by pelson** [comment]
Looks like this got resolved. Thanks for the question @ahmedshaaban1  and thanks to @dopplershift for the really valuable response.

There is definitely room for improvement here - for example, it would be great to be able to specify only one of width / height and to get the non-defined metric to be maximised given the space that the Axes can consume. Recent developments in matplotlib might make doing this easier (the geometry manager springs to mind).

I'd be super interested if anybody plays with this, but for now, looks like the question is resolved, so I'll close the issue.

Thanks again to both of you!
