### ISSUE TITLE
cannot remove margins

### ISSUE THREAD

**Issue by nschiraldi** [SciTools/cartopy#1079]
### Description

It appears that you cannot completely remove the margin from a cartopy figure, which causes issues when trying to overlay .png in leaflet. Unless, GOOGLE_MERCATOR isn't truly EPSG:3857?

In a perfect world, my leaflet overlay boundary would == set_extent of the cartopy figure, by stripping all margins. 

Is there a better way to strip all margins from the figure, to ensure the figure bbox is aligned with the input extent?

This is how I'm generating the maps
#### Code to reproduce

```
import matplotlib
matplotlib.use('Agg')

import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import cartopy.feature as cfeature


fig = plt.figure()
ax = plt.axes(projection = ccrs.GOOGLE_MERCATOR)

# set extent
ax.set_extent([-80,-71.5,40,45.5], crs=ccrs.PlateCarree())

# make transparent 
ax.outline_patch.set_visible(False)
ax.background_patch.set_visible(False)

# no margin through axes
ax.set_xmargin(0)
ax.set_ymargin(0)

# contour some data on the map

# no margin with bbox_inches=0
plt.savefig('/home/nschiraldi/public_html/test.png',pad_inches=0,bbox_inches = 'tight')

```

Some relevant information on the leaflet initialization:
```
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.1/dist/leaflet.css"
    integrity="sha512-Rksm5RenBEKSKFjgI3a41vrjkw4EVPlJ3+OiI65vTjIdo9brlAacEuKOiQ5OFh7cOI1bkDwLqdLw3Zg0cRJAAQ=="
    crossorigin=""/>
    <script src="https://unpkg.com/leaflet@1.3.1/dist/leaflet.js"
      integrity="sha512-/Nsx9X4HebavoBvEBuyp3I7od5tA0UzAxs+j83KgC8PU0kgB4XiK4Lfe4y4cgBtaRJQEIFCW+oC506aPT2L1zw=="
      crossorigin=""> </script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet-ajax/2.1.0/leaflet.ajax.min.js"></script>

<script>
var map = L.map(
       'mapid',
       {minZoom: 7, maxZoom: 10, maxBounds: [[39.58,-80.022],[45.875,-71.47]],
       crs: L.CRS.EPSG3857}
     );
L.imageOverlay(
       'test.png',
       [[40,-80],[45,-71.5]],
     ).addTo(map);
</script>
```

And the final data does not line up. 
![cartopy_overlay](https://user-images.githubusercontent.com/8190840/41557219-ef6e793e-730a-11e8-89f4-335855a18d4b.PNG)

### Cartopy version
'0.16.0'

>>> print(matplotlib.__version__)
2.2.2
>>> print(cartopy.__version__)
0.16.0
>>> print(cartopy.crs.PROJ4_VERSION)
(4, 9, 3)
</details>

**Comment by QuLogic** [comment]
Please provide a self-contained, _complete_ example. I tried to run this but just got a blank plot (because there's no plotting commands).

**Comment by nschiraldi** [comment]
Sorry about that, this example seems to be trimming the border appropriately. That is, I would expect the edge of the figure to be the rectangle, once the margin is removed.  So this likely rules out that I'm experiencing a margin issue, and more likely to be a GOOGLE_MERCATOR CRS issue, or simply just a leaflet misuse. 


import matplotlib
matplotlib.use('Agg')

import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import cartopy.feature as cfeature

from matplotlib.patches import Polygon


# -- remove margins -- #
fig = plt.figure()
ax = plt.axes(projection = ccrs.GOOGLE_MERCATOR)

# set extent
ax.set_extent([-80,-71.5,40,45.5], crs=ccrs.PlateCarree())

# make transparent 
ax.outline_patch.set_visible(False)
ax.background_patch.set_visible(False)

# no margin through axes
ax.set_xmargin(0)
ax.set_ymargin(0)

# vertices 
x1,y1 = (-80,40)
x2,y2 = (-80,45.5)
x3,y3 = (-71.5,45.5)
x4,y4 = (-71.5,40)

# add rectangle
poly = Polygon([(x1,y1),(x2,y2),(x3,y3),(x4,y4)],
    facecolor='w',
    edgecolor='black',linewidth=1,
    transform = ccrs.PlateCarree(),
    alpha = 0.9)
plt.gca().add_patch(poly)
         
# no margin with bbox_inches=0
plt.savefig('no_margin.png',pad_inches=0,bbox_inches = 'tight')

#-- leave margin --#
fig = plt.figure()
ax = plt.axes(projection = ccrs.GOOGLE_MERCATOR)

# set extent
ax.set_extent([-80,-71.5,40,45.5], crs=ccrs.PlateCarree())

# make transparent 
ax.outline_patch.set_visible(False)
ax.background_patch.set_visible(False)

# vertices 
x1,y1 = (-80,40)
x2,y2 = (-80,45.5)
x3,y3 = (-71.5,45.5)
x4,y4 = (-71.5,40)

# add rectangle
poly = Polygon([(x1,y1),(x2,y2),(x3,y3),(x4,y4)],
    facecolor='w',
    edgecolor='black',linewidth=1,
    transform = ccrs.PlateCarree(),
    alpha = 0.9)
plt.gca().add_patch(poly)
plt.savefig('with_margin.png')
