### ISSUE TITLE
Installation with coastlines

### ISSUE THREAD

**Issue by jvegasbsc** [SciTools/cartopy#1082]
We are having troubles working with cartopy in a cluster that do not allow external internet connections, thus cartopy is not able to download the coastlines. I looked for a way to install it with the coastlines already available in local but did not found anything in the installation guide

Is this possible at all?

cc @schlunma

**Comment by pelson** [comment]
You can download sets of data from various sources using the [tools/feature_download.py](https://github.com/SciTools/cartopy/blob/master/tools/feature_download.py) found in the root of the repository.

**Comment by jvegasbsc** [comment]
Thanks!

**Comment by pelson** [comment]
👍
