### ISSUE TITLE
WMS 1.3.0 support ? 

### ISSUE THREAD

**Issue by psychicLocust** [SciTools/cartopy#1085]
### Description

I'm trying to display some WMS layer (via ax.ad_wms(...)) from a WMS 1.3.0 only server. 
I've made a quick and dirty patch at `line 238` of `ogc_clients.py` based on the fact that apparently OWSlib now supports WMS 1.3.0

> service = WebMapService(service **,version='1.3.0'** )

Would it possible to include some sort of negociation (like [here](https://github.com/cga-harvard/Hypermap-Registry/blob/master/hypermap/aggregator/utils.py#L415-L426)) in order for cartopy to support WMS 1.1.0 and WMS 1.3.0 ?

Thanks in advance 

### Cartopy version

0.16.0

**Comment by pelson** [comment]
So it is possible to do this without needing to hack cartopy it seems.

```
from owslib.wms import WebMapService
service = WebMapService(url, version='1.3.0')
ax.add_wms(service)
```

I haven't tested this, but it appears to me that the hooks are all there and reasonably documented (https://scitools.org.uk/cartopy/docs/latest/cartopy/io/ogc_clients.html#cartopy.io.ogc_clients.WMSRasterSource and https://scitools.org.uk/cartopy/docs/latest/matplotlib/geoaxes.html?highlight=add_wms#cartopy.mpl.geoaxes.GeoAxes.add_wms).

I guess the thing that isn't clear is whether we should do anything else in this regard. If you have any proposals for improving the interface, I'd be very happy to discuss them over a straw-man PR (or here).
