### ISSUE TITLE
SegFault for initializing cartopy crs for Southern Hemisphere LambertAzimuthalEqualArea

### ISSUE THREAD

**Issue by mjbrodzik** [SciTools/cartopy#1099]
### Description
Hello, I am trying to initialize a LambertAzimuthalEqualArea centered at the South Pole, but this generates a SegFault and crashes python.

I get this error on Mac OS X (High Sierra, 10.13.5) and Mac OS X (Sierra, 10.12.6).

I believe this may be only be a problem for the Southern hemisphere exactly at the South Pole, because it works correctly if I set it to the North Pole (central_latitude=90.0), and does not seg fault of I try other latitudes in the Southern Hemisphere besides the Pole.

#### Code to reproduce

```
(cartopy) $ python
Python 3.6.5 | packaged by conda-forge | (default, Apr  6 2018, 13:44:09) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cartopy.crs as ccrs
>>> e2s = ccrs.LambertAzimuthalEqualArea(central_latitude=-90.0)
IllegalArgumentException: Points of LinearRing do not form a closed linestring
Segmentation fault: 11
$ 
```

<details>
 <summary>Full environment definition</summary>

### Operating system
Mac OS X  

### Cartopy version
cartopy                   0.16.0                   py36_0    conda-forge

### conda list

```
I am attaching output from my conda list command.  I've made a fresh conda env using the environment recommended at the recent SciPy2018 tutorial.
[cartopy_env.txt](https://github.com/SciTools/cartopy/files/2246495/cartopy_env.txt)


```

</details>

**Comment by ajdawson** [comment]
Thanks for the report @mjbrodzik, this looks like a problem in the projection class when it defines the boundary, a bug fix will be necessary (see #1100).
