### ISSUE TITLE
xtick labels not respecting central_longitude for PlateCarree()

### ISSUE THREAD

**Issue by erikvansebille** [SciTools/cartopy#1106]
### Description
The xlabels in the PlateCarree (and potentially other projections) don't respect the central_longitude. In the example code below, the central longitude is correctly set to 160E. The xlabel at that longitude, however, is 0. 

![cartopy_bug](https://user-images.githubusercontent.com/14315062/43952174-6928cf96-9c95-11e8-83e1-4163957d0db2.png)

I've seen the same issue in #204, but there is was first reported fixed and then a[ patch was proposed](https://github.com/SciTools/cartopy/issues/204#issuecomment-63437882). That does not seem to be included in version 0.16.0?

#### Code to reproduce

```
import matplotlib.pyplot as plt
import cartopy.crs as ccrs

proj = ccrs.PlateCarree(central_longitude=160)
ax = plt.subplot(111, projection=proj)
gl = ax.gridlines(crs=proj)
gl.xlabels_bottom, gl.ylabels_left = (True, True)
ax.coastlines()
plt.show()
```

<details>
 <summary>Full environment definition</summary>

### Operating system
macOS with Python 2.7.15

### Cartopy version
0.16.0

### conda list

```
```

### pip list

```
```

</details>

**Comment by QuLogic** [comment]
You should not pass `crs=proj` when calling `ax.gridlines`, because in that projection, 0 _is_ at 160E. So in fact, it is respecting the central longitude and placing 0 where you tell it to place it. If you pass nothing, you get a 0 tick in the expected location.
