### ISSUE TITLE
Installation on Windows

### ISSUE THREAD

**Issue by klicperajo** [SciTools/cartopy#1109]
### Description

Installation on Windows is extremely complicated (at least without Anaconda).

The required bin, include and lib directories are not detected (I've used OSGeo4W for this). The bin folder can be added to the Path to fix this (which is necessary (and undocumented) for Shapely as well), but there is no decent solution for the include and lib directories.

There is no geos-config tool on this platform, so GEOS is not detected. Proj.4's files are not detected either. Include and lib cannot be specified at all - the only possible way I saw is to download and directly edit setup.py.

There has to be a better way of handling this - i.e. an alternative to geos-config on Windows.

<details>
 <summary>Full environment definition</summary>

### Operating system

Windows 10 64-bit

### Cartopy version

0.16

### pip list
Package                Version
---------------------- -----------
absl-py                0.1.8
asn1crypto             0.24.0
astor                  0.6.2
astroid                1.6.3
attrs                  17.4.0
autopep8               1.3.4
bleach                 1.5.0
cffi                   1.11.4
click                  6.7
colorama               0.3.9
configparser           3.5.0
coverage               4.4.2
cryptography           2.1.4
cycler                 0.10.0
Cython                 0.28.5
decorator              4.2.1
entrypoints            0.2.3
enum34                 1.1.6
flake8                 3.5.0
Flask                  1.0.2
future                 0.16.0
gast                   0.2.0
geos                   0.2.1
grpcio                 1.10.0
gust                   0.1
html5lib               0.9999999
hypothesis             3.44.16
idna                   2.6
ipykernel              4.8.0
ipython                6.2.1
ipython-genutils       0.2.0
ipywidgets             7.1.0
isort                  4.3.4
itsdangerous           0.24
jedi                   0.11.1
Jinja2                 2.10
joblib                 0.11
json-rpc               1.10.8
jsonschema             2.6.0
jupyter                1.0.0
jupyter-client         5.2.1
jupyter-console        5.2.0
jupyter-core           4.4.0
jupyterthemes          0.19.1
lazy-object-proxy      1.3.1
lesscpy                0.13.0
llvmlite               0.22.0
lxml                   4.2.4
Markdown               2.6.11
MarkupSafe             1.0
matplotlib             2.1.1
mccabe                 0.6.1
mistune                0.8.3
mypy                   0.590
nbconvert              5.3.1
nbformat               4.4.0
networkx               2.1
notebook               5.3.1
numba                  0.37.0
numpy                  1.14.0
nxviz                  0.3.5
palettable             3.1.0
pandas                 0.23.3
pandocfilters          1.4.2
parso                  0.1.1
pep8                   1.7.1
pickleshare            0.7.4
Pillow                 5.2.0
pip                    18.0
pluggy                 0.6.0
ply                    3.11
prompt-toolkit         1.0.15
protobuf               3.5.1
py                     1.5.2
pycodestyle            2.3.1
pycparser              2.18
pydocstyle             2.1.1
pyflakes               1.6.0
Pygments               2.2.0
pylint                 1.8.4
pyparsing              2.2.0
pyproj                 1.9.5.1
pyshp                  1.2.12
pytest                 3.3.2
python-dateutil        2.6.1
python-language-server 0.17.0
pytz                   2017.3
pywinpty               0.5.1
PyYAML                 3.12
pyzmq                  16.0.3
qtconsole              4.3.1
rope                   0.10.7
scikit-learn           0.19.1
scipy                  1.0.0
seaborn                0.8.1
Send2Trash             1.4.2
setuptools             38.4.0
Shapely                1.6.4.post2
simplegeneric          0.8.1
six                    1.11.0
snakeviz               0.4.2
snowballstemmer        1.2.1
sphinxcontrib-fulltoc  1.2.0
tensorboard            1.6.0
tensorflow-gpu         1.6.0
termcolor              1.1.0
terminado              0.8.1
testpath               0.3.1
tornado                4.5.3
traitlets              4.3.2
typed-ast              1.1.0
virtualenv             15.1.0
wcwidth                0.1.7
Werkzeug               0.14.1
wheel                  0.30.0
widgetsnbextension     3.1.0
wrapt                  1.10.11
yapf                   0.21.0

</details>

**Comment by pelson** [comment]
> Installation on Windows is extremely complicated (at least without Anaconda).

I agree. I don't think this is a cartopy issue per-say - installing anything requiring a compiler and python is somewhat complicated in Windows.  

We are working on systematic CI for Windows (#1224) which goes through all of the steps needed to install cartopy on Windows. Additionally, the tricks employed to build cartopy for Windows on conda-forge can be followed at https://github.com/conda-forge/cartopy-feedstock: 

 * https://github.com/conda-forge/cartopy-feedstock/blob/master/recipe/meta.yaml
 * https://github.com/conda-forge/cartopy-feedstock/blob/master/recipe/bld.bat
 * https://github.com/conda-forge/cartopy-feedstock/blob/master/recipe/cartopy.win.patch
 
There is only so much that cartopy can do to simplify the compilation step that is necessary on Windows. Any help improving what cartopy does in that regard is most welcome.

I'm going to close this issue as there isn't really anything tangible that we need to do just yet.
