### ISSUE TITLE
Jittering gridlines

### ISSUE THREAD

**Issue by CSlocumWX** [SciTools/cartopy#1113]
### Description
I recently generated a series of plots with a 20x20 degree domain in the PlateCarree projection with coastlines and gridlines. These plots are centered on a moving feature (e.g., the eye of a hurricane) where the center location is determined using a tensioned cubic B-spline. Once the individual plots are converted to an animated gif, it appears that where the gridlines intersect the coastlines changes from plot-to-plot creating irregular random movement or a jittering effect. The coastlines appear to transition smoothly suggesting it is a issues related to accurately rendering the gridlines&mdash;the issue is apparent if you focus in on a section of complex coast (e.g., the Baja Peninsala;  ftp://ftp.cira.colostate.edu/ftp/Slocum/ep032018_20180612.gif). I included a simplified piece of code that reproduces the jittering issue below.

I attempted the following to see if I could get to the route of the jitter on my own to no avail:
* Tried both the Gridliner class and adding natural earth feature gridlines
* Changed the matplotlib `figsize` and `dpi` to see if it is an anti-aliasing issue based on my initial plot configuration
* Decreased the threshold to increase resolution for the PlateCarree projection by following https://github.com/SciTools/cartopy/issues/8
* Increased the default value `self.n_steps` from 30 to 300 on [line 189 in gridliner.py](https://github.com/SciTools/cartopy/blob/7321e9a7b1e19ecc55550ef5d99f8acbbcbc1a65/lib/cartopy/mpl/gridliner.py#L189)
* Set matplotlib collections keyword argument `antialiased=(False,)` in `mcollections.LineCollection` call on [lines 338 & 350 in gridliner.py](https://github.com/SciTools/cartopy/blob/7321e9a7b1e19ecc55550ef5d99f8acbbcbc1a65/lib/cartopy/mpl/gridliner.py#L338) to see if the anti-aliasing is impacting the rendering of gridlines
* I set matplotlib collections `offset_position` keyword argument from `screen` to `data` in `mcollections.LineCollection` call on [lines 338 & 350 in gridliner.py](https://github.com/SciTools/cartopy/blob/7321e9a7b1e19ecc55550ef5d99f8acbbcbc1a65/lib/cartopy/mpl/gridliner.py#L338). According to the collections documentation, this improves the accuracy of the transformation.
* Changed `autolim` to `False` in `add_collection` call to avoid auto-scaling errors in [lines 340 & 352 in gridliner.py](https://github.com/SciTools/cartopy/blob/7321e9a7b1e19ecc55550ef5d99f8acbbcbc1a65/lib/cartopy/mpl/gridliner.py#L340)

I am not sure what else to test in the gridliner.py code to see if I can resolve the jitter issue within the Gridliner class or if the gridline jitters are a red herring for a different issue possibly related to precision and the transform/plotting step related.

####  Code to reproduce
Here is some sample code that can recreate the issue. To generate the animated gif (see ftp://ftp.cira.colostate.edu/ftp/Slocum/test_jitter.gif), I used an ImageMagick utility as follows `convert -delay 20 -loop 0 test*.png test_jitter.gif`

```python
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import cartopy

DELTA = 10
FEATURE_RES = '10m'
PROJ = cartopy.crs.PlateCarree()
XTICKS = np.arange(-122.5, -90, 5)
YTICKS = np.arange(2.5, 35, 5)

def generate_plot(center_lon, center_lat, count):
    """
    Generate a plot centered on a longitude/latitude pair

    Parameters
    ----------
    center_lon : float
        the center longitude point
    center_lat : float
        the center latitude point
    count : int
        a numerical value to generate a figure filename
    """
    ax = plt.axes(projection=PROJ)
    coast = cartopy.feature.NaturalEarthFeature('physical', 'coastline', FEATURE_RES, edgecolor='k', facecolor='none', linewidth=1.5)
    ax.add_feature(coast)
    # Add gridlines using cartopy built-in option
    gl = ax.gridlines(crs=PROJ, linewidth=1.1, color='#4daf4a')
    gl.xlocator = mticker.FixedLocator(XTICKS)
    gl.ylocator = mticker.FixedLocator(YTICKS)
    # Add natural earth feature grid lines
    gl = cartopy.feature.NaturalEarthFeature('physical', 'graticules_5', FEATURE_RES, edgecolor='#ff7f00')
    ax.add_feature(gl)
    # setup extent
    xmax = center_lon + DELTA
    xmin = center_lon - DELTA
    ymax = center_lat + DELTA
    ymin = center_lat - DELTA
    ax.set_extent([xmin, xmax, ymin, ymax], crs=PROJ)
    plt.savefig('test_{count:02d}.png'.format(count=count))
    plt.close()

if __name__ == '__main__':
    lons = np.linspace(-110, -109.25, 20)
    lats = np.linspace(21, 21.25, 20)
    for count, lon in enumerate(lons):
        generate_plot(lon, lats[count], count)
```

### Cartopy version
0.16.0

**Comment by QuLogic** [comment]
GIFs can be posted directly in the issue:
![test_jitter](https://user-images.githubusercontent.com/302469/45061012-8b9dcb00-b070-11e8-9cfb-7869b0923946.gif)

The problem is likely due to snapping of lines in Matplotlib. I can't check at the moment, but if you can grab the lines from the Gridliner, then `line.set_snap(False)`, that might fix the issue.

**Comment by CSlocumWX** [comment]
Ah, it looks like you are right. Adding a `x_lc.set_snap(False)` and `y_lc.set_snap(False)` to `self._draw_gridliner` seems to address the issue on the Gridliner side of things. There is a small amount of aliasing. But, the result looks better&mdash;at least, I find the result less nauseating.
![test_jitter](https://user-images.githubusercontent.com/10509557/45061684-ce58a680-b062-11e8-957b-aa1b9bb46154.gif)

I did not test if this works in feature_artist.py. But, it seems reasonable that a `set_snap` to the [collection object](https://github.com/SciTools/cartopy/blob/7321e9a7b1e19ecc55550ef5d99f8acbbcbc1a65/lib/cartopy/mpl/feature_artist.py#L176) in `draw()` would address this issue with features as well.

Also, adding the following to the top of my example script yields the gif below for both Gridliner and the NaturalEarthFeature.
```python
import matplotlib as mpl
mpl.rcParams['path.snap'] = False
```
![test_jitter2](https://user-images.githubusercontent.com/10509557/45062210-2b555c00-b065-11e8-9001-b3ba81cb341f.gif)

I'm not sure that setting `path.snap` ends up being the best solution in every situation. I guess the question is whether there is a way that `set_snap` can or should be made accessible when adding gridlines and features so that this can be avoided.

**Comment by QuLogic** [comment]
You may also wish to try the [mplcairo backend](https://pypi.org/project/mplcairo/), which I believe should not have such snapping issues.

**Comment by CSlocumWX** [comment]
Thanks for the suggestions. I've gone back to using the basemap package since I find it less buggy. Maybe these suggestions will help others?
