### ISSUE TITLE
Can't manually place colorbar in axes

### ISSUE THREAD

**Issue by BrendanMD** [SciTools/cartopy#1118]
In order to preserve the aspect ratio and physical size of a Plate Carree plot (trying to match old figures made in IDL), I tried to manually place the colorbar so the plot axes would not resize. The end result is the colorbar not being placed in the axes I created for it, but making a lilliputian appearance. 
![](https://user-images.githubusercontent.com/10945244/45833310-ce031100-bcda-11e8-9097-3b9fc50c9840.png)

```
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import cartopy

plot_crs = ccrs.PlateCarree()
vertices = np.array([[[-60,40],[-60,50],[-50,50],[-50,40]]], dtype=np.float64)
data = np.array([25], dtype=np.float64) 
pc = matplotlib.collections.PolyCollection(vertices, array=data, closed=True,
    norm=matplotlib.colors.LogNorm(vmin=0.01, vmax=64.))
pc.set_edgecolor('face')
pc.set_zorder(1)
pc.set_antialiased(False)
pc.set_linewidth(0)
plt.close('all')
#fig = plt.figure(1,(18.5,9.25))
fig = plt.figure(1, (8.858277, 11.5923))
ax = fig.add_axes([0.2, 0.1, 0.675, 0.8125], projection=plot_crs)
#ax.set_extent((-137,-49,30,87))
ax.set_extent((-71, -42, 39, 62.5))
ax.set_zorder(3)
s = ax.add_collection(pc)
feature = cartopy.feature.NaturalEarthFeature(name='land', category='physical',
    scale='50m', zorder=2, antialiased=False, edgecolor='black',
    facecolor=cartopy.feature.COLORS['land'], linewidth=0.1)
ax.add_feature(feature)
#ax.gridlines()
ax.set_aspect('auto')
cax = fig.add_axes([0.2, 0.025, 0.675, 0.025])
cb = plt.colorbar(s, ax=cax, ticks=(0.01,0.1,1,10,50), format='%5.2f', orientation='horizontal')
plt.show()
```

**Comment by greglucas** [comment]
This is related to matplotlib and not Cartopy because the call signature you are using is wrong I think. You currently have `ax=cax` in the `plt.colorbar` call. Change that to `cax=cax` and I think it will behave as you are intending. There are some other gotchas with adding colorbars to Cartopy geoaxes because of the transformations (you're avoiding them in figure space right now), but in general there are a lot of good answers on stackoverflow.

**Comment by QuLogic** [comment]
As @greglucas says, you are calling `plt.colorbar` incorrectly; you are asking for a new colorbar Axes.
