### ISSUE TITLE
AttributeError: 'GeoAxesSubplot' object has no attribute '_hold'

### ISSUE THREAD

**Issue by zssherman** [SciTools/cartopy#1120]
### Description

Hello, when running Travis on our package https://travis-ci.org/ARM-DOE/pyart/jobs/432631010#L1645-L1675. I encountered the error in the traceback below.

Looking into it more, it seems that in matplotlib 3.0.0, axes attribute hold was removed. 
https://matplotlib.org/api/api_changes.html#removals

In geoaxes.py, hold is used. Matplotlib 3.0.0.
https://github.com/SciTools/cartopy/blob/master/lib/cartopy/mpl/geoaxes.py#L1450-L1465
#### Code
https://github.com/SciTools/cartopy/blob/master/lib/cartopy/mpl/geoaxes.py#L1450-L1465

#### Traceback 
```
./../../miniconda3/envs/testenv/lib/python3.6/site-packages/cartopy/mpl/geoaxes.py:1451: in pcolormesh
    result = self._pcolormesh_patched(*args, **kwargs)

def _pcolormesh_patched(self, *args, **kwargs):
        """
            A temporary, modified duplicate of
            :func:`~matplotlib.pyplot.pcolormesh'.
    
            This function contains a workaround for a Matplotlib issue
            and will be removed once the issue has been resolved.
            https://github.com/matplotlib/matplotlib/pull/1314
    
            """
        import warnings
        import matplotlib.colors as mcolors
        import matplotlib.collections as mcoll
    
>       if not self._hold:
E       AttributeError: 'GeoAxesSubplot' object has no attribute '_hold'
```

<details>
 <summary>Full environment definition</summary>

### Operating system
Ubuntu 14.04.5 LTS

### Cartopy version
```
cartopy=0.16.0
```
### conda list

```
python=3.6.6
matplotlib=3.0.0
numpy=1.15.1
```

</details>

**Comment by dopplershift** [comment]
So, I see the function says:

> This function contains a workaround for a Matplotlib issue
            and will be removed once the issue has been resolved.
            https://github.com/matplotlib/matplotlib/pull/1314

This issue was apparently fixed in matplotlib 1.2.x...so considering we only support matplotlib >=1.5, should we just nuke this function and be done?

It would seem this should probably push us to get 0.17 out the door ASAP with whatever we have done.

**Comment by dopplershift** [comment]
@zssherman Can you try monkey patching for me and see if it fixes PyART?
```python
from matplotlib.axes import Axes
from cartopy.mpl.geoaxes import GeoAxes
GeoAxes._pcolormesh_patched = Axes.pcolormesh
```

To be clear, I don't recommend this as anything you guys ship, but want to see if that's enough to fix it.

**Comment by zssherman** [comment]
@dopplershift Sounds good! I will do the change and see if it fixes it. Thanks for the suggestion! And yeah I'll take your recommendation and not ship that.

**Comment by dopplershift** [comment]
I also think matplotlib will put `_hold` back for us (as a do-nothing bit of code) in 3.0.1.

**Comment by zssherman** [comment]
@dopplershift Ah gotcha. And the monkey patch seems to work for radarmapdisplay_cartopy. I will submit a pull request to pyart for the mean time as a temporary fix.

**Comment by QuLogic** [comment]
That docstring is outdated; other things are done in `pcolormesh` that are not workarounds.
