### ISSUE TITLE
Cartopy installation denied because of pystan

### ISSUE THREAD

**Issue by petre-dimo** [SciTools/cartopy#1127]
### Description

Want to install cartopy in a windows10/Anaconda3 environment.

The installation is rejected with the following error message 👍 

**The following packages will be DOWNGRADED:

    pystan:  2.18.0.0-py36h8300f20_0             --> 2.17.1.0-py36_vc14_0 conda-forge [vc14]

Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: failed
ERROR conda.core.link:_execute(502): An error occurred while uninstalling package 'defaults::pystan-2.18.0.0-py36h8300f20_0'.
PermissionError(13, 'Access is denied')
Attempting to roll back.

Rolling back transaction: done

PermissionError(13, 'Access is denied')**

_Is any workaround procedure available ?
Thak you all
Pierre

```_

**Comment by QuLogic** [comment]
This is a problem with conda or your installation. You should report this to the conda people.

On Windows, you might get permission denied if the file is open. Maybe you have a running environment with `pystan` loaded?

Closing as this is not a Cartopy bug.
