### ISSUE TITLE
Convert to proj v5 API

### ISSUE THREAD

**Issue by QuLogic** [SciTools/cartopy#1140]
>The proj_api.h header and the functions related to it is considered deprecated from version 5.0.0 and onwards. The header will be removed from PROJ in version 7.0.0 scheduled for release February 1st 2020.

This applies to `trace.pyx`.

_Originally posted by @dopplershift in https://github.com/SciTools/cartopy/issues/1045#issuecomment-390043613_

**Comment by QuLogic** [comment]
xref to jswhit/pyproj#152

**Comment by snowman2** [comment]
I would be happy to take a stab at it if no one else is planning to do it anytime soon.

**Comment by aeroevan** [comment]
Now that proj 6 is out, it might be nice to define `ACCEPT_USE_OF_DEPRECATED_PROJ_API_H` for the proper proj_version until the API update is complete.

**Comment by adamjstewart** [comment]
Just a heads up, PROJ 7 is now out...

**Comment by dopplershift** [comment]
Looks like removing `proj_api.h` has been postponed to 8.0 according to OSGeo/PROJ#837. Which explains how cartopy was built against PROJ 7.1 on conda-forge. I'd love to solve this by taking a stab at #1477.

**Comment by snowman2** [comment]
The `proj_api.h` has been removed from the PROJ src code. Change will be released in PROJ 8.

**Comment by sebastic** [comment]
PROJ 8.0.0-rc1 has been released with which it's impossible to build cartopy.

**Comment by bjkindia** [comment]
> The `proj_api.h` has been removed from the PROJ src code. Change will be released in PROJ 8.

In this case how can we install Cartopy ? 
I am getting error 
`lib/cartopy/trace.cpp:634:10: fatal error: 'proj_api.h' file not found
  #include "proj_api.h"
           ^~~~~~~~~~~~`

**Comment by dopplershift** [comment]
@bjkindia For now, the workaround is to install PROJ<8.

**Comment by bjkindia** [comment]
Well finally I installed with Conda. I can't solve with manually. 

Conda is great
