### ISSUE TITLE
Error when using `set_extent()` on `Mollweide()` with `central_longitude` set

### ISSUE THREAD

**Issue by andreas-h** [SciTools/cartopy#1165]
### Description
I would like to plot a Mollweide projection, not for the full globe.  This works without problems if I don't set `central_longitude` to a custom value.  Otherwise, I get a `ValueError: Failed to determine the required bounds in projection coordinates`

#### Code to reproduce

    import cartopy.crs as ccrs
    import matplotlib.pyplot as plt
    
    fig, ax = plt.subplots(subplot_kw={'projection': ccrs.Mollweide(central_longitude=10)})
    ax.set_extent([-20, 55, -40, 40], crs=ccrs.PlateCarree())
    ax.coastlines()

#### Traceback 

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/.conda/envs/py3/lib/python3.6/site-packages/cartopy/mpl/geoaxes.py in set_extent(self, extents, crs)
    686             # the projection extents, so try and give a better error message.
--> 687             x1, y1, x2, y2 = projected.bounds
    688         except ValueError:

ValueError: not enough values to unpack (expected 4, got 0)

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-27-f37db0a3638d> in <module>()
      4 
      5 fig, ax = plt.subplots(subplot_kw={'projection': ccrs.Mollweide(central_longitude=10)})
----> 6 ax.set_extent([-20, 55, -40, 40], crs=ccrs.PlateCarree())
      7 ax.coastlines()

~/.conda/envs/py3/lib/python3.6/site-packages/cartopy/mpl/geoaxes.py in set_extent(self, extents, crs)
    692                    'y_limits=[{ylim[0]}, {ylim[1]}]).')
    693             raise ValueError(msg.format(xlim=self.projection.x_limits,
--> 694                                         ylim=self.projection.y_limits))
    695         self.set_xlim([x1, x2])
    696         self.set_ylim([y1, y2])

ValueError: Failed to determine the required bounds in projection coordinates. Check that the values provided are within the valid range (x_limits=[-18040095.696147293, -1.1046372725299363e-09], y_limits=[-9020047.848073646, 9020047.848073646]).
```

#### Probably related

When not using `set_extent` I still don't get what I expect:

    import cartopy.crs as ccrs
    import matplotlib.pyplot as plt
    
    fig, ax = plt.subplots(subplot_kw={'projection': ccrs.Mollweide(central_longitude=10.)})
    ax.coastlines()

Gives me a

    /home2/hilboll/.conda/envs/py3/lib/python3.6/site-packages/cartopy/mpl/feature_artist.py:136: UserWarning: Unable to determine extent. Defaulting to global.
      warnings.warn('Unable to determine extent. Defaulting to global.')

And I see a half-globe (only the left, i.e., Western half), with no coastlines.

<details>
 <summary>Full environment definition</summary>

### Operating system

Debian testing (Buster)

### Cartopy version

0.16.0

### conda list

```alabaster                 0.7.11                   py36_0  
anaconda                  custom           py36hbbc8b67_0  
anaconda-client           1.6.14                   py36_0  
anaconda-project          0.8.2                    py36_0  
asn1crypto                0.24.0                   py36_0  
astroid                   1.6.5                    py36_0  
astropy                   3.0.3            py36h14c3975_2  
atomicwrites              1.1.5                    py36_0  
attrs                     18.1.0                   py36_0  
babel                     2.6.0                    py36_0  
backcall                  0.1.0                    py36_0  
backports                 1.0                      py36_1  
backports.shutil_get_terminal_size 1.0.0                    py36_2  
basemap                   1.1.0                    py36_4    conda-forge
beautifulsoup4            4.6.0                    py36_1  
bitarray                  0.8.2            py36h14c3975_0  
bkcharts                  0.2                      py36_0  
blas                      1.0                         mkl  
blaze                     0.11.3                   py36_0  
bleach                    2.1.3                    py36_0  
blosc                     1.14.3               hdbcaa40_0  
bokeh                     0.13.0                   py36_0  
boto                      2.48.0                   py36_1  
bottleneck                1.2.1            py36h035aef0_1  
brewer2mpl                1.4.1                      py_3    conda-forge
bzip2                     1.0.6                h14c3975_5  
ca-certificates           2018.03.07                    0  
cairo                     1.14.12              h8948797_3  
cartopy                   0.16.0           py36hfa13621_0  
certifi                   2018.10.15               py36_0  
cf_units                  1.2.0                    py36_0    conda-forge
cffi                      1.11.5           py36h9745a5d_0  
cftime                    1.0.0b1          py36h035aef0_0  
chardet                   3.0.4                    py36_1  
click                     6.7                      py36_0  
cloudpickle               0.5.3                    py36_0  
clyent                    1.2.2                    py36_1  
colorama                  0.3.9                    py36_0  
contextlib2               0.5.5                    py36_0  
cryptography              2.2.2            py36h14c3975_0  
curl                      7.60.0               h84994c4_0  
cycler                    0.10.0                   py36_0  
cython                    0.28.3           py36h14c3975_0  
cytoolz                   0.9.0.1          py36h14c3975_1  
dask                      0.18.1                   py36_0  
dask-core                 0.18.1                   py36_0  
datashape                 0.5.4                    py36_1  
dbus                      1.13.2               h714fa37_1  
decorator                 4.3.0                    py36_0  
distributed               1.22.0                   py36_0  
docutils                  0.14                     py36_0  
entrypoints               0.2.3                    py36_2  
esmf                      7.1.0r               ha678704_2    conda-forge
esmpy                     7.1.0r                   py36_1    conda-forge
et_xmlfile                1.0.1                    py36_0  
expat                     2.2.5                he0dffb1_0  
f90nml                    1.0.2                    py36_0    conda-forge
fastcache                 1.0.2            py36h14c3975_2  
filelock                  3.0.4                    py36_0  
flask                     1.0.2                    py36_1  
flask-cors                3.0.6                    py36_0  
fontconfig                2.13.0               h9420a91_0  
freetype                  2.9.1                h8a8886c_0  
fribidi                   1.0.4                h14c3975_0  
geos                      3.6.2                heeff764_2  
get_terminal_size         1.0.0                haa9412d_0  
gevent                    1.3.4            py36h14c3975_0  
glib                      2.56.1               h000015b_0  
glob2                     0.6                      py36_0  
gmp                       6.1.2                h6c8ec71_1  
gmpy2                     2.0.8            py36h10f8cd9_2  
graphite2                 1.3.11               h16798f4_2  
greenlet                  0.4.13           py36h14c3975_0  
gst-plugins-base          1.14.0               hbbd80ab_1  
gstreamer                 1.14.0               hb453b48_1  
h5py                      2.8.0            py36h8d01980_0  
harfbuzz                  1.7.6                hec2c2bc_3  
hdf4                      4.2.13               h3ca952b_2  
hdf5                      1.10.2               hba1933b_1  
heapdict                  1.0.0                    py36_2  
html5lib                  1.0.1                    py36_0  
icu                       58.2                 h9c2bf20_1  
idna                      2.7                      py36_0  
imageio                   2.3.0                    py36_0  
imagesize                 1.0.0                    py36_0  
intel-openmp              2018.0.3                      0  
ipykernel                 4.8.2                    py36_0  
ipython                   6.4.0                    py36_1  
ipython_genutils          0.2.0                    py36_0  
ipywidgets                7.2.1                    py36_0  
iris                      2.0.0                    py36_1    conda-forge
isort                     4.3.4                    py36_0  
itsdangerous              0.24                     py36_1  
IUPy                      0.3.4                     <pip>
jbig                      2.1                  hdba287a_0  
jdcal                     1.4                      py36_0  
jedi                      0.12.1                   py36_0  
jeepney                   0.3.1                    py36_0  
jinja2                    2.10                     py36_0  
jpeg                      9b                   h024ee3a_2  
jsonschema                2.6.0                    py36_0  
jupyter                   1.0.0                    py36_4  
jupyter_client            5.2.3                    py36_0  
jupyter_console           5.2.0                    py36_1  
jupyter_core              4.4.0                    py36_0  
jupyterlab                0.32.1                   py36_0  
jupyterlab_launcher       0.10.5                   py36_0  
keyring                   13.0.0                   py36_0  
kiwisolver                1.0.1            py36hf484d3e_0  
lazy-object-proxy         1.3.1            py36h14c3975_2  
libcurl                   7.60.0               h1ad7b7a_0  
libedit                   3.1.20170329         h6b74fdf_2  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 7.2.0                hdf63c60_3  
libgfortran               3.0.0                         1  
libgfortran-ng            7.2.0                hdf63c60_3  
libnetcdf                 4.6.1                h13459d8_0  
libpng                    1.6.34               hb9fc6fc_0  
libsodium                 1.0.16               h1bed415_0  
libssh2                   1.8.0                h9cfc8f7_4  
libstdcxx-ng              7.2.0                hdf63c60_3  
libtiff                   4.0.9                he85c1e1_1  
libtool                   2.4.6                h544aabb_3  
libuuid                   1.0.3                h1bed415_2  
libxcb                    1.13                 h1bed415_1  
libxml2                   2.9.8                h26e45fe_1  
libxslt                   1.1.32               h1312cb7_0  
llvmlite                  0.24.0           py36hdbcaa40_0  
locket                    0.2.0                    py36_1  
lxml                      4.2.2            py36hf71bdeb_0  
lzo                       2.10                 h49e0be7_2  
markupsafe                1.0              py36h14c3975_1  
matplotlib                2.2.2            py36hb69df0a_2  
mccabe                    0.6.1                    py36_1  
mistune                   0.8.3            py36h14c3975_1  
mkl                       2018.0.3                      1  
mkl-service               1.1.2            py36h651fb7a_4  
mkl_fft                   1.0.2            py36h651fb7a_0  
mkl_random                1.0.1            py36h4414c95_1  
more-itertools            4.2.0                    py36_0  
mpc                       1.1.0                h10f8cd9_1  
mpfr                      4.0.1                hdf1c602_3  
mpi                       1.0                       mpich    conda-forge
mpich                     3.2.1                h26a2512_5    conda-forge
mpmath                    1.0.0                    py36_2  
msgpack-python            0.5.6            py36h6bb024c_0  
multipledispatch          0.5.0                    py36_0  
nbconvert                 5.3.1                    py36_0  
nbformat                  4.4.0                    py36_0  
ncurses                   6.1                  hf484d3e_0  
netcdf-fortran            4.4.4                h4363f12_9    conda-forge
netcdf4                   1.4.0            py36ha06eab4_1  
networkx                  2.1                      py36_0  
nltk                      3.3.0                    py36_0  
nose                      1.3.7                    py36_2  
notebook                  5.5.0                    py36_0  
numba                     0.39.0           py36h04863e7_0  
numexpr                   2.6.5            py36hedc7406_0  
numpy                     1.14.5           py36h1b885b7_4  
numpy-base                1.14.5           py36hdbf6ddf_4  
numpydoc                  0.8.0                    py36_0  
odo                       0.5.1                    py36_0  
olefile                   0.45.1                   py36_0  
openpyxl                  2.5.4                    py36_0  
openssl                   1.0.2p               h14c3975_0  
owslib                    0.16.0                   py36_0  
packaging                 17.1                     py36_0  
pandas                    0.23.2           py36h04863e7_0  
pandoc                    2.2.1                h629c226_0  
pandocfilters             1.4.2                    py36_1  
pango                     1.42.1               h8589676_0  
parso                     0.3.1                    py36_0  
partd                     0.3.8                    py36_0  
patchelf                  0.9                  hf484d3e_2  
path.py                   11.0.1                   py36_0  
pathlib2                  2.3.2                    py36_0  
patsy                     0.5.0                    py36_0  
pcre                      8.42                 h439df22_0  
pep8                      1.7.1                    py36_0  
pexpect                   4.6.0                    py36_0  
pickleshare               0.7.4                    py36_0  
pillow                    5.1.0            py36heded4f4_0  
pip                       10.0.1                   py36_0  
pixman                    0.34.0               hceecf20_3  
pkginfo                   1.4.2                    py36_1  
pluggy                    0.6.0                    py36_0  
ply                       3.11                     py36_0  
proj4                     5.0.1                h14c3975_0  
prompt_toolkit            1.0.15                   py36_0  
psutil                    5.4.6            py36h14c3975_0  
ptyprocess                0.6.0                    py36_0  
py                        1.5.3                    py36_0  
pycodestyle               2.4.0                    py36_0  
pycosat                   0.6.3            py36h14c3975_0  
pycparser                 2.18                     py36_1  
pycrypto                  2.6.1            py36h14c3975_9  
pycurl                    7.43.0.2         py36hb7f436b_0  
pyepsg                    0.3.2                    py36_0  
pyflakes                  2.0.0                    py36_0  
pygments                  2.2.0                    py36_0  
pyhdf                     0.9.10           py36he2eb8c5_0    conda-forge
pyke                      1.1.1                    py36_0    conda-forge
pylint                    1.9.2                    py36_0  
pyodbc                    4.0.23           py36hf484d3e_0  
pyopenssl                 18.0.0                   py36_0  
pyparsing                 2.2.0                    py36_1  
pyproj                    1.9.5.1          py36h7b21b82_1  
pyqt                      5.9.2            py36h22d08a2_0  
pyshp                     1.2.12                   py36_0  
pysocks                   1.6.8                    py36_0  
pytables                  3.4.4            py36ha205bf6_0  
pytest                    3.6.2                    py36_0  
pytest-arraydiff          0.2              py36h39e3cac_0  
pytest-astropy            0.4.0                    py36_0  
pytest-doctestplus        0.1.3                    py36_0  
pytest-openfiles          0.3.0                    py36_0  
pytest-remotedata         0.3.0                    py36_0  
python                    3.6.6                hc3d631a_0  
python-dateutil           2.7.3                    py36_0  
pytz                      2018.5                   py36_0  
pywavelets                0.5.2            py36h035aef0_2  
pyyaml                    3.12             py36h14c3975_1  
pyzmq                     17.0.0           py36h14c3975_3  
qt                        5.9.6                h52aff34_0  
qtawesome                 0.4.4                    py36_0  
qtconsole                 4.3.1                    py36_0  
qtpy                      1.4.2                    py36_1  
readline                  7.0                  ha6073c6_4  
requests                  2.19.1                   py36_0  
rope                      0.10.7                   py36_0  
ruamel_yaml               0.15.42          py36h14c3975_0  
scikit-image              0.14.0           py36hf484d3e_1  
scikit-learn              0.19.1           py36hedc7406_0  
scipy                     1.1.0            py36hc49cb51_0  
seaborn                   0.8.1                    py36_0  
secretstorage             3.0.1                    py36_0  
send2trash                1.5.0                    py36_0  
setuptools                39.2.0                   py36_0  
shapely                   1.6.4            py36h7ef4460_0  
simplegeneric             0.8.1                    py36_2  
singledispatch            3.4.0.3                  py36_0  
sip                       4.19.8           py36hf484d3e_0  
six                       1.11.0                   py36_1  
snappy                    1.1.7                hbae5bb6_3  
snowballstemmer           1.2.1                    py36_0  
sortedcollections         1.0.1                    py36_0  
sortedcontainers          2.0.4                    py36_0  
sphinx                    1.7.5                    py36_0  
sphinxcontrib             1.0                      py36_1  
sphinxcontrib-websupport  1.1.0                    py36_1  
spyder                    3.3.0                    py36_0  
spyder-kernels            0.2.4                    py36_0  
sqlalchemy                1.2.8            py36h14c3975_0  
sqlite                    3.24.0               h84994c4_0  
statsmodels               0.9.0            py36h035aef0_0  
sympy                     1.1.1                    py36_0  
tblib                     1.3.2                    py36_0  
terminado                 0.8.1                    py36_1  
testpath                  0.3.1                    py36_0  
tk                        8.6.7                hc745277_3  
toolz                     0.9.0                    py36_0  
tornado                   5.0.2            py36h14c3975_0  
traitlets                 4.3.2                    py36_0  
typing                    3.6.4                    py36_0  
udunits2                  2.2.25               hd30922c_1  
unicodecsv                0.14.1                   py36_0  
unixodbc                  2.3.6                h1bed415_0  
urllib3                   1.23                     py36_0  
wcwidth                   0.1.7                    py36_0  
webencodings              0.5.1                    py36_1  
werkzeug                  0.14.1                   py36_0  
wheel                     0.31.1                   py36_0  
widgetsnbextension        3.2.1                    py36_0  
wrapt                     1.10.11          py36h14c3975_2  
xarray                    0.10.7                   py36_0  
xesmf                     0.1.1                    py36_0    conda-forge
xlrd                      1.1.0                    py36_1  
xlsxwriter                1.0.5                    py36_0  
xlwt                      1.3.0                    py36_0  
xz                        5.2.4                h14c3975_4  
yaml                      0.1.7                had09818_2  
zeromq                    4.2.5                hf484d3e_0  
zict                      0.1.3                    py36_0  
zlib                      1.2.11               ha838bed_2  
```

### pip list

`alabaster                          0.7.11     
anaconda-client                    1.6.14     
anaconda-project                   0.8.2      
asn1crypto                         0.24.0     
astroid                            1.6.5      
astropy                            3.0.3      
atomicwrites                       1.1.5      
attrs                              18.1.0     
Babel                              2.6.0      
backcall                           0.1.0      
backports.shutil-get-terminal-size 1.0.0      
basemap                            1.1.0      
beautifulsoup4                     4.6.0      
bitarray                           0.8.2      
bkcharts                           0.2        
blaze                              0.11.3     
bleach                             2.1.3      
bokeh                              0.13.0     
boto                               2.48.0     
Bottleneck                         1.2.1      
brewer2mpl                         1.4.1      
Cartopy                            0.16.0     
certifi                            2018.10.15 
cf-units                           1.2.0      
cffi                               1.11.5     
cftime                             1.0.0b1    
chardet                            3.0.4      
click                              6.7        
cloudpickle                        0.5.3      
clyent                             1.2.2      
colorama                           0.3.9      
contextlib2                        0.5.5      
cryptography                       2.2.2      
cycler                             0.10.0     
Cython                             0.28.3     
cytoolz                            0.9.0.1    
dask                               0.18.1     
datashape                          0.5.4      
decorator                          4.3.0      
distributed                        1.22.0     
docutils                           0.14       
entrypoints                        0.2.3      
ESMPy                              7.1.0.dev0 
et-xmlfile                         1.0.1      
f90nml                             1.0.2      
fastcache                          1.0.2      
filelock                           3.0.4      
Flask                              1.0.2      
Flask-Cors                         3.0.6      
gevent                             1.3.4      
glob2                              0.6        
gmpy2                              2.0.8      
greenlet                           0.4.13     
h5py                               2.8.0      
heapdict                           1.0.0      
html5lib                           1.0.1      
idna                               2.7        
imageio                            2.3.0      
imagesize                          1.0.0      
ipykernel                          4.8.2      
ipython                            6.4.0      
ipython-genutils                   0.2.0      
ipywidgets                         7.2.1      
isort                              4.3.4      
itsdangerous                       0.24       
IUPy                               0.3.4      
jdcal                              1.4        
jedi                               0.12.1     
jeepney                            0.3.1      
Jinja2                             2.10       
jsonschema                         2.6.0      
jupyter                            1.0.0      
jupyter-client                     5.2.3      
jupyter-console                    5.2.0      
jupyter-core                       4.4.0      
jupyterlab                         0.32.1     
jupyterlab-launcher                0.10.5     
keyring                            13.0.0     
kiwisolver                         1.0.1      
lazy-object-proxy                  1.3.1      
llvmlite                           0.24.0     
locket                             0.2.0      
lxml                               4.2.2      
MarkupSafe                         1.0        
matplotlib                         2.2.2      
mccabe                             0.6.1      
mistune                            0.8.3      
mkl-fft                            1.0.2      
mkl-random                         1.0.1      
more-itertools                     4.2.0      
mpmath                             1.0.0      
msgpack-python                     0.5.6      
multipledispatch                   0.5.0      
nbconvert                          5.3.1      
nbformat                           4.4.0      
netCDF4                            1.4.0      
networkx                           2.1        
nltk                               3.3        
nose                               1.3.7      
notebook                           5.5.0      
numba                              0.39.0     
numexpr                            2.6.5      
numpy                              1.14.5     
numpydoc                           0.8.0      
odo                                0.5.1      
olefile                            0.45.1     
openpyxl                           2.5.4      
OWSLib                             0.16.0     
packaging                          17.1       
pandas                             0.23.2     
pandocfilters                      1.4.2      
parso                              0.3.1      
partd                              0.3.8      
path.py                            11.0.1     
pathlib2                           2.3.2      
patsy                              0.5.0      
pep8                               1.7.1      
pexpect                            4.6.0      
pickleshare                        0.7.4      
Pillow                             5.1.0      
pip                                10.0.1     
pkginfo                            1.4.2      
pluggy                             0.6.0      
ply                                3.11       
prompt-toolkit                     1.0.15     
psutil                             5.4.6      
ptyprocess                         0.6.0      
py                                 1.5.3      
pycodestyle                        2.4.0      
pycosat                            0.6.3      
pycparser                          2.18       
pycrypto                           2.6.1      
pycurl                             7.43.0.2   
pyepsg                             0.3.2      
pyflakes                           2.0.0      
Pygments                           2.2.0      
pyhdf                              0.9.0      
pyke                               1.1.1      
pylint                             1.9.2      
pyodbc                             4.0.23     
pyOpenSSL                          18.0.0     
pyparsing                          2.2.0      
pyproj                             1.9.5.1    
pyshp                              1.2.12     
PySocks                            1.6.8      
pytest                             3.6.2      
pytest-arraydiff                   0.2        
pytest-astropy                     0.4.0      
pytest-doctestplus                 0.1.3      
pytest-openfiles                   0.3.0      
pytest-remotedata                  0.3.0      
python-dateutil                    2.7.3      
pytz                               2018.5     
PyWavelets                         0.5.2      
PyYAML                             3.12       
pyzmq                              17.0.0     
QtAwesome                          0.4.4      
qtconsole                          4.3.1      
QtPy                               1.4.2      
requests                           2.19.1     
rope                               0.10.7     
ruamel-yaml                        0.15.42    
scikit-image                       0.14.0     
scikit-learn                       0.19.1     
scipy                              1.1.0      
scitools-iris                      2.0.0      
seaborn                            0.8.1      
SecretStorage                      3.0.1      
Send2Trash                         1.5.0      
setuptools                         39.2.0     
Shapely                            1.6.4.post1
simplegeneric                      0.8.1      
singledispatch                     3.4.0.3    
six                                1.11.0     
snowballstemmer                    1.2.1      
sortedcollections                  1.0.1      
sortedcontainers                   2.0.4      
Sphinx                             1.7.5      
sphinxcontrib-websupport           1.1.0      
spyder                             3.3.0      
spyder-kernels                     0.2.4      
SQLAlchemy                         1.2.8      
statsmodels                        0.9.0      
sympy                              1.1.1      
tables                             3.4.4      
tblib                              1.3.2      
terminado                          0.8.1      
testpath                           0.3.1      
toolz                              0.9.0      
tornado                            5.0.2      
traitlets                          4.3.2      
typing                             3.6.4      
unicodecsv                         0.14.1     
urllib3                            1.23       
wcwidth                            0.1.7      
webencodings                       0.5.1      
Werkzeug                           0.14.1     
wheel                              0.31.1     
widgetsnbextension                 3.2.1      
wrapt                              1.10.11    
xarray                             0.10.7     
xesmf                              0.1.1      
xlrd                               1.1.0      
XlsxWriter                         1.0.5      
xlwt                               1.3.0      
zict                               0.1.3      
``
```

</details>

**Comment by QuLogic** [comment]
> proj4 5.0.1 h14c3975_0

This version does not work with Cartopy 0.16.0; you'll need to either create an environment with 4.9.3, only use `central_longitude=0`, or wait for 0.17.0 (sometime next week). Both of these work correctly on `master` and will be working with any version of proj4. See #1124 for more details.

**Comment by andreas-h** [comment]
Ah, I see -- thanks so much for the lightning-fast response!  I'll happily wait :-)
