### ISSUE TITLE
Shapereader doctest failure

### ISSUE THREAD

**Issue by dopplershift** [SciTools/cartopy#1171]
Currently seeing this on Travis on the latest py2k build:
```
024     >>> filename = shapereader.natural_earth(resolution='110m'
025     ...                                      category='physical'
026     ...                                      name='geography_regions_points')
027     >>> reader = shapereader.Reader(filename)
028     >>> len(reader)
029     3
030     >>> records = list(reader.records())
031     >>> print(type(records[0]))
032     <class 'cartopy.io.shapereader.Record'>
033     >>> print(sorted(records[0].attributes.keys()))
Expected:
    ['comment', ... 'name', 'name_alt', ... 'region', ...]
Got:
    [u'comment', u'featurecla', u'label', u'lat_y', u'long_x', u'min_zoom', u'name', u'name_alt', u'name_ar', u'name_bn', u'name_de', u'name_el', u'name_en', u'name_es', u'name_fr', u'name_hi', u'name_hu', u'name_id', u'name_it', u'name_ja', u'name_ko', u'name_nl', u'name_pl', u'name_pt', u'name_ru', u'name_sv', u'name_tr', u'name_vi', u'name_zh', u'ne_id', u'region', u'scalerank', u'subregion', u'wdid_score', u'wikidataid']
```

So it looks like the problem is the leading `u`...but does anyone know if this is new behavior from a library (and who) or if it's a problem with the doctest runner?

**Comment by QuLogic** [comment]
It looks like it's using pyshp 2.0.0, and the first lines of its changes is:

> - Full support for unicode text, with custom encoding, and exception handling.
> - Means that the Reader returns unicode, and the Writer accepts unicode.

**Comment by pelson** [comment]
FWIW: Long term, I'd like to move away from the shapereader implementation altogether - Fiona and geopandas have both arrived since that code was written, and they do a better job of documenting and performance.
