### ISSUE TITLE
Dealing with optional cartopy dependencies

### ISSUE THREAD

**Issue by ngoldbaum** [SciTools/cartopy#1176]
Right now it's a little bit awkward from a packaging perspective to depend on cartopy in an external package and also to use optional functionality in cartopy. For example, let's say I want my package to directly depend on cartopy and I also want to use cartopy's integration with matplotlib or the image transforms, which depend on scipy.

Now I can't tell my users that they should just install cartopy, since that won't also install all the direct dependencies of cartopy. I also can't list just cartopy in my `pyproject.toml` or `install_requires`.

One way to fix this would be to define a set of "extras" for optional functionality, then I could tell my users to install e.g. `cartopy[plotting]` from pip.

Another way to fix this would be to add e.g. matplotlib, scipy, and other python libraries with a relatively "solved" packaging story on most major platforms as direct dependencies of cartopy.

**Comment by QuLogic** [comment]
Extras are defined [here](https://github.com/SciTools/cartopy/blob/master/setup.py#L353); do they not work?

**Comment by dopplershift** [comment]
To be even more clear, `pip install cartopy[plotting]` should work today already. Have you tried it?

**Comment by ngoldbaum** [comment]
Ah cool I didn't appreciate this already works. I guess it just needs to be documented? For example, in the installation docs:

https://scitools.org.uk/cartopy/docs/latest/installing.html#installing

**Comment by pelson** [comment]
Agreed. We can improve the docs here.

As for conda packages, it is pretty much the same argument as https://github.com/conda-forge/xarray-feedstock/issues/5 - should ``conda install cartopy`` install the full package, or the minimum viable product. Conda variants are perhaps the closest thing we have to being able to deliver that, but I'm not 100% on the status of using them (there is quite some irony here).

**Comment by greglucas** [comment]
Some documentation on installing the extras is now included in the release.
