### ISSUE TITLE
Default ‘origin’ for imshow

### ISSUE THREAD

**Issue by dopplershift** [SciTools/cartopy#1187]
So, the default value for the `origin` argument to `imshow` for base matplotlib is as documented:
```
origin : {'upper', 'lower'}, optional
Place the [0,0] index of the array in the upper left or lower left corner of the axes.
The convention 'upper' is typically used for matrices and images. If not given, 
rcParams["image.origin"] is used, defaulting to 'upper'.

Note that the vertical axes points upward for 'lower' but downward for 'upper'.
```

Why on earth do we default to ‘lower’??? 
https://github.com/SciTools/cartopy/blob/f918d97924339887d301c0a8bb7cd34d0590b6ed/lib/cartopy/mpl/geoaxes.py#L1092

**Comment by dopplershift** [comment]
I’d like to change the default, or at least start moving in that direction, by matching matplotlib. If we need to do a deprecation cycle, I’d like to start warning about it then.

**Comment by jrleeman** [comment]
👍 on this - it's a strange quirk and certainly makes teaching `imshow` then `imshow` on geoaxes a bit difficult.

**Comment by dopplershift** [comment]
I guess the better question is: why on earth does CartoPy have a different default than matplotlib itself? It seems like a confusing break from matplotlib for little benefit.

**Comment by pelson** [comment]
> I am unsure if your question is rhetorical, but I always assumed it was because that is the typical orientation of scientific grids.

Precisely. *It is* inconsistent though, and I would support changing it to be consistent with matplotlib.

There is an assumption in the image re-projection code that the image is lower, and hence the comment further down that states:

```
                # It is implicitly assumed by the regridding operation that the
                # origin of the image is 'lower', so simply adjust for that
                # here.
```

This doesn't preclude fixing the default though.

**Comment by pelson** [comment]
Bigger question: anybody know why upper is the default in matplotlib. Is it a historical quirk? PNGs are lower, scientific data is lower, JPEGs are upper (normally)...

**Comment by pelson** [comment]
Advise: don't try to fix this in v0.17 - it is a breaking change that we don't *need* to make in the next few days. v0.17 is already pretty big... 😉

**Comment by dopplershift** [comment]
I'm sure matplotlib does it because MATLAB does--probably because metrices and rows-based data. Blaming MATLAB is what I usually do when I encounter *ahem* unconventional behavior in matplotlib.

No to changing the default in 0.17 seems sensible...but how about a `DeprecationWarning` or a `FutureWarning` so that people know the change is coming?

**Comment by QuLogic** [comment]
PNGs are lower? That seems opposite to most graphics applications.

**Comment by dopplershift** [comment]
See #1194 for a PR to warn when using the default value for origin.
