### ISSUE TITLE
Switch examples from Bitstream to DejaVu

### ISSUE THREAD

**Issue by QuLogic** [SciTools/cartopy#1202]
The default (and shipped) font in Matplotlib changed from Bitstream to DejaVu in 2.0. This causes a warning when running the examples with a new version.

We still support 1.5.1, but whenever we bump minimum versions to at least 2, we should update these examples.

**Comment by pelson** [comment]
Let's drop mpl v1 immediately after the next release. I'm OK with the docs representing the state-of-art, not the legacy (so python3, matplotlib 3, everything latest and greatest). Does this make solving this issue easier?

**Comment by philippemiron** [comment]
Seems like the only examples using Bitstream font are for the cartopy logo.

- lib/cartopy/examples/favicon.py
- lib/cartopy/examples/logo.py

**Comment by QuLogic** [comment]
Fixed by @greglucas in #1860.
