### ISSUE TITLE
test_nightshade_image fails without network

### ISSUE THREAD

**Issue by sebastic** [SciTools/cartopy#1206]
The Debian package build for cartopy 0.17.0 due to `test_nightshade_image` failing because there is no network in the package build chroots.

Marking the test accordingly fixes the issue:
```diff
--- a/lib/cartopy/tests/mpl/test_nightshade.py
+++ b/lib/cartopy/tests/mpl/test_nightshade.py
@@ -27,6 +27,7 @@ from cartopy.feature.nightshade import N
 from cartopy.tests.mpl import ImageTesting
 
 
+@pytest.mark.network
 @ImageTesting(['nightshade_platecarree'])
 def test_nightshade_image():
     # Test the actual creation of the image
```

**Comment by greglucas** [comment]
I don't see where this is requiring a network connection, is there a specific spot you see? I don't think it should go out and get the aurora images in here.

**Comment by QuLogic** [comment]
It requires the network for `coastlines`, which use Natural Earth data. This test should be marked with the `natural_earth` marker instead of `network` though.
