### ISSUE TITLE
DOC: Publish documentation for Cartopy 0.17

### ISSUE THREAD

**Issue by kaedonkers** [SciTools/cartopy#1209]
Thank you everyone for releasing version 0.17.0 ! 🎉🎆 👏 

The [documentation](https://scitools.org.uk/cartopy/docs/latest/index.html) is still at v0.16.0, it would be good to update them too 👍 

Here? -> https://github.com/SciTools/scitools.org.uk/tree/master/cartopy/docs

**Comment by kaedonkers** [comment]
@dopplershift My memory is awful, did we discuss automating the doc builds?

**Comment by QuLogic** [comment]
Docs were published a couple days ago.
