### ISSUE TITLE
Remove nose from test setup

### ISSUE THREAD

**Issue by QuLogic** [SciTools/cartopy#1212]
We currently use pytest for testing, but nose is still installed on Travis. This is due to matplotlib having a testing dependency on it.

When we raise our minimum required version of Matplotlib to 2.1, this dependency can be removed.

**Comment by pelson** [comment]
So this is a v0.19 issue then (assuming we are all comfortable with v0.18 being the last version to support mpl 1.5). 👍

**Comment by dopplershift** [comment]
👍

**Comment by greglucas** [comment]
`nose` is no longer installed in the testing setup files.
