### ISSUE TITLE
Test builds on Windows

### ISSUE THREAD

**Issue by QuLogic** [SciTools/cartopy#1221]
We should really test on Windows too. I don't have the power to do this, so could someone enable either Azure or AppVeyor?

**Comment by dkillick** [comment]
Ping @bjlittle - I think you might have the power to do this (think it needs administrator access to the **SciTools organisation**).

**Comment by bjlittle** [comment]
@dkillick Oh... I'll take a peek

**Comment by bjlittle** [comment]
@QuLogic and @dkillick I think AppVeyor is now enabled...

**Comment by dopplershift** [comment]
That part’s done—I say leave this open until we run on AppVeyor.

**Comment by QuLogic** [comment]
Slight problem in that it's project/**bjlittle**/cartopy/ (see build in linked PR), but it would be best in the SciTools organization.

**Comment by bjlittle** [comment]
@QuLogic Not entirely sure how to make that project "owned" by SciTools the organization. Naively I thought that enabling the project associated with SciToold woud be akin to the same for Travis-CI, Stickler-CI or Coveralls-CI ... clearly not.

I seem to missing a trick here... any thoughts / guidance from those in the know?

**Comment by QuLogic** [comment]
It looks like you have to follow [these somewhat-more-complicated steps](https://www.appveyor.com/docs/team-setup/#setting-up-appveyor-account-for-github-organization). Or give up and use Azure (I've never tried it though.)

**Comment by QuLogic** [comment]
So appveyor builds are working now, we just need to get the ownership fixed up.

**Comment by pelson** [comment]
I've just created an Org account for SciTools on AppVeyor, and have enabled cartopy.

https://ci.appveyor.com/project/SciTools/cartopy

I've also turned on the teams so that GH Admin -> AppVeyor Admin, GH Dev -> Appveyor User.

I'll liaise with @bjlittle to move us over to the org account today.

**Comment by QuLogic** [comment]
It seems to have been migrated, though I also don't seem to have any permissions (like restart or cancel.)

**Comment by greglucas** [comment]
I'm going to close this because builds are now being tested on Windows.
