### ISSUE TITLE
OSNI Projection Grid Lines seem to fail on version 0.17.0

### ISSUE THREAD

**Issue by ahuang11** [SciTools/cartopy#1233]
Directly from pip
![image](https://user-images.githubusercontent.com/15331990/49490512-4458df00-f805-11e8-96b3-f2fc8ffa92c5.png)

cartopy==0.17.0
![image](https://user-images.githubusercontent.com/15331990/49490506-399e4a00-f805-11e8-898a-299a5a73cfee.png)

cartopy==0.16.0
![image](https://user-images.githubusercontent.com/15331990/49490540-618dad80-f805-11e8-9d6f-cb2ef74d9d96.png)

**Comment by QuLogic** [comment]
Bisect says 7d348d92694a079e861b5950790aa90040d384f2, which is a bit unexpected.
