### ISSUE TITLE
va='center_baseline' only with MPL>3

### ISSUE THREAD

**Issue by stefraynaud** [SciTools/cartopy#1241]
Hi,

the 'center_baseline' value seems to not available to the `set_verticalaligment` method  before matplotlib version **3.0**, not **2.0**, despite this value is treated without error internally (method `_get_layout`) at least in MPL version 2.2.3.
I can fix this in my pull request #1117.
https://github.com/SciTools/cartopy/blob/fb7f6c7443443580b5f1efcdbd913cca26690d32/lib/cartopy/mpl/gridliner.py#L259

**Comment by pelson** [comment]
In the interests of keeping things separate, I suggest a small PR that addresses this issue directly (#1117 is a much bigger change that will inevitably take a lot longer to review).
