### ISSUE TITLE
lib C error when importing cartopy

### ISSUE THREAD

**Issue by nmalan** [SciTools/cartopy#1244]
### Description
Hi all, recently I have encountered a problem when importing cartopy on Mac OSX (both High Sierra and Mojave). I have initialised a new environment to test, but still receive the same error 'OSError: Could not find lib c or load any of its variants [].'

Have tried uninstalling and reinstalling a bunch of things, but no luck so far - has anyone seen this error before?

#### Code to reproduce
```
[neilmalan] ~ $ source activate cartopy-test
(cartopy-test) [neilmalan] ~ $ python
Python 3.7.1 | packaged by conda-forge | (default, Nov 13 2018, 09:50:42) 
[Clang 9.0.0 (clang-900.0.37)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cartopy

```
#### Traceback 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/neilmalan/anaconda3/envs/cartopy-test/lib/python3.7/site-packages/cartopy/__init__.py", line 107, in <module>
    import cartopy.crs
  File "/Users/neilmalan/anaconda3/envs/cartopy-test/lib/python3.7/site-packages/cartopy/crs.py", line 32, in <module>
    import shapely.geometry as sgeom
  File "/Users/neilmalan/anaconda3/envs/cartopy-test/lib/python3.7/site-packages/shapely/geometry/__init__.py", line 4, in <module>
    from .base import CAP_STYLE, JOIN_STYLE
  File "/Users/neilmalan/anaconda3/envs/cartopy-test/lib/python3.7/site-packages/shapely/geometry/base.py", line 17, in <module>
    from shapely.coords import CoordinateSequence
  File "/Users/neilmalan/anaconda3/envs/cartopy-test/lib/python3.7/site-packages/shapely/coords.py", line 8, in <module>
    from shapely.geos import lgeos
  File "/Users/neilmalan/anaconda3/envs/cartopy-test/lib/python3.7/site-packages/shapely/geos.py", line 113, in <module>
    free = load_dll('c').free
  File "/Users/neilmalan/anaconda3/envs/cartopy-test/lib/python3.7/site-packages/shapely/geos.py", line 56, in load_dll
    libname, fallbacks or []))
OSError: Could not find lib c or load any of its variants [].
>>> 
```

<details>
 <summary>Full environment definition</summary>

### Operating system
OSX 10.14

### Cartopy version
0.17.0

### conda list
# packages in environment at /Users/neilmalan/anaconda3/envs/cartopy-test:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                py37_1003    conda-forge
blas                      1.0                         mkl  
ca-certificates           2018.11.29           ha4d7672_0    conda-forge
cartopy                   0.17.0           py37h7547761_1    conda-forge
certifi                   2018.11.29            py37_1000    conda-forge
cffi                      1.11.5           py37h5e8e0c9_1    conda-forge
chardet                   3.0.4                 py37_1003    conda-forge
cryptography              2.3.1            py37hdffb7b8_0    conda-forge
cycler                    0.10.0                     py_1    conda-forge
freetype                  2.9.1                h6debe1e_4    conda-forge
geos                      3.6.2                hfc679d8_4    conda-forge
icu                       58.2                 hfc679d8_0    conda-forge
idna                      2.8                   py37_1000    conda-forge
intel-openmp              2019.1                      144  
jpeg                      9c                   h470a237_1    conda-forge
kiwisolver                1.0.1            py37h2d50403_2    conda-forge
libcxx                    4.0.1                hcfea43d_1  
libcxxabi                 4.0.1                hcfea43d_1  
libedit                   3.1.20170329         hb402a30_2  
libffi                    3.2.1                h475c297_4  
libgfortran               3.0.1                h93005f0_2  
libiconv                  1.15                 h470a237_3    conda-forge
libpng                    1.6.36               ha92aebf_0    conda-forge
libtiff                   4.0.10               he6b73bb_1    conda-forge
libxml2                   2.9.8                h422b904_5    conda-forge
libxslt                   1.1.32               h88dbc4e_2    conda-forge
lxml                      4.2.5            py37hc9114bc_0    conda-forge
matplotlib                3.0.2                    py37_1    conda-forge
matplotlib-base           3.0.2            py37hb2d221d_1    conda-forge
mkl                       2019.1                      144  
mkl_fft                   1.0.6            py37h27c97d8_0  
mkl_random                1.0.2            py37h27c97d8_0  
ncurses                   6.1                  h0a44026_1  
numpy                     1.15.4           py37hacdab7b_0  
numpy-base                1.15.4           py37h6575580_0  
olefile                   0.46                       py_0    conda-forge
openssl                   1.0.2p               h470a237_1    conda-forge
owslib                    0.17.0                     py_0    conda-forge
pillow                    5.3.0            py37hc736899_0    conda-forge
pip                       18.1                     py37_0  
proj4                     5.2.0                h470a237_1    conda-forge
pycparser                 2.19                       py_0    conda-forge
pyepsg                    0.4.0                      py_0    conda-forge
pykdtree                  1.3.1            py37h7eb728f_2    conda-forge
pyopenssl                 18.0.0                py37_1000    conda-forge
pyparsing                 2.3.0                      py_0    conda-forge
pyproj                    1.9.5.1          py37h429999c_7    conda-forge
pyshp                     2.0.0                      py_0    conda-forge
pysocks                   1.6.8                 py37_1002    conda-forge
python                    3.7.1                h46c1a51_0    conda-forge
python-dateutil           2.7.5                      py_0    conda-forge
pytz                      2018.7                     py_0    conda-forge
readline                  7.0                  h1de35cc_5  
requests                  2.21.0                py37_1000    conda-forge
scipy                     1.1.0            py37h1410ff5_2  
setuptools                40.6.3                   py37_0  
shapely                   1.6.4            py37h164cb2d_0    conda-forge
six                       1.12.0                py37_1000    conda-forge
sqlite                    3.26.0               ha441bb4_0  
tk                        8.6.8                ha441bb4_0  
tornado                   5.1.1            py37h470a237_0    conda-forge
urllib3                   1.24.1                py37_1000    conda-forge
wheel                     0.32.3                   py37_0  
xz                        5.2.4                h1de35cc_4  
zlib                      1.2.11               h1de35cc_3  

```
```

### pip list
(cartopy-test) [neilmalan] ~ $ pip list
Package         Version    
--------------- -----------
asn1crypto      0.24.0     
Cartopy         0.16.0     
certifi         2018.11.29 
cffi            1.11.5     
chardet         3.0.4      
cryptography    2.4.2      
cycler          0.10.0     
idna            2.8        
kiwisolver      1.0.1      
lxml            4.2.5      
matplotlib      3.0.2      
mkl-fft         1.0.6      
mkl-random      1.0.2      
numpy           1.15.4     
olefile         0.46       
OWSLib          0.17.0     
Pillow          5.3.0      
pip             18.1       
pycparser       2.19       
pyepsg          0.4.0      
pykdtree        1.3.1      
pyOpenSSL       18.0.0     
pyparsing       2.3.0      
pyproj          1.9.5.1    
pyshp           2.0.0      
PySocks         1.6.8      
python-dateutil 2.7.5      
pytz            2018.7     
requests        2.21.0     
scipy           1.1.0      
setuptools      40.6.3     
Shapely         1.6.4.post2
six             1.12.0     
tornado         5.1.1      
urllib3         1.24.1     
wheel           0.32.3 
```
```

</details>

**Comment by QuLogic** [comment]
This looks like a problem in [Shapely](https://github.com/Toblerity/Shapely), not Cartopy.

**Comment by pelson** [comment]
Do you get the same issue upon importing ``shapely.geometry`` @nmalan? This does appear to be a shapely installation issue. Have you installed GEOS through Homebrew? Are you perhaps seeing another angle on #805?

All of the above being equal, it is highly likely that this is a local installation issue rather than a bug that the cartopy maintainers can fix in this repository. Therefore, in the interests of keeping the issue tracker focussed, I'll close this issue.

@nmalan - please let us know if you believe this is an issue that can be fixed in the repository, and we can happily re-open.
