### ISSUE TITLE
How to add plotting scale？

### ISSUE THREAD

**Issue by hengcall0** [SciTools/cartopy#1247]
#### Code to reproduce

```

```

#### Traceback 

```

```

<details>
 <summary>Full environment definition</summary>

### conda list

```
```

### pip list

```
```

</details>

**Comment by pelson** [comment]
Please see the GitHub suggestions for the best way to get help with this kind of question https://github.com/SciTools/cartopy/blob/master/.github/SUPPORT.md. Something like StackOverflow would be a far better medium for such a question.  There are also several such questions available on the internet - the top two google hits for "cartopy scale bar" are https://stackoverflow.com/questions/32333870/how-can-i-show-a-km-ruler-on-a-cartopy-matplotlib-plot and https://github.com/SciTools/cartopy/issues/490.

Finally, I think it is pretty likely that cartopy will gain such functionality built-in. I have a prototype in a branch, with and example of usage in https://github.com/pelson/cartopy/blob/scalebar/lib/cartopy/examples/scalebar.py. (this requires installing cartopy from source, using my branch to test).
