### ISSUE TITLE
Minimum Cython version updated

### ISSUE THREAD

**Issue by pelson** [SciTools/cartopy#1253]
### Description

It seems that #1251 means that we now depend on Cython 0.29+. 

The compile error I got with 0.28.5 (Linux, GCC 4.4.7):

```
cythoning lib/cartopy/trace.pyx to lib/cartopy/trace.cpp

Error compiling Cython file:
------------------------------------------------------------
...
        else:
            geom = GEOSGeom_createCollection_r(handle, GEOS_MULTILINESTRING,
                                               &geoms[0], geoms.size())
        return geom

    cdef list[Line].size_type size(self):
        ^
------------------------------------------------------------

lib/cartopy/trace.pyx:173:9: 'list[Line].size_type' is not a type identifier
```

We should either try to relax this version dependency, or document it (either is fine IMO).

cc @QuLogic

**Comment by QuLogic** [comment]
That's odd; both [Travis](https://travis-ci.org/SciTools/cartopy/jobs/474287107) and [AppVeyor](https://ci.appveyor.com/project/bjlittle/cartopy/builds/21306953/job/y9pn7pv2se256fk9) build against Cython 0.17.

**Comment by pelson** [comment]
Hmm, yes indeed. Perhaps it isn't as simple as the Cython version. I was using a pretty old GCC there, so there may be more to it. For others that come across this issue (via Google), upgrading to Cython v0.29 *did* solve the issue for me.

**Comment by QuLogic** [comment]
Here's a build where I pass `--no-build-isolation` and it fails as yours did: https://travis-ci.org/QuLogic/cartopy/builds/479829383 This switch seems to have been quietly hiding some subtle bugs.

**Comment by pelson** [comment]
> I'd like to see if we can still support Cython 0.28 as that's what's in current Fedora and Debian testing.

With #1264 you don't need Cython at all if you are using the sdist? Is that helpful?
