### ISSUE TITLE
GSHHS problem on MacOS: raise BadZipfile, "File is not a zip file"

### ISSUE THREAD

**Issue by ForTozs** [SciTools/cartopy#1260]
### Description

I recently discovered that Basemap will not be supported after 2020, so I am trying to begin the transition to cartopy. On a MacPorts build of cartopy (MacOS High Sierra), I am having an issue making high-resolution maps. Whenever I try to create a full-resolution GSHHS map, I get an error saying ```zipfile.BadZipfile: File is not a zip file```. I assume this is not a duplicate of 
https://github.com/SciTools/cartopy/issues/1011, because that one is in respect to Windows. 

#### Code to reproduce

```
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import cartopy.feature as cfeature

ax = plt.axes(projection=ccrs.PlateCarree())
ax.set_extent([-91., -88., 29., 31.])
land_hires = cfeature.GSHHSFeature('full', edgecolor='k', facecolor='lightGreen')
ax.add_feature(land_hires)

plt.show()
```

#### Traceback 

```
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cartopy/io/__init__.py:260: DownloadWarning: Downloading: https://www.ngdc.noaa.gov/mgg/shorelines/data/gshhs/oldversions/version2.2.0/GSHHS_shp_2.2.0.zip
  warnings.warn('Downloading: {}'.format(url), DownloadWarning)
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/backends/backend_macosx.py", line 83, in _draw
    self.figure.draw(renderer)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/figure.py", line 1475, in draw
    renderer, self, artists, self.suppressComposite)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/image.py", line 141, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cartopy/mpl/geoaxes.py", line 385, in draw
    inframe=inframe)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 2607, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/image.py", line 141, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cartopy/mpl/feature_artist.py", line 142, in draw
    for geom in geoms:
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cartopy/feature.py", line 312, in intersecting_geometries
    path = shapereader.gshhs(scale, level)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cartopy/io/shapereader.py", line 379, in gshhs
    return gshhs_downloader.path(format_dict)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cartopy/io/__init__.py", line 222, in path
    result_path = self.acquire_resource(target_path, format_dict)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cartopy/io/shapereader.py", line 466, in acquire_resource
    self.acquire_all_resources(format_dict)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cartopy/io/shapereader.py", line 423, in acquire_all_resources
    zfh = ZipFile(six.BytesIO(shapefile_online.read()), 'r')
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/zipfile.py", line 811, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
zipfile.BadZipfile: File is not a zip file
```

<details>
 <summary>Full environment definition</summary>

### Operating system

MacOS High Sierra

### Cartopy version

cartopy 0.16.0

### pip list

Package                            Version    
---------------------------------- -----------
ACRSI                              1.0        
alabaster                          0.7.11     
altgraph                           0.16.1     
appdirs                            1.4.3      
appnope                            0.1.0      
atomicwrites                       1.2.1      
attrs                              18.1.0     
Babel                              2.6.0      
backports                          1.0        
backports-abc                      0.5        
backports.functools-lru-cache      1.5        
backports.shutil-get-terminal-size 1.0.0      
basemap                            1.1.0      
bathy-smoother                     0.1        
Beaker                             1.10.0     
beautifulsoup4                     4.6.3      
bleach                             2.1.4      
Bottleneck                         1.2.1      
bz2file                            0.98       
CacheControl                       0.11.6     
Cartopy                            0.16.0     
certifi                            2018.8.24  
chardet                            3.0.4      
cloudpickle                        0.5.6      
configobj                          5.0.6      
configparser                       3.5.0      
contextlib2                        0.5.1      
cycler                             0.10.0     
Cython                             0.28.5     
dap                                2.2.6.7    
dask                               0.19.2     
decorator                          4.3.0      
defusedxml                         0.5.0      
Django                             1.11.15    
docutils                           0.14       
ecopy                              0.1.2.2    
entrypoints                        0.2.2      
enum34                             1.1.6      
ephem                              3.7.6.0    
et-xmlfile                         1.0.1      
funcsigs                           1.0.2      
functools32                        3.2.3.post2
future                             0.15.2     
futures                            3.2.0      
GDAL                               2.3.1      
Genshi                             0.7        
geographiclib                      1.49       
geopy                              1.16.0     
gnureadline                        6.3.8      
html5lib                           1.0.1      
httplib2                           0.11.3     
idna                               2.7        
imagesize                          1.1.0      
ipaddress                          1.0.22     
ipykernel                          4.9.0      
ipython                            5.4.0      
ipython-genutils                   0.2.0      
ipywidgets                         7.4.2      
jdcal                              1.2        
Jinja2                             2.10       
jsonschema                         2.6.0      
jupyter                            1.0.0      
jupyter-client                     5.2.3      
jupyter-console                    5.2.0      
jupyter-core                       4.4.0      
kiwisolver                         1.0.1      
libxml2-python                     2.9.7      
lockfile                           0.12.2     
macholib                           1.11       
Mako                               1.0.7      
MarkupSafe                         1.0        
matplotlib                         2.2.2      
mercurial                          4.6.1      
mistune                            0.8.3      
mock                               2.0.0      
modulegraph                        0.17       
monotonic                          1.5        
more-itertools                     4.3.0      
mpmath                             1.0.0      
natsort                            4.0.4      
nbconvert                          5.4.0      
nbformat                           4.4.0      
netCDF4                            1.2.2      
networkx                           2.2        
nfldb                              0.2.17     
nflgame                            1.2.20     
nose                               1.3.7      
notebook                           5.7.0      
numexpr                            2.6.8      
numpy                              1.15.2     
octant                             0.1.0      
olefile                            0.45.1     
openpyxl                           2.3.2      
OWSLib                             0.17.0     
packaging                          17.1       
pandas                             0.23.4     
pandocfilters                      1.4.2      
Paste                              2.0.3      
PasteDeploy                        1.5.2      
PasteScript                        2.0.2      
pathlib2                           2.3.2      
patsy                              0.5.0      
pbr                                4.2.0      
pep8                               1.7.0      
pexpect                            4.6.0      
pickleshare                        0.7.5      
Pillow                             5.2.0      
pip                                18.0       
pluggy                             0.7.1      
prometheus-client                  0.3.1      
prompt-toolkit                     1.0.15     
psycopg2                           2.7.5      
ptyprocess                         0.6.0      
py                                 1.6.0      
py2app                             0.17       
Py6S                               1.6.2      
pycairo                            1.17.1     
Pydap                              3.1.1      
pydot                              1.2.4      
pyepsg                             0.3.2      
pygaarst                           0.0.1      
Pygments                           2.2.0      
pygobject                          3.28.3     
pygridgen                          0.2.dev0   
pyobjc-core                        3.0.4      
pyobjc-framework-Cocoa             3.0.4      
pyodbc                             3.0.6      
pyparsing                          2.2.0      
pyproj                             1.9.5.1    
pyresample                         1.1.6      
pyroms                             0.1.0      
pyroms-toolbox                     0.1        
pyshp                              1.2.12     
Pysolar                            0.6        
pyspatialite                       3.0.1a0    
pystan                             2.9.0.0    
pytest                             3.8.1      
python-dateutil                    2.7.3      
pytz                               2018.5     
PyWavelets                         1.0.1      
pyzmq                              17.1.2     
qtconsole                          4.4.1      
requests                           2.19.1     
rios                               1.4.2      
roman                              3.0        
scandir                            1.9.0      
scikit-bio                         0.4.1      
scikit-image                       0.14.0     
scikit-learn                       0.19.2     
scipy                              1.1.0      
seawater                           3.3.4      
Send2Trash                         1.5.0      
setuptools                         40.4.2     
Shapely                            1.6.4      
simplegeneric                      0.8.1      
simplejson                         3.16.0     
singledispatch                     3.4.0.3    
sip                                4.19.12    
six                                1.11.0     
snowballstemmer                    1.2.1      
Sphinx                             1.7.9      
sphinxcontrib-websupport           1.1.0      
statsmodels                        0.9.0      
subprocess32                       3.5.2      
sympy                              1.3        
tables                             3.4.4      
terminado                          0.8.1      
testpath                           0.3.1      
Tkinter                            0.0.0      
toolz                              0.9.0      
tornado                            5.1.1      
traitlets                          4.3.2      
TuiView                            1.2.3      
typing                             3.6.6      
urllib3                            1.23       
utm                                0.4.2      
wcwidth                            0.1.7      
webencodings                       0.5.1      
widgetsnbextension                 3.4.2      
xlrd                               0.9.4      

</details>

**Comment by QuLogic** [comment]
Because of the government shutdown, the NOAA site that's used for the download is completely broken. The link in the output redirects to a message about its unavailability.

**Comment by ForTozs** [comment]
Ugh. Didn't even cross my mind. Yeah, too bad the data isn't served from UH. Having an install option to store the GSHHS basemap locally on my machine wouldn't be bad either. Thanks for the heads up.

**Comment by pelson** [comment]
> I'm not entirely sure why we use NOAA and not the UHawaii site.

Sadly, I can't see the older versions on UH that *are* hosted on NOAA's site. To be honest, I'd also rather choose a provider that didn't force us to download a zipfile full of files that mostly aren't needed.

I've done some work in #1262 which identifies that if we switch to the UH zipfile we will get another exception regarding a shapefile that is missing from the zipfile. On the whole, the story for getting hold of GHSSH in a sane way is pretty poor at the moment.  

I'm at a bit of an impasse - I don't particularly want to move to the UH hosting as I believe it will introduce issues further down the line, but equally I can't improve/fix the existing implementation because of the shutdown.


As I don't think there is anything that cartopy can do here, I'm going to close this issue. Happy for it to be re-opened if there is something that you think we can do (I considered improving the error message but it is painful to maintain the code to test the two states [shutdown vs no-shutdown]), especially if you are motivated to submit a PR 😉.
