### ISSUE TITLE
Python 3.7 Crashes

### ISSUE THREAD

**Issue by kqi914** [SciTools/cartopy#1274]
### Description

Hello everyone, 
I am trying to plot some points on a map by using cartopy, I am staring slow by following the tutorials on [this](https://scitools.org.uk/cartopy/docs/v0.15/matplotlib/intro.html) website. More specifically, I am trying to run the following script:
```
import cartopy.crs as ccrs
import matplotlib.pyplot as plt

ax = plt.axes(projection=ccrs.PlateCarree())
ax.coastlines()

plt.show()
```

At first, the script ran yielding me a "DownloadWarning" and a link to download a zip file, which I did and I can't seem to recreate even by deleting the zipped folder.
Then, every time I run this script python crashes. I added some technical details below, I installed version 0.16.0 of Cartopy due to some installation errors as seen in #1270.
I am thinking that probably I am missing something or making a silly mistake, I am relatively new to python and no expert when it comes to using the Terminal.

<details>
 <summary>Full environment definition</summary>

### Operating system
```
MacOs 10.13.6
```
### Python version
```
python 3.7
```
### Cartopy version
```
0.16.0
```
### conda list

Not using conda, should I?

### pip list

```
Package           Version    
----------------- -----------
Cartopy           0.16.0     
certifi           2018.8.24  
chardet           3.0.4      
cycler            0.10.0     
Cython            0.29.4     
easydict          1.9        
idna              2.7        
kiwisolver        1.0.1      
matplotlib        3.0.2      
numpy             1.15.2     
pandas            0.23.4     
pip               19.0.1     
pyparsing         2.3.1      
pyshp             2.0.1      
python-dateutil   2.7.3      
python-forecastio 1.4.0      
pytz              2018.5     
requests          2.20.1     
responses         0.10.5     
scipy             1.2.0      
setuptools        39.0.1     
Shapely           1.6.4.post2
simplekml         1.3.1      
six               1.11.0     
urllib3           1.24.1     
weather-api       1.0.6      
WunderWeather     1.1.0 
```

### brew list
```
gdbm		openssl		python		sqlite
geos		proj		readline	xz
```
</details>

**Comment by QuLogic** [comment]
The DownloadWarning is notifying you that Cartopy is downloading something itself; you don't need to do anything with the link.

You didn't say what the error was but I guess it is probably #879, so try `pip uninstall shapely`; `pip install --no-binary :all: shapely`.

**Comment by kqi914** [comment]
> The DownloadWarning is notifying you that Cartopy is downloading something itself; you don't need to do anything with the link.
> 
> You didn't say what the error was but I guess it is probably #879, so try `pip uninstall shapely`; `pip install --no-binary :all: shapely`.

Thats my issue, I am running the script on python's IDLE so when it crashes I am not getting any errors, it only restarts the shell inside the IDLE. What I am getting though is a report from my computer, I do not know if that would be of any help. I do not have shapely installed but even if I install it it still crashes. Also, compared to #879, I haven't successfully created a map.

### Copy of report
```
Process:               Python [6577]
Path:                  /Library/Frameworks/Python.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python
Identifier:            org.python.python
Version:               3.7.0 (3.7.0)
Code Type:             X86-64 (Native)
Parent Process:        Python [6573]
Responsible:           Python [6577]
User ID:               507

Date/Time:             2019-02-07 14:41:08.998 -0600
OS Version:            Mac OS X 10.13.6 (17G5019)
Report Version:        12
Anonymous UUID:        2831A693-AF5B-DA3E-3F93-04769022649F

Sleep/Wake UUID:       57ABE6B1-206A-48AA-ADD7-C3E592BFBA38

Time Awake Since Boot: 34000 seconds
Time Since Wake:       1700 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGBUS)
Exception Codes:       KERN_PROTECTION_FAILURE at 0x00007fffb3e9a058
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Bus error: 10
Termination Reason:    Namespace SIGNAL, Code 0xa
Terminating Process:   exc handler [0]
```

**Comment by kqi914** [comment]
Oh sorry, I over looked it as I am currently having trouble with my system as I have python 3.6, 3.7, and 2.7 so to check what packages I have installed I have to to:
```python#.# -m pip list```
But anyways, after uninstalling shapely and installing it using:
```python3.7 -m pip install --no-binary :all: shapely``` 
and running the program from the terminal instead of running the IDLE by pressing F5 I was able to produce a map!

Thank you very much!!
Also, any websites or video tutorials apart from [this](https://scitools.org.uk/cartopy/docs/v0.15/matplotlib/intro.html) where I can look over more examples that you would personally recommend?

**Comment by efiring** [comment]
Can this issue be closed?  It looks like an installation glitch that has been solved.

**Comment by QuLogic** [comment]
Yes, there's no need to keep this open.
