### ISSUE TITLE
interrupted by signal 11: SIGSEGV set_extent function

### ISSUE THREAD

**Issue by am2222** [SciTools/cartopy#1277]
### Description

Hi, I tried to install cartopy using pip and also build from source but In both cases `set_extent` function throws this error,
`Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)`

#### Code to reproduce

```
import warnings

import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import cartopy.io.img_tiles as cimgt


import warnings
warnings.filterwarnings("ignore", message="numpy.dtype size changed")
warnings.filterwarnings("ignore", message="numpy.ufunc size changed")
extent = [5, 20, 36, 48]

request = cimgt.GoogleTiles()

fig, ax = plt.subplots(figsize=(10, 15))
ax = plt.axes(projection=request.crs)
ax.set_extent(extent)
ax.add_image(request, 6)
plt.show()
# plt.draw()
fig.savefig(r'/home/m/tessstttyyy.png', dpi=100)
```

#### Traceback 

```

```

<details>
 <summary>Full environment definition</summary>

### Operating system

Ubunto Linux 
### Cartopy version
built with lates version on git and on pip

### conda list

```
```

### pip list

```
affine==2.2.2
apturl==0.5.2
argh==0.26.2
arrow==0.13.0
asn1crypto==0.24.0
atomicwrites==1.3.0
attrs==18.2.0
binaryornot==0.4.4
Brlapi==0.6.6
bumpversion==0.5.3
Cartopy==0.17.0
certifi==2018.1.18
chardet==3.0.4
Click==7.0
click-plugins==1.0.4
cligj==0.5.0
cmake-example==0.0.1
command-not-found==0.3
cookiecutter==1.6.0
coverage==4.5.1
cryptography==2.1.4
cupshelpers==1.0
cycler==0.10.0
Cython==0.29.5
decorator==4.3.2
defer==1.0.6
distro-info==0.18
Django==2.1.5
filelock==3.0.10
flake8==3.5.0
future==0.17.1
GDAL==2.3.2
geojsonvt==0.1.0
httplib2==0.9.2
idna==2.6
Jinja2==2.10
jinja2-time==0.2.0
keyring==10.6.0
keyrings.alt==3.0
kiwisolver==1.0.1
language-selector==0.1
launchpadlib==1.10.6
lazr.restfulclient==0.13.5
lazr.uri==1.0.3
louis==3.5.0
macaroonbakery==1.1.3
Mako==1.0.7
mapbox-vector-tile==1.2.0
# Editable install with no version control (mapnik==3.1.0)
-e /usr/local/lib/python3.6/dist-packages/mapnik-3.1.0-py3.6-linux-x86_64.egg
MarkupSafe==1.1.0
matplotlib==3.0.2
mccabe==0.6.1
mercantile==1.0.4
more-itertools==6.0.0
Naked==0.1.31
netifaces==0.10.4
networkx==2.2
numpy==1.16.1
oauth==1.0.1
oauthlib==3.0.1
olefile==0.45.1
packaging==19.0
pandas==0.24.1
pathtools==0.1.2
pexpect==4.2.1
Pillow==5.1.0
pip-review==1.0
pluggy==0.8.1
poyo==0.4.2
protobuf==3.0.0
psycopg2==2.7.7
psycopg2-binary==2.7.7
py==1.7.0
pybind11==2.2.4
pycairo==1.16.2
pyclipper==1.1.0.post1
pycodestyle==2.3.1
pycrypto==2.6.1
pycups==1.9.73
pyflakes==1.6.0
pyGeoTile==1.0.6
Pygments==2.3.1
pygobject==3.26.1
pymacaroons==0.13.0
PyNaCl==1.1.2
pyodbc==4.0.25
pyparsing==2.3.1
pyproj==1.9.6
pyRFC3339==1.0
pyshp==2.1.0
PySocks==1.6.8
pytest==4.3.0
python-apt==1.6.3+ubuntu1
python-dateutil==2.7.5
python-debian==0.1.32
python-example==0.0.1
pytz==2018.9
pyxdg==0.25
PyYAML==3.13
rasterio==1.0.18
reportlab==3.4.0
requests==2.18.4
requests-oauthlib==1.2.0
requests-unixsocket==0.1.5
rpy2==2.9.5
scipy==1.2.1
SecretStorage==2.3.1
Shapely==1.6.4.post2
simplejson==3.13.2
six==1.12.0
snuggs==1.4.2
SQLAlchemy==1.2.18
sqlparse==0.2.4
system-service==0.3
systemd-python==234
toml==0.10.0
tox==3.5.2
tweepy==3.7.0
ubuntu-drivers-common==0.0.0
ufw==0.35
unattended-upgrades==0.1
urllib3==1.22
usb-creator==0.3.3
virtualenv==16.2.0
wadllib==1.3.2
watchdog==0.9.0
whichcraft==0.5.2
xkit==0.0.0
zope.interface==4.3.2
```

</details>

**Comment by greglucas** [comment]
Have you looked at the request you're getting back, perhaps you're not getting back a request object from the GoogleTiles because of proxy or other internet issues?

**Comment by am2222** [comment]
I had no issue with Internet, Does this library needs Internet to get tile info?

**Comment by greglucas** [comment]
You have to get the GoogleTile from somewhere... You can view the url that is tried by viewing the `request.url` in your code.

In general, I'd be explicit with your set_extent method, and put the data projection coordinates into the call. Your request object creates an axis in a Mercator projection, but then you set extent with lat/lon coordinates, so add this to your extent call:
`ax.set_extent(extent, crs=ccrs.PlateCarree())`

Have you tried any other img_tiles or just background images to see if you can get those to work? I'm doubtful that this is a Cartopy error, but more likely just manifesting itself in that function.

**Comment by am2222** [comment]
You know I just copied this script from examples section and it might be out dated. I will check your solution and get back to you

**Comment by QuLogic** [comment]
Like #1285, you probably have mixed versions of libgeos from your system and a pre-compiled Shapely. This is the same as #879, so try pip3 uninstall shapely; pip3 install --no-binary :all: shapely.

**Comment by QuLogic** [comment]
Closing because this is old without a response.
