### ISSUE TITLE
MapBox plotting throws an error

### ISSUE THREAD

**Issue by simonrp84** [SciTools/cartopy#1278]
### Description
I am trying to use a MapBox basemap, but get an error when I run a modified version of the example script (the example fails too).

This is the code I run...minus my API key, which I've replaced with KEY_GOES_HERE:
```
import matplotlib.pyplot as plt
from cartopy.io.img_tiles import MapboxTiles
tiler = MapboxTiles('KEY_GOES_HERE','mapbox.satellite')
mercator = tiler.crs
ax = plt.axes(projection=mercator)
ax.set_extent([-75,-74,40,41])
ax.add_image(tiler, 10)
ax.coastlines('10m')
plt.show()
```

And this is the error I get:

```
python image_tiles.py 

(python:9843): dbind-WARNING **: 14:43:33.256: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-TBaQ6eZbhG: Connection refused
Traceback (most recent call last):
  File "/network/aopp/apres/users/proud/conda/lib/python3.6/site-packages/matplotlib/backends/backend_qt5.py", line 519, in _draw_idle
    self.draw()
  File "/network/aopp/apres/users/proud/conda/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 402, in draw
    self.figure.draw(self.renderer)
  File "/network/aopp/apres/users/proud/conda/lib/python3.6/site-packages/matplotlib/artist.py", line 50, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/network/aopp/apres/users/proud/conda/lib/python3.6/site-packages/matplotlib/figure.py", line 1649, in draw
    renderer, self, artists, self.suppressComposite)
  File "/network/aopp/apres/users/proud/conda/lib/python3.6/site-packages/matplotlib/image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "/network/aopp/apres/users/proud/conda/lib/python3.6/site-packages/matplotlib/artist.py", line 50, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/network/aopp/apres/users/proud/conda/lib/python3.6/site-packages/cartopy/mpl/geoaxes.py", line 382, in draw
    self._get_extent_geom(factory.crs), args[0])
  File "/network/aopp/apres/users/proud/conda/lib/python3.6/site-packages/cartopy/io/img_tiles.py", line 68, in image_for_domain
    img, extent, origin = _merge_tiles(tiles)
  File "/network/aopp/apres/users/proud/conda/lib/python3.6/site-packages/cartopy/io/img_tiles.py", line 503, in _merge_tiles
    raise ValueError('A non-empty list of tiles should '
ValueError: A non-empty list of tiles should be provided to merge.
```

I'm running cartopy 0.17.0, matplotlib 3.0.3 and python 3.6.7

Any ideas what the problem could be here? My API key is valid (it works in other applications) so that's not the issue..

**Comment by DPeterK** [comment]
Hi @simonrp84, thanks for contacting us with this issue. I wonder whether the problem here is that there's a disconnect between the resolution / zoom level of the tiles you've requested (the number in `ax.add_image`) and the size / location of your extent (set with `ax.set_extent`). It's possible that effectively no tiles describe the extent you've asked for at the requested zoom level as the extent is wholly contained within a single tile. 

To test this you could initially try something like one of these options:
* increase the zoom level requested to 11 (but note that this might cause your code to run slower because more tiles will need to be requested and returned)
* increase the area of extent by a few degrees in both x and y (the returned plot won't be quite what you're after of course, but it should request more than one tile and so be a useful test that this is what was causing the problem)

Hope this helps!

**Comment by simonrp84** [comment]
Hi @DPeterK, thanks for your reply. I should have mentioned in my original post that I had already tried both of these solutions.
First, I tried various zoomlevels between 8-15.
Second, I used `ax.set_extent([-90,-60,30,50])`, which should be big enough to cover multiple tiles.

Both of these resulted in the same error as in my post above. I do think, though, that cartopy is trying to access the tiles...looking at my Mapbox API I can see the number of mapviews has increased dramatically since I started playing with this - which makes me think it might be something to do with downloading the data rather than finding the correct tiles.

**Comment by DPeterK** [comment]
Thanks for the update - it's always worth hoping there's a simple solution! Looking closer at the stacktrace above, I wonder if the problem isn't happening in Python at all, given the first line in the stacktrace:

> ```(python:9843): dbind-WARNING **: 14:43:33.256: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-TBaQ6eZbhG: Connection refused```

I googled the part `Couldn't connect to accessibility bus`, which provided a number of hits of different  applications causing similar errors containing this text. Given you know your OS and environment better than I, it might be worth you also googling the same quote and see if any of the solutions apply to a similar / equivalent environment to that which you're working on. 

One solution I saw a number of times was this (including at https://bugs.launchpad.net/ubuntu/+source/at-spi2-core/+bug/1193236):

```bash
export NO_AT_BRIDGE=1
```

I admit I don't know what this environment variable does or changes, but it seems to have solved a number of similar issues, so it might be worth trying it.

**Comment by simonrp84** [comment]
Hi,
That line is because I'm using XFCE. While annoying, it's harmless and occurs whenever I use matplotlib/cartopy - I get it even when I successfully create a plot.

**Comment by DPeterK** [comment]
OK, not that then!

Looking again at your code, it occurs to me that you've defined your extents in the Plate Carrée projection, but your map projection is Web Mercator. Try specifying the CRS of the extents in `ax.set_extent`:

```python
ax.set_extent([-75,-74,40,41], crs=ccrs.PlateCarree())
```

**Comment by simonrp84** [comment]
Unfortunately that doesn't help, same error!

I did a little more digging and it seems that the code can find the tiles. I used this:
```
print(list(tiler.find_images(tiler.crs.domain,0)))
print(list(tiler.find_images(tiler.crs.domain,5)))
```
Which returns:
`[(0, 0, 0)]` in the first case and a huge list of tiles in the second case.


However, if I then run
```
tiles=list(tiler.find_images(tiler.crs.domain,0))
tiler.get_image(tiles[0])
```
Then I get an error with the following traceback:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/network/aopp/apres/users/proud/conda/lib/python3.6/site-packages/cartopy/io/img_tiles.py", line 166, in get_image
    fh = urlopen(url)
  File "/network/aopp/apres/users/proud/conda/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/network/aopp/apres/users/proud/conda/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/network/aopp/apres/users/proud/conda/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/network/aopp/apres/users/proud/conda/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/network/aopp/apres/users/proud/conda/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/network/aopp/apres/users/proud/conda/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request
```

Is this any help in tracking down what's gone wrong?

**Comment by simonrp84** [comment]
Ok, I added a print statement to the img_tiles.py file and that's exposed the problem. This line:
`tiler = MapboxTiles('KEY_GOES_HERE','mapbox.satellite')`
should really be:
`tiler = MapboxTiles('KEY_GOES_HERE','satellite')`
As the `mapbox.` part is automatically added.

With this change, the script runs fine. It would be great if a note describing that 'mapbox.' is not needed could be added to the documentation, as this was not clear to me (apologies if it's there and I missed it!)

Thanks for your help, I'll close this issue now.
