### ISSUE TITLE
Unexpected behaviour of contourf

### ISSUE THREAD

**Issue by nicolamartin** [SciTools/cartopy#1279]
### Description

I’ve come across an issue with contourf when using cartopy at version 0.16. This is related to an earlier problem that we had been experiencing with cartopy 0.15.1. Under this version we get errors for some of our contour plots, similar to those described in issue #883. It looked like the bug was being fixed at 0.16 and indeed we longer get the errors at this version. However, we do not get the expected behaviour.

It looks like for the data that contourf would previously fail on, it now just fills in the surrounding area with the outer contour colour. 

When we used to get the errors, we would shift the data by a tiny amount and contourf would produce the expected plot.

#### Examples

The attached plots show an example where contouf would fail with cartopy 0.15, but succeed with 0.16. The image below is how the plot should look (produced byt shifting the data by tiny amount. 
![contourf_plot_good](https://user-images.githubusercontent.com/48281981/53880823-f45b0580-4009-11e9-9892-54ae1e67c578.png)
This image is what we get with cartopy 0.16.
![contourf_plot_bad](https://user-images.githubusercontent.com/48281981/53880835-fc1aaa00-4009-11e9-81b3-9d0bc1699b92.png)

I have found it difficult to reproduce the problem with made up data since I’m not entirely sure what causes the error. I’ve managed to cut this down to a smaller region to produce the example in this notebook: [cartopy0.16_bug.pdf](https://github.com/SciTools/cartopy/files/2936242/cartopy0.16_bug.pdf)

**Comment by ajdawson** [comment]
Are you able to try your example with version 0.17.0? The 0.17.0 release contains at least 1 fix related to contourf, and maybe it is sufficient to fix this problem too. In any case we need to know if this problem is still a problem.

**Comment by corinnebosley** [comment]
Tried the example with cartopy 0.17.0, and this is still a problem.

Also tried the example without cartopy at all, and the error still occurs.  I don't think this is a cartopy problem at all actually, I think it's in the guts of matplotlib, so I will close this issue, compress the example and create a new issue in matplotlib.

**Comment by corinnebosley** [comment]
On second thoughts I won't raise another issue anywhere until I know where this comes from.  Could be iris for all I know, and then I'd feel really stupid...
