### ISSUE TITLE
error: Proj 4.9.0 must be installed. when pkg-config not installed

### ISSUE THREAD

**Issue by gijzelaerr** [SciTools/cartopy#1283]
for my installation, pkg-config is used to determine if proj is correctly installed:

https://github.com/SciTools/cartopy/blob/master/setup.py#L258

This fails if pkg-config is not installed, which gives a confusing error message that proj is not installed while it could be.

Probably best to add a check if pkg-config is installed.

**Comment by greglucas** [comment]
PROJ is no longer required, so I think this is no longer relevant? But perhaps the pkg-config failure would show up for the GEOS check too. Feel free to reopen if this is still an issue.
