### ISSUE TITLE
cartopy cannot plot anything in python 3.7

### ISSUE THREAD

**Issue by thelahunginjeet** [SciTools/cartopy#1284]
### Description

I know this may be related to other issues, but I am not having exactly the same problem as other users and I have not seen a consistent explanation.  I cannot plot anything with cartopy in python 3.7.  No projection of any kind.  Ipython crashes at plt.axes(projection=X), where projection is anything I have tried (see below for error message).  Everything has been installed using conda; no home-brew of any kind.

#### Code to reproduce

import cartopy.crs as ccrs
import matplotlib.pyplot as plt

plt.axes(projection=ccrs.PlateCarree())

#### Traceback 

2019-03-15 14:44:57.379 python[47270:115254856] -[NSApplication _setup:]: unrecognized selector sent to instance 0x7f90ded89560
2019-03-15 14:44:57.382 python[47270:115254856] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSApplication _setup:]: unrecognized selector sent to instance 0x7f90ded89560'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff32f5ffa5 __exceptionPreprocess + 256
	1   libobjc.A.dylib                     0x00007fff5f056efb objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff32fddc8d -[NSObject(NSObject) __retain_OA] + 0
	3   CoreFoundation                      0x00007fff32f015de ___forwarding___ + 1468
	4   CoreFoundation                      0x00007fff32f00f98 _CF_forwarding_prep_0 + 120
	5   libtk8.6.dylib                      0x000000011d5cb31d TkpInit + 413
	6   libtk8.6.dylib                      0x000000011d52317e Initialize + 2622
	7   _tkinter.cpython-37m-darwin.so      0x000000011d34ba0f _tkinter_create + 1183
	8   python                              0x0000000105e068b6 _PyMethodDef_RawFastCallKeywords + 230
	9   python                              0x0000000105f43ba2 call_function + 306
	10  python                              0x0000000105f41852 _PyEval_EvalFrameDefault + 46114
	11  python                              0x0000000105f351fe _PyEval_EvalCodeWithName + 414
	12  python                              0x0000000105e05587 _PyFunction_FastCallDict + 231
	13  python                              0x0000000105e87c31 slot_tp_init + 193
	14  python                              0x0000000105e91c01 type_call + 241
	15  python                              0x0000000105e06283 _PyObject_FastCallKeywords + 179
	16  python                              0x0000000105f43c35 call_function + 453
	17  python                              0x0000000105f41946 _PyEval_EvalFrameDefault + 46358
	18  python                              0x0000000105e06075 function_code_fastcall + 117
	19  python                              0x0000000105f43b27 call_function + 183
	20  python                              0x0000000105f41852 _PyEval_EvalFrameDefault + 46114
	21  python                              0x0000000105f351fe _PyEval_EvalCodeWithName + 414
	22  python                              0x0000000105e05587 _PyFunction_FastCallDict + 231
	23  python                              0x0000000105e094a2 method_call + 130
	24  python                              0x0000000105e06ef2 PyObject_Call + 130
	25  python                              0x0000000105f41a9d _PyEval_EvalFrameDefault + 46701
	26  python                              0x0000000105f351fe _PyEval_EvalCodeWithName + 414
	27  python                              0x0000000105e06783 _PyFunction_FastCallKeywords + 195
	28  python                              0x0000000105f43b27 call_function + 183
	29  python                              0x0000000105f4188d _PyEval_EvalFrameDefault + 46173
	30  python                              0x0000000105e06075 function_code_fastcall + 117
	31  python                              0x0000000105f43b27 call_function + 183
	32  python                              0x0000000105f4188d _PyEval_EvalFrameDefault + 46173
	33  python                              0x0000000105f351fe _PyEval_EvalCodeWithName + 414
	34  python                              0x0000000105e05587 _PyFunction_FastCallDict + 231
	35  python                              0x0000000105f41a9d _PyEval_EvalFrameDefault + 46701
	36  python                              0x0000000105f351fe _PyEval_EvalCodeWithName + 414
	37  python                              0x0000000105e06783 _PyFunction_FastCallKeywords + 195
	38  python                              0x0000000105f43b27 call_function + 183
	39  python                              0x0000000105f41946 _PyEval_EvalFrameDefault + 46358
	40  python                              0x0000000105f351fe _PyEval_EvalCodeWithName + 414
	41  python                              0x0000000105f2fffb builtin_exec + 347
	42  python                              0x0000000105e068b6 _PyMethodDef_RawFastCallKeywords + 230
	43  python                              0x0000000105f43ba2 call_function + 306
	44  python                              0x0000000105f4188d _PyEval_EvalFrameDefault + 46173
	45  python                              0x0000000105e1f609 gen_send_ex + 169
	46  python                              0x0000000105f3c9fd _PyEval_EvalFrameDefault + 26061
	47  python                              0x0000000105e1f609 gen_send_ex + 169
	48  python                              0x0000000105f3c9fd _PyEval_EvalFrameDefault + 26061
	49  python                              0x0000000105e1f609 gen_send_ex + 169
	50  python                              0x0000000105e06853 _PyMethodDef_RawFastCallKeywords + 131
	51  python                              0x0000000105e13634 _PyMethodDescr_FastCallKeywords + 84
	52  python                              0x0000000105f43c25 call_function + 437
	53  python                              0x0000000105f417bc _PyEval_EvalFrameDefault + 45964
	54  python                              0x0000000105e06075 function_code_fastcall + 117
	55  python                              0x0000000105f43b27 call_function + 183
	56  python                              0x0000000105f4188d _PyEval_EvalFrameDefault + 46173
	57  python                              0x0000000105e06075 function_code_fastcall + 117
	58  python                              0x0000000105f43b27 call_function + 183
	59  python                              0x0000000105f417bc _PyEval_EvalFrameDefault + 45964
	60  python                              0x0000000105f351fe _PyEval_EvalCodeWithName + 414
	61  python                              0x0000000105e06783 _PyFunction_FastCallKeywords + 195
	62  python                              0x0000000105f43b27 call_function + 183
	63  python                              0x0000000105f41946 _PyEval_EvalFrameDefault + 46358
	64  python                              0x0000000105f351fe _PyEval_EvalCodeWithName + 414
	65  python                              0x0000000105e06783 _PyFunction_FastCallKeywords + 195
	66  python                              0x0000000105f43b27 call_function + 183
	67  python                              0x0000000105f417bc _PyEval_EvalFrameDefault + 45964
	68  python                              0x0000000105f351fe _PyEval_EvalCodeWithName + 414
	69  python                              0x0000000105e06783 _PyFunction_FastCallKeywords + 195
	70  python                              0x0000000105f43b27 call_function + 183
	71  python                              0x0000000105f417bc _PyEval_EvalFrameDefault + 45964
	72  python                              0x0000000105e06075 function_code_fastcall + 117
	73  python                              0x0000000105f43b27 call_function + 183
	74  python                              0x0000000105f417bc _PyEval_EvalFrameDefault + 45964
	75  python                              0x0000000105f351fe _PyEval_EvalCodeWithName + 414
	76  python                              0x0000000105e05587 _PyFunction_FastCallDict + 231
	77  python                              0x0000000105e094a2 method_call + 130
	78  python                              0x0000000105e06ef2 PyObject_Call + 130
	79  python                              0x0000000105f41a9d _PyEval_EvalFrameDefault + 46701
	80  python                              0x0000000105f351fe _PyEval_EvalCodeWithName + 414
	81  python                              0x0000000105e06783 _PyFunction_FastCallKeywords + 195
	82  python                              0x0000000105f43b27 call_function + 183
	83  python                              0x0000000105f4188d _PyEval_EvalFrameDefault + 46173
	84  python                              0x0000000105f351fe _PyEval_EvalCodeWithName + 414
	85  python                              0x0000000105f98760 PyRun_FileExFlags + 256
	86  python                              0x0000000105f97bd7 PyRun_SimpleFileExFlags + 391
	87  python                              0x0000000105fc57bf pymain_main + 9583
	88  python                              0x0000000105dd8bbd main + 125
	89  libdyld.dylib                       0x00007fff6011e08d start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6

<details>
 <summary>Full environment definition</summary>

### Operating system

MacOS Mojave 10.14.1

### Cartopy version

cartopy 0.17.0

### conda list

# packages in environment at /opt/anaconda/envs/python37:
#
appnope                   0.1.0                    py37_0
asn1crypto                0.24.0                   py37_0
backcall                  0.1.0                    py37_0
blas                      1.0                         mkl
blosc                     1.15.0               hd9629dc_0
bzip2                     1.0.6                h1de35cc_5
ca-certificates           2019.1.23                     0
cartopy                   0.17.0           py37haea56ea_1
certifi                   2019.3.9                 py37_0
cffi                      1.12.2           py37hb5b8e2f_1
cftime                    1.0.3.4          py37h1d22016_0
chardet                   3.0.4                    py37_1
cryptography              2.6.1            py37ha12b0ac_0
curl                      7.64.0               ha441bb4_2
cycler                    0.10.0                   py37_0
decorator                 4.3.2                    py37_0
freetype                  2.9.1                hb4e5f40_0
geos                      3.7.1                h0a44026_0
h5py                      2.9.0            py37h3134771_0
hdf4                      4.2.13               h39711bb_2
hdf5                      1.10.4               hfa1e0ec_0
icu                       58.2                 h4b95b61_1
idna                      2.8                      py37_0
intel-openmp              2019.1                      144
ipython                   7.3.0            py37h39e3cac_0
ipython_genutils          0.2.0                    py37_0
jedi                      0.13.3                   py37_0
jpeg                      9b                   he5867d9_2
kiwisolver                1.0.1            py37h0a44026_0
krb5                      1.16.1               hddcf347_7
libcurl                   7.64.0               h051b688_2
libcxx                    4.0.1                hcfea43d_1
libcxxabi                 4.0.1                hcfea43d_1
libedit                   3.1.20181209         hb402a30_0
libffi                    3.2.1                h475c297_4
libgfortran               3.0.1                h93005f0_2
libiconv                  1.15                 hdd342a3_7
libnetcdf                 4.6.1                hd5207e6_2
libpng                    1.6.36               ha441bb4_0
libssh2                   1.8.0                ha12b0ac_4
libtiff                   4.0.10               hcb84e12_2
libxml2                   2.9.9                hab757c2_0
libxslt                   1.1.33               h33a18ac_0
lxml                      4.3.2            py37hef8c89e_0
lzo                       2.10                 h362108e_2
matplotlib                3.0.3            py37h54f8f79_0
mkl                       2019.1                      144
mkl_fft                   1.0.10           py37h5e564d8_0
mkl_random                1.0.2            py37h27c97d8_0
ncurses                   6.1                  h0a44026_1
netcdf4                   1.4.2            py37h13743db_0
numexpr                   2.6.9            py37h7413580_0
numpy                     1.16.2           py37hacdab7b_0
numpy-base                1.16.2           py37h6575580_0
olefile                   0.46                     py37_0
openssl                   1.1.1b               h1de35cc_1
owslib                    0.17.1                     py_0
parso                     0.3.4                    py37_0
pexpect                   4.6.0                    py37_0
pickleshare               0.7.5                    py37_0
pillow                    5.4.1            py37hb68e598_0
pip                       19.0.3                   py37_0
proj4                     5.2.0                h0a44026_1
prompt_toolkit            2.0.9                    py37_0
ptyprocess                0.6.0                    py37_0
pycparser                 2.19                     py37_0
pyepsg                    0.4.0                    py37_0
pygeosci                  1.2.5                     <pip>
pygments                  2.3.1                    py37_0
pykdtree                  1.3.1            py37h1d22016_2
pyopenssl                 19.0.0                   py37_0
pyparsing                 2.3.1                    py37_0
pyproj                    1.9.6            py37h9c430a6_0
pyshp                     2.0.1                    py37_0
pysocks                   1.6.8                    py37_0
pytables                  3.4.4            py37h5bccee9_0
python                    3.7.2                haf84260_0
python-dateutil           2.8.0                    py37_0
pytz                      2018.9                   py37_0
readline                  7.0                  h1de35cc_5
requests                  2.21.0                   py37_0
scipy                     1.2.1            py37h1410ff5_0
setuptools                40.8.0                   py37_0
shapely                   1.6.4            py37he8793f5_0
six                       1.12.0                   py37_0
snappy                    1.1.7                he62c110_3
sqlite                    3.27.2               ha441bb4_0
tk                        8.6.8                ha441bb4_0
tornado                   6.0.1            py37h1de35cc_0
traitlets                 4.3.2                    py37_0
urllib3                   1.24.1                   py37_0
wcwidth                   0.1.7                    py37_0
wheel                     0.33.1                   py37_0
xz                        5.2.4                h1de35cc_4
zlib                      1.2.11               h1de35cc_3
zstd                      1.3.7                h5bba6e5_0

### pip list

Package          Version
---------------- -----------
appnope          0.1.0
asn1crypto       0.24.0
backcall         0.1.0
Cartopy          0.17.0
certifi          2019.3.9
cffi             1.12.2
cftime           1.0.3.4
chardet          3.0.4
cryptography     2.6.1
cycler           0.10.0
decorator        4.3.2
h5py             2.9.0
idna             2.8
ipython          7.3.0
ipython-genutils 0.2.0
jedi             0.13.3
kiwisolver       1.0.1
lxml             4.3.2
matplotlib       3.0.3
mkl-fft          1.0.10
mkl-random       1.0.2
netCDF4          1.4.2
numexpr          2.6.9
numpy            1.16.2
olefile          0.46
OWSLib           0.17.1
parso            0.3.4
pexpect          4.6.0
pickleshare      0.7.5
Pillow           5.4.1
pip              19.0.3
prompt-toolkit   2.0.9
ptyprocess       0.6.0
pycparser        2.19
pyepsg           0.4.0
pygeosci         1.2.5
Pygments         2.3.1
pykdtree         1.3.1
pyOpenSSL        19.0.0
pyparsing        2.3.1
pyproj           1.9.6
pyshp            2.0.1
PySocks          1.6.8
python-dateutil  2.8.0
pytz             2018.9
requests         2.21.0
scipy            1.2.1
setuptools       40.8.0
Shapely          1.6.4.post1
six              1.12.0
tables           3.4.4
tornado          6.0.1
traitlets        4.3.2
urllib3          1.24.1
wcwidth          0.1.7
wheel            0.33.1

</details>

**Comment by dopplershift** [comment]
Looks like you're on MacOS. Are you able to plot just using matplotlib:
```python
import matplotlib.pyplot as plt
plt.plot([1, 2], [3, 4])
plt.show()
```
?

**Comment by thelahunginjeet** [comment]
Grrr!  No, actually I can't.  I didn't even think of trying that.  Any ideas, or do I need to post this ticket over there?

**Comment by dopplershift** [comment]
If you're using conda-forge matplotlib, I'm guessing it's actually conda-forge/matplotlib-feedstock#200. If that's the case, feel free to chime in there.

**Comment by thelahunginjeet** [comment]
Thanks dopplershift - those hacks about changing the matplotlib backend worked for me.

**Comment by dopplershift** [comment]
Glad to hear it.
