### ISSUE TITLE
Checking of Proj-4.9 install in setup.py should check for newer versions from PATH

### ISSUE THREAD

**Issue by lsteadman** [SciTools/cartopy#1287]
The setup.py file checks to see which version of Proj is installed by calling pkg-config. If the user has installed proj from source to their user directory (in the case of shared environments, like HPC clusters), pkg-config returns saying an old version is installed but the user's own install isn't checked. 

To fix, find the most up-to-date version of proj using both 
`proj_version = subprocess.check_output(['pkg-config', '--modversion',
                                                'proj'],
                                               stderr=subprocess.STDOUT)`
and
`proj_version = find_proj_version_by_program()`

Then, check if either are new enough before exiting with error.

**Comment by QuLogic** [comment]
This is an environment inconsistency. You should set `PKG_CONFIG_PATH` to a location similar to the updated `PATH`, so that pkg-config finds your files.
