### ISSUE TITLE
Add Cartopy to Python 3 Statement

### ISSUE THREAD

**Issue by CAM-Gerlach** [SciTools/cartopy#1297]
### Description

As a corollary to #1186 , assuming Cartopy intends to stop supporting Python 2 by the January 1, 2020 deadline (as that issue seems to imply), as an important package used in the atmospheric science community, I suggest [adding](https://github.com/python3statement/python3statement.github.io) the project to the [Python3Statement](https://python3statement.org/), like most of the PyData stack and [MetPy](https://github.com/python3statement/python3statement.github.io/pull/123) have done, to make it easy and clear for users and downstream projects to find in one central place and help accelerate Python 3 adoption across the userbase.

Let me know if you'd like any help or have any questions. Thanks!

**Comment by CAM-Gerlach** [comment]
@pelson @QuLogic I've opened a draft PR in python3statement/python3statement.github.io#215 to illustrate; of course, it will not be merged without your explicit approval. Just let us know over there whether it looks good to you and if you want us to go ahead with it. Thanks!

**Comment by dopplershift** [comment]
I don't see any reason not to go ahead with it since we've established we're dropping Python 2 by that date.

**Comment by QuLogic** [comment]
This was done some time back.
