### ISSUE TITLE
Cartopy shift costline to the left when I plot contourf for three variables

### ISSUE THREAD

**Issue by mada0007** [SciTools/cartopy#1304]
### Description

When I plot two of the variables, I get the correct Image with the coastlines properly draw but the addition of a third shift the whole coastline to the right like this

#### Code to reproduce

```proj = ccrs.Mollweide(central_longitude=0, globe=None)
fig, axarr = plt.subplots( figsize=(12, 10),
                              subplot_kw=dict(projection=proj))
# = axarr.flatten()
    # APRIL TO SEPTEMBER
axarr.contourf(lon, lat, shift, transform=proj, cmap=cm.Reds,)
axarr.contourf(lon, lat, pskw, transform=proj, cmap=cm.Blues,)
axarr.contourf(lon, lat, nskw, transform=proj, cmap=cm.Greens,)
#axarr.contourf(lon, lat, Var, transform=proj, cmap=cm.Yellows,)
axarr.coastlines()

```

#### Traceback 

```

```

<details>
 <summary>Full environment definition</summary>

### conda list

```
```

### pip list

```
```

</details>

**Comment by dopplershift** [comment]
Can you add some synthetic/real data with full code to reproduce? There's almost no way we're going to be able to reproduce this otherwise.

**Comment by rcomer** [comment]
I’m going to close this one for lack of a reproducing example.
