### ISSUE TITLE
Some links are missing on the outline page

### ISSUE THREAD

**Issue by jypeter** [SciTools/cartopy#1322]
I wanted to read the _LatitudeFormatter_ and _LongitudeFormatter_ documentation on the [outline page](https://scitools.org.uk/cartopy/docs/latest/cartopy_outline.html), after checking the Ticks [labels example](https://scitools.org.uk/cartopy/docs/latest/gallery/tick_labels.html), but there are no links for documenting LatitudeFormatter and LongitudeFormatter (and other listed functions)

I reverted to using `help(LongitudeFormatter)` in my interpreter, but it would be nice to have this online too! :)

**Comment by lgolston** [comment]
This was fixed by #1652
