### ISSUE TITLE
Cartopy Not Found in Python 

### ISSUE THREAD

**Issue by pythonweather** [SciTools/cartopy#1351]
I apologize in advance as I know there are numerous topics on this issue. I have read through numerous topics and have done extensive google searching and I am getting absolutely nowhere. I will explain what I have done thus far. 

I originally tried to install Cartopy through pip...this yielded no success. Within the error message it said Proj version 0.0.0 is installed, but Cartopy requires at least version 4.9.0

Through Conda I made sure I had the latest Proj version installed and I even installed Cartopy through Conda and as far as I can tell it worked fine as I din't see any errors. 

When I go into python and do

import cartopy.crs as ccrs I receive an error message stating:

ModuleNotfoundError no module named Cartopy. 

I am in the beginning phases of learning Python and have very little background with computer programming which makes it difficult when trying to follow along information I come across. 

I've even downloaded OSGeo4w for Proj 4 and I have the latest version. I even installed the GEOS package which I came across. 

This is entirely frustrating..

**Comment by pythonweather** [comment]
Within python I did

pip list 

I did not see Cartopy

Within Anaconda I did

Conda list

Cartopy is there

It's just when I do

import cartopy.crs as ccrs I get the ModuleNotFoundError

**Comment by dopplershift** [comment]
Since you have Anaconda, let's stick with `conda` for now and ignore `pip`. What happens if you run: `which python` ? What OS are you on?

This may be better to discuss over on [Gitter](https://gitter.im/SciTools/cartopy).

**Comment by pythonweather** [comment]
I am using Windows 10.

When I run which python in Conda I receive this message"The term 'which' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. 

In case I did that in the incorrect program I also did it in a command window as well as within python.

**Comment by dopplershift** [comment]
Oh, on windows I think that should be `where python`. It might be easier to do this when you run Python:
```python
import sys
print(sys.prefix)
```

Just trying to confirm first that you're really running the version of Python you expect.

**Comment by pythonweather** [comment]
Conforming from both steps I am running Python 3.7!

**Comment by dopplershift** [comment]
I wasn't so much caring about the version as I wanted to see the output of `sys.prefix` to see if it's really picking up your Anaconda Python.

**Comment by pythonweather** [comment]
Sorry for the late reply. I am trying to do this at work and was obviously home for the weekend. But upon running that script this is what I am returned with

C:\Users\DELL-20\AppData\Local\Programs\Python\Python37

**Comment by pythonweather** [comment]
Here is a weird update...

I tried running Conda this morning and apparently it looked like it uninstalled. So I install Conda3 and with it came Spyder. I used the command conda install cartopy...it installed and installed numerous other packages. 

Within spyder cartopy works and I am getting plots. However, if I use the python command window I still get the cartopy not found message...weird...

but if I can do it through Spyder...AWESOME!

**Comment by dopplershift** [comment]
I'm not sure what the "python command window" you're using is doing, but I'm pretty sure it's not using anaconda, or at least not the one where you've installed cartopy. `C:\Users\DELL-20\AppData\Local\Programs\Python\Python37` does not look like a normal installed location for Anaconda Python. You should be running something like "Anaconda Prompt" to get there. But if you're happy with Spyder, great!

Regardless, this seems like a problem with straightening out the versions of Python you have installed on your system rather than a problem with CartoPy, so I'm going to close this out.

**Comment by pythonweather** [comment]
Awesome...so it sounds like I may be able to easily fix this? Sypder was yielding other issues. 

What I did was go into the Anaconda Prompt and did "conda install cartopy" everything installed!

Now...when I run my python shell I get the Cartopy not found...what do I do for the python shell to use the anaconda shell...this is where my ignorance with python shows as I don't know how to do this.

**Comment by dopplershift** [comment]
So if you want to run python with Anaconda, try going back to "Anaconda Prompt", then type `python`.

**Comment by pythonweather** [comment]
OMG...thank you so much!!! It worked...you have no clue how many hours I've spent on this over the past month. This is fantastic...I can't thank you enough.
