### ISSUE TITLE
Use a higher default zorder value for outline_patch ?

### ISSUE THREAD

**Issue by jypeter** [SciTools/cartopy#1364]
The current zorder of `outline_patch `(i.e the map border) is currently 2.5, which I think is too low
```
>>> bot_plot.outline_patch.get_zorder()
2.5
```
I have already found some cases where **the border of a plot was sometimes partly covered with the very edge of a plot** (must have been when I used coutourf or pcolormesh)

I have run into this problem again today when I tried to **plot white gridlines** going all the way to the edge of the plot (as is usually the case) with
```
bot_plot.gridlines(draw_labels=coord_labels_ok,
                   xlocs=np.arange(-180, 181., 60.),
                   ylocs=np.arange(-90., 91., 30.),
                   linestyle='--',
                   color='white',
                   linewidth=0.3,
                   zorder=20)
```
... and the edge gridlines were plotted over the top of the plot border
![outline_patch_priority](https://user-images.githubusercontent.com/2785573/64709608-d984b480-d4b6-11e9-96d7-d946d05101b2.png)
I could have tried to plot the gridlines with a lower zorder, but I also wanted to be sure that they appeared on top of everything (except the plot border)

My initial workaround was to skip the gridlines on the edges by using
```
                   xlocs=np.arange(-120, 121., 60.),
                   ylocs=np.arange(-60., 61., 30.),
```

but then I ran into the #1339 problem and my parallels/meridians did not extend all the way to the plot border

I finally solved my problem by overriding the outline_patch zorder with
```
# Make sure that the black outline of the plotting zone is plotted on
# top of everything
top_plot.outline_patch.set_zorder(50)
bot_plot.outline_patch.set_zorder(50)
```

This **outline_patch trick** is nice, but is not really documented on the cartopy, except indirectly in the [Hurricane Katrina example](https://scitools.org.uk/cartopy/docs/latest/gallery/hurricane_katrina.html?highlight=outline_patch). You can't expect a beginning user to find this... But using a higher default zorder value for outline_patch may do the trick. Unless this has side effects

**Comment by QuLogic** [comment]
In master, the `outline_patch` is gone and replaced by Matplotlib-equivalent `Spine`s, which are drawn after almost all artists, so it should work better then.

**Comment by dopplershift** [comment]
Should we call this fixed in master then?

**Comment by QuLogic** [comment]
I suppose so.
