### ISSUE TITLE
Truncation of Robinson projection

### ISSUE THREAD

**Issue by adamcpovey** [SciTools/cartopy#1367]
Using `set_extent` with a Robinson projection truncates the globe in an unexpected way:
```python
import matplotlib.pyplot as plt
import cartopy.crs as ccrs

ax = plt.axes(projection=ccrs.Robinson())
ax.coastlines()
ax.gridlines()
ax.set_extent((-180, 180, -60, 60), ccrs.PlateCarree())
plt.show()
```
![Figure_1](https://user-images.githubusercontent.com/24915701/65138261-98365c80-da02-11e9-9f01-6059e80b50bc.png)

No idea if it's an easy thing to fix, but I thought you should be aware of this intuitive behaviour.

<details> <summary> conda list </summary><blockquote>
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
antlr-python-runtime      4.7.2                 py36_1000    conda-forge
anytree                   2.6.0                    pypi_0    pypi
asn1crypto                0.24.0                py36_1003    conda-forge
astropy                   3.2.1            py36h516909a_0    conda-forge
atomicwrites              1.3.0                      py_0    conda-forge
attrs                     19.1.0                     py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
bleach                    3.1.0                      py_0    conda-forge
bokeh                     1.3.4                    py36_0    conda-forge
bzip2                     1.0.8                h516909a_1    conda-forge
ca-certificates           2019.9.11            hecc5488_0    conda-forge
cairo                     1.16.0            h18b612c_1001    conda-forge
cartopy                   0.17.0          py36h4331854_1006    conda-forge
certifi                   2019.9.11                py36_0    conda-forge
cf-units                  2.1.3            py36hc1659b7_0    conda-forge
cffi                      1.12.3           py36h8022711_0    conda-forge
cftime                    1.0.3.4         py36hd352d35_1001    conda-forge
chardet                   3.0.4                 py36_1003    conda-forge
cis                       1.7.1                    py36_0    conda-forge
click                     7.0                        py_0    conda-forge
cloudpickle               1.2.2                      py_0    conda-forge
cryptography              2.7              py36h72c5cf5_0    conda-forge
curl                      7.65.3               hf8cf82a_0    conda-forge
cycler                    0.10.0                     py_1    conda-forge
cytoolz                   0.10.0           py36h516909a_0    conda-forge
dask                      2.4.0                      py_0    conda-forge
dask-core                 2.4.0                      py_0    conda-forge
dbus                      1.13.6               he372182_0    conda-forge
decorator                 4.4.0                      py_0    conda-forge
defusedxml                0.5.0                      py_1    conda-forge
distributed               2.4.0                      py_0    conda-forge
eccodes                   2.12.3               h4fa793d_1    conda-forge
entrypoints               0.3                   py36_1000    conda-forge
expat                     2.2.5             he1b5a44_1003    conda-forge
ffmpeg                    4.1.3                h167e202_0    conda-forge
fontconfig                2.13.1            he4413a7_1000    conda-forge
freetype                  2.10.0               he983fc9_1    conda-forge
fsspec                    0.4.5                      py_0    conda-forge
geographiclib             1.49                       py_0    conda-forge
geopy                     1.20.0                     py_0    conda-forge
geos                      3.7.2                he1b5a44_2    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
giflib                    5.1.9                h516909a_0    conda-forge
glib                      2.58.3            h6f030ca_1002    conda-forge
gmp                       6.1.2             hf484d3e_1000    conda-forge
gnutls                    3.6.5             hd3a4fd2_1002    conda-forge
graphite2                 1.3.13            hf484d3e_1000    conda-forge
gst-plugins-base          1.14.5               h0935bb2_0    conda-forge
gstreamer                 1.14.5               h36ae1b5_0    conda-forge
h5py                      2.9.0           nompi_py36hf008753_1102    conda-forge
harfbuzz                  2.4.0                h37c48d4_1    conda-forge
hdf4                      4.2.13            h9a582f1_1002    conda-forge
hdf5                      1.10.4          nompi_h3c11f04_1106    conda-forge
heapdict                  1.0.0                 py36_1000    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
idna                      2.8                   py36_1000    conda-forge
importlib_metadata        0.23                     py36_0    conda-forge
ipykernel                 5.1.2            py36h5ca1d4c_0    conda-forge
ipython                   7.8.0            py36h5ca1d4c_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.5.1                      py_0    conda-forge
iris                      2.2.1                    py36_0    conda-forge
jasper                    1.900.1           h07fcdf6_1006    conda-forge
jedi                      0.15.1                   py36_0    conda-forge
jinja2                    2.10.1                     py_0    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
jsonschema                3.0.2                    py36_0    conda-forge
jupyter                   1.0.0                      py_2    conda-forge
jupyter_client            5.3.1                      py_0    conda-forge
jupyter_console           6.0.0                      py_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
jupyterthemes             0.20.0                     py_0    conda-forge
kiwisolver                1.1.0            py36hc9558a2_0    conda-forge
krb5                      1.16.3            h05b26f9_1001    conda-forge
lame                      3.100             h14c3975_1001    conda-forge
lesscpy                   0.13.0                     py_1    conda-forge
libaec                    1.0.4                hf484d3e_0    conda-forge
libblas                   3.8.0               12_openblas    conda-forge
libcblas                  3.8.0               12_openblas    conda-forge
libcurl                   7.65.3               hda55be3_0    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libiconv                  1.15              h516909a_1005    conda-forge
liblapack                 3.8.0               12_openblas    conda-forge
liblapacke                3.8.0               12_openblas    conda-forge
libnetcdf                 4.6.2             hbdf4f91_1001    conda-forge
libopenblas               0.3.7                h6e990d7_1    conda-forge
libpng                    1.6.37               hed695b0_0    conda-forge
libsodium                 1.0.17               h516909a_0    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.0.10            h57b8799_1003    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libwebp                   1.0.2                h576950b_1    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.9                h13577e0_2    conda-forge
locket                    0.2.0                      py_2    conda-forge
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
markupsafe                1.1.1            py36h14c3975_0    conda-forge
matplotlib                2.2.3            py36hb69df0a_0  
matplotlib-base           3.1.1            py36hfd891ef_0    conda-forge
mistune                   0.8.4           py36h14c3975_1000    conda-forge
more-itertools            7.2.0                      py_0    conda-forge
msgpack-python            0.6.1            py36h6bb024c_0    conda-forge
nb_conda                  2.2.1                    py36_2    conda-forge
nb_conda_kernels          2.2.2                    py36_0    conda-forge
nbconvert                 5.6.0                    py36_1    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
netcdf4                   1.5.1.2          py36had58050_0    conda-forge
nettle                    3.4.1             h1bed415_1002    conda-forge
notebook                  6.0.1                    py36_0    conda-forge
numpy                     1.17.2           py36h95a1406_0    conda-forge
nvector                   0.7.4                    pypi_0    pypi
olefile                   0.46                       py_0    conda-forge
opencv                    4.1.0            py36h5517eff_4    conda-forge
openh264                  1.8.0             hdbcaa40_1000    conda-forge
openssl                   1.1.1c               h516909a_0    conda-forge
owslib                    0.18.0                     py_0    conda-forge
packaging                 19.0                       py_0    conda-forge
pandas                    0.24.2           py36hb3f55d8_0    conda-forge
pandoc                    2.7.3                         0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.5.1                      py_0    conda-forge
partd                     1.0.0                      py_0    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pcre                      8.41              hf484d3e_1003    conda-forge
pexpect                   4.7.0                    py36_0    conda-forge
pickleshare               0.7.5                 py36_1000    conda-forge
pillow                    6.1.0            py36h6b7be26_1    conda-forge
pip                       19.2.3                   py36_0    conda-forge
pixman                    0.38.0            h516909a_1003    conda-forge
pluggy                    0.12.0                     py_0    conda-forge
ply                       3.11                       py_1    conda-forge
proj4                     6.1.1                hc80f0dc_1    conda-forge
prometheus_client         0.7.1                      py_0    conda-forge
prompt_toolkit            2.0.9                      py_0    conda-forge
psutil                    5.6.3            py36h516909a_0    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
py                        1.8.0                      py_0    conda-forge
pycparser                 2.19                     py36_1    conda-forge
pyepr                     0.9.5            py36h14c3975_0    avalentino
pyepsg                    0.4.0                      py_0    conda-forge
pygments                  2.4.2                      py_0    conda-forge
pygrib                    2.0.4            py36hf3f1b0b_0    conda-forge
pyhdf                     0.10.1           py36h3a4e923_1    conda-forge
pykdtree                  1.3.1           py36h3010b51_1002    conda-forge
pyke                      1.1.1                 py36_1000    conda-forge
pyopenssl                 19.0.0                   py36_0    conda-forge
pyparsing                 2.4.2                      py_0    conda-forge
pyproj                    2.3.1            py36h2fd02e8_0    conda-forge
pyqt                      5.9.2            py36hcca6a23_4    conda-forge
pyrsistent                0.15.4           py36h516909a_0    conda-forge
pyshp                     2.1.0                      py_0    conda-forge
pysocks                   1.7.0                    py36_0    conda-forge
pytest                    5.1.2                    py36_0    conda-forge
pytest-arraydiff          0.3                        py_0    conda-forge
pytest-astropy            0.5.0                      py_0    conda-forge
pytest-doctestplus        0.3.0                      py_1    conda-forge
pytest-openfiles          0.4.0                      py_0    conda-forge
pytest-remotedata         0.3.1                      py_0    conda-forge
python                    3.6.7             h357f687_1005    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
pytz                      2019.2                     py_0    conda-forge
pyyaml                    5.1.2            py36h516909a_0    conda-forge
pyzmq                     18.1.0           py36h1768529_0    conda-forge
qt                        5.9.7                h52cfd70_2    conda-forge
qtconsole                 4.5.5                      py_0    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
requests                  2.22.0                   py36_1    conda-forge
scipy                     1.3.1            py36h921218d_2    conda-forge
seaborn                   0.9.0                      py_1    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                41.2.0                   py36_0    conda-forge
shapely                   1.6.4           py36hec07ddf_1006    conda-forge
sip                       4.19.8          py36hf484d3e_1000    conda-forge
six                       1.12.0                py36_1000    conda-forge
sortedcontainers          2.1.0                      py_0    conda-forge
sqlite                    3.29.0               hcee41ef_1    conda-forge
statsmodels               0.10.1           py36hc1659b7_0    conda-forge
tblib                     1.4.0                      py_0    conda-forge
terminado                 0.8.2                    py36_0    conda-forge
testpath                  0.4.2                   py_1001    conda-forge
tk                        8.6.9             hed695b0_1003    conda-forge
toolz                     0.10.0                     py_0    conda-forge
tornado                   6.0.3            py36h516909a_0    conda-forge
traitlets                 4.3.2                 py36_1000    conda-forge
udunits2                  2.2.27.6          h4e0c4b3_1001    conda-forge
urllib3                   1.25.3                   py36_0    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.33.6                   py36_0    conda-forge
widgetsnbextension        3.5.1                    py36_0    conda-forge
windrose                  1.6.7                      py_0    conda-forge
x264                      1!152.20180806       h14c3975_0    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.8                h516909a_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
yaml                      0.1.7             h14c3975_1001    conda-forge
zeromq                    4.3.2                he1b5a44_2    conda-forge
zict                      1.0.0                      py_0    conda-forge
zipp                      0.6.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
zstd                      1.4.0                h3b9ef0a_0    conda-forge
</blockquote>
</details>

**Comment by dopplershift** [comment]
Thanks for the report. That's *ahem* interesting behavior.

**Comment by QuLogic** [comment]
While not quite intuitive, this is expected. `GeoAxes.set_extent` takes the 4 boundaries you give it, makes a 4-point box out of it, transforms those 4 points, and then sets the limits based on the min/max of those points. It does _no interpolation_, so has no idea that 180 in PlateCarree extends further to the right in Robinson.

See also #697.

**Comment by QuLogic** [comment]
Closing as it's essentially the issue I noted above.
