### ISSUE TITLE
central_latitude does not work for conic projection???

### ISSUE THREAD

**Issue by ildoildi** [SciTools/cartopy#1375]
### Description

central_latitude function does not work for conic projections: Albers Equal Area, Equidistant Conic and Lambert Conformal.

#### Code to reproduce
from tkinter import*
from matplotlib import*
from cartopy import*
from tkinter import ttk
from tkinter import filedialog
from tkinter import messagebox
import cartopy.crs as alfa
import cartopy.feature as cfeature
import matplotlib.pyplot as amarildo
import requests, os, sys, zipfile, shutil, subprocess
import numpy
import pandas
import shapefile as shp
import seaborn as beta
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg
from matplotlib.figure import Figure

entry_4 = ttk.Entry(canvas1)
canvas1.create_window(95, 280, window=entry_4)
centrlon = float(entry_4.get())
if name =='Conic' and a =='AlbersEqualArea':
ax = amarildo.axes(projection=alfa.AlbersEqualArea(central_longitude = centr, central_latitude = centrlon))
        ax.set_global()
        ax.stock_img()
        ax.coastlines()
        ax.gridlines()
        amarildo.show()
```

```

#### Traceback 

```

```

<details>
 <summary>Full environment definition</summary>

### Operating system
Windows 10

### Cartopy version
0.17 Cartopy version

### conda list

```
```

### pip list

```
```

</details>

**Comment by ildoildi** [comment]
Figure is created but changing latitude does not give any change on it, it remain static, only longitude works

**Comment by dopplershift** [comment]
`central_latitude` only affects the origin of the plot, so only matters if you're plotting "externally" projected values onto a given map. What you're looking for, I think, is `standard_parallels`:
```python
fig = plt.figure()
for ind, lat in enumerate((10, 25, 45, 60)):
    proj = ccrs.LambertConformal(central_latitude=lat,
        central_longitude=-100, standard_parallels=(lat,))
    ax = fig.add_subplot(2, 2, ind + 1, projection=proj)
    ax.coastlines('50m')
    ax.set_extent((-130, -60, 15, 55))
    ax.gridlines()
```
gives me:
![image](https://user-images.githubusercontent.com/221526/66347999-c37dde80-e912-11e9-9ca3-0b5e29ed9a1d.png)

**Comment by ildoildi** [comment]
I try to put standard parallels and now its working
