### ISSUE TITLE
Cartopy and PROJ4- python 2 only

### ISSUE THREAD

**Issue by mccronep** [SciTools/cartopy#1379]
### Description
We are being directed to upgrade from PROJ4 to PROJ5. We made a test version of Python 2 that uses PROJ5. The basemap works ok. Cartopy seems to needs proj4. 

We are intending to keep legacy code running in python 2, we are trying to move to python 3, but this takes a while. Need help here.

Is Cartopy in py2 dependent on PROJ4?

Please contact me at paul@mccrones.com

#### Code to reproduce

```

```

#### Traceback 

```

```

<details>
 <summary>Full environment definition</summary>

### conda list

```
```

### pip list

```
```

</details>

**Comment by mccronep** [comment]
1838 a4au-a901:/satdat/bin > ${PYTHONDIR}/python -W ignore ${RUNDIR}/process_nport_GOES16_ir_nc4_TIRS13_PAX_ze.py
Traceback (most recent call last):
  File "/satdat/bin/process_nport_GOES16_ir_nc4_TIRS13_PAX_ze.py", line 70, in <module>
    import cartopy.feature as cfeat
  File "/opt/global/python/2.7.9-fnmoc/lib/python2.7/site-packages/cartopy/__init__.py", line 107, in <module>
    import cartopy.crs
  File "/opt/global/python/2.7.9-fnmoc/lib/python2.7/site-packages/cartopy/crs.py", line 36, in <module>
    from cartopy._crs import CRS, Geodetic, Globe, PROJ4_VERSION
ImportError: libproj.so.12: cannot open shared object file: No such file or directory

**Comment by dopplershift** [comment]
The current released version of CartoPy depends on proj4. This has been merged in #1289 , but has not been released yet.

**Comment by QuLogic** [comment]
Cartopy depends on Proj 8 now, and no longer supports Python 2.
