### ISSUE TITLE
Cartopy crashes when attempting to project data on macOS

### ISSUE THREAD

**Issue by MarkWieczorek** [SciTools/cartopy#1392]
I am attempting to use cartopy on macOS (python 3.7), but it seems to be extremely unstable, and crashes all the time. Here is one simple example where stock_img() crashes:

```
In [1]: import cartopy.crs as ccrs
   ...: import matplotlib.pyplot as plt
   ...:
   ...: ax = plt.axes(projection=ccrs.Mollweide())
   ...: ax.stock_img()
Assertion failed: (0), function query, file AbstractSTRtree.cpp, line 287.
[1]    11950 abort      ipython
```
Using `projection=ccrs.Orthographic(-80, 35)` crashes as well, but `projection=ccrs.PlateCarree()` works fine.

For info, here is how I installed cartopy on my system.
```
pip3 install --upgrade cython numpy shapely pyshp six
brew install proj geos
pip3 install git+https://github.com/SciTools/cartopy.git --no-binary cartopy # installing from pypi does not work.
```
I should note that I have never been able to get cartopy to work in the past, so this is not a simple problem related to some sort of system update that broke something.

**Comment by MarkWieczorek** [comment]
Here's another example using coastline that gives a less informative error:
```
In [1]: import cartopy.crs as ccrs
   ...: import matplotlib.pyplot as plt
   ...: plt.figure(figsize=(6, 3))
   ...: ax = plt.axes(projection=ccrs.PlateCarree())
   ...: ax.set_global()
   ...: ax.coastlines()
Out[1]: <cartopy.mpl.feature_artist.FeatureArtist at 0x139038690>

In [2]: [1]    13242 bus error  ipython
```

**Comment by dopplershift** [comment]
Ok, so this same code works for me on macOS 10.15 and Python 3.7.3 and CartoPy 0.17.0 from conda-forge. My guess is that your problem comes from having the binary (wheel) Shapely install, which causes Shapely and CartoPy to be compiled against different versions of geos. Can you try this for your install process:

```
pip3 install --upgrade cython numpy pyshp six
brew install proj geos
pip3 install --upgrade --no-binary shapely
pip3 install git+https://github.com/SciTools/cartopy.git --no-binary cartopy
```

**Comment by MarkWieczorek** [comment]
That works. Thanks!

Would it be possible to put these install instructions somewhere in the web documentation or readme file? Though many people use conda, not everyone does. Over the past several years, it appears to have gotten easier to install cartopy, but it is still one of the trickier packages I use.

Here are the complete instructions:

```
# Install proj and geos using brew
brew install proj geos
# If shapely is already installed, first uninstall it
pip3 uninstall shapely
# Install the cython, numpy, pyshp, and six dependencies using pip
pip3 install --upgrade cython numpy pyshp six
# Install shapely from source with pip (the binary may not be linked to the correct version of geos
pip3 install shapely --no-binary shapely
# Finally, install cartopy using pip. The version on pypi does not yet work with the most recent
# release of proj, so instead install cartopy from source using the most recent version on github
pip3 install git+https://github.com/SciTools/cartopy.git --no-binary cartopy
```

**Comment by dopplershift** [comment]
Yeah, including these in the install guide is probably a good idea. Interested in making a Pull Request to https://github.com/SciTools/cartopy/blob/master/INSTALL ?

**Comment by MarkWieczorek** [comment]
https://github.com/SciTools/cartopy/pull/1396

**Comment by SherryStudio** [comment]
Thanks a lot!
