### ISSUE TITLE
Cartopy Install Error on Raspbian

### ISSUE THREAD

**Issue by carterhumphreys** [SciTools/cartopy#1393]
### Description
When attempting to install cartopy via pip3 I get the error below. I've already attempted to correct by doing `pip3 install --upgrade setuptools` with no luck.

#### Code to reproduce

```
$ sudo pip3 install cartopy

```

#### Traceback 

```
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting cartopy
  Using cached https://files.pythonhosted.org/packages/e5/92/fe8838fa8158931906dfc4f16c5c1436b3dd2daf83592645b179581403ad/Cartopy-0.17.0.tar.gz
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    /tmp/pip-install-4ee559ob/cartopy/setup.py:171: UserWarning: Unable to determine GEOS version. Ensure you have 3.3.3 or later installed, or installation may fail.
      '.'.join(str(v) for v in GEOS_MIN_VERSION), ))
    /tmp/pip-install-4ee559ob/cartopy/setup.py:227: UserWarning: Unable to determine Proj version. Ensure you have 4.9.0 or later installed, or installation may fail.
      '.'.join(str(v) for v in PROJ_MIN_VERSION), ))
    Proj version 0.0.0 is installed, but cartopy requires at least version 4.9.0.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-4ee559ob/cartopy/

```

<details>
 <summary>Full environment definition</summary>

### Operating system
Raspbian GNU/Linux 10

### Cartopy version
0.17.0

</details>

**Comment by dopplershift** [comment]
You need to [install](https://scitools.org.uk/cartopy/docs/latest/installing.html#installing) the PROJ and GEOS libraries on your system before cartopy can build. These are non-Python libraries that need to be installed using your OS package manager. On Raspbian, (I think) that's `apt`, so try something like:
```
apt-get install libproj-dev libgeos-dev
```
which should install the libraries and the development headers.

**Comment by carterhumphreys** [comment]
That did it, thank you!! I was trying to install those with pip rather than as an OS package, thus not getting anywhere.

________________________________
