### ISSUE TITLE
Add a "Table of Contents" to the web documentation

### ISSUE THREAD

**Issue by MarkWieczorek** [SciTools/cartopy#1397]
**Problem**
It is very difficult to understand how the web documentation is organized, what documentation exists, and how to navigate the documentation. There is no table of contents, and the only way to discover what documentation actually exists is to (1) click continuously on the "next topic" to go through all pages in order, (2) "search" and hope you get lucky, (3) use the "index" that provides a list that is way too long to read, or (4) use the "outline" which provides information that is not easy to understand.

**Solution: Add a table of contents**
It would be very easy to add a table of contents and to add a prominent link to this in the top navigation bar. My proposal would be to remove the "outline" link at the top of the page, and replace this with a "Table of Contents" link. I would probably also remove the "index" as well as I suspect people don't use this. You could also remove the redundant "next" on the top bar as this link is already present in the right sidebar. Finally, I would probably rename the "table of contents" in the side bar to simply "contents".

**Comment by dopplershift** [comment]
Good ideas, though probably depends on the implementation (as far as what it actually looks like. I'm definitely in favor PRs from anyone improving the docs.

**Comment by lgolston** [comment]
Fixed by #1652
