### ISSUE TITLE
Segfault with streamplot

### ISSUE THREAD

**Issue by julietbravo** [SciTools/cartopy#1399]
### Description
The streamplot example from here: https://scitools.org.uk/cartopy/docs/latest/gallery/streamplot.html fails with a segfault on MacOS. I read that many of these problems are Shapely related, I already (re-)installed that using:

```
pip uninstall shapely && pip install --no-binary :all: shapely
```

Beyond this segfault, Cartopy works without any problems. 

#### Code to reproduce

```
import matplotlib.pyplot as plt

import cartopy.crs as ccrs
from cartopy.examples.arrows import sample_data


def main():
    fig = plt.figure(figsize=(10, 5))
    ax = fig.add_subplot(1, 1, 1, projection=ccrs.PlateCarree())
    ax.set_extent([-90, 75, 10, 85], crs=ccrs.PlateCarree())
    ax.coastlines()

    x, y, u, v, vector_crs = sample_data(shape=(80, 100))
    magnitude = (u ** 2 + v ** 2) ** 0.5
    ax.streamplot(x, y, u, v, transform=vector_crs,
                  linewidth=2, density=2, color=magnitude)
    plt.show()


if __name__ == '__main__':
    main()
```

#### Traceback 

Output of `python3 -q -X faulthandler cartopy_crash.py`:

```
Fatal Python error: Segmentation fault

Current thread 0x00007fffe1a0a3c0 (most recent call first):
  File "/usr/local/lib/python3.7/site-packages/scipy/interpolate/ndgriddata.py", line 222 in griddata
  File "/usr/local/lib/python3.7/site-packages/cartopy/vector_transform.py", line 68 in _interpolate_to_grid
  File "/usr/local/lib/python3.7/site-packages/cartopy/vector_transform.py", line 146 in vector_scalar_to_grid
  File "/usr/local/lib/python3.7/site-packages/cartopy/mpl/geoaxes.py", line 1897 in streamplot
  File "cartopy_crash.py", line 16 in main
  File "cartopy_crash.py", line 21 in <module>
Segmentation fault: 11
```

<details>
 <summary>Full environment definition</summary>

### Operating system
MacOS Sierra

### Cartopy version
0.17.0, using Python 3.7.4

</details>

**Comment by julietbravo** [comment]
Seems to be a problem with Scipy's `LinearNDInterpolator`, but its difficult to reproduce on other systems with slightly different version number of Scipy, Numpy, ....
I've posted a more minimal example/bugreport here: https://github.com/scipy/scipy/issues/11088

**Comment by dopplershift** [comment]
I'm going to close this because it seems to be purely a SciPy issue. Please do re-open if you find there's something that's broken in CartoPy itself.
