### ISSUE TITLE
Problem drawing geodetic polygon on map

### ISSUE THREAD

**Issue by AgilentGCMS** [SciTools/cartopy#1403]
### Description
I am trying to draw a geodetic polygon on a map projection following the examples [here](https://scitools.org.uk/cartopy/docs/v0.5/matplotlib/introductory_examples/02.polygon.html). Since my polygons are not rectangles, I tried using Polygon patches instead of Rectangle (the title of that page says "Drawing a geodetic polygon", so I thought that should work). However, the resultant polygon is not drawn using great circles, and have more vertices than I specified.

#### Code to reproduce
```
import numpy as np
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import matplotlib.patches as mpatches

map_proj = ccrs.Orthographic(central_latitude=0.0, central_longitude=80.0)
ax = plt.axes(projection=map_proj)

ax.set_global()
ax.gridlines()

ax.coastlines(linewidth=0.5, color='k', resolution='50m')

lat_corners = np.array([-20.,  0., 50., 30.])
lon_corners = np.array([ 20., 90., 90., 30.]) + 15.0

poly_corners = np.zeros((len(lat_corners), 2), np.float64)
poly_corners[:,0] = lon_corners
poly_corners[:,1] = lat_corners

poly = mpatches.Polygon(poly_corners, closed=True, ec='r', fill=False, lw=1, fc=None, transform=ccrs.Geodetic())
ax.add_patch(poly)
```

#### Result
[View image here](https://i.stack.imgur.com/JIAdy.png)

### Operating system
Ubuntu 18.04.3 (amd64)

### Cartopy version
0.17.1.dev172+

**Comment by ajdawson** [comment]
I think this is an artefact of the transform resolution associated with this projection being too low. It is set as `np.diff(self._x_limits)[0] * 0.02` which is quite coarse, especially for a global domain. A lower threshold produces a much nicer image:

![nice](https://user-images.githubusercontent.com/390602/69537469-191c5200-0f78-11ea-898d-8e96f57ae0dc.png)

```python
import numpy as np
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import matplotlib.patches as mpatches

map_proj = ccrs.Orthographic(central_latitude=0.0, central_longitude=80.0)
map_proj._threshold /= 100.
ax = plt.axes(projection=map_proj)

ax.set_global()
ax.gridlines()

ax.coastlines(linewidth=0.5, color='k', resolution='50m')

lat_corners = np.array([-20.,  0., 50., 30.])
lon_corners = np.array([ 20., 90., 90., 30.]) + 15.0

poly_corners = np.zeros((len(lat_corners), 2), np.float64)
poly_corners[:,0] = lon_corners
poly_corners[:,1] = lat_corners

poly = mpatches.Polygon(poly_corners, closed=True, ec='r', fill=False, lw=1, fc=None, transform=ccrs.Geodetic())
ax.add_patch(poly)
```

**Comment by AgilentGCMS** [comment]
OK, that fixed it, thanks! Perhaps there should be a more robust way to calculate the number of intermediate points? I realize this is non-trivial, because it's projection-dependent and domain-dependent.

**Comment by QuLogic** [comment]
Yes, that request is #8, but I don't think anyone is working on it.
