### ISSUE TITLE
How to run all unit tests?

### ISSUE THREAD

**Issue by kacmak7** [SciTools/cartopy#1405]
Hi, I couldn't find anything about how to run all unit tests at once locally. I tried `python -m pytest` and got `ModuleNotFoundError: No module named 'cartopy._crs'`.

**Comment by dopplershift** [comment]
You need to first build and install the package first. That's most easily done by:
```
pip install -ve .
```
See more information in the [installation instructions](https://scitools.org.uk/cartopy/docs/latest/installing.html#building-from-source).

After that, `python -m pytest` should work.

**Comment by kacmak7** [comment]
yeah, it's working fine. Thanks!

**Comment by PhilipeRLeal** [comment]
Dear @dopplershift, how do you suggest to install the package in Windows? The "pip install -ve ." does not work for it.

Sincerely,

**Comment by dopplershift** [comment]
@PhilipeRLeal That does not seem related to this issue, so can you please open a new issue?

**Comment by PhilipeRLeal** [comment]
Dear @dopplershift, thank you for your reply. 

Nevertheless, this is exactly the issue discued in here. I wish to properly install a local cartopy (git clone cartopy...) version in my computer (which is in Windows), and apply the tests within the package (i.e.: "python -m pytest").

Apparently, there are some issues regarding how to properly install it using the recomendations provided in the cartopy main [page](https://scitools.org.uk/cartopy/docs/latest/installing.html#installing):

'''
...
# you can clone the git repo on your computer and install manually using the setup.py file:

git clone https://github.com/SciTools/cartopy.git
cd cartopy

# Uncomment the following to specify non-standard include and library paths

python setup.py build_ext -I/path/to/include -L/path/to/lib
python setup.py install
'''
For instance, what are the meaning of the "-I/path/to/include" and "-L/path/to/lib" for the setup.py build_ext?

All I understand is that one can use the following options for build_ext:

"python setup.py build_ext --inplace"

"python setup.py build_ext -i"

**Comment by guziy** [comment]
It would be nice if I could test a local build without installing it. 

I tried the following 

```bash
python setup.py build
export PYTHONPATH=./build/lib.linux-x86_64-3.9/:$PYTHONPATH
pytest
```

but no luck, I get the following error:

```bash
lib/cartopy/__init__.py:7: in <module>
    from ._version import version as __version__  # noqa: F401
E   ModuleNotFoundError: No module named 'cartopy._version'
```

**Comment by QuLogic** [comment]
Create a new venv if you need isolation; messing with `PYTHONPATH` is fragile.

**Comment by guziy** [comment]
Thanks I ended up creating a conda environment as described in `environment.yml` (cartopy-dev), I had to downgrade the geos version for pytest to work otherwize tests fail python process. And yes had to install cartopy to be able to test..
