### ISSUE TITLE
set_extent ValueError: Failed to determine the required bounds 

### ISSUE THREAD

**Issue by danbr890** [SciTools/cartopy#1407]
No matter what I try, I always get the same set_extent error when attempting to use OSM projections.

Even this simple code throws this error:

```
    request = OSM()
    ax = plt.axes(projection=request.crs)
    extent = [-89, -88, 41, 42]  # (xmin, xmax, ymin, ymax)
    ax.set_extent(extent)
    ax.add_image(request, 8)
```

`ValueError: Failed to determine the required bounds in projection coordinates. Check that the values provided are within the valid range (x_limits=[-3.141592653589793, 3.141592653589793], y_limits=[-1.4844222297453324, 1.4844222297453324]).`

I've tried converting the x/y to radians, formating the xy/min/max's into lists/sets and still no go.
I did have some difficultly installing cartopy, could it be a dependency issue?

**Comment by htonchia** [comment]
I have added that line to the code above:
`
from cartopy.io.img_tiles import OSM
`
I have tried the code above with the latest version of cartopy.io.img_tiles and it works, well it plots a map without any error message.
![Figure_9](https://user-images.githubusercontent.com/54799451/70261626-1d741680-1793-11ea-9b3e-f81790ce81e2.png)

With an older version, I get errors, but not that one.
Can you confirm that you are using the version of cartopy.io.img_tiles currently available on GitHub?

I have installed cartopy using conda, but as it doesn't include the latest modifications, I have changed myself cartopy.io.img_tiles to the latest version.

**Comment by danbr890** [comment]
I'm not quite sure where/when my install went wrong, but reinstalling both cartopy and Cython from source fixed the issue.
