### ISSUE TITLE
Typo of ISO3 country code

### ISSUE THREAD

**Issue by soma-funahashi** [SciTools/cartopy#1434]
### Description
Though this is a tiny issue, I found one typo in the country codes. South Sudan's country code should be 'SSD', but it seems like 'SDS' in cartopy shpreader.
Reference : https://www.iso.org/obp/ui/#search

#### Code to reproduce

```
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import cartopy.feature as cfeature
import cartopy.io.shapereader as shpreader

def area(ax, iso, clr) :
    shp = shpreader.natural_earth(resolution='50m',category='cultural',
                                  name='admin_0_countries')
    reader = shpreader.Reader(shp)
    for n in reader.records():
        print(n.attributes['NAME_EN'],n.attributes['ADM0_A3'])
        if n.attributes['ADM0_A3'] == iso: 
            ax.add_geometries(n.geometry, ccrs.PlateCarree(), facecolor=clr, 
                              alpha = 1.00, linewidth =0.15, edgecolor = "black",
                              label=n.attributes['ADM0_A3']) 
    return ax

iso3 = ['SSD']

plt.figure()
countries_50m  = cfeature.NaturalEarthFeature('cultural', 'admin_0_countries', '50m', edgecolor='gray', facecolor='none', linewidth=0.1)
ax = plt.subplot(1, 1, 1, projection=ccrs.PlateCarree())
ax.outline_patch.set_linewidth(1)
ax.set_extent([-30, 90, -60, 60], ccrs.PlateCarree())
ax.coastlines(resolution='50m', linewidth=0.5)
ax.add_feature(countries_50m)

for n in iso3 :
    area(ax, n, "red")

plt.show()
```
Then the fig is as follows.
![image](https://user-images.githubusercontent.com/40226162/71826636-b45d2700-30e1-11ea-890d-fe8195890a96.png)

But if I change the country code 'SSD' into 'SDS', the fig is like this.
![image](https://user-images.githubusercontent.com/40226162/71826659-bd4df880-30e1-11ea-955e-bf2a225c13da.png)

**Comment by ajdawson** [comment]
Thanks for taking the time to report this. However, this is not something inside of Cartopy, it appears to be part of the shapefile metadata from the [Natural Earth dataset](https://www.naturalearthdata.com/downloads/10m-cultural-vectors/10m-admin-0-countries/). Cartopy is just retrieving the shapefile for you, the contents of the files is the responsibility of the folks at Natural Earth. For what it is worth I found [this listing](https://discovery.opendatasoft.com/explore/dataset/natural-earth-countries-1-110m/table/) of the Natural Earth shapefile in question which shows SDS and not SSD.

**Comment by greglucas** [comment]
Great links @ajdawson. As a followup, the attribute in the original question is actually just looking at the wrong value. It should be: `ISO_A3` rather than `ADM0_A3`

**Comment by soma-funahashi** [comment]
Thank you for your information and sorry for telling non-related issue.
@greglucas  I confirmed that "SSD" represented South Sudan with `ISO_A3`.
Thank you for your kind and quick comments!
