### ISSUE TITLE
Setting extent is not easy when central_longitude=180

### ISSUE THREAD

**Issue by ahuang11** [SciTools/cartopy#1446]
https://stackoverflow.com/questions/59584276/cartopy-set-extent-with-central-longitude-180

Cartopy 0.17.0: When I set central_longitude, I don't know how to set the extents exactly provided:

```
import matplotlib.pyplot as plt
import cartopy.crs as ccrs

projection = ccrs.PlateCarree(central_longitude=180)
ax = plt.axes(projection=projection)
ax.coastlines()
ax.set_extent((-120, 120, -45, 45), crs=ccrs.PlateCarree())
ax.gridlines(draw_labels=True, crs=ccrs.PlateCarree())
```
![image](https://user-images.githubusercontent.com/15331990/73213305-90579900-4115-11ea-8d82-a68930248c41.png)

This subsets longitudes correctly, but has extra labels:
```
import matplotlib.pyplot as plt
import cartopy.crs as ccrs

projection = ccrs.PlateCarree(central_longitude=180)
ax = plt.axes(projection=projection)
ax.coastlines()
ax.set_extent((-120, 120, -45, 45))
ax.gridlines(draw_labels=True, crs=ccrs.PlateCarree())
```
![image](https://user-images.githubusercontent.com/15331990/73213376-b2511b80-4115-11ea-8d74-35012865687d.png)

**Comment by QuLogic** [comment]
Your second example works on `master`, so this was probably fixed by one of the gridliner PRs.
