### ISSUE TITLE
Plotting data on map works only in sequential programming.

### ISSUE THREAD

**Issue by wxguy** [SciTools/cartopy#1448]
I have installed cartopy from pip using Arch Linux. The packages are up to date. I am trying to plot simple sample `slp` examples given in the official documentation from here https://wrf-python.readthedocs.io/en/latest/plot.html using cartopy. I copied the code in to text editor and run the file. It produced the image as intended. However, I would like to segregate plotting map and data in to two separate functions so that data plotting is made easy for large number of variables. Here is the sample functions I have created:-

```
#!/usr/bin/env python3
from wrf import latlon_coords, to_np, get_cartopy, getvar, smooth2d, cartopy_xlim, cartopy_ylim
from netCDF4 import Dataset
import matplotlib.pyplot as plt
from cartopy.feature import NaturalEarthFeature, LAND, COASTLINE
from cartopy.mpl.gridliner import LONGITUDE_FORMATTER, LATITUDE_FORMATTER
import numpy as np
from datetime import datetime 

in_file = "/media/sundar/Data/WRF_DATA/wrfout_d03_2016-04-08_12_00_00"
in_nc_file = Dataset(in_file)

def plot_map_boundary(wrd_data, extent=False, stock_image=False):
    proj = get_cartopy_proj(wrd_data)
    fig, ax = plt.subplots(figsize=(8, 6), subplot_kw=dict(projection=proj))
    if stock_image is True:
        ax.stock_img()
    #ax.add_feature(LAND)
    ax.coastlines('50m', linewidth=0.8)
    gl = ax.gridlines(draw_labels=True)
    gl.xlabels_top = False
    gl.ylabels_right = False
    gl.xformatter = LONGITUDE_FORMATTER
    gl.yformatter = LATITUDE_FORMATTER
    
    # plt.savefig('test_netcdf.png', bbox_inches='tight')
    return fig, ax

def plot_wrf_data(wrf_data, wrf_var, fcst_day=None, subregion=False, resolution='med',
                  contour=True, cfill=False):
    data = get_wrf_var(wrf_data, wrf_var)
    smooth_slp = smooth2d(data, 3, cenweight=4)
    lats, lons = get_lat_lon(data)
    #proj = get_cartopy_proj(data)
    #print('proj', proj)
    fig, ax = plot_map_boundary(data)
    #ax = plt.axes(projection=proj)
    ax = plot_title(ax, get_title(wrf_var))
    cs = ax.contour(to_np(lons), to_np(lats), to_np(smooth_slp))
    plt.show()

    return fig, ax

plot_wrf_data(in_nc_file, 'slp')
```

This produces the below image with out plotting actual data:-
![test_netcdf](https://user-images.githubusercontent.com/9054645/73365032-96927480-42d1-11ea-9c48-bb930dc82bb3.png)

Is there anything I am missing? Any help to solve the issue is appreciated.

**Comment by QuLogic** [comment]
>     cs = ax.contour(to_np(lons), to_np(lats), to_np(smooth_slp))

If these are truly longitude and latitude, then you need to pass the `transform` specifying the projection of your data, otherwise it is expected to be in the units of the projection you are plotting (which is likely metres.)

**Comment by wxguy** [comment]
@QuLogic ,
Yup. You are correct. Thanks for pointing out the mistake.
