### ISSUE TITLE
Proj4Error: Error from proj: b'lat_0, lat_1 or lat_2 >= 90'

### ISSUE THREAD

**Issue by leeprevost** [SciTools/cartopy#1450]
### Description
I am using Geoplot and when I try to create a kdeplot, Cartopy throws this error.    I've also tried rolling back/downgrading Cartopy.

```
geoplot.kdeplot(sf_home_sales_19.geometry.centroid, shade=True, clip = wake_shp.geometry, cmap="Reds", projection=geoplot.crs.AlbersEqualArea())

```

My geodataframe has standard point geometries with the following min/max bounds:

```
minx, miny, maxx, maxy = sf_home_sales_19.geometry.centroid.total_bounds
minx, miny, maxx, maxy
```
(2012917.9711255452, 649985.8803260227, 2213722.8048523366, 837421.6407012716)
 3 geoplot.kdeplot(sf_home_sales_19.geometry.centroid, shade=True, clip = wake_shp.geometry, cmap="Reds", projection=geoplot.crs.AlbersEqualArea())
      4 #geoplot.polyplot(wake_highways, ax=ax, zorder=1)

~\Anaconda3\lib\site-packages\geoplot\geoplot.py in kdeplot(df, projection, extent, figsize, ax, clip, shade_lowest, **kwargs)
   1323         df, projection=projection, extent=extent, figsize=figsize, ax=ax, clip=clip,
   1324         shade_lowest=shade_lowest,
-> 1325         **kwargs
   1326     )
   1327     return plot.draw()

~\Anaconda3\lib\site-packages\geoplot\geoplot.py in __init__(self, df, **kwargs)
   1291     class KDEPlot(Plot, HueMixin, LegendMixin, ClipMixin):
   1292         def __init__(self, df, **kwargs):
-> 1293             super().__init__(df, **kwargs)
   1294             self.set_hue_values(
   1295                 color_kwarg=None, default_color=None, supports_categorical=False,

~\Anaconda3\lib\site-packages\geoplot\geoplot.py in __init__(self, df, **kwargs)
    602         self.projection = kwargs.pop('projection')
    603         # TODO: init_axis() -> init_axis(ax)
--> 604         self.init_axis()
    605         self.kwargs = kwargs
    606 

~\Anaconda3\lib\site-packages\geoplot\geoplot.py in init_axis(self)
    632             self.projection = self.projection.load(self.df, {
    633                 'central_longitude': central_longitude,
--> 634                 'central_latitude': central_latitude
    635             })
    636 

~\Anaconda3\lib\site-packages\geoplot\crs.py in load(self, df, centerings)
     77             return WebMercator(self.args)
     78         else:
---> 79             return getattr(ccrs, self.__class__.__name__)(**{**centerings, **self.args})
     80 
     81     def _as_mpl_axes(self):

~\Anaconda3\lib\site-packages\cartopy\crs.py in __init__(self, central_longitude, central_latitude, false_easting, false_northing, standard_parallels, globe)
   2212                 proj4_params.append(('lat_1', standard_parallels))
   2213 
-> 2214         super(AlbersEqualArea, self).__init__(proj4_params, globe=globe)
   2215 
   2216         # bounds

lib\cartopy\_crs.pyx in cartopy._crs.CRS.__init__()

Proj4Error: Error from proj: b'lat_0, lat_1 or lat_2 >= 90'

<Figure size 576x432 with 0 Axes>

### Operating system
Windows10

### Cartopy version
cartopy                   0.17.0          py37hde43876_1009    conda-forge

**Comment by ResidentMario** [comment]
Hi @leeprevost, can you provide a copy of `sf_home_sales_19`, or the subset of the geometries within that are causing this error to occur? I can then take a look at this on my local machine to debug.

**Comment by leeprevost** [comment]
Thanks for the feedback. Would be glad to share the file.  the CRS is: {'init': 'epsg:4326'}  Would be glad to share the file.  How shall I share it?

**Comment by leeprevost** [comment]
This file originated from an ARCGIS download from wake county's open gis system.   Doing further research, I think the original data uses this format:  NAD83 (http://www.wakegov.com/gis/services/Pages/metadata.aspx).   But, after spatially joining it to some other data and filtering the results, the crs of the geograme is in fact epsg:4326.

**Comment by leeprevost** [comment]
@ResidentMario your questions caused me to go back to the origins of my geopandas frame. The origin was an extract of a layer from an ARCGIS server.    I looked that properties of the parcels layer that I extracted from and found the following properties:

{
  "currentVersion": 10.51,
  "id": 0,
  "name": "Property",
  "type": "Feature Layer",
  "description": "",
  "geometryType": "esriGeometryPolygon",
  "sourceSpatialReference": {
    "wkid": 102719,
    "latestWkid": 2264
  },
arcgis.features.layer.FeatureLayer

I'm now thinking that when I converted from the ARCGIS feature layer sdf to a geopandas frame, the crs settings were not transferred.     So, I'm assuming now that my fix is to properly convert the arcgis layer to the geopandas object and proper CRS and then do a to_crs() transform?

**Comment by ResidentMario** [comment]
I believe so. Having a CRS in the data is in does not actually match the CRS assigned to the data in the dataframe will cause incorrect or failure behavior in all CRS-sensitive applications (like e.g. projecting data onto a map, which is what you were doing).

**Comment by leeprevost** [comment]
I have successfully gotten KDEplot to run on an alternate dataset.   I think my problem was an incorrectly set crs.  Thanks for your help with this.
