### ISSUE TITLE
Add @greglucas as a maintainer

### ISSUE THREAD

**Issue by QuLogic** [SciTools/cartopy#1459]
I don't have the power to do this, but I'd like to nominate @greglucas as a Cartopy maintainer. He's been keeping up with issues and PRs even while the rest of us have been unable to, and I think he deserves it.

cc @SciTools/cartopy-admins

**Comment by pelson** [comment]
@QuLogic - great suggestion. I'm 👍 too. I've added @greglucas to the development team.

Welcome aboard @greglucas! It's great to have your energy and enthusiasm helping to shape cartopy for the better 🌐 .

@QuLogic - I've added you to the admins group, thanks for keeping your 👀 on this. Currently we technically should propose new developers through the SciTools steering-council (@SciTools/steering-council) preferably in a way that it would be possible for the council to reject the proposal without having a detrimental impact on the nominee in question, so we normally do it via email. I can forward anything on to the steering-council if their email addresses aren't readily available (I don't see them on their github profiles). It is a little bit cumbersome as a process, and for-sure can be improved, but it is what we have as per https://scitools.org.uk/organisation.html#organisation-top. 

Anyway, thanks again to you @QuLogic and welcome to the cartopy developers team @QuLogic!

**Comment by QuLogic** [comment]
Thanks @pelson, and welcome @greglucas!

The @SciTools/steering-council team does not appear to be public, or I might have thought to post there... I'll try and remember for next time though.

**Comment by greglucas** [comment]
Thanks, @QuLogic and @pelson!

**Comment by dopplershift** [comment]
Congrats @greglucas !
