### ISSUE TITLE
Undesirable line through Antarctica when using GSHHS

### ISSUE THREAD

**Issue by esc24** [SciTools/cartopy#146]
PR #126 provides support for GSHHS coastlines. The source for this feature are shapefiles available from http://www.ngdc.noaa.gov/mgg/shorelines/gshhs.html. When viewed in PlateCarree the combination of two geometries to form Antartica leads to a vertical line at longitude=0 though the continent. Investigate the cause of this artefact and fix it.

**Comment by QuLogic** [comment]
The GSHHS shapes are basically like this. The Antarctica polygon is in fact two, one from -180 to 0 and one from 0 to 180. Unless we do some polygon merging, this line is not going away.

In fact, if you use a different central longitude (like say 30), you get two lines:
![figure_1-5](https://user-images.githubusercontent.com/302469/47190891-e8e49780-d311-11e8-98d7-bd1abcebb96f.png)

**Comment by pelson** [comment]
> The GSHHS shapes are basically like this. 

I agree. Happy enough for this to be addressed in cartopy, but fundamentally, it is an issue with the data itself.

**Comment by robbiemallett** [comment]
For people viewing this issue, I've just been shown how to draw over the 'undesirable line' with a line of the same color as the land fill like this:
```
import cartopy.feature as cfea

ax.plot([180, 180], [-90, -85],
                 zorder=3, color=cfea.COLORS['land'],
                 linewidth=2,
                 transform=ccrs.PlateCarree())
```
A horrible hack, but worked for me so might be useful for some
