### ISSUE TITLE
Update pcolormesh with new matplotlib versions

### ISSUE THREAD

**Issue by greglucas** [SciTools/cartopy#1470]
### Description

The current master of matplotlib has changed the keyword arguments for `pcolor*`. See: https://github.com/matplotlib/matplotlib/pull/16258

We will need to change the `_pcolormesh_patched` function. Specifically, the call to `_pcolor_args` and the `shading` option and get rid of `allmatch` when that update from mpl is released.

Note: I didn't find any version checks and if statements to handle cases like this for MPL_VERSION in the code, only in the tests, so I'm also not sure how we want to handle this.

**Comment by dopplershift** [comment]
Just to add that this is slated for release with matplotlib 3.3.
