### ISSUE TITLE
Update cartopy 0.18

### ISSUE THREAD

**Issue by dramauh** [SciTools/cartopy#1484]
Dear community and developers,

these days, I have been trying to update cartopy from 0.17 to 0.18 because I want to use the gridline label function in my northpolestereo grid. I have got several errors that I suspect that are related with the path of my libraries in windows and Microsoft visual. 

Firstly, Microsoft Visual Studio 14.0 could not find  geos and proj4 include files, even though I had those libraries installed.  I copied and pasted those files in the main include directory of anaconda (i.e. IC:\ProgramData\Anaconda3\include ) .  I am pretty sure, that this is not the way to do it. However, Microsoft visual does not call all the conda library paths when it is compiling. Now, I am having this error related with proj4 

**\ProgramData\Anaconda3\include\proj_api.h(37): fatal error C1189: #error:  'To use the proj_api.h you must define the macro ACCEPT_USE_OF_DEPRECATED_PROJ_API_H'
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2**

I attach the last lines of the compiling to show you which paths are called every time that cartopy tries to update:

  **C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I. -I./lib/cartopy -IC:\ProgramData\Anaconda3\lib\site-packages\numpy\core\include -IC:\ProgramData\Anaconda3\include -IC:\ProgramData\Anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /EHsc /Tplib/cartopy/trace.cpp /Fobuild\temp.win-amd64-3.7\Release\lib/cartopy/trace.obj
    trace.cpp
    C:\ProgramData\Anaconda3\include\proj_api.h(37): fatal error C1189: #error:  'To use the proj_api.h you must define the macro ACCEPT_USE_OF_DEPRECATED_PROJ_API_H'
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
    ----------------------------------------
  Rolling back uninstall of cartopy
  Moving to c:\programdata\anaconda3\lib\site-packages\cartopy-0.17.0.dist-info\
   from c:\programdata\anaconda3\lib\site-packages\~-rtopy-0.17.0.dist-info
  Moving to c:\programdata\anaconda3\lib\site-packages\cartopy\
   from c:\programdata\anaconda3\lib\site-packages\~artopy
ERROR: Command errored out with exit status 1: 'C:\ProgramData\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\drama\\AppData\\Local\\Temp\\pip-install-xu5tyftu\\Cartopy\\setup.py'"'"'; __file__='"'"'C:\\Users\\drama\\AppData\\Local\\Temp\\pip-install-xu5tyftu\\Cartopy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\drama\AppData\Local\Temp\pip-record-ez25bc3h\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\ProgramData\Anaconda3\Include\Cartopy' Check the logs for full command output.**

Thanks so much in advance for all your assistance

Kind regards,

Estanislao

**Comment by QuLogic** [comment]
It appears you are using a new version of Proj with Cartopy 0.17. You will need to use Cartopy 0.18 (the beta right now) if you want to use a new version of Proj.

Also, Cartopy 0.18 beta1 is available in conda-forge, so there's no need to compile it yourself. You will need to install using a dev label to get it: https://anaconda.org/conda-forge/cartopy/labels

**Comment by dramauh** [comment]
I  have tried that before but it gives me the 16 version
Typing:  **conda install -c conda-forge/label/cartopy_dev cartopy=0.18.0b1**
I have this error
This is the log
**Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: |
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining @/win-64::__cuda==10.2=0:  33%|████████████████                                | 1/3 [00:00<00Examining cartopy=0.18.0b1:  67%|█████████████████████████████████████▎           Examining conflict for __cuda:  33%|█████████████████▋                                   | 1/3 [00:00<failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\install.py", line 265, in install
        should_retry_solve=(_should_retry_unfrozen or repodata_fn != repodata_fns[-1]),
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\solve.py", line 117, in solve_for_transaction
        should_retry_solve)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\solve.py", line 158, in solve_for_diff
        force_remove, should_retry_solve)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\solve.py", line 281, in solve_final_state
        ssc = self._run_sat(ssc)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\io.py", line 88, in decorated
        return f(*args, **kwds)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\solve.py", line 808, in _run_sat
        should_retry_solve=ssc.should_retry_solve
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\io.py", line 88, in decorated
        return f(*args, **kwds)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\resolve.py", line 1316, in solve
        raise UnsatisfiableError({})
    conda.exceptions.UnsatisfiableError:
    Did not find conflicting dependencies. If you would like to know which
    packages conflict ensure that you have enabled unsatisfiable hints.

    conda config --set unsatisfiable_hints True


    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 82, in do_call
        return getattr(module, func_name)(args, parser)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 20, in execute
        install(args, parser, 'install')
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\install.py", line 299, in install
        should_retry_solve=(repodata_fn != repodata_fns[-1]),
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\solve.py", line 117, in solve_for_transaction
        should_retry_solve)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\solve.py", line 158, in solve_for_diff
        force_remove, should_retry_solve)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\solve.py", line 275, in solve_final_state
        ssc = self._add_specs(ssc)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\solve.py", line 694, in _add_specs
        ssc.r.find_conflicts(spec_set)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\resolve.py", line 347, in find_conflicts
        bad_deps = self.build_conflict_map(specs, specs_to_add, history_specs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\resolve.py", line 507, in build_conflict_map
        root, search_node, dep_graph, num_occurances)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\resolve.py", line 369, in breadth_first_search_for_dep_graph
        last_spec = MatchSpec.union((path[-1], target_paths[-1][-1]))[0]
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\models\match_spec.py", line 481, in union
        return cls.merge(match_specs, union=True)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\models\match_spec.py", line 475, in merge
        reduce(lambda x, y: x._merge(y, union), group) if len(group) > 1 else group[0]
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\models\match_spec.py", line 475, in <lambda>
        reduce(lambda x, y: x._merge(y, union), group) if len(group) > 1 else group[0]
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\models\match_spec.py", line 502, in _merge
        final = this_component.union(that_component)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\models\match_spec.py", line 764, in union
        return '|'.join(options)
    TypeError: sequence item 0: expected str instance, Channel found

`$ C:\ProgramData\Anaconda3\Scripts\conda-script.py install -c conda-forge/label/cartopy_dev cartopy=0.18.0b1`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=C:\ProgramData\Anaconda3\Scripts\conda.exe
             CONDA_PREFIX=C:\ProgramData\Anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=C:\ProgramData\Anaconda3\python.exe
               CONDA_ROOT=C:\ProgramData\Anaconda3
              CONDA_SHLVL=1
                 HOMEPATH=\Users\drama
                     PATH=C:\ProgramData\Anaconda3;C:\ProgramData\Anaconda3\Library\mingw-w64\bi
                          n;C:\ProgramData\Anaconda3\Library\usr\bin;C:\ProgramData\Anaconda3\Li
                          brary\bin;C:\ProgramData\Anaconda3\Scripts;C:\ProgramData\Anaconda3\bi
                          n;C:\ProgramData\Anaconda3;C:\ProgramData\Anaconda3\Library\mingw-w64\
                          bin;C:\ProgramData\Anaconda3\Library\usr\bin;C:\ProgramData\Anaconda3\
                          Library\bin;C:\ProgramData\Anaconda3\Scripts;C:\ProgramData\Anaconda3\
                          bin;C:\ProgramData\Anaconda3;C:\ProgramData\Anaconda3\Library\mingw-w6
                          4\bin;C:\ProgramData\Anaconda3\Library\usr\bin;C:\ProgramData\Anaconda
                          3\Library\bin;C:\ProgramData\Anaconda3\Scripts;C:\ProgramData\Anaconda
                          3\bin;C:\ProgramData\Anaconda3\condabin;C:\WINDOWS\system32;C:\WINDOWS
                          ;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C
                          :\Program Files\MATLAB\R2018b\runtime\win64;C:\Program
                          Files\MATLAB\R2018b\bin;D:\Program
                          Files\MATLAB\R2016b\runtime\win64;D:\Program
                          Files\MATLAB\R2016b\bin;D:\Program Files\MATLAB\R2016b\polyspace\bin;C
                          :\WINDOWS\System32\OpenSSH;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\S
                          ystem32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\Sys
                          tem32\OpenSSH;C:\Program Files\NVIDIA Corporation\NVIDIA
                          NvDLISR;C:\Program Files (x86)\NVIDIA
                          Corporation\PhysX\Common;C:\Program Files\MiKTeX
                          2.9\miktex\bin\x64;C:\Program Files (x86)\Windows Kits\8.1\Windows
                          Performance Toolkit;C:\Users\drama\AppData\Local\Microsoft\WindowsApps
             PSMODULEPATH=C:\Users\drama\Documents\WindowsPowerShell\Modules;C:\Program Files\Wi
                          ndowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Mod
                          ules\
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
    VBOX_MSI_INSTALL_PATH=C:\Program Files\Oracle\VirtualBox\

     active environment : base
    active env location : C:\ProgramData\Anaconda3
            shell level : 1
       user config file : C:\Users\drama\.condarc
 populated config files : C:\Users\drama\.condarc
          conda version : 4.8.2
    conda-build version : 3.18.11
         python version : 3.7.4.final.0
       virtual packages : __cuda=10.2
       base environment : C:\ProgramData\Anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/label/cartopy_dev/win-64
                          https://conda.anaconda.org/conda-forge/label/cartopy_dev/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\drama\.conda\pkgs
                          C:\Users\drama\AppData\Local\conda\conda\pkgs
       envs directories : C:\ProgramData\Anaconda3\envs
                          C:\Users\drama\.conda\envs
                          C:\Users\drama\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.4 Windows/10 Windows/10.0.18362
          administrator : True
             netrc file : None
           offline mode : False**

**Comment by philippjfr** [comment]
@QuLogic Sorry to bother you but is there an update on when the v0.18 release will be available. I'm hoping to release [GeoViews](https://github.com/holoviz/geoviews) but in the current state I'm going to have to pin proj in the conda recipes, which I'd rather avoid.

**Comment by QuLogic** [comment]
@dramauh that seems like conda is crashing; you might want to report it to them.

@philippjfr Please follow the release ticket #1458.

**Comment by xylar** [comment]
@dramauh please see https://github.com/conda-forge/cartopy-feedstock/issues/77#issuecomment-612891564 and comment on that issue (which I will re-open if needed) if you are still having trouble.
