### ISSUE TITLE
Gridliner projection support

### ISSUE THREAD

**Issue by dbpodrasky** [SciTools/cartopy#1495]
### Description
cartopy.mpl.gridliner.Gridliner lacks support for crs other than PlateCarree.

This a rather limiting feature set. Projected coordinate axes are commonplace when mapping on smaller scales. When will this be supported?

#### Code to reproduce

```
from cartopy.mpl.gridliner import Gridliner
stamen_background = cimgt.Stamen('terrain-background')
ax = plt.axes(projection = stamen_background.crs)
Gridliner(ax, crs=stamen_background.crs, draw_labels=True)
```

#### Traceback 

```
TypeError: Cannot label Mercator gridlines. Only PlateCarree gridlines are currently supported.
```

### Operating system
Mojave

### Cartopy version
0.17

**Comment by QuLogic** [comment]
This is fixed by #1117 already and will be in 0.18.

**Comment by dbpodrasky** [comment]
@QuLogic,

#1117 does not mention projected coordinate axis grids/labels, only geographic values for various projections. Can you confirm that 0.18 allows for grids/labels in the projected coordinate system, ie UTM NAD83?

For some reason the install script for 0.18 won't find my installed and active proj4.9.3, so I can't test the functionality of 0.18.

**Comment by QuLogic** [comment]
Yes, it should work with all projections.

**Comment by dbpodrasky** [comment]
Thanks, @QuLogic!
