### ISSUE TITLE
Unicode exception when trying to read records of Natural Earth 10m / 50m data 

### ISSUE THREAD

**Issue by afontenot** [SciTools/cartopy#1501]
### Description

Hi, I have some code that works on the 110m dataset, but breaks with an internal error with the 10m or 50m data (even though it downloads correctly). Maybe this is expected, but if so it's pretty unfriendly to the user and the error message doesn't provide any clue as to the user can do to fix the issue.

I was able to isolate the following simple test case. If you replace `50m` with `110m` the code will work.

#### Code to reproduce

    import cartopy.io.shapereader as shpreader
    shapename="admin_1_states_provinces_lakes_shp"
    states_shp = shpreader.natural_earth(
        resolution='50m',
        category='cultural',
        name=shapename
    )
    shape_reader = shpreader.Reader(states_shp)
    recs = list(shape_reader.records())

#### Traceback 

    Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "/usr/lib/python3.8/site-packages/cartopy/io/shapereader.py", line 249, in records
        shape_record = self._reader.shapeRecord(i)
    File "/usr/lib/python3.8/site-packages/shapefile.py", line 1033, in shapeRecord
        return ShapeRecord(shape=self.shape(i), record=self.record(i))
    File "/usr/lib/python3.8/site-packages/shapefile.py", line 1002, in record
        return self.__record(oid=i)
    File "/usr/lib/python3.8/site-packages/shapefile.py", line 987, in __record
        value = u(value, self.encoding, self.encodingErrors)
    File "/usr/lib/python3.8/site-packages/shapefile.py", line 104, in u
        return v.decode(encoding, encodingErrors)
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf4 in position 4: invalid continuation byte

<details>
 <summary>Full environment definition</summary>

### Operating system

Arch Linux 5.5.13-arch1-1

### Cartopy version

0.17.0-3 (distribution package)

### Dependency list (I'm not using a pip environment)

pyshp 2.1.0-1
shapely 1.7.0-1
matplotlib 3.2.1-1

I do not have Fiona installed - it's not in the Arch Linux repositories.
</details>

**Comment by dopplershift** [comment]
Thanks for the report. I'll add for future debuggers: if you have Fiona installed this will work without error. It turns out it works with `FionaReader` but fails with `BasicReader`. (Just sub for `Reader` in the example code).

**Comment by afontenot** [comment]
Thanks for the quick response! I can probably make Fiona work, but it's a bit annoying as I have to compile it, since it's not packaged on Arch Linux. More importantly, it's not a complete drop in replacement, as the following code does different things depending on whether Fiona is installed.

    import cartopy.io.shapereader as shpreader
    shapename="admin_1_states_provinces_lakes_shp"
    states_shp = shpreader.natural_earth(
        resolution='110m',
        category='cultural',
        name=shapename
    )
    shape_reader = shpreader.Reader(states_shp)
    recs = list(shape_reader.records())
    print(type(recs[0].geometry))

Without Fiona, `recs[0].geometry` is a 

    <class 'shapely.geometry.multipolygon.MultiPolygon'>

With Fiona, it's a 

    <class 'shapely.geometry.polygon.Polygon'>

Now granted, maybe I shouldn't have written code that crashes if `.geometry` doesn't return a MultiPolygon, but it's annoying nonetheless.

**Comment by dopplershift** [comment]
Yeah, there some differences between the two readers. We certainly want to fix `BasicReader` though to eliminate the original error.

**Comment by QuLogic** [comment]
The differences will be fixed in 0.18; not sure if `BasicReader` is also fixed.

**Comment by afontenot** [comment]
> The differences will be fixed in 0.18; not sure if `BasicReader` is also fixed.

Has it already been fixed? Is there a commit I can backport for my own builds? (It's been a long time since the last release.)

**Comment by greglucas** [comment]
The BasicReader will now use Shapely to create the geometries. This is the PR:
https://github.com/SciTools/cartopy/pull/1210
I'm pretty sure your new geometry will be a Polygon now because of that.

I'm not sure if the main problem with those files is the same as this issue: https://github.com/SciTools/cartopy/issues/1282
where someone else wanted to pass through an encoding parameter to the readers. If you want to give that a try and make a PR that'd be great!

**Comment by QuLogic** [comment]
So Natural Earth changed to UTF-8 a long time ago. However, they renamed the files when they did that. If you instead use:
```
shapename = "admin_1_states_provinces_lakes"
```
then it will load just fine (also if you check in QGis, it's actually UTF-8 and not garbage.)
