### ISSUE TITLE
Cartopy on a CentOS 7.7

### ISSUE THREAD

**Issue by carterhumphreys** [SciTools/cartopy#1508]
### Description

Hello,

I'm trying to install Cartopy on a CentOS 7.7 server but can't seem to get past the Proj version requirement when installing via pip.

#### Code to reproduce

```
# pip3 install cartopy
```

#### Traceback 

```
Collecting cartopy
  Using cached Cartopy-0.17.0.tar.gz (8.9 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python3.7 /usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpsheh55bp
       cwd: /tmp/pip-install-tyfwgqeo/cartopy
  Complete output (1 lines):
  Proj version 4.8.0 is installed, but cartopy requires at least version 4.9.0.
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/bin/python3.7 /usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpsheh55bp Check the logs for full command output.
```

I've tried already ```yum install proj-devel geos-devel``` as that's been my issue in the past but all I get is:
```
Package proj-devel-4.8.0-4.el7.x86_64 already installed and latest version
Package geos-devel-3.4.2-2.el7.x86_64 already installed and latest version
Nothing to do
```

Any ideas?

**Comment by sodaBitters** [comment]
proj-devel 4.8 is the latest version centos 7 supports, which is pretty dated. That error says you need version 4.9. 

Centos 8 has a higher version, so you could either pull packages from the centos 8 repo, or just update your OS to the latest version.

This isn't a bug, so you might want to close this issue.... stay safe in NY brah

**Comment by carterhumphreys** [comment]
Alright, I’ll give them a try. Thank you!!

**Comment by akrherz** [comment]
@carterhumphreys I'd also strongly suggest you use [anaconda/miniconda](https://www.anaconda.com/distribution/) to manage your python install on Centos 7.  They go through all the pain to manage the sprawling GIS python stack on 64 bit Linux.  Otherwise, for newer Proj, you need to check out the vendoring done by yum repos like [pgrpms](https://yum.postgresql.org/)
