### ISSUE TITLE
Expose the full Table of Content of the web site ?

### ISSUE THREAD

**Issue by jypeter** [SciTools/cartopy#1510]
I got **lost again when trying to navigate the cartopy website**!

This may come from the fact that some pages are listed on the home page, in the _Getting Started_ section, but **some other useful pages are not listed** there, and you can only find them by searching the web site, or by visiting one of the pages listed in _Getting Started_ and then clicking on the **Next/Previous Topic** in the right part of the page. **This is not intuitive at all!** Would it be possible to have a full Table of Content of the site available somewhere?

I confess I don't know what would be the (best) solution. Maybe listing [A], [B] and [C] (see below) in _Getting Started_? Maybe explicitly mentioning [A], [B] and [C] in the _Using cartopy with matplotlib_ would help as well

You'll see below the pages listed in _Getting Started_ (not indented). The indented lines are the pages that are not listed
```
         home page
         [more topics]
         Cartopy
Coordinate reference systems in Cartopy
Cartopy projection list
Using cartopy with matplotlib
	  [A] More advanced mapping with cartopy and matplotlib
	  [B] Cartopy Matplotlib integration reference document
	  [C] Cartopy map gridlines and tick labels
The cartopy Feature interface
Understanding the transform and projection keywords
Using the cartopy shapereader
Cartopy developer interfaces
	  The cartopy module
```

**Comment by QuLogic** [comment]
There's an outline page, and an index page, and it seems like none of these are shown there either. I don't know why or how that happens though, but I also just got lost trying to find a page.

**Comment by jypeter** [comment]
Well, there are _outline_ and _index_ links at the top and bottom of all the pages, but:
- No global Table of Content (or I have not found it yet)
- Some links are missing on the outline page (#1322)
- The _outline_ word is not helpful enough (in my opinion), as it does not really describe what is behind the link (#1319)

**Comment by stefraynaud** [comment]
Yep, the site is far from being clear.

Possible **content**?

* Installation/setup
* User guide
  * Coordinate reference systems in Cartopy
  * Cartopy projection list
  * etc..
* Reference guide
  * API
  * What's new
  * Appendices
* Getting involed

A good use of the `.. toctree::` makes the toc always accessible.
A use of the toctree `:caption:` option may also help to clarify.
The **theme** may also be updated. A RTD-like theme?

Keeping most of the actual content, it should be not that difficult to reorganised the doc.

**Comment by greglucas** [comment]
I think this is much improved now and should be easier to navigate. Closing due to #1652, but lets open up new issues if there is still work to be done here.
