### ISSUE TITLE
Add the "Cartopy map gridlines and tick labels" example to the gallery

### ISSUE THREAD

**Issue by jypeter** [SciTools/cartopy#1511]
One of my colleagues used `gridlines(draw_labels=True, ...)` and complained that she got labels at the top (that collided with the figure title), and on the right. It took me ~2 hours to find the [Cartopy map gridlines and tick labels](https://scitools.org.uk/cartopy/docs/latest/matplotlib/gridliner.html) page, because I first started to look for a solution on the matplotlib web site, and also finding the _gridline_ page is not easy (see #1510)

**gridlines and labels and ticks are very important**, even if they are only supported  by a few projections (for now). It would be therefore very useful to have the example at the bottom of [Cartopy map gridlines and tick labels](https://scitools.org.uk/cartopy/docs/latest/matplotlib/gridliner.html) in the [Cartopy Gallery](https://scitools.org.uk/cartopy/docs/latest/gallery/index.html), probably next to the _Tick Labels_ example

Or maybe have an example using both, to prevent people being confused because of #1321

And there is also  #1339

**Comment by philippemiron** [comment]
On the [Cartopy map gridlines and tick labels](https://scitools.org.uk/cartopy/docs/latest/matplotlib/gridliner.html) page, there are:
- one example with gridlines and labels on all sides of the figure
- one example with labels *only* on the right and bottom of the figure.

Should we close this issue?

**Comment by jypeter** [comment]
Please, keep this issue open until there is an **easy** way to find the nice _Cartopy map gridlines and tick labels_ page! The page is fine, but my point is that it is very difficult to find, when you are a new or casual or returning cartopy user!

I suggested above adding a link to this page from the [Gallery ](https://scitools.org.uk/cartopy/docs/latest/gallery/index.html) page and I have just revisited the Gallery page and followed both links to the [Gridlines and tick labels](https://scitools.org.uk/cartopy/docs/latest/gallery/gridliner.html#sphx-glr-gallery-gridliner-py) example. But when you are on the _Gridlines and tick labels_ page, there is no link to _Cartopy map gridlines and tick labels_ ! This documentation page is really hard to find :-(

**Comment by philippemiron** [comment]
Ok,

We could simply add an example to the [gridliner.py](https://github.com/SciTools/cartopy/blob/68a21658e1917d7af6c6adcaedfa49a4cc000cab/lib/cartopy/examples/gridliner.py) file with selected axis label. 

I was going to edit and push a commit but I can't get the example to work...

`TypeError: Cannot label gridlines on a RotatedPole plot.  Only PlateCarree and Mercator plots are currently supported.`

**Comment by QuLogic** [comment]
You need 0.18 to label gridlines on arbitrary projections.
