### ISSUE TITLE
inline tick labels outside map boundary

### ISSUE THREAD

**Issue by stefraynaud** [SciTools/cartopy#1526]
### Description

Tickels that are plotted with `x/y_inline = True` may be outside map boundary, like in the code below.
I didn' took time to investigate it.

#### Code to reproduce
```python
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
rotated_crs = ccrs.RotatedPole(pole_longitude=120.0, pole_latitude=70.0)
plt.figure(figsize=(6, 6))
ax = plt.axes(projection=rotated_crs)
ax.set_extent([-6, 3, 48, 58], crs=ccrs.PlateCarree())
ax.coastlines(resolution='50m')
ax.gridlines(draw_labels=True, x_inline=True, y_inline=True)
plt.show()
```
![inline_bug](https://user-images.githubusercontent.com/1941408/79310712-ab5bcd00-7efc-11ea-9403-796104d29dc2.png)

**Comment by QuLogic** [comment]
I think this is because it uses `Axes.text` which defaults to `clip_on=False`, but turning it on doesn't seem to clip it.

**Comment by QuLogic** [comment]
This is related to #1422, as `clip_on=True` plus reverting that change fixes the clipping, but I'm not sure why it only affects `Text`, and not everything else.

**Comment by greglucas** [comment]
Potentially an instance of https://github.com/matplotlib/matplotlib/issues/8270?

**Comment by QuLogic** [comment]
After a bit of puzzlement last night, I think I figured out why it used to work in the old mode. Previously, the `patch` was not changed, so it was the default `Rectangle`, which happens to coincide with the boundaries in this plot. If the patch is a `Rectangle`, then the clip _box_ is set, not the clip _path_, and `Text` respects the former.

Looking at the gridliner code, there is some stuff to tweak visibility based on inline:
https://github.com/SciTools/cartopy/blob/f3784c64d3ddc35060bbba06d2fae0757b010ad0/lib/cartopy/mpl/gridliner.py#L784-L786
but I think the logic is not quite right. Basically the first clause will be true for _almost any_ inline label, and so they will almost always be shown, even if not inline.
