### ISSUE TITLE
Text not properly clipped in CartoPy 0.18

### ISSUE THREAD

**Issue by dopplershift** [SciTools/cartopy#1558]
### Description

It looks like `Text` artists are not properly clipped with CartoPy 0.18. This breaks MetPy code that plots multiple text strings in a single artist. MetPy's code works fine when using just stock Matplotlib, and fine with CartoPy 0.17. This is reproducible using only matplotlib + cartopy 0.18

#### Code to reproduce

```python
import matplotlib.pyplot as plt
from matplotlib.text import Text
import cartopy.crs as ccrs
import cartopy.feature as cfeature

fig = plt.figure(figsize=(10, 5))

ax_mpl = fig.add_subplot(1, 2, 1)
t1 = Text(-1.3, 0.5, 'MyLongTextStuff', clip_on=True)
ax_mpl.add_artist(t1)
ax_mpl.set_xlim(-1, 1)
ax_mpl.set_ylim(0, 1)
ax_mpl.set_title('Matplotlib')

ax_c = fig.add_subplot(1, 2, 2, projection=ccrs.PlateCarree())
t2 = Text(-130, 30, 'MyLongTextStuff', clip_on=True)
ax_c.add_artist(t2)
ax_c.set_extent((-120, -60, 25, 50))
ax_c.add_feature(cfeature.STATES)
ax_c.set_title('Cartopy')
```

This produces:
<img width="608" alt="image" src="https://user-images.githubusercontent.com/221526/81776854-dc540100-94ac-11ea-8a13-1e61f958bb37.png">

I can confirm that on CartoPy 0.17, this image shows proper clipping for text.

**Comment by dopplershift** [comment]
@QuLogic Guessing this is related to #1422 . Not surprising, this is not fixed by #1535.

**Comment by dopplershift** [comment]
Looks like the same core problem as #1526, but there's no quick hack here to fix it.

**Comment by QuLogic** [comment]
If you're using a rectangular (section of a) projection, then you can workaround it with `Text.set_clip_path(Rectangle(something suitable))` because that's not broken in Matplotlib.

This is matplotlib/matplotlib#8270 for which I tried the linked PR, but it doesn't seem to be the right approach.

**Comment by dopplershift** [comment]
I guess there's not really any resolution here for cartopy, is there?

**Comment by QuLogic** [comment]
It only really worked by chance since it was clipping to a rectangle, not the actual patch, but again you can workaround it by doing that manually if your plot is rectangular.

**Comment by dopplershift** [comment]
Closing here since there's nothing CartoPy is doing wrong here.
