### ISSUE TITLE
imshow() extrapolates RGBA data to fill the region

### ISSUE THREAD

**Issue by kdpenner** [SciTools/cartopy#1570]
### Description

Apologies for #1569. imshow() extrapolates RGBA data to fill the region.

#### Code to reproduce

```python
import matplotlib.pyplot as plt
import numpy as np
import cartopy.crs as ccrs
import matplotlib.cm as cm
import matplotlib.colors as colors

z = np.random.rand(100, 100)

cmap = cm.get_cmap()
norm = colors.Normalize(vmin = 0, vmax = 1)

plt_crs = ccrs.LambertAzimuthalEqualArea()

latlon_crs = ccrs.PlateCarree()

fig = plt.figure(figsize = (5, 5))

ax = fig.add_subplot(1, 1, 1, projection = plt_crs)

ax.set_extent([-30, -20, 60, 70], crs = latlon_crs)

ax.gridlines()

ax.imshow(cm.ScalarMappable(norm = norm, cmap = cmap).to_rgba(z),
          extent = [-26, -24, 64, 66], transform = latlon_crs)

```
produces this:
![t1](https://user-images.githubusercontent.com/9297904/82512693-cebafe80-9ade-11ea-9f8a-3acb75871acd.png)

A hack like this corrects the problem:

```python
z1 = cm.ScalarMappable(norm = norm, cmap = cmap).to_rgba(z)
z1[0,:,3] = 0
z1[-1,:,3] = 0
z1[:,0,3] = 0
z1[:,-1,3] = 0

ax.imshow(z1, extent = [-26, -24, 64, 66], transform = latlon_crs)
```

![t2](https://user-images.githubusercontent.com/9297904/82512814-2eb1a500-9adf-11ea-8055-88eaa91fc060.png)

<details>
 <summary>Full environment definition</summary>

### Cartopy version

0.18.0

</details>

**Comment by greglucas** [comment]
That hack hides all of the edge data though. A better way is
```python
ax.imshow(z, norm = norm, cmap = cmap,
          extent = [-26, -24, 64, 66], transform = latlon_crs)
```
which works as expected. My guess is there is some transform logic that expects MxN matrices and not MxNx4.

**Comment by kdpenner** [comment]
True, but the hack is required for my non-MWE because I use matplotlib's `LightSource.shade()`, which returns a RGBA array.

I have time to fix this if no changes are needed for the next month or so.
