### ISSUE TITLE
Cartopy 0.18.0 fills the inside of a Line/MultiLineString shapefile 

### ISSUE THREAD

**Issue by miguel123-gis** [SciTools/cartopy#1577]
### Description
I have a fault line shapefile that has a multilinestring geometry. When imported via Cartopy's ShapelyFeature() and Reader() functions, it comes out as a polygon with a fill instead of a line. 

The issue has already been filed in 2017. 
https://github.com/SciTools/cartopy/issues/856 , https://www.net-analysis.com/blog/cartopymultiline.html

It was said in the issue that `facecolor='none` should work. I have tried `none`, `'none'`, and `"none"` but nothing works. 

#### Code to reproduce
```
import os
import matplotlib.pyplot as plt
import geopandas as gpd
from geopandas import GeoDataFrame
import cartopy.crs as ccrs
import cartopy.io.img_tiles as cimgt
from cartopy.feature import ShapelyFeature
from cartopy.io import shapereader
from cartopy.io.shapereader import Reader
from shapely.geometry import MultiLineString
os.chdir(r'path')

proj = ccrs.PlateCarree() 
bounds = [116.9283371, 126.90534668, 4.58693981, 21.07014084]
stamen_terrain = cimgt.Stamen('terrain-background')
fault_line = 'faultLines.shp' #MultiLineString
shp_feature = ShapelyFeature(Reader(fault_line).geometries(), ccrs.epsg(32651), 
                             linewidth=1, color='black', facecolor='None')   
fig = plt.figure(figsize=(15,10))   
ax  = fig.add_subplot(1, 1, 1, projection=proj)

ax.set_extent(bounds)
ax.add_image(stamen_terrain, 8)
ax.add_feature(shp_feature, zorder=1)
plt.show()
```
#### Result

![image](https://user-images.githubusercontent.com/63440740/83482716-90a4de00-a4d3-11ea-98ec-8b8c9505549f.png)

<details>
 <summary>Full environment definition</summary>

### Operating system
Windows 10 Pro 1909 build

### Cartopy version
Cartopy 0.18.0

### conda list
Name                    Version                   Build  Channel
alabaster                 0.7.12                     py_0    conda-forge
argh                      0.26.2                py38_1001    conda-forge
astroid                   2.4.1            py38h32f6830_0    conda-forge
atomicwrites              1.4.0              pyh9f0ad1d_0    conda-forge
attrs                     19.3.0                     py_0    conda-forge
autopep8                  1.5.2              pyh9f0ad1d_0    conda-forge
babel                     2.8.0                      py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
basemap                   1.3.0            py38hcdd3ad8_2    conda-forge
bcrypt                    3.1.7            py38h9de7a3e_1    conda-forge
bleach                    3.1.5              pyh9f0ad1d_0    conda-forge
boost-cpp                 1.72.0               h0caebb8_0    conda-forge
brotlipy                  0.7.0           py38h1e8a9f7_1000    conda-forge
bzip2                     1.0.8                hfa6e2cd_2    conda-forge
ca-certificates           2020.4.5.1           hecc5488_0    conda-forge
cartopy                   0.18.0           py38h4990f70_0    conda-forge
certifi                   2020.4.5.1       py38h32f6830_0    conda-forge
cffi                      1.14.0           py38ha419a9e_0    conda-forge
cfitsio                   3.470                he774522_5    conda-forge
chardet                   3.0.4           py38h32f6830_1006    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
cloudpickle               1.4.1                      py_0    conda-forge
colorama                  0.4.3                      py_0    conda-forge
cryptography              2.9.2            py38hba49e27_0    conda-forge
curl                      7.69.1               h1dcc11c_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
descartes                 1.1.0                      py_4    conda-forge
diff-match-patch          20181111                   py_0    conda-forge
docutils                  0.16             py38h32f6830_1    conda-forge
entrypoints               0.3             py38h32f6830_1001    conda-forge
expat                     2.2.9                he025d50_2    conda-forge
ffmpeg                    4.2                  h6538335_0    conda-forge
fiona                     1.8.13           py38h41bf4fa_1    conda-forge
flake8                    3.7.9            py38h32f6830_1    conda-forge
freetype                  2.10.1               ha9979f8_0    conda-forge
freexl                    1.0.5             hd288d7e_1002    conda-forge
future                    0.18.2           py38h32f6830_1    conda-forge
gdal                      3.0.4            py38h3ba59e7_9    conda-forge
geopandas                 0.7.0                      py_1    conda-forge
geos                      3.8.1                he025d50_0    conda-forge
geotiff                   1.5.1               h3d29ae3_10    conda-forge
gettext                   0.19.8.1          hb01d8f6_1002    conda-forge
glib                      2.64.2               he4de6d7_0    conda-forge
hdf4                      4.2.13            hf8e6fe8_1003    conda-forge
hdf5                      1.10.6          nompi_ha405e13_100    conda-forge
icc_rt                    2019.0.0             h0cc432a_1
icu                       64.2                 he025d50_1    conda-forge
idna                      2.9                        py_1    conda-forge
imageio                   2.8.0                      py_0    conda-forge
imageio-ffmpeg            0.4.2                      py_0    conda-forge
imagesize                 1.2.0                      py_0    conda-forge
importlib-metadata        1.6.0            py38h32f6830_0    conda-forge
importlib_metadata        1.6.0                         0    conda-forge
intel-openmp              2020.0                      166
intervaltree              3.0.2                      py_0    conda-forge
ipykernel                 5.2.1            py38h5ca1d4c_0    conda-forge
ipython                   7.14.0           py38h32f6830_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
isort                     4.3.21           py38h32f6830_1    conda-forge
jedi                      0.15.2                   py38_0    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
jpeg                      9c                hfa6e2cd_1001    conda-forge
jsonschema                3.2.0            py38h32f6830_1    conda-forge
jupyter_client            6.1.3                      py_0    conda-forge
jupyter_core              4.6.3            py38h32f6830_1    conda-forge
kealib                    1.4.13               h3b59ab9_1    conda-forge
keyring                   21.2.1           py38h32f6830_0    conda-forge
kiwisolver                1.2.0            py38heaebd3c_0    conda-forge
krb5                      1.17.1               hdd46e55_0    conda-forge
lazy-object-proxy         1.4.3            py38h9de7a3e_2    conda-forge
libblas                   3.8.0                    15_mkl    conda-forge
libcblas                  3.8.0                    15_mkl    conda-forge
libclang                  9.0.1           default_hf44288c_0    conda-forge
libcurl                   7.69.1               h1dcc11c_0    conda-forge
libffi                    3.2.1             h6538335_1007    conda-forge
libgdal                   3.0.4                h6f60a84_9    conda-forge
libiconv                  1.15              hfa6e2cd_1006    conda-forge
libkml                    1.3.0             h7e985d0_1011    conda-forge
liblapack                 3.8.0                    15_mkl    conda-forge
libnetcdf                 4.7.4           nompi_h256d12c_104    conda-forge
libpng                    1.6.37               hfe6a214_1    conda-forge
libpq                     12.2                 hd9aa61d_1    conda-forge
libsodium                 1.0.17               h2fa13f4_0    conda-forge
libspatialindex           1.9.3                he025d50_3    conda-forge
libspatialite             4.3.0a            h51df0ed_1038    conda-forge
libssh2                   1.8.2                h642c060_2    conda-forge
libtiff                   4.1.0                h885aae3_6    conda-forge
libwebp-base              1.1.0                hfa6e2cd_3    conda-forge
libxml2                   2.9.10               h9ce36c8_0    conda-forge
lz4-c                     1.9.2                h62dcd97_1    conda-forge
m2w64-expat               2.1.1                         2
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gettext             0.19.7                        2
m2w64-gmp                 6.1.0                         2
m2w64-libiconv            1.14                          6
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
m2w64-xz                  5.2.2                         2
markupsafe                1.1.1            py38h9de7a3e_1    conda-forge
matplotlib                3.2.1                         0    conda-forge
matplotlib-base           3.2.1            py38h1626042_0    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
mistune                   0.8.4           py38h9de7a3e_1001    conda-forge
mkl                       2020.0                      166
moviepy                   1.0.1                      py_0    conda-forge
msys2-conda-epoch         20160418                      1
munch                     2.5.0                      py_0    conda-forge
natsort                   7.0.1                    pypi_0    pypi
nbconvert                 5.6.1            py38h32f6830_1    conda-forge
nbformat                  5.0.6                      py_0    conda-forge
numpy                     1.18.4           py38h72c728b_0    conda-forge
numpydoc                  0.9.2                      py_0    conda-forge
olefile                   0.46                       py_0    conda-forge
openjpeg                  2.3.1                h57dd2e7_3    conda-forge
openssl                   1.1.1g               he774522_0    conda-forge
ospybook                  1.0                      pypi_0    pypi
owslib                    0.19.2                     py_1    conda-forge
packaging                 20.1                       py_0    conda-forge
pandas                    1.0.3            py38he6e81aa_1    conda-forge
pandoc                    2.9.2.1                       0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
paramiko                  2.7.1                    py38_0    conda-forge
parso                     0.5.2                      py_0    conda-forge
pathtools                 0.1.2                      py_1    conda-forge
pcre                      8.44                 h6538335_0    conda-forge
pexpect                   4.8.0            py38h32f6830_1    conda-forge
pickleshare               0.7.5           py38h32f6830_1001    conda-forge
pillow                    7.1.2            py38h7011068_0    conda-forge
pip                       20.1               pyh9f0ad1d_0    conda-forge
pluggy                    0.13.1           py38h32f6830_1    conda-forge
poppler                   0.87.0               h0cd1227_1    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                12.2                 he14cc48_1    conda-forge
proglog                   0.1.9                      py_0    conda-forge
proj                      7.0.0                haa36216_3    conda-forge
prompt-toolkit            3.0.5                      py_0    conda-forge
psutil                    5.7.0            py38h9de7a3e_1    conda-forge
pycodestyle               2.5.0                      py_0    conda-forge
pycparser                 2.20                       py_0    conda-forge
pydocstyle                5.0.2                      py_0    conda-forge
pyepsg                    0.4.0                      py_0    conda-forge
pyflakes                  2.1.1                      py_0    conda-forge
pygments                  2.6.1                      py_0    conda-forge
pylint                    2.5.2            py38h32f6830_0    conda-forge
pynacl                    1.3.0           py38h2fa13f4_1001    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyproj                    2.6.1.post1      py38h1dd9442_0    conda-forge
pyqt                      5.12.3           py38h7ae7562_3    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtchart                 5.12                     pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pyrsistent                0.16.0           py38h9de7a3e_0    conda-forge
pyshp                     2.1.0                      py_0    conda-forge
pysocks                   1.7.1            py38h32f6830_1    conda-forge
python                    3.8.2           h5fd99cc_7_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python-jsonrpc-server     0.3.4              pyh9f0ad1d_1    conda-forge
python-language-server    0.31.10          py38h32f6830_0    conda-forge
python_abi                3.8                      1_cp38    conda-forge
pytz                      2020.1             pyh9f0ad1d_0    conda-forge
pywin32                   227              py38hfa6e2cd_0    conda-forge
pywin32-ctypes            0.2.0           py38h32f6830_1001    conda-forge
pyyaml                    5.3.1            py38h9de7a3e_0    conda-forge
pyzmq                     19.0.1           py38h77b9d75_0    conda-forge
qdarkstyle                2.8.1              pyh9f0ad1d_0    conda-forge
qt                        5.12.5               h7ef1ec2_0    conda-forge
qtawesome                 0.7.2              pyh9f0ad1d_0    conda-forge
qtconsole                 4.7.3              pyh9f0ad1d_0    conda-forge
qtpy                      1.9.0                      py_0    conda-forge
requests                  2.23.0             pyh8c360ce_2    conda-forge
rope                      0.17.0             pyh9f0ad1d_0    conda-forge
rtree                     0.9.4            py38h7ad75cc_1    conda-forge
scipy                     1.3.2            py38h582fac2_0    conda-forge
setuptools                46.1.3           py38h32f6830_0    conda-forge
shapely                   1.7.0            py38hbf43935_3    conda-forge
six                       1.14.0                     py_1    conda-forge
snowballstemmer           2.0.0                      py_0    conda-forge
sortedcontainers          2.1.0                      py_0    conda-forge
sphinx                    3.0.3                      py_0    conda-forge
sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    1.0.3                      py_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.4                      py_0    conda-forge
spyder                    4.1.3            py38h32f6830_0    conda-forge
spyder-kernels            1.9.1            py38h32f6830_0    conda-forge
sqlite                    3.30.1               hfa6e2cd_0    conda-forge
tbb                       2018.0.5             he980bc4_0    conda-forge
testpath                  0.4.4                      py_0    conda-forge
tiledb                    1.7.7                h0b90766_1    conda-forge
tk                        8.6.10               hfa6e2cd_0    conda-forge
toml                      0.10.0                     py_0    conda-forge
tornado                   6.0.4            py38hfa6e2cd_0    conda-forge
tqdm                      4.46.0             pyh9f0ad1d_0    conda-forge
traitlets                 4.3.3            py38h32f6830_1    conda-forge
ujson                     1.35            py38hb99c5c2_1002    conda-forge
urllib3                   1.25.9                     py_0    conda-forge
vc                        14.1                 h869be7e_1    conda-forge
vs2015_runtime            14.16.27012          h30e32a0_2    conda-forge
watchdog                  0.10.2                   py38_0    conda-forge
wcwidth                   0.1.9              pyh9f0ad1d_0    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.34.2                     py_1    conda-forge
win_inet_pton             1.1.0                    py38_0    conda-forge
wincertstore              0.2                   py38_1003    conda-forge
wrapt                     1.11.2           py38h9de7a3e_0    conda-forge
xerces-c                  3.2.2             h6538335_1004    conda-forge
xz                        5.2.5                h2fa13f4_0    conda-forge
yaml                      0.2.4                he774522_0    conda-forge
yapf                      0.29.0                     py_0    conda-forge
zeromq                    4.3.2                h6538335_2    conda-forge
zipp                      3.1.0                      py_0    conda-forge
zlib                      1.2.11            h2fa13f4_1006    conda-forge
zstd                      1.4.4                h9f78265_3    conda-forge
```
```

### pip list

```
```

</details>

**Comment by miguel123-gis** [comment]
Fault line shapefile
[faultLines_shp.zip](https://github.com/SciTools/cartopy/files/4714942/faultLines_shp.zip)

**Comment by greglucas** [comment]
You are specifying the `color=black` keyword as well which is getting mapped to `facecolor`. You need to specify `edgecolor=black`.

**Comment by miguel123-gis** [comment]
@greglucas copy. It works now. Thank you.
