### ISSUE TITLE
scatter plot with Spherical transform not supported since v0.18

### ISSUE THREAD

**Issue by trichter** [SciTools/cartopy#1583]
Hey, thanks for the great cartopy project!

I just wanted to drop a note that `ax.scatter(..., transform=Geodetic)` used to work in cartopy 0.17, but does not work any more in cartopy 0.18.

No big deal, from #1431 I understand that this is intended behaviour and maybe was also the desired behaviour in 0.17.

obspy/obspy#2624

**Comment by greglucas** [comment]
Actually, I think that should still be supported and I added a regression with that PR for this case. Note that the error wasn't being raised within scatter itself, but rather within the transform check I added. I just opened a PR to add that capability back in.

**Comment by trichter** [comment]
Thanks for the quick fix :+1:
