### ISSUE TITLE
setup.py crashes if numpy is not installed before cartopy

### ISSUE THREAD

**Issue by rune-bk** [SciTools/cartopy#1584]
This crashes the setup if numpy is not installed by pip before cartopy.

https://github.com/SciTools/cartopy/blob/60ae9a63bd8a4887475620bd8d9176f1cb721544/setup.py#L59-L62

Given that it is already in the requirements this block of code should be removed?

**Comment by greglucas** [comment]
It is in the requirements, but it is also needed for installation I believe, so needs an install_requires as well. See also issue #1552, which I think is similar to this.

**Comment by dopplershift** [comment]
`install_requires` is for run/import-time dependencies. `setup_requires` is for install-time dependencies (need to run `setup.py`).

**Comment by QuLogic** [comment]
I believe this is fixed by #1681.
