### ISSUE TITLE
Drawing user-specified latitudes and longitudes does not work

### ISSUE THREAD

**Issue by AgilentGCMS** [SciTools/cartopy#1587]
### Description
I am trying to draw latitudes and longitudes on a global map with the ```gridlines``` method in cartopy. If I do not specify the latitudes and longitudes to draw, it draws the default, which looks fine. However, if I specify the latitudes and/or longitude to draw, the result is wrong. The latitudes and longitudes are not drawn completely.

#### Code to reproduce
My basic code to plot the map and the default set of lats/lons is
```python
import numpy as np
import cartopy.crs as ccrs
import cartopy.feature as cfeature
from matplotlib import pyplot as plt
import matplotlib.ticker as mticker

lon_center = 0.0

map_proj = ccrs.Robinson(central_longitude=lon_center)
data_proj = ccrs.PlateCarree(central_longitude=lon_center)

# not strictly necessary, but looks nice
aspect = (map_proj.x_limits[1]-map_proj.x_limits[0])/(map_proj.y_limits[1]-map_proj.y_limits[0])
height = 5.0
width = aspect * height
fig = plt.figure(figsize=(width, height))

plot_ax = plt.axes([0.,0.,1.,1.], projection=map_proj)

plot_ax.add_feature(cfeature.COASTLINE.with_scale('50m'), linewidth=0.7, edgecolor='k')
plot_ax.add_feature(cfeature.LAKES.with_scale('50m'), linewidth=0.5, edgecolor='k', facecolor='none')

gl = plot_ax.gridlines(crs=data_proj, linewidth=0.5, linestyle=(0,(5,2)), color='0.25')
```
This [looks fine](https://drive.google.com/file/d/1okfqF-G7DF3BzgY9HtqTRk8eGqNRiUll/view?usp=sharing). However, if I now try to specify the latitudes and longitudes I want with
```python
gl = plot_ax.gridlines(crs=data_proj, linewidth=0.5, linestyle=(0,(5,2)), color='0.25')
gl.xlocator = mticker.FixedLocator(np.arange(-150.,151.,30.))
gl.ylocator = mticker.FixedLocator(np.arange(-60.,61.,30.))
```
I [get this](https://drive.google.com/file/d/1plcs5o3tkVlsrEELo2NlRp6wsYsqr5ex/view?usp=sharing). None of the latitudes and longitudes span the entire map. If instead I try to use a single call to gridlines, as in
```python
plot_ax.gridlines(xlocs=np.arange(-150.,151.,30.), ylocs=np.arange(-60.,61.,30.), linewidth=0.5, linestyle=(0,(5,2)), color='0.25')
```
The same problem occurs.

### Operating system and environment definition
- Operating system: MacOS 10.15.5 (64 bit)
- Python version: 3.8.3 (installed via macports)
- Cartopy version: 0.17.0
- Matplotlib version: 3.2.1
- Numpy version: 1.18.4

**Comment by QuLogic** [comment]
Please update to 0.18, and try again.

**Comment by AgilentGCMS** [comment]
I installed cartopy through macports, so it's not easy for me to update cartopy until version 0.18 makes its way into macports. Is there another fix? Is something as basic (not in the sense of being easy, but in the sense of being essential to most mapping) as drawing lats and lons broken except in the latest release?

**Comment by QuLogic** [comment]
Gridlines were limited to the range of the other direction in 0.17. If you want them to fill the entire Axes, just add another gridline at ±180 in `xlocs` and ±90 in `ylocs`.

**Comment by AgilentGCMS** [comment]
OK, that worked. Thanks!
