### ISSUE TITLE
proj version error

### ISSUE THREAD

**Issue by dbpodrasky** [SciTools/cartopy#1594]
Trying to upgrade to cartopy 0.18 from 0.17. Getting PROJ version error:

```
Proj version 4.8.0 is installed, but cartopy requires at least version 4.9.0.
```
$PKG_CONFIG_PATH is set
```
pkg-config --modversion proj
```
gives
```
4.9.3
```
What _else_ do I have to do to upgrade to 0.18?

**Comment by QuLogic** [comment]
Does `pkg-config --cflags proj` and `pkg-config --libs proj` work?

**Comment by dbpodrasky** [comment]
```pkg-config --cflags proj``` and ```pkg-config --libs proj``` give
```-I/opt/local/lib/proj49/include``` and ```-L/opt/local/lib/proj49/lib -lproj```

**Comment by greglucas** [comment]
PROJ is no longer an explicit dependency, so this should be solved.
