### ISSUE TITLE
Plotting points with scatter() changes the lat/lon bounds

### ISSUE THREAD

**Issue by AgilentGCMS** [SciTools/cartopy#1597]
### Description
If I plot some points on a cartopy map with ```scatter()```, it changes the extent of the plot. Best way is to illustrate with an example (below).

#### Code to reproduce
```python
import numpy as np
import cartopy.crs as ccrs
import cartopy.feature as cfeature
from matplotlib import pyplot as plt

lon_center = 0.0

map_proj = ccrs.Robinson(central_longitude=lon_center)
data_proj = ccrs.PlateCarree(central_longitude=lon_center)

# not strictly necessary, but looks nice
aspect = (map_proj.x_limits[1]-map_proj.x_limits[0])/(map_proj.y_limits[1]-map_proj.y_limits[0])
height = 5.0
width = aspect * height
fig = plt.figure(figsize=(width, height))

plot_ax = plt.axes([0.,0.,1.,1.], projection=map_proj)

plot_ax.add_feature(cfeature.BORDERS.with_scale('50m'), linewidth=0.5, edgecolor='k', facecolor='none')
plot_ax.add_feature(cfeature.LAKES.with_scale('50m'), linewidth=0.5, edgecolor='k', facecolor='none')
plot_ax.add_feature(cfeature.COASTLINE.with_scale('50m'), linewidth=0.7, edgecolor='k')

plot_ax.gridlines(xlocs=np.arange(-180.,181.,30.), ylocs=np.arange(-90.,91.,30.), linewidth=0.5, linestyle=(0,(5,2)), color='0.25')
```
The above will plot a [nice globe with country borders and coastlines](https://drive.google.com/file/d/1F5HB6B3lDQqyj3nAehEvPA2qrEJgqVtl/view?usp=sharing). So far so good. However, if I want to add a few points as a scatter plot, like so:
```python
lats = np.random.uniform(20.,40.,size=10)
lons = np.random.uniform(-120.,-90.,size=10)
plot_ax.scatter(lons, lats, s=20, c='r', marker='o', linewidths=1, transform=data_proj)
```
The extent of the map [automatically shrinks](https://drive.google.com/file/d/1GsazeTNk-HQJwByyTY6Up_LucZLzzQSi/view?usp=sharing) to accommodate just the plotted points. Why??

### Operating system and environment definition
- Operating system: MacOS 10.15.5 (64 bit)
- Python version: 3.8.3 (installed via macports)
- Cartopy version: 0.17.0
- Matplotlib version: 3.2.1
- Numpy version: 1.18.4

I would appreciate a fix other than to "upgrade to the latest release", at the moment that's not practical for me.

**Comment by QuLogic** [comment]
Call `plot_ax.set_global` or `plot_ax.set_extent` to set explicit extent.

**Comment by AgilentGCMS** [comment]
OK, that fixed it.
