### ISSUE TITLE
Cartopy module not found 

### ISSUE THREAD

**Issue by adelhasse** [SciTools/cartopy#1599]
Hi,
I'm a python beginner. I use Anaconda3 and spyder (under linux). I would like to use Cartopy. I installed it as follows: 
"conda install -c conda-forge cartopy"
the installation seems to have gone well but when running in spyder, I get this message "ModuleNotFoundError: No module named 'cartopy' ".
Cartopy is actually not in my package list ("conda list").

In this list, I don't have the following prerequisites either: Geos, proj, pyshp and shapely. I tried to install them, but obviously it doesn't work. 

Here is an example when I install something:

> conda install -c conda-forge proj

Collecting package metadata (current_repodata.json): done
Solving environment: \ 
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - defaults/linux-64::netcdf4==1.4.2=py37h808af73_0
  - defaults/linux-64::astroid==2.3.1=py37_0
  - defaults/noarch::backports.functools_lru_cache==1.5=py_2
  - defaults/linux-64::bleach==3.1.0=py37_0
  - defaults/linux-64::clyent==1.2.2=py37_1
  - defaults/linux-64::cython==0.29.13=py37he6710b0_0
  - defaults/linux-64::isort==4.3.21=py37_0
  - defaults/noarch::jinja2==2.10.3=py_0
  - defaults/linux-64::jsonschema==3.0.2=py37_0
  - defaults/noarch::networkx==2.3=py_0
  - defaults/linux-64::nose==1.3.7=py37_2
  - defaults/noarch::pygments==2.4.2=py_0
  - defaults/linux-64::sympy==1.4=py37_0
  - defaults/linux-64::wheel==0.33.6=py37_0
  - defaults/noarch::conda-verify==3.4.2=py_1
  - defaults/noarch::flask==1.1.1=py_0
  - defaults/linux-64::nbformat==4.4.0=py37_0
  - defaults/noarch::prompt_toolkit==2.0.10=py_0
  - defaults/linux-64::pylint==2.4.2=py37_0
  - defaults/linux-64::ipython==7.8.0=py37h39e3cac_0
  - defaults/linux-64::nbconvert==5.6.0=py37_1
  - defaults/linux-64::pytest==5.2.1=py37_0
  - defaults/linux-64::ipykernel==5.1.2=py37h39e3cac_0
  - defaults/noarch::pytest-openfiles==0.4.0=py_0
  - defaults/linux-64::pytest-remotedata==0.3.2=py37_0
  - defaults/linux-64::anaconda-client==1.7.2=py37_0
  - defaults/linux-64::jupyter_console==6.0.0=py37_0
  - defaults/linux-64::notebook==6.0.1=py37_0
  - defaults/noarch::qtconsole==4.5.5=py_0
  - defaults/noarch::sphinx==2.2.0=py_0
  - defaults/linux-64::spyder-kernels==0.5.2=py37_0
  - defaults/linux-64::anaconda-navigator==1.9.7=py37_0
  - defaults/noarch::anaconda-project==0.8.3=py_0
  - defaults/linux-64::conda-build==3.18.9=py37_3
  - defaults/noarch::jupyterlab_server==1.0.6=py_0
  - defaults/noarch::numpydoc==0.9.1=py_0
  - defaults/linux-64::widgetsnbextension==3.5.1=py37_0
  - defaults/noarch::ipywidgets==7.5.1=py_0
  - defaults/noarch::jupyterlab==1.1.4=pyhf63ae98_0
  - defaults/linux-64::spyder==3.3.6=py37_0
  - defaults/linux-64::_ipyw_jlab_nb_ext_conf==0.1.0=py37_0
  - defaults/linux-64::jupyter==1.0.0=py37_7
  - defaults/linux-64::bokeh==1.3.4=py37_0
  - defaults/noarch::dask==2.5.2=py_0
  - defaults/linux-64::matplotlib==3.1.1=py37h5429711_0
  - defaults/linux-64::pytest-arraydiff==0.3=py37h39e3cac_0
  - defaults/noarch::pytest-doctestplus==0.4.0=py_0
  - defaults/linux-64::pytest-astropy==0.5.0=py37_0
  - defaults/linux-64::scikit-image==0.15.0=py37he6710b0_0
  - defaults/linux-64::astropy==3.2.2=py37h7b6447c_0
  - defaults/linux-64::anaconda==2019.10=py37_0
  - anaconda/linux-64::seaborn==0.9.0=py37_0
  - defaults/linux-64::conda==4.8.3=py37_0
  - defaults/noarch::xarray==0.15.1=py_0
done

## Package Plan ##

  environment location: /home/adelhasse/anaconda3

  added / updated specs:
    - proj

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    proj-6.2.0                 |       hc80f0dc_1        10.1 MB  conda-forge
    ------------------------------------------------------------
                                           Total:        10.1 MB

The following NEW packages will be INSTALLED:

  _anaconda_depends  pkgs/main/linux-64::_anaconda_depends-2020.02-py37_0
  argh               conda-forge/linux-64::argh-0.26.2-py37_1001
  autopep8           pkgs/main/linux-64::autopep8-1.4.3-py37_0
  diff-match-patch   conda-forge/noarch::diff-match-patch-20181111-py_0
  flake8             conda-forge/linux-64::flake8-3.7.9-py37hc8dfbb8_1
  hypothesis         conda-forge/noarch::hypothesis-5.18.2-py_0
  intervaltree       conda-forge/noarch::intervaltree-3.0.2-py_0
  ld_impl_linux-64   conda-forge/linux-64::ld_impl_linux-64-2.34-h53a641e_5
  libspatialindex    conda-forge/linux-64::libspatialindex-1.9.3-he1b5a44_3
  matplotlib-base    pkgs/main/linux-64::matplotlib-base-3.1.3-py37hef1b27d_0
  path               conda-forge/linux-64::path-14.0.1-py37hc8dfbb8_0
  pathtools          conda-forge/noarch::pathtools-0.1.2-py_1
  pip                conda-forge/noarch::pip-20.1.1-py_1
  proj               conda-forge/linux-64::proj-6.2.0-hc80f0dc_1
  pydocstyle         conda-forge/noarch::pydocstyle-5.0.2-py_0
  pytest-astropy-he~ conda-forge/noarch::pytest-astropy-header-0.1.2-py_0
  python-jsonrpc-se~ conda-forge/noarch::python-jsonrpc-server-0.3.4-pyh9f0ad1d_1
  python-language-s~ conda-forge/linux-64::python-language-server-0.31.10-py37hc8dfbb8_0
  pyxdg              conda-forge/noarch::pyxdg-0.26-py_0
  qdarkstyle         conda-forge/noarch::qdarkstyle-2.8.1-pyh9f0ad1d_0
  rtree              conda-forge/linux-64::rtree-0.9.4-py37h8526d28_1
  setuptools         conda-forge/linux-64::setuptools-47.3.1-py37hc8dfbb8_0
  ujson              conda-forge/linux-64::ujson-1.35-py37h3340039_1002
  watchdog           conda-forge/linux-64::watchdog-0.10.3-py37hc8dfbb8_0
  yapf               conda-forge/noarch::yapf-0.29.0-py_0

The following packages will be UPDATED:

  ca-certificates    pkgs/main::ca-certificates-2019.8.28-0 --> conda-forge::ca-certificates-2020.6.20-hecda079_0
  certifi               pkgs/main::certifi-2019.9.11-py37_0 --> conda-forge::certifi-2020.6.20-py37hc8dfbb8_0
  openssl              pkgs/main::openssl-1.1.1d-h7b6447c_2 --> conda-forge::openssl-1.1.1g-h516909a_0

The following packages will be DOWNGRADED:

  anaconda                                   2019.10-py37_0 --> custom-py37_1

Proceed ([y]/n)? 

Downloading and Extracting Packages
proj-6.2.0           | 10.1 MB   | ############################################################# | 100% 
Preparing transaction: done
Verifying transaction: failed

RemoveError: 'setuptools' is a dependency of conda and cannot be removed from
conda's operating environment.

I have no idea how to solve this.
Many thanks to help me in advance

**Comment by QuLogic** [comment]
The environment you are running `conda install` in and the environment you are running Spyder in are not the same. You need to put those in sync or this will happen for all packages you install.

Closing though, because this is not a Cartopy bug.
