### ISSUE TITLE
Clip data array to map extent before plotting

### ISSUE THREAD

**Issue by karlwx** [SciTools/cartopy#1603]
### Feature Request

Most of my projects with cartopy involve plotting the same data on many different map domains/zooms. Often, when working with weather data, I'll open a large netcdf file (could be data for the entire globe), but I'm only interested in plotting the data for a few different map domains in North America. As anyone who has experience plotting large datasets will know, this process can be _very_ slow. Often, this is because matplotlib wastes time plotting data that will ultimately be outside of the map extent. The way I speed this up is by taking a subset of the main dataset that covers each domain, with a bit of overlap to make sure I don't get gaps around the edges of the plot. This is fairly easy to do, if you are dealing with an xarray dataset. 

My general workflow goes something like this:
```python
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import cartopy.feature as cfeature
import xarray as xr

# Figure
extent = [-123,-70,20,55]
fig = plt.figure(figsize=(12,9))
ax = fig.add_subplot(111, projection=ccrs.LambertConformal())
ax.set_extent(extent)
ax.add_feature(cfeature.COASTLINE.with_scale('50m'))
ax.add_feature(cfeature.STATES.with_scale('50m'))

# Open precip dataset and clip to domain shape
ds  = xr.open_dataset('precip.nc')
padding = 1 # padding around domain
ds = ds.where((ds.longitude>=(extent[0]+360.-padding))&(ds.longitude<=(extent[1]+360.+padding))&
          (ds.latitude>=(extent[2]-padding))&(ds.latitude<=(extent[3]+padding)), drop=True)

# Then contour the data
ax.contourf(ds.longitude, ds.latitude, ds['APCP_surface'].values, cmap=..., ...)
```
It would be nice if we could skip the step of selecting a subset of the data (especially because if you're not using xarray, this is very inconvenient), and I could instead simply pass the original global arrays of longitude, latitude, and data to contourf, and any points outside of the map extent would be automatically masked (this assumes the map extent has been set before the data is plotted).  I'm not sure how easy this would be to do, but maybe determine all points that are inside of the map window and mask the rest before plotting? Could be a keyword argument in the countourf/pcolormesh/contour call that will mask to a specified extent, or the axis extent if it's already set.

**Comment by greglucas** [comment]
Would adding a clip_path suit your needs? Just make a patch to clip the contour data with before plotting.
```python
patch = mpatches.PathPatch(path, transform=ax.transData)
cont = ax.contourf(...)
for col in cont.collections:
    col.set_clip_path(patch)
```

I think leaving the data processing upstream in `xarray` or `geopandas` to sub-select data makes sense since those are the data processing libraries and have lots of functionality for powerful differences and unions of data. I think it would be a rabbit hole of deciding what data to keep and is needed for the plotting versus what can be masked. Especially when considering interactive capabilities where a user may pan to a new region outside of that extra 1 degree pad and then it may be empty when they originally passed in data for that region.

**Comment by QuLogic** [comment]
In 0.18, the clip path should be set, I think? Because it would come from the Axes patch.

**Comment by karlwx** [comment]
> Would adding a clip_path suit your needs? Just make a patch to clip the contour data with before plotting.

I'm fine with adding a clip path, if that can work. I can see that it would be simple to define such a path for projections that have straight latitude/longitude lines, like PlateCarree, Mercator, Miller, etc. But would this become difficult for LambertConformal? 

I thought it would be possible to select the data to plot based on the visible lat/lon extent in the image, but so far I've gotten no response on my stackoverflow question: https://stackoverflow.com/questions/62722894/how-to-determine-visible-map-extent-for-any-cartopy-projection

> I think leaving the data processing upstream in `xarray` or `geopandas` to sub-select data makes sense since those are the data processing libraries and have lots of functionality for powerful differences and unions of data. I think it would be a rabbit hole of deciding what data to keep and is needed for the plotting versus what can be masked. Especially when considering interactive capabilities where a user may pan to a new region outside of that extra 1 degree pad and then it may be empty when they originally passed in data for that region.

I suppose I use cartopy a bit differently than most users. I never encounter scenarios where I want to adjust the map extent, but leave all the features I plotted the same. If I'm zoomed in over Pennsylvania, for instance, I want to show roads, counties, and maybe a few city labels. If I'm showing the entire east coast, I probably won't want those things, and I'd probably have a different resolution for the state lines, anyway. I would think this would involve clearing the entire axes and then plotting these features again, which I don't think would save any time over starting a new process to create an entirely new graphic. Maybe there's something I'm not seeing and I've been approaching this from the wrong angle, though. 

I think a similar issue arises for shapefiles too - again there is no reason for me to plot all of the US counties if all I'll be showing is Pennsylvania. 

If we could properly define a clip path that is the exact boundaries of the visible map extent, I think that would solve my issue. I could just add that in to my own code.

**Comment by greglucas** [comment]
I think @QuLogic is right, the clip path should already be automatically applied in 0.18. But, I think the contour(f) math calculations will still occur right away using all the data...? So I think the `clip_path` will help with the rendering speed, but not the contour math calculation speed.

My guess is your use-case is not unique at all! For different scales, there is an AdaptiveScaler feature that should automatically be applied to coastlines and things like that to choose a better high/medium/low resolution depending on the extents. But, you can also tune it to your needs to grab different resolutions at different limits.

I still think the math calculation data restrictions are probably better pushed up to one of the data handling libraries. But, what you can do is possibly grab the boundary patch that was obtained with a `set_extent` command and then filter your geometries/data with that patch. Some helper routines I commonly use to restrict my data extents to regions of interest using a predefined polygon I define may be able to help in your situation I put below here.

<details>
  <summary>click for code</summary>
  
```python
def get_intersections(df, lon_bounds, lat_bounds):
    spatial_index = df.sindex

    x0, x1 = lon_bounds
    y0, y1 = lat_bounds
    polygon = shapely.geometry.Polygon([[x0, y0], [x1, y0], [x1, y1], [x0, y1]])

    possible_matches_index = list(spatial_index.intersection(polygon.bounds))
    possible_matches = df.iloc[possible_matches_index]
    precise_matches = possible_matches[possible_matches.intersects(polygon)]
    return precise_matches

def get_intersection_polygon(df, polygon):
    spatial_index = df.sindex
    possible_matches_index = list(spatial_index.intersection(polygon.bounds))
    possible_matches = df.iloc[possible_matches_index]
    precise_matches = possible_matches[possible_matches.intersects(polygon)]
    return precise_matches
```

</details>

**Comment by karlwx** [comment]
I didn't realize I was still on v0.17 so the ```clip_path``` feature was not available. Unfortunately, I can't upgrade to v0.18 quite yet because of some compatibility issues with metpy. Hopefully it will make a difference when I am able to upgrade!

The problem I'm dealing with as far as clipping goes is determining the bounds to use for the clip, not necessarily defining any polygon to do it and/or using xarray. On a LambertConformal map, if I clip my data to the extent specified in ```set_extent``` the data does not fill the entire image. 

```python
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import cartopy.feature as cfeature
import numpy as np

extent = [-123,-70,20,55]
fig = plt.figure(figsize=(12,9))
ax = fig.add_subplot(111, projection=ccrs.LambertConformal())
ax.set_extent(extent)
ax.add_feature(cfeature.COASTLINE.with_scale('50m'))
ax.add_feature(cfeature.STATES.with_scale('50m'))

# Test data, the same size as extent
lons = np.arange(extent[0],extent[1]+1,1)
lats = np.arange(extent[2],extent[3]+1,1)
data = np.random.rand(len(lats), len(lons))

ax.contourf(lons,lats,data,transform=ccrs.PlateCarree())
```

The result:
![test1](https://user-images.githubusercontent.com/45180714/86975190-c88fe880-c145-11ea-8ced-a0d47265ffcc.png)

My primary question is - how do I determine the proper area to clip to (what are the ACTUAL lat/lon limits visible in the map)? So far I have not found a solid answer for this. I want to set the extent and clip in data coordinates (usually lat/lon).

**Comment by karlwx** [comment]
I think I figured it out - I realized that I could create a decent mask by converting each data point to axes coordinates. If the points are in the figure, they should be between (0,0) and (1,1). I expanded the selection to be from (-0.05, -0.05) to (1.05, 1.05) to give some padding for coarse grids. Here's the code:
```python
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import cartopy.feature as cfeature
import numpy as np

# Set up map
extent = [-123,-70,20,55]
fig = plt.figure(figsize=(12,9))
ax = fig.add_subplot(111, projection=ccrs.LambertConformal())
ax.set_extent(extent)
ax.add_feature(cfeature.COASTLINE.with_scale('50m'))
ax.add_feature(cfeature.STATES.with_scale('50m'))

# Define some dummy coordinates and variable - the entire northern hemisphere
lat = np.arange(0,91,1)
lon = np.arange(-180,1,1)
lons,lats = np.meshgrid(lon,lat)
data = np.random.rand(len(lat), len(lon))

# Converts data coordinates to matplotlib axis coordinates
def data_to_ax_coords(x, y):
    point = ccrs.LambertConformal().transform_point(x,y,src_crs=ccrs.PlateCarree())
    fig_coords = ax.transData.transform(point)
    ax_coords = ax.transAxes.inverted().transform(fig_coords)
    
    return ax_coords

# Convert each data grid point to axes coordinates
x, y = (np.empty((len(lat), len(lon))), np.empty((len(lat), len(lon))))
for yy in lat:  
    for xx in lon:
        x2, y2 = data_to_ax_coords(xx, yy)
        x[yy][xx], y[yy][xx] = (x2, y2)
        
# Mask out areas that are outside of the axes - add a bit of padding
mask = (x>=-0.05) & (x<=1.05) & (y>=-0.05) & (y<=1.05)
lons = np.ma.masked_array(lons, ~mask)
lats = np.ma.masked_array(lats, ~mask)
data = np.ma.masked_array(data, ~mask)

ax.contourf(lons,lats,data,transform=ccrs.PlateCarree())
```
The only thing I don't like about the code I've written is the nested for loop that calculates the axis coordinates for each point. I think this could be very slow for a large number of grid points. Anyone have ideas on how to improve it? 

I'll leave the issue open for a few more days if anyone has ideas, otherwise I will close it as it seems I have solved my own issue.

**Comment by greglucas** [comment]
There is also a `transform_points` method to do all the points at once which will avoid your loops.
https://scitools.org.uk/cartopy/docs/latest/crs/index.html#cartopy.crs.CRS.transform_points

**Comment by karlwx** [comment]
Thanks, I finally figured it out with ```transform_points``` - just had to do a bit of flattening and reshaping to work with matplotlib's transforms. 

```python
points = ccrs.LambertConformal().transform_points(ccrs.PlateCarree(), lons, lats)
xpts = points[:,:,0].flatten().tolist()
ypts = points[:,:,1].flatten().tolist()
crs_pts = list(zip(xpts,ypts))
fig_pts = ax.transData.transform(crs_pts)
ax_pts = ax.transAxes.inverted().transform(fig_pts)
x = ax_pts[:,0].reshape(lats.shape)
y = ax_pts[:,1].reshape(lats.shape)

mask = (x>=-0.05) & (x<=1.05) & (y>=-0.05) & (y<=1.05)
```
The runtime is now reasonable even with a large number of points.
