### ISSUE TITLE
Cannot download shape files

### ISSUE THREAD

**Issue by K20shores** [SciTools/cartopy#1605]
### Description
I posted an issue on [stackoverflow](https://stackoverflow.com/questions/62733532/cartopy-cant-download-shapefiles-because-a-certificate-is-not-trusted), but I thought, for posterity, that I should post it here as well.

I am trying to run the most basic example below. This, of course, tries to download some shape files. That download fails because of a certificate error. I've tried downloading the certificate and placing it into my key chain and trusting it. That did not work.

#### Code to reproduce
```
import cartopy.crs as ccrs
import matplotlib.pyplot as plt

ax = plt.axes(projection=ccrs.PlateCarree())
ax.coastlines()

plt.show()
```

#### Traceback 

> Downloading: https://naciscdn.org/naturalearth/110m/physical/ne_110m_coastline.zip
>   warnings.warn('Downloading: {}'.format(url), DownloadWarning)
> Traceback (most recent call last):
>   File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1317, in do_open
>     encode_chunked=req.has_header('Transfer-encoding'))
>   File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 1229, in request
>     self._send_request(method, url, body, headers, encode_chunked)
>   File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 1275, in _send_request
>     self.endheaders(body, encode_chunked=encode_chunked)
>   File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 1224, in endheaders
>     self._send_output(message_body, encode_chunked=encode_chunked)
>   File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 1016, in _send_output
>     self.send(msg)
>   File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 956, in send
>     self.connect()
>   File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 1392, in connect
>     server_hostname=server_hostname)
>   File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 412, in wrap_socket
>     session=session
>   File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 853, in _create
>     self.do_handshake()
>   File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 1117, in do_handshake
>     self._sslobj.do_handshake()
> ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/env/lib/python3.7/site-packages/matplotlib/backends/backend_macosx.py", line 74, in _draw
>     self.figure.draw(renderer)
>   File "/env/lib/python3.7/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
>     return draw(artist, renderer, *args, **kwargs)
>   File "/env/lib/python3.7/site-packages/matplotlib/figure.py", line 1736, in draw
>     renderer, self, artists, self.suppressComposite)
>   File "/env/lib/python3.7/site-packages/matplotlib/image.py", line 137, in _draw_list_compositing_images
>     a.draw(renderer)
>   File "/env/lib/python3.7/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
>     return draw(artist, renderer, *args, **kwargs)
>   File "/env/lib/python3.7/site-packages/cartopy/mpl/geoaxes.py", line 479, in draw
>     return matplotlib.axes.Axes.draw(self, renderer=renderer, **kwargs)
>   File "/env/lib/python3.7/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
>     return draw(artist, renderer, *args, **kwargs)
>   File "/env/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 2630, in draw
>     mimage._draw_list_compositing_images(renderer, self, artists)
>   File "/env/lib/python3.7/site-packages/matplotlib/image.py", line 137, in _draw_list_compositing_images
>     a.draw(renderer)
>   File "/env/lib/python3.7/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
>     return draw(artist, renderer, *args, **kwargs)
>   File "/env/lib/python3.7/site-packages/cartopy/mpl/feature_artist.py", line 155, in draw
>     geoms = self._feature.intersecting_geometries(extent)
>   File "/env/lib/python3.7/site-packages/cartopy/feature/__init__.py", line 302, in intersecting_geometries
>     return super(NaturalEarthFeature, self).intersecting_geometries(extent)
>   File "/env/lib/python3.7/site-packages/cartopy/feature/__init__.py", line 110, in intersecting_geometries
>     return (geom for geom in self.geometries() if
>   File "/env/lib/python3.7/site-packages/cartopy/feature/__init__.py", line 286, in geometries
>     name=self.name)
>   File "/env/lib/python3.7/site-packages/cartopy/io/shapereader.py", line 295, in natural_earth
>     return ne_downloader.path(format_dict)
>   File "/env/lib/python3.7/site-packages/cartopy/io/__init__.py", line 222, in path
>     result_path = self.acquire_resource(target_path, format_dict)
>   File "/env/lib/python3.7/site-packages/cartopy/io/shapereader.py", line 350, in acquire_resource
>     shapefile_online = self._urlopen(url)
>   File "/env/lib/python3.7/site-packages/cartopy/io/__init__.py", line 261, in _urlopen
>     return urlopen(url)
>   File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
>     return opener.open(url, data, timeout)
>   File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 525, in open
>     response = self._open(req, data)
>   File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 543, in _open
>     '_open', req)
>   File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
>     result = func(*args)
>   File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1360, in https_open
>     context=self._context, check_hostname=self._check_hostname)
>   File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1319, in do_open
>     raise URLError(err)
> urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)>

<details>

### Operating system
macOS Catalina 10.15.4
python 3.7.3

### Cartopy version
Cartopy 0.18.0

### pip list
```
astroid==2.4.2
autopep8==1.5.3
Cartopy==0.18.0
cycler==0.10.0
isort==4.3.21
kiwisolver==1.2.0
lazy-object-proxy==1.4.3
matplotlib==3.2.2
mccabe==0.6.1
numpy==1.19.0
pandas==1.0.5
patsy==0.5.1
pycodestyle==2.6.0
pylint==2.5.3
pyparsing==2.4.7
pyshp==2.1.0
python-dateutil==2.8.1
pytz==2020.1
rope==0.17.0
scipy==1.5.0
Shapely==1.7.0
six==1.15.0
statsmodels==0.11.1
toml==0.10.1
typed-ast==1.4.1
wrapt==1.12.1
```

</details>

**Comment by QuLogic** [comment]
I'm not sure there's much we can help you with here; it seems to be a Python problem.

**Comment by K20shores** [comment]
I thought the problem might be the python version.

I made a virtual environment for python 3.8, installed the packages, and then tried to run the same example above.

```
python3.8 -m venv env
source env/bin/activate
vim example.py // added the basic example
pip install --upgrade pip
pip install numpy
pip install cartopy
pip install matplotlib
pip install scipy
python example.py 
```

And I received this error

>Geometry must be a Point or LineString
>Geometry must be a Point or LineString
>Assertion failed: (0 != cs), function GEOSCoordSeq_getSize_r, file geos_ts_c.cpp, line 4038.
>Abort trap: 6

So the download happened just fine, but the basic example doesn't work.

**Comment by K20shores** [comment]
Ah, I had to re-sintall `shapely` not from a binary. https://stackoverflow.com/questions/60111684/geometry-must-be-a-point-or-linestring-error-using-cartopy
