### ISSUE TITLE
OSError

### ISSUE THREAD

**Issue by rgoalcast** [SciTools/cartopy#1632]
### Description
After Installation of cartopy, not able to import; Please, How can I improve OSError?
import cartopy.crs as ccrs

import cartopy.crs as ccrs
Traceback (most recent call last):

  File "<ipython-input-1-139fa5ad2567>", line 1, in <module>
    import cartopy.crs as ccrs
  File "/Users/name/opt/anaconda3/lib/python3.8/site-packages/cartopy/__init__.py", line 96, in <module>
    import cartopy.crs
  File "/Users/name/opt/anaconda3/lib/python3.8/site-packages/cartopy/crs.py", line 32, in <module>
    import shapely.geometry as sgeom
  File "/Users/name/opt/anaconda3/lib/python3.8/site-packages/shapely/geometry/__init__.py", line 4, in <module>
    from .base import CAP_STYLE, JOIN_STYLE
  File "/Users/name/opt/anaconda3/lib/python3.8/site-packages/shapely/geometry/base.py", line 18, in <module>
    from shapely.coords import CoordinateSequence
  File "/Users/name/opt/anaconda3/lib/python3.8/site-packages/shapely/coords.py", line 8, in <module>
    from shapely.geos import lgeos
  File "/Users/name/opt/anaconda3/lib/python3.8/site-packages/shapely/geos.py", line 112, in <module>
    _lgeos = CDLL(os.path.join(sys.prefix, 'lib', 'libgeos_c.dylib'))
  File "/Users/name/opt/anaconda3/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)

OSError: dlopen(/Users/name/opt/anaconda3/lib/libgeos_c.dylib, 6): image not found

**Comment by dopplershift** [comment]
I see you're using Anaconda. How did you install cartopy and shapely? I wouldn't expect this error if you used `conda` to install them.

**Comment by rgoalcast** [comment]
OsError : OSError: dlopen(/Users/name/opt/anaconda3/lib/libgeos_c.dylib, 6): image not found. Error is coming, after updates also trough Spyder IPython Console : 

pip install --upgrade cartopy

Requirement already up-to-date: cartopy in ./opt/anaconda3/lib/python3.8/site-packages (0.18.0)
Requirement already satisfied, skipping upgrade: numpy>=1.10 in ./opt/anaconda3/lib/python3.8/site-packages (from cartopy) (1.19.1)
Requirement already satisfied, skipping upgrade: setuptools>=0.7.2 in ./opt/anaconda3/lib/python3.8/site-packages (from cartopy) (49.3.1)
Requirement already satisfied, skipping upgrade: shapely>=1.5.6 in ./opt/anaconda3/lib/python3.8/site-packages (from cartopy) (1.7.0)
Requirement already satisfied, skipping upgrade: six>=1.3.0 in ./opt/anaconda3/lib/python3.8/site-packages (from cartopy) (1.15.0)
Requirement already satisfied, skipping upgrade: pyshp>=1.1.4 in ./opt/anaconda3/lib/python3.8/site-packages (from cartopy) (2.1.0)
Note: you may need to restart the kernel to use updated packages.

pip install --upgrade shapely
Requirement already up-to-date: shapely in ./opt/anaconda3/lib/python3.8/site-packages (1.7.0)
Note: you may need to restart the kernel to use updated packages.

**Comment by dopplershift** [comment]
Installing CartoPy with pip is fraught with challenges with making cartopy and shapely install using the same libgeos. The way for that is:
```
pip uninstall shapely
pip install --no-binary :all: shapely
```
Really, since you're already using Anaconda, the easier way is just to install everything from conda-forge:
```
pip uninstall cartopy shapely
conda install -c conda-forge cartopy
```

**Comment by rgoalcast** [comment]
Thank you.
