### ISSUE TITLE
Feature request: option to remove 'E', 'W', 'N', 'S' from axis labels

### ISSUE THREAD

**Issue by ricitron** [SciTools/cartopy#1635]
### Description

I would like to be able to format my axis labels so that there is no N/S/E/W after the label. 

Is this possible? It seems like a simple option could be added to the Longitude/Latitude formatters. 

In Basemap there was an option for labelstyle="+/-" that could do exactly this. 
<!--

**Comment by greglucas** [comment]
Seems like an option for that could definitely be added to the formatters. We already have `dateline_direction_label` https://github.com/SciTools/cartopy/blob/466c901f8f38ab4a26fd2736ccf49c98086de03b/lib/cartopy/mpl/ticker.py#L318-L322
Maybe just `direction_label` as a boolean that defaults to True? Would you want to open a PR to add something like that in?

**Comment by gcaria** [comment]
Hi,
I'm a beginner and I'd be happy to work on this.

I'm assuming the new `direction_label` option would overwrite both `zero_direction_label` and `dateline_direction_label`, right ?

**Comment by greglucas** [comment]
Great, thanks for taking this on! I think this new keyword would take precedence over the more specific dateline options.
