### ISSUE TITLE
Issues with baked-in oceans

### ISSUE THREAD

**Issue by karlwx** [SciTools/cartopy#1661]
I'm currently adding oceans to my maps with cartopy's cfeature.OCEAN:
```python
ax.add_feature(cfeature.OCEAN.with_scale('10m'), facecolor='lightblue')
```
There are several issues I've encountered. Most notably, 10m oceans render incorrectly on several projections I've tried. 
PlateCarree:
![platecarree](https://user-images.githubusercontent.com/45180714/93622882-debeee00-f9ab-11ea-8335-41aa3a6ee27f.png)
Miller:
![miller](https://user-images.githubusercontent.com/45180714/93622885-debeee00-f9ab-11ea-82b8-b4566524cd1f.png)
I tried LambertConformal as well, but the image generation was too slow to produce anything. 

I've had success with 50m and 110m oceans, but not 10m. 

Also, it appears the default zorder for the ocean is incorrect; when using a user-defined map background inserted with ```ax.background_img()```, the map background appears above the ocean layer (even when background is added first). This is fixed with setting zorder=1 on the ocean, but seems a bit odd that this is the default.

**Comment by karlwx** [comment]
I installed Fiona and it seems to have fixed the problems with the oceans rendering. I'll leave this open because of the small issue with the basemap/ocean zorder.

**Comment by greglucas** [comment]
The OCEANS have an explicitly set zorder.
https://github.com/SciTools/cartopy/blob/b71173be425d402e9863745987c9b34b55768ad2/lib/cartopy/feature/__init__.py#L507-L509

I'm not clear which way you're expecting it to work, should the oceans have a zorder=1, or the `background_img` should have a lower zorder. Intuitively I would say the `background_img` method should allow a zorder keyword argument that defaults to -2 or something else low to make sure it is actually in the background.

**Comment by QuLogic** [comment]
You can set zorder on the returned image object as well.

**Comment by karlwx** [comment]
> I'm not clear which way you're expecting it to work, should the oceans have a zorder=1, or the `background_img` should have a lower zorder. Intuitively I would say the `background_img` method should allow a zorder keyword argument that defaults to -2 or something else low to make sure it is actually in the background.

I originally was thinking the ocean zorder was the issue, but now that you point it out, setting the background_img zorder to something like -2 makes more sense.
