### ISSUE TITLE
Inaccurate distinction between ocean and land when plotting the Arctic

### ISSUE THREAD

**Issue by xiuyongwu** [SciTools/cartopy#1674]
Now, I'm ready to plot the map for the Arctic, with land and ocean in different colors. 
However, when I add_feature to the land and ocean, the color of ocean will overlap the land (or the continents near the Arctic). That is, the cartopy may be treat the ocean inaccurately in the Arctic.

The code for this map is shown as follows:

```python
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import cartopy.feature as cfeature
fig = plt.figure(figsize=[5,5])
ax1 = fig.add_subplot(1, 1, 1, projection=ccrs.NorthPolarStereo(central_longitude=0))
ax1.set_extent([-180, 180,60, 90], ccrs.PlateCarree())
ax1.gridlines()
ax1.add_feature(cfeature.LAND)
ax1.add_feature(cfeature.OCEAN)
plt.show()
```

However, if I exchange the order for the two sentences, write the "ax1.add_feature(cfeature.OCEAN)"  first and then write "ax1.add_feature(cfeature.LAND)", it seems works.

#### Code to reproduce

```

```

#### Traceback 

```

```

<details>
 <summary>Full environment definition</summary>

### conda list

```
```

### pip list

```
```

</details>

**Comment by greglucas** [comment]
There is an interpolation that takes place when adding those features to a different projection than the one they are defined in. Some other options:
* Set the axes background color to the ocean color and overplot the land to make sure there are no gaps at all.
* The default OCEAN and LAND features are also very coarse resolution (110m), so you can try to use `cfeature.LAND.with_scale('10m')` to get higher resolution data to plot and look nicer too.

**Comment by elenabrooks228** [comment]
The issue of inaccurately distinguishing between ocean and land when plotting the Arctic can significantly affect how geographic data is interpreted. Clear boundaries and precise visualization are essential for reliable mapping and research. Similar attention to detail is important in fields involving property data, where resources such as https://bergencountypropertyappraiser.org can help users better understand local assessments and values. Improving accuracy in both geographic and data-driven representations ultimately leads to more dependable results.
