### ISSUE TITLE
patch.set_facecolor fails with Cartopy 0.18 and Matplotlib 3.3.3

### ISSUE THREAD

**Issue by marceloandrioni** [SciTools/cartopy#1683]
### Description

Hello, sometimes when using very high-resolution country layers I use `ax.patch.set_facecolor` instead of `ax.add_feature(cfeature.OCEAN)` so that there is no mismatch in the coast due to the difference in resolutions. 

With `matplotlib 3.3.1` and `cartopy 0.18` it worked fine, but now with `matplotlib 3.3.3` and `cartopy 0.18` it gives a DeprecationWarning and does not change the background color:

In `matplotlib 3.3.1` and `cartopy 0.18`:
![matplotlib_331](https://user-images.githubusercontent.com/13545615/100296608-73753780-2f6b-11eb-99c0-16493ef63758.png)

In `matplotlib 3.3.3` and `cartopy 0.18`:
![matplotlib_333](https://user-images.githubusercontent.com/13545615/100296609-740dce00-2f6b-11eb-8b3a-f8db98a4fcce.png)

Thank you.

#### Code to reproduce

```
import cartopy.crs as ccrs
import cartopy.feature as cfeature
import matplotlib.pyplot as plt

fig, ax = plt.subplots(1, 1, subplot_kw={'projection': ccrs.PlateCarree()})
ax.set_extent([-20, 60, -40, 45], crs=ccrs.PlateCarree())

ax.patch.set_facecolor(color='blue')
```

#### Traceback 

```
/home/user/anaconda3/envs/work/lib/python3.7/site-packages/cartopy/mpl/geoaxes.py:388: MatplotlibDeprecationWarning: 
The 'inframe' parameter of draw() was deprecated in Matplotlib 3.3 and will be removed two minor releases later. Use Axes.redraw_in_frame() instead. If any parameter follows 'inframe', they should be passed as keyword, not positionally.
  inframe=inframe)
```

<details>
 <summary>Full environment definition</summary>

### Operating system
Linux 5.4.0-54-generic #60-Ubuntu SMP Fri Nov 6 10:37:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Cartopy version
0.18

### Matplotlib version
3.3.3

### conda list

```
```

### pip list

```
```

</details>

**Comment by greglucas** [comment]
This should have been updated in 0.18 with commit https://github.com/SciTools/cartopy/commit/210ee4becd63d1410e7260533c7412d8284bfb1b. Are you sure you are still getting Cartopy 0.18 in your virtual environment? The traceback to line 388 on 0.18 points to adding an image, which your example isn't doing and makes me think maybe it is a different version you've got...
https://github.com/SciTools/cartopy/blob/v0.18.0/lib/cartopy/mpl/geoaxes.py#L388

I can't reproduce this locally with MPL 3.3.3 and Cartopy 0.18, the blue background shows up fine and there are no deprecation warnings.

**Comment by marceloandrioni** [comment]
Hi @greglucas, you are completely right. I ran the test in one of my (several) environments that I assumed had v0.18.0 but I see now that it had v0.17.0 all along. I am very sorry for this mix-up and I will try to be more careful next time. In my defense, it was really late at night :(
Sorry again and I will be closing this issue.

**Comment by greglucas** [comment]
No problem! Glad to hear it is fixed for you :)
