### ISSUE TITLE
When is 0.19 slated for release?

### ISSUE THREAD

**Issue by LiamBindle** [SciTools/cartopy#1695]
Hi everyone,

Is there a scheduled release date in the pipeline for 0.19? #1622 is highly desirable for the GEOS-Chem High Performance user community (the model grid is a gnominic cubed-sphere), and we're approaching a new major release, so I thought I'd ping the cartopy community to inquire about 0.19's schedule.

Thanks again for all your terrific work!
Liam

**Comment by dopplershift** [comment]
I don't know that there's a schedule, just when someone has the time to dedicate to merging the last few items and calling it "pencils down". I'd love to say I'll do something over the holidays, but my track record of late leaves me not making any promises of any sort.

**Comment by LiamBindle** [comment]
That's fair, I totally understand that.

Thanks for yours and everyones work!

**Comment by greglucas** [comment]
I think we have a lot of good new additions ready for a release, and some important bug fixes in there too. I will try and go through to put a release notes together in the next week or two. No real reason to keep pushing a release off indefinitely, especially considering we are still in the 0.x release state.

**Comment by dopplershift** [comment]
@greglucas 100% agree.
