### ISSUE TITLE
SciPy dependency

### ISSUE THREAD

**Issue by dopplershift** [SciTools/cartopy#1697]
### Description

Currently we unconditionally import scipy in two places:

https://github.com/SciTools/cartopy/blob/d12c86ca228365c61d5fb8b7121b49201f19fea8/lib/cartopy/img_transform.py#L13-L18

(when no pykdtree) and here:

https://github.com/SciTools/cartopy/blob/d59d275045f4aac42d3665f3532e0ed9cc3cdbf4/lib/cartopy/vector_transform.py#L12-L14

That would contradict where we list scipy as an "optional" dependency. We should either update the docs in [`INSTALL`](https://github.com/SciTools/cartopy/blob/a3ce915cdcd245e99d971ff707d83912f8aa21f1/INSTALL) or handle those imports differently.

**Comment by jackieleng** [comment]
Ran into this issue today. Followed the installation guide and thought I installed all deps. Tried running the `animate_surface.ipynb` notebook, but failed, because I have no pykdtree nor scipy installed

**Comment by greglucas** [comment]
We also list matplotlib as an optional dependency, which seems a bit odd :) So, that should probably be updated as well.
