### ISSUE TITLE
request: geostationary projection- multiply scanning angles with satellite height on the fly

### ISSUE THREAD

**Issue by djuncu** [SciTools/cartopy#1702]
Hello
Currently the geostationary projection requires as input coordinates the satellite scanning angles multiplied with the satellite height. However, the satellite height is a required argument for the projection already, so this multiplication could be done on the fly if only scanning angles are supplied. I am assuming here that this might be a more common use case, although I might not be aware of cases where the current implementation is more convenient for others?

**Comment by dopplershift** [comment]
The choice of projection coordinates is dictated by [PROJ](https://proj.org/operations/projections/geos.html?highlight=geostationary#usage). It would require significant work on CartoPy's side to handle the multiplication. I agree it would be more convenient if the projection coordinates were angular.

**Comment by djuncu** [comment]
OK thanks for the clarification!
