### ISSUE TITLE
Coastlines not appearing on a Mollweide projection

### ISSUE THREAD

**Issue by profxj** [SciTools/cartopy#1704]
### Description

I am generating a cartopy plot with a Mollweide projection and
am using matplotlib's `tricontourf()` to generate the map.  
I am trying to add coastlines with  `ax.coastlines()` but
with no success.  The image plots fine with a color bar.

#### Code to reproduce

Here is the main snippet of code.
`hp_lons`, `hp_lats` and `hp_events` are simple numpy arrays

```
    fig = plt.figure(figsize=(12, 8))
    plt.clf()

    ax = plt.axes(projection=ccrs.Mollweide())

    cm = plt.get_cmap('Greens')

    # Cut down
    img = ax.tricontourf(hp_lons, hp_lats, hp_events, transform=ccrs.Mollweide(),
                         levels=20, cmap=cm, zorder=10)

    # Colorbar
    cb = plt.colorbar(img, orientation='horizontal', pad=0.)
    clbl=r'$\log_{10} \, N$'
    cb.set_label(clbl, fontsize=20.)


    ax.coastlines()#resolution='50m')

    # Layout and save
    plt.savefig(outfile, dpi=300)
    plt.close()
```

#### Traceback 

```

```

<details>
 <summary>Full environment definition</summary>

### Operating system

Ubuntu 18.0

### Cartopy version
0.18.0

python = 3.8

### conda list

```
```

### pip list

```
```

</details>

**Comment by greglucas** [comment]
This is similar to issue: https://github.com/SciTools/cartopy/issues/1345

If you are passing longitudes and latitudes into your plotting function you want to use `transform=ccrs.PlateCarree()`

Then you need to readjust your limits since tricontour isn't implemented within Cartopy yet (PRs welcome!). To get the full global extent and see the coastlines you can use `ax.set_global()`

**Comment by profxj** [comment]
Ok, but what if my grid is not regular?

It is mollweide,  generated with healpix:
https://healpix.sourcieforge.io

Please advise.

Thanks!

**Comment by greglucas** [comment]
Yes, the `tricontourf()` function is meant for ungridded datasets.

On this line
`img = ax.tricontourf(hp_lons, hp_lats, hp_events, transform=ccrs.PlateCarree(),`
the `transform=...` is what coordinate frame the data is originally in. You have lons/lats in your variable names, so I assumed that is what you wanted. If your data is in Molleweide coordinates, then use that.

This line `ax = plt.axes(projection=ccrs.Mollweide())` says what projection you want your data displayed in.

**Comment by profxj** [comment]
Right, that is as I coded it. 

And can I also confirm that I *cannot* plot the coastlines 
if I do so?  Bummer, if true.  
But, as you say, I can 
help develop that if I possible.

**Comment by greglucas** [comment]
No, you *can* plot the coastlines. The autoscaling is what isn't implemented.

Here is an extension of your example with minimal data.
![Figure_1](https://user-images.githubusercontent.com/12417828/103902606-000d2c80-50b8-11eb-88cb-78cfc48765ec.png)
```python
import matplotlib.pyplot as plt
import numpy as np
import cartopy.crs as ccrs

fig = plt.figure(figsize=(12, 8))
plt.clf()

ax = plt.axes(projection=ccrs.Mollweide())

cm = plt.get_cmap('Greens')

hp_lons = np.random.random(100)*360 - 180
hp_lats = np.random.random(100)*90 - 45
hp_events = np.random.random(100)

# Cut down
img = ax.tricontourf(hp_lons, hp_lats, hp_events, transform=ccrs.PlateCarree(),
                     levels=20, cmap=cm, zorder=10)

# Colorbar
cb = plt.colorbar(img, orientation='horizontal', pad=0.)
clbl=r'$\log_{10} \, N$'
cb.set_label(clbl, fontsize=20.)

ax.coastlines()
ax.set_global()

plt.show()

```

**Comment by profxj** [comment]
Ok, I can see the coastlines where there is *no* data.
But since I have data across the globe, when I do the
above I see *no* coastlines.  

Hence, my feeble attempt with `zorder`.  Is there a way
in your example to enforce seeing *all* of the coastlines?

Thanks!

**Comment by greglucas** [comment]
Did you try zorder?

`ax.coastlines(zorder=10)` works for me...

**Comment by profxj** [comment]
I hadn't (I was putting `zorder` in the tricountourf method) but
I have now and no love..

```
    fig = plt.figure(figsize=(12, 8))
    plt.clf()

    ax = plt.axes(projection=ccrs.Mollweide())

    cm = plt.get_cmap('Blues')
    img = ax.tricontourf(hp_lons, hp_lats, hp_events, transform=ccrs.Mollweide(),
                         levels=20, cmap=cm)

    # Colorbar
    cb = plt.colorbar(img, orientation='horizontal', pad=0.)
    clbl=r'$\log_{10} \, N_{\rm '+'{}'.format(lbl)+'}$'
    cb.set_label(clbl, fontsize=20.)

    # Median dSST
    ax.coastlines(zorder=10)

    # Layout and save
    plt.savefig(outfile, dpi=300)
    plt.close()
    print('Wrote {:s}'.format(outfile))
```

![image](https://user-images.githubusercontent.com/3998093/103906833-4b720b80-50b5-11eb-9c51-b3fc4b5c83fb.png)

**Comment by greglucas** [comment]
Why are you still calling it with `Molleweide()` in the transform argument to `tricontourf`? Please use a reproducible example like the one I included.

My guess is that if you put in `ax.set_global()` you'll see the coastlines and this data will be a small subsection in the middle because it is not truly coming from a Molleweide projection.

**Comment by profxj** [comment]
Ah, ok.  My bad.  Now I have land but a crummy looking plot
(compare to my other, without the land):

![fig_std_evals_spatial](https://user-images.githubusercontent.com/3998093/103909147-32b72500-50b8-11eb-9832-e7ceb6e62aa3.png)

I suspect this is because I am mixing projections..
Thanks for your patience on all of this.

**Comment by greglucas** [comment]
I believe this can be closed now. Please raise a new issue with a minimal example if you are still running into issues.
