### ISSUE TITLE
If point is outside the limits of Orthographic projection, the point defaults to the center of the plot

### ISSUE THREAD

**Issue by ahuang11** [SciTools/cartopy#1705]
Is there a way to programmatically clip it instead?
```
import cartopy.crs as ccrs

import matplotlib.pyplot as plt

ax = plt.subplot(projection=ccrs.Orthographic())
ax.coastlines()
ax.scatter(-120, 80, transform=ccrs.PlateCarree())
ax.set_global()
```
![image](https://user-images.githubusercontent.com/15331990/103853206-2361b880-5073-11eb-89a1-63efb1c963f8.png)

**Comment by greglucas** [comment]
That is odd. If you transform the points before calling scatter, then the transformation produces `(nan, nan)` as expected.

`ax.scatter(*ccrs.Orthographic().transform_point(-120, 80, ccrs.PlateCarree()))`

I wonder if the `PathCollection` returned with nan's in the path is getting messed up in the transformations somewhere. I wonder if we should even just transform the x/y points immediately on call to scatter...

**Comment by QiaoFeng0419** [comment]
when i run `ccrs.Orthographic().transform_point(-120, 80, ccrs.PlateCarree())`, it return `(nan, nan)`, I guess the conversion from latitude and longitude to orthographic projection has not yet been realized.

**Comment by ahuang11** [comment]
I think you should do the opposite ccrs.platecarree.transform_points()

**Comment by greglucas** [comment]
You want to go from `(-120, 80)` in the `PlateCarree()` space to `Orthographic()` space, so I think that is right if you get rid of the `transform=` to the scatter function.

https://scitools.org.uk/cartopy/docs/latest/crs/index.html#cartopy.crs.CRS.transform_points

**Comment by greglucas** [comment]
I _think_ something like this would work. Not sure if it has other negative side-effects though.

```diff
diff --git a/lib/cartopy/mpl/geoaxes.py b/lib/cartopy/mpl/geoaxes.py
index 101021d..a848f81 100644
--- a/lib/cartopy/mpl/geoaxes.py
+++ b/lib/cartopy/mpl/geoaxes.py
@@ -1594,7 +1594,7 @@ class GeoAxes(matplotlib.axes.Axes):
         return result
 
     @_add_transform
-    def scatter(self, *args, **kwargs):
+    def scatter(self, x, y, *args, **kwargs):
         """
         Add the "transform" keyword to :func:`~matplotlib.pyplot.scatter'.
 
@@ -1613,7 +1613,12 @@ class GeoAxes(matplotlib.axes.Axes):
                              'geodetic, consider using the cyllindrical form '
                              '(PlateCarree or RotatedPole).')
 
-        result = matplotlib.axes.Axes.scatter(self, *args, **kwargs)
+        xyz = self.projection.transform_points(kwargs.pop('transform'),
+                                               np.asarray(x), np.asarray(y))
+        x = xyz[..., 0]
+        y = xyz[..., 1]
+
+        result = matplotlib.axes.Axes.scatter(self, x, y, *args, **kwargs)
         self.autoscale_view()
         return result
 
```

**Comment by akrherz** [comment]
> Not sure if it has other negative side-effects though.

You'd want to support the `data=` API [matplotlib supports](https://matplotlib.org/api/_as_gen/matplotlib.axes.Axes.scatter.html?highlight=scatter#matplotlib.axes.Axes.scatter) too.

**Comment by greglucas** [comment]
Good point. I think that suggestion would also fail when updating points in an animation with `set_offsets()` because the transform would be lost.

So, the right thing to do here is to fix the transform applied to `PathCollection` for this case.

**Comment by ahuang11** [comment]
Thanks for the quick troubleshooting!
