### ISSUE TITLE
Image is downsampled after reprojection 

### ISSUE THREAD

**Issue by QiaoFeng0419** [SciTools/cartopy#1708]
### Description
I want to show a true color image of `Orthographic` projection with `PlateCarree`, but after the projection conversion, the true color image appears serious distortion. I feel like I've been downsampled.

#### Code to reproduce

```
import cartopy.crs as ccrs
import matplotlib.pyplot as plt
img = plt.imread('img.png')
fig = plt.figure()
proj = ccrs.Orthographic(central_longitude=129.994492,
                             central_latitude=35.540474)
ax = fig.add_subplot(1, 1, 1, projection=ccrs.PlateCarree())
extents = proj.transform_points(ccrs.Geodetic(), np.array([116.844, 123.30207]), np.array([36.720875, 41.65152]))
img_extents = (extents[0][0], extents[1][0], extents[0][1], extents[1][1])
ax.imshow(img, origin='upper', extent=img_extents, transform=proj)
ax.coastlines()
ax.set_extent([116.844, 123.30207, 36.720875, 41.65152])
plt.show()
```

#### Traceback 
True color image is:
![img](https://user-images.githubusercontent.com/15885479/104095072-df1f2400-52cf-11eb-935a-c6f8a721675e.png)

reprojection image is:
![Figure_1](https://user-images.githubusercontent.com/15885479/104095087-f52ce480-52cf-11eb-8047-cf70a35f5b4b.png)

```
```

<details>
 <summary>Full environment definition</summary>

### Operating system
Win10 Pro

### Cartopy version
0.18.0

### conda list
no conda
```
```

### pip list

```
Cartopy                0.18.0
GDAL                   3.1.4
h5netcdf               0.8.1
h5py                   3.1.0
netCDF4                1.5.5.1
pyproj                 3.0.0.post1

```

</details>

**Comment by greglucas** [comment]
There is a `regrid_shape=` keyword argument you can pass to `imshow()`, although it looks to be undocumented in the online documentation...

Looks to be a similar question as this one:
https://github.com/SciTools/cartopy/issues/1415

This suggests we should add some documentation about this option.

**Comment by QiaoFeng0419** [comment]
After `imshow()` added `regrid_shape` parameter, it solved my problem, but it was a little slow to run.
Thanks.

**Comment by greglucas** [comment]
See this comment for a suggestion on speed improvements: https://github.com/SciTools/cartopy/issues/1643#issuecomment-681249995
