### ISSUE TITLE
GSHHS download is causing 404 error

### ISSUE THREAD

**Issue by gauteh** [SciTools/cartopy#1716]
https://www.ngdc.noaa.gov/mgg/shorelines/data/gshhs/oldversions/version2.2.0/GSHHS_shp_2.2.0.zip is not available.

**Comment by greglucas** [comment]
The whole NGDC site is down...
https://www.ngdc.noaa.gov/
Try again tomorrow I guess?

**Comment by akrherz** [comment]
> The whole NGDC site is down...

The Boulder, CO datacenter is offline due to scheduled power work.  They hope to have it back online sometime tomorrow.

**Comment by gauteh** [comment]
Back up
