### ISSUE TITLE
Can't draw outside of boundary of orthographic projection

### ISSUE THREAD

**Issue by ricsonc** [SciTools/cartopy#1719]
### Description

I want to draw lines / points / etc outside the boundary of an orthographic projection. However, things seem to get clipped at the boundary. IIRC, this didn't happen in 0.17, but it happens in 0.18 and also on the current master.

#### Code to reproduce

```
import matplotlib.pyplot as plt
import cartopy.crs as ccrs

ax = plt.axes(projection=ccrs.Orthographic(central_latitude=0.0, central_longitude=0.0))
ax.plot([0,5e6,5e6,0,0], [0,0,5e6,5e6,0], color='red')
plt.xlim(-7e6,7e6)
plt.ylim(-7e6,7e6)
plt.show()
```

I'd like to be able to see the top right corner of the square in this plot without it getting cut off. I realize it's sounds a bit strange, but I'd like to be able to draw things not just on the surface of the globe. [Here's a link](https://github.com/ricsonc/flight-mapper/blob/main/out.gif) to the plot that I've made in 0.17, that I'm hoping to get working in 0.18 as well.

**Comment by greglucas** [comment]
First off, I really like that visualization! It is a very nice example of extending Cartopy's capabilities.

In 0.18 the background patch now has a clip path associated with it. If you tell the artists that they shouldn't be clipped, then I think your lines will show up again.
`ax.plot([0,5e6,5e6,0,0], [0,0,5e6,5e6,0], color='red', clip_on=False)`

**Comment by ricsonc** [comment]
Thanks!

**Comment by altairgomes** [comment]
Hi, I have the same issue.
The `clip_on=False` parameter solved for `ax.plot()`, but it did not solved for `ax.quiver()`.
Here it follows a [map](https://sora.readthedocs.io/_images/map_0.png) that showed the quiver with cartopy 0.17.

**Comment by greglucas** [comment]
Can you open a new issue for the quiver problem and include a minimal reproducible example? In the vector transforms, the vectors get masked if the data is outside of the domain, so that could be the problem. If you want just a single arrow you can use Matplotlib's arrow function and place it in axes coordinates.
