### ISSUE TITLE
annotate

### ISSUE THREAD

**Issue by shaharkadmiel** [SciTools/cartopy#1720]
It is a bit cumbersome and unintuitive to use the `annotate` method with `GeoAxes` (see [this discussion](https://stackoverflow.com/a/25421922/1579211) on stackoverflow).

To make the `ax.annotate` method more like the other `GeoAxes` methods (like plot, scatter, etc.), I suggest this thin wrapper:

```python
class GeoAxes():
    ...

    def annotate(self, *args, **kwargs):
        crs = kwargs.pop('transform', self.projection)
        transform = crs._as_mpl_transform(self)
        kwargs['xycoords'] = transform
        xy = kwargs['xy']
        return self.annotate(*args, **kwargs)
```

This way the `transform` keyword is used to properly construct the `xycoords` transform.

Example:

```python
ax = plt.axes(projection=ccrs.PlateCarree())
ax.stock_img()

ny_lon, ny_lat = -75, 43
delhi_lon, delhi_lat = 77.23, 28.61

ax.plot(
    [ny_lon, delhi_lon], [ny_lat, delhi_lat], '-bo', transform=ccrs.Geodetic(),
)

ax.annotate('New York', xy=(ny_lon, ny_lat), xytext=(-30, +15),
         textcoords='offset points', ha='center', va='center',
         arrowprops=dict(arrowstyle='->'), 
         transform=ccrs.Geodetic())

ax.annotate('Delhi', xy=(delhi_lon, delhi_lat), xytext=(+30, -15),
         textcoords='offset points', ha='center', va='center',
         arrowprops=dict(arrowstyle='->'), 
         transform=ccrs.Geodetic())
```

![image](https://user-images.githubusercontent.com/6872529/106035050-ee75de00-60d3-11eb-8103-e29e01f3f323.png)

**Comment by QuLogic** [comment]
Seems pretty reasonable, though you have to be careful to only do so if the coords are really for data space; would you like to open a PR?

**Comment by shaharkadmiel** [comment]
Thanks @QuLogic , I can make a pull request.
Indeed, I will have to first check that ``xycoords`` is either  'data' or unset (the default is 'data') and only then assign the transform to it.
