### ISSUE TITLE
Examples: tube_stations example gives error when trying to execute with cartopy 0.18.0

### ISSUE THREAD

**Issue by pushkarnimkar** [SciTools/cartopy#1725]
### Description
[tube_stations example](https://scitools.org.uk/cartopy/docs/v0.15/examples/tube_stations.html) throws an error when trying to execute with cartopy 0.18.0

#### Traceback 
```
Traceback (most recent call last):
  File "/home/pushkar/.local/share/virtualenvs/algorithms-Lx3oAzG8/lib/python3.7/site-packages/cartopy/mpl/geoaxes.py", line 825, in set_extent
    x1, y1, x2, y2 = projected.bounds
ValueError: not enough values to unpack (expected 4, got 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/snap/pycharm-community/226/plugins/python-ce/helpers/pydev/pydevd.py", line 1477, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/pycharm-community/226/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/pushkar/intangles/algorithms/tmp/working_map.py", line 69, in <module>
    main()
  File "/home/pushkar/intangles/algorithms/tmp/working_map.py", line 40, in main
    ax.set_extent((-0.14, -0.1, 51.495, 51.515))
  File "/home/pushkar/.local/share/virtualenvs/algorithms-Lx3oAzG8/lib/python3.7/site-packages/cartopy/mpl/geoaxes.py", line 832, in set_extent
    ylim=self.projection.y_limits))
ValueError: Failed to determine the required bounds in projection coordinates. Check that the values provided are within the valid range (x_limits=[-3.141592653589793, 3.141592653589793], y_limits=[-1.4844222297453324, 1.4844222297453324]).
```

### Operating system
Ubuntu 16.04

### Cartopy version
0.18.0

### Pipfile
```
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]
tqdm = "*"
pygount = "*"
pylint = "*"
xlwt = "*"
jupyter = "*"
jupyterlab = "*"
ipywidgets = "*"
ipympl = "*"
widgetsnbextension = "*"
seaborn = "*"
sphinx = "*"
numpydoc = "*"
gmplot = "*"
grpcio = "==1.32.0"

[packages]
pymongo = "*"
tblib = "*"
requests = "*"
urllib3 = "*"
pandas = "==0.25.3"
scipy = "==1.3.1"
pydash = "*"
scikit-learn = "==0.21.1"
matplotlib = "*"
flask = "*"
mpld3 = "*"
memory-profiler = "*"
watchtower = "*"
pika = "==0.12.0"
aio-pika = "==4.8.0"
statsmodels = "*"
async-timeout = "*"
aioredis = "*"
motor = "*"
aiofiles = "*"
geopy = "*"
shapely = "*"
tornado = "==5.0.2"
cmake = "*"
dlib = "*"
face-recognition = "*"
pillow = "*"
opencv-python = "*"
joblib = "==0.13.2"
aiohttp = "*"
supervisor = "==4.2.1"
ipykernel = "*"
xlrd = "*"
tqdm = "*"
rdp = "*"
grpcio-tools = "==1.32.0"
dask = {extras = ["complete"],version = "==2.14.0"}
bokeh = "==1.3.4"
pdocs = "*"
numba = "*"
zerorpc = "*"
psutil = "==5.6.7"
superlance = "*"
seaborn = "*"
msgpack= "==0.6.2"
pyarrow = "==1.0.0"
dnspython = "==2.0.0"
cartopy = "==0.18.0"

[requires]
python_version = "3.7.1"
```

**Comment by iskur** [comment]
Another example that fails with the same ValueError under cartopy version 0.18.0 is [Web tile imagery](https://scitools.org.uk/cartopy/docs/latest/gallery/image_tiles.html). I have not checked more examples. It seems to me that (at least) set_extent with PlateCarree-crs on an axis with mercator-projection is broken.

**Comment by smartlixx** [comment]
I can't reproduce either the problems in my system (MacOS, python 3.7, cartopy 0.18, geos 3.8.0, proj 6.2.1). Maybe you should provide more information about your installation (e.g., the versions of the packages that cartopy was built on).

**Comment by iskur** [comment]
Sorry, it seems to be a problem with my personal emacs setup and not with cartopy! The example runs just fine in a minimal conda environment with current package versions in the shell outside of the almighty editor.
So from my side, this issue could be closed.

**Comment by pushkarnimkar** [comment]
After creating the above issue, I removed that environment and replaced it with a conda environment, the example is working now. As @smartlixx said, it must be an issue with other package versions. 
I'll try to reproduce this in a fresh pipenv environment and let you know by this weekend.

**Comment by iskur** [comment]
After comparing the output of `os.environ` in the shell and emacs, I found out that the `PROJ_LIB` environment variable was not set in emacs. Setting it to `<home>/anaconda/envs/<env>/share/proj` solved it for me.

**Comment by QuLogic** [comment]
Seems like this is a proj+conda+emacs problem.
