### ISSUE TITLE
Ticks in gridliner disappeared between 0.18.0==py38h9b6dd9e_7 and 0.18.0=py39he68b33d_10

### ISSUE THREAD

**Issue by gauteh** [SciTools/cartopy#1731]
Hi,

we enable gridlines for a cartopy plot using `gl = ax.gridlines(ccrs.PlateCarree(), draw_labels=True)`.

For python 3.8.6, matplotlib 3.3.2 and cartopy version 0.18.0==py38h9b6dd9e_7: this works fine:
![result](https://user-images.githubusercontent.com/56827/108071199-bbd15c80-7065-11eb-8aff-073e4122aadc.png)

while for python 3.9, matplotlib 3.3.4, and cartopy version 0.18.0=py39he68b33d_10 they disapear:
![results](https://user-images.githubusercontent.com/56827/108071301-dc99b200-7065-11eb-9e09-6ddb1c15fd68.png)

backend is set to agg using env: MPLBACKEND.

Best regards, Gaute

**Comment by greglucas** [comment]
Are you linking to the same version of GEOS for those installs? How are you installing Cartopy, with pip or conda? If you can attach the lists of other dependencies that may help too.
I think this may be the bug seen when using GEOS 3.9.0... Upgrading to `geos==3.9.1` should fix the issue if that is the problem.

**Comment by gauteh** [comment]
Pristine miniconda3 docker img, using conda update python with conda-forge.
Installing cartopy from conda-forge. Will provide more details later.

tir. 16. feb. 2021, 15:51 skrev Greg Lucas <notifications@github.com>:

**Comment by greglucas** [comment]
I'm pretty sure this is the GEOS issue then because conda-forge isn't getting the newest 3.9.1 for some reason even though it is available there. Here is a link to the recent PR with CI builds I was trying out to verify that: https://github.com/SciTools/cartopy/pull/1724

**Comment by akrherz** [comment]
> conda-forge isn't getting the newest 3.9.1 for some reason even though it is available there

The migration is not done, so there's dependency issues yet. https://conda-forge.org/status/#geos391

**Comment by greglucas** [comment]
I _think_ that this should be updated in the conda installs now. Can you try again @gauteh?

**Comment by gauteh** [comment]
Yes, I think so too. I'll check again.

fre. 26. feb. 2021, 15:45 skrev Greg Lucas <notifications@github.com>:

**Comment by gauteh** [comment]
Yes, this works great now. thanks!
