### ISSUE TITLE
ModuleNotFoundError: No module named 'cartopy.crs'; 'cartopy' is not a package

### ISSUE THREAD

**Issue by leonardojimenez1990** [SciTools/cartopy#1735]
### Description
hi, I use Ubuntu, python3.8 pip, pycharm. I have a problem with Cartopy 0.18.0. ModuleNotFoundError: No module named 'cartopy.crs'; 'cartopy' is not a package

r: ~ $ which python
/ usr / bin / python
r: ~ $ python -c 'import sys; print (sys.prefix) '
/ usr
r: ~ $ python -c 'import cartopy.crs as ccrs'
Traceback (most recent call last):
File "<string>", line 1, in <module>
ImportError: No module named cartopy.crs

### pip list
Package                  Version
------------------------ --------------------
basemap                  1.2.1
bcrypt                   3.1.7
beautifulsoup4           4.8.2
bleach                   3.3.0
blinker                  1.4
blosc                    1.7.0
Bottleneck               1.2.1
Brlapi                   0.7.0
cachetools               4.0.0
Cartopy                  0.18.0

**Comment by greglucas** [comment]
Did you install into your system Python path or a different virtual environment? When you `pip list` there my guess is that is aliased to a different pip than the Python version you're importing from, what does `python -m pip list` produce?

**Comment by leonardojimenez1990** [comment]
r:~$ python3 -m pip list
Package                  Version
------------------------ ----------------------
...
Babel                    2.9.0
backcall                 0.1.0
basemap                  1.2.1
bcrypt                   3.1.7
beautifulsoup4           4.8.2
bleach                   3.3.0
blinker                  1.4
blosc                    1.7.0
Bottleneck               1.2.1
Brlapi                   0.7.0
cachetools               4.0.0
Cartopy                  0.18.1.dev190+g7e077e5
...

**Comment by akrherz** [comment]
It appears you just answered your own question, but to emphasize, you have multiple versions of python installed and perhaps multiple versions of cartopy within those python versions.  What does `python3 -c 'import cartopy.crs as ccrs'` report?

**Comment by leonardojimenez1990** [comment]
Thanks, with python3 I found the cartopy.crs library
