### ISSUE TITLE
Error commands when installing 

### ISSUE THREAD

**Issue by JRoth9125** [SciTools/cartopy#1736]
I receive the error below when attempting to install cartopy. I have Proj 2 install from python.org. Looking for suggestions on how to resolve this issue?

pip install cartopy gives me the below error:

ERROR: Command errored out with exit status 1:
   command: 'c:\users\justin-r\appdata\local\programs\python\python39\python.exe' 'c:\users\justin-r\appdata\local\programs\python\python39\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel 'C:\Users\tech\AppData\Local\Temp\tmptnubofzv'
       cwd: C:\Users\tech\AppData\Local\Temp\pip-install-6foydlgz\cartopy_d50586a575454d4a865c88687a047378
  Complete output (3 lines):
  setup.py:168: UserWarning: Unable to determine GEOS version. Ensure you have 3.3.3 or later installed, or installation may fail.
    warnings.warn(
  Proj 4.9.0 must be installed.

**Comment by greglucas** [comment]
Do you have GEOS installed on your system? The two dependencies that will help you here are `shapely` (GEOS), and `pyproj` (not strictly a dependency, but may help with installing PROJ).
