### ISSUE TITLE
After projection is set, the codes control the linewidth of axes do no work

### ISSUE THREAD

**Issue by 664787022** [SciTools/cartopy#1738]
I want to change the linewidth of axes. But if i add projection to the axes, the codes control the linewidth of axes do not work. I think it's a bug of cartopy.  No error or warning was reported. Does anyone know how to deal with this problem or provide other methods to change the linewidth？Thanks!

import matplotlib.pyplot as plt
import cartopy.crs as ccrs

proj=ccrs.PlateCarree(central_longitude=180)
crs=ccrs.PlateCarree()

fig=plt.figure()
ax=fig.add_subplot(111,projection=proj)

width=2
ax.spines['bottom'].set_linewidth(width)
ax.spines['left'].set_linewidth(width)
ax.spines['right'].set_linewidth(width)
ax.spines['top'].set_linewidth(width)

**Comment by greglucas** [comment]
We create a new `geo` spine, so you will need to reference that one.

`ax.spines['geo'].set_linewidth(width)`

**Comment by 664787022** [comment]
Thank you! I found this keyword in 0.18.0 just now and my cartopy verison is 0.17.0.  I should read the update log first. Thank you for your help！
