### ISSUE TITLE
Missing .prj for NaturalEarth data

### ISSUE THREAD

**Issue by tfardet** [SciTools/cartopy#1744]
### Description

With the current default downloader from ``cartopy``, not all elements from the NaturalEarth zip container are extracted.
Currently, [only shp, dbf, and shx](https://github.com/SciTools/cartopy/blob/8b106fec9511911eb49a7f78b65407895c37bfc3/lib/cartopy/io/shapereader.py#L319) are present.

This means that when loading the file (e.g. in my case with ``geopandas.read_file``) leads to a ``GeoDataFrame`` that has its ``crs`` element set to ``None`` instead of ``"epsg:4326"``.

### Feature request

Unless there is a good reason not to include the .prj file (that has already been downloaded anyways), I'd suggest to include it in the list of extensions [there](https://github.com/SciTools/cartopy/blob/8b106fec9511911eb49a7f78b65407895c37bfc3/lib/cartopy/io/shapereader.py#L319).
Given that it takes virtually no space, I'd also suggest to include the .cpg in case it might also be of use to somebody somewhere.

I can provide a PR if necessary.

**Comment by dopplershift** [comment]
That sounds reasonable—a PR implementing it would be welcome.

**Comment by tfardet** [comment]
See #1745
