### ISSUE TITLE
Are there any osx-arm64 build or noarch build?

### ISSUE THREAD

**Issue by david-tao-as01** [SciTools/cartopy#1749]
### Description

Here's a m1 mbp user asking

**Comment by greglucas** [comment]
We only upload the source distribution to PyPI, no machine-specific builds. See: https://pypi.org/project/Cartopy/0.19.0rc1/#files
Other package managers may provide builds for you though.

**Comment by dopplershift** [comment]
Given the mention of "noarch", I think you mean conda packages? Any questions related to the conda packaging is best asked on the [cartopy conda-forge feedstock](https://github.com/conda-forge/cartopy-feedstock).
