### ISSUE TITLE
Feature request: create a GeoAxes from an existing matplotlib Axes

### ISSUE THREAD

**Issue by rcomer** [SciTools/cartopy#1756]
### Description

I have some code that takes data on a regular latitude/longitude grid and plots it on a northern hemisphere Orthographic projection.  Something like this:

```python
import cartopy.crs as ccrs
import cartopy.feature as cfeature
import iris.quickplot as qplt
import matplotlib.pyplot as plt

MAP_CRS = ccrs.Orthographic(central_latitude=90)
SOURCE_CRS = ccrs.PlateCarree()
EXTENT = [0.005, 360, 57, 90]


def plot_map(cube, **kwargs):
    qplt.contourf(cube, **kwargs)
    ax = plt.gca()
    ax.set_extent(EXTENT, crs=SOURCE_CRS)
    ax.add_feature(cfeature.LAND, zorder=1, facecolor='LightGrey')
    ax.coastlines('50m')


plt.subplot(2, 2, 1, projection=MAP_CRS)
plot_map(some_cube, **contourf_kwargs)
plt.subplot(2, 2, 2, projection=MAP_CRS)
plot_map(some_other_cube, **other_contourf_kwargs)
...etc...
```

Since these maps will all be on the same projection, I'd like to include the `MAP_CRS` within my `plot_map` function somehow, rather than having to specify it in every call to `subplot`.  Under the hood, Iris already has a function that [replaces the current matplotlib axes with a geoaxes](https://github.com/SciTools/iris/blob/e4706ab6855317ab9bf2a90d2494c0daadbefba8/lib/iris/plot.py#L827-L855.)  So I thought about just making that function public (https://github.com/SciTools/iris/issues/4041).  But on further reflection, I think this sort of functionality probably fits better in Cartopy than in Iris.  Perhaps it could be a class method, so users could do something like

```python
geoax = cartopy.mpl.geoaxes.GeoAxes.from_axes(ax, projection=MAP_CRS)
```

If there is agreement in principle, I'd be happy to have a go at implementing this.  As I've never delved into these objects before I may need some help/advice though!

**Comment by dopplershift** [comment]
Well, the problem here is that the Iris function only copies over labels/titles. To do this properly, you'd need to copy over *all* of the state from an Axes--otherwise we're going to get bug reports where the users expect something to happen that's not. 

In my opinion, your `plot_map` function should be taking `ax` as a parameter rather than relying on global state (through `gca()`). If I were solving this, I'd make `ax` optionally work if given a tuple and create the CRS for me:
```python
def plot_map(ax, cube, **kwargs):
    try:
        ax = plt.subplot(*ax, projection=MAP_CRS)
    except TypeError:  # Assume already an Axes
        pass
    qplt.contourf(cube, **kwargs)
    ax.set_extent(EXTENT, crs=SOURCE_CRS)
    ax.add_feature(cfeature.LAND, zorder=1, facecolor='LightGrey')
    ax.coastlines('50m')

ax1 = plt.subplot(2, 2, 1, projection=MAP_CRS)
plot_map(ax1, some_cube, **contourf_kwargs)
# or
plot_map((2,2,2), some_cube, **contourf_kwargs)
```

**Comment by rcomer** [comment]
Thanks @dopplershift for taking the time to look at this.  When you say "_all_ of the state from an Axes" I guess that would include anything that has been added to it since instantiation.  I must admit I had not thought beyond newly created axes, but now I see why this would be problematic!

I have previously implemented this sort of thing by passing the `subplot` numerical args to my function, but I've been wondering how to make it more flexible so it works regardless of the approach for creating the axes (`subplot`, `subplots`, `add_axes`, `subplot2grid`, etc).  Obviously there's nothing to stop me locally saving a version of the Iris function that covers my own use-cases though.

I think I'll file this under "nice ideas that won't work in practice"!
