### ISSUE TITLE
Inaccurate country borders 

### ISSUE THREAD

**Issue by rossmaidment** [SciTools/cartopy#1757]
The country boundaries used in cartopy are inaccurate over Somalia. A border is inserted that seems to recognise Somaliland as a country, when it is not internationally recognised as an independent country. I think the error lies with the Natural Earth shapefiles used by cartopy, but this is something that should be rectified.

**Comment by QuLogic** [comment]
We do not manage the shapefiles. You should report issues with them at their GitHub https://github.com/nvkelso/natural-earth-vector/
