### ISSUE TITLE
Set gridline locators for all four axes of the plot 

### ISSUE THREAD

**Issue by icetianli** [SciTools/cartopy#1758]
### Description

Cartopy sometimes produces maps with mixed latitude and longitude gridline labels on the same side of the plot, like this one mentioned in  https://github.com/SciTools/cartopy/issues/1560:

![image](https://user-images.githubusercontent.com/45267156/106366286-b91afb80-6332-11eb-8058-f61a94142b33.png)

The right axis has an unexpected longitude label 16 E. This looks a bit messy, especially in terms of producing maps of publication quality. 

One solution is the custom function written by @friedrichknuth in https://github.com/SciTools/cartopy/issues/1560, it solves the issue of mixed lat/lon labels by modifying the gridline locators of each axis. However, this would require writing extra function everytime plotting the figure. 

I was wondering if it is possible for cartopy to implement additional gridline locator parameters for all four axes of the plot, such as `x_top_locator`, `x_bottom_locator`, `y_left_locator`,  `y_right_locator`, instead of just `xlocator` and `ylocator` in the current version. This will allow users to specify locators where they would like to label the gridline for any axis.

**Comment by greglucas** [comment]
There is some discussion in #1537 around how to draw the combinations x/y + sides. Feel free to chime in there with your thoughts and ideas.

**Comment by QuLogic** [comment]
Closed by #1537
