### ISSUE TITLE
version 0.19.0?

### ISSUE THREAD

**Issue by rmvanhees** [SciTools/cartopy#1766]
### Description

Yesterday version 0.19.0 of cartopy was released, however, when I update the source tree git claims that the version is now 0.19.0, but installing the software gives me 0.19.0rc2.dev2+g4ca93c1.d20210422.
This is also true when I clone the current source tree

Using python3.9 and Cython 0.29.23, I get complains from Cython that the language_level is not set. My attempts to fix this warning by adding to de directives 'language_level': 3 in the setup.py have no effect.

#### Code to reproduce
Move into the source tree and give the command: 'python3 setup.py install --user'
```

```

#### Traceback 
running build_ext
cythoning lib/cartopy/trace.pyx to lib/cartopy/trace.cpp
/data/richardh/nadc_extern/x86_64/lib/python3.9/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/richardh/git/cartopy/lib/cartopy/trace.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
warning: lib/cartopy/trace.pyx:527:15: local variable 't_min' referenced before assignment
warning: lib/cartopy/trace.pyx:527:29: local variable 't_max' referenced before assignment
warning: lib/cartopy/trace.pyx:529:28: local variable 't_min' referenced before assignment
warning: lib/cartopy/trace.pyx:529:41: local variable 't_max' referenced before assignment
warning: lib/cartopy/trace.pyx:535:15: local variable 't_min' referenced before assignment
warning: lib/cartopy/trace.pyx:537:28: local variable 't_min' referenced before assignment
warning: lib/cartopy/trace.pyx:540:28: local variable 't_max' referenced before assignment
warning: lib/cartopy/trace.pyx:547:15: local variable 't_min' referenced before assignment
warning: lib/cartopy/trace.pyx:548:28: local variable 't_min' referenced before assignment
warning: lib/cartopy/trace.pyx:551:28: local variable 't_max' referenced before assignment
warning: lib/cartopy/trace.pyx:558:24: local variable 't_max' referenced before assignment
cythoning lib/cartopy/_crs.pyx to lib/cartopy/_crs.c
/data/richardh/nadc_extern/x86_64/lib/python3.9/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/richardh/git/cartopy/lib/cartopy/_crs.pxd
  tree = Parsing.p_module(s, pxd, full_module_name)
cythoning lib/cartopy/geodesic/_geodesic.pyx to lib/cartopy/geodesic/_geodesic.c
/data/richardh/nadc_extern/x86_64/lib/python3.9/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/richardh/git/cartopy/lib/cartopy/geodesic/_geodesic.pxd
  tree = Parsing.p_module(s, pxd, full_module_name)
building 'cartopy.trace' extension

```

```

<details>
 <summary>Full environment definition</summary>

### Operating system
Ubuntu 20.10

### Cartopy version
0.19.0rc2.dev2+g4ca93c1.d20210422

### conda list

```
```

### pip list

```
```

</details>

**Comment by greglucas** [comment]
For the first part of your question about claiming to be 0.19.0rc2, I just created #1768 to bring the commits that were in the tagged release branch into master. So, that should show 0.19.1+dev soon.

**Comment by dopplershift** [comment]
With #1768 merged, this should be fixed. Feel free to re-open if that's not the case.
