### ISSUE TITLE
Unable to install version 0.19.0 - lib/cartopy/trace.cpp not found

### ISSUE THREAD

**Issue by stefanmaar** [SciTools/cartopy#1767]
### Description
I have tried to install cartopy version 0.19.0 using pip. It failed, because when building the cartopy.trace extension, the file lib/cartopy/trace.cpp was not found.
The output of the installation process given in _Traceback_ shows my installation attempt using the downloaded source code.

Installing version 0.18.0 works without a problem.

#### Code to reproduce
pip install cartopy

#### Traceback 
pip install -e Cartopy-0.19.0/

Obtaining file:///home/stefan/01_gtd/04_aktuelleProjekte/mertl-research/macro_shake_net/github_mss/Cartopy-0.19.0
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: numpy>=1.13.3 in /home/stefan/python_environments/mss_dataserver/lib/python3.6/site-packages (from Cartopy==0.19.0) (1.17.4)
Requirement already satisfied: shapely>=1.5.6 in /home/stefan/python_environments/mss_dataserver/lib/python3.6/site-packages (from Cartopy==0.19.0) (1.7.1)
Requirement already satisfied: pyshp>=2 in /home/stefan/python_environments/mss_dataserver/lib/python3.6/site-packages (from Cartopy==0.19.0) (2.1.3)
Installing collected packages: Cartopy
  Running setup.py develop for Cartopy
    ERROR: Command errored out with exit status 1:
     command: /home/stefan/python_environments/mss_dataserver/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/stefan/01_gtd/04_aktuelleProjekte/mertl-research/macro_shake_net/github_mss/Cartopy-0.19.0/setup.py'"'"'; __file__='"'"'/home/stefan/01_gtd/04_aktuelleProjekte/mertl-research/macro_shake_net/github_mss/Cartopy-0.19.0/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /home/stefan/01_gtd/04_aktuelleProjekte/mertl-research/macro_shake_net/github_mss/Cartopy-0.19.0/
    Complete output (22 lines):
    running develop
    running egg_info
    writing lib/Cartopy.egg-info/PKG-INFO
    writing dependency_links to lib/Cartopy.egg-info/dependency_links.txt
    writing requirements to lib/Cartopy.egg-info/requires.txt
    writing top-level names to lib/Cartopy.egg-info/top_level.txt
    adding license file 'COPYING' (matched pattern 'COPYING*')
    adding license file 'COPYING.LESSER' (matched pattern 'COPYING*')
    reading manifest file 'lib/Cartopy.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching 'README.rst'
    warning: no files found matching '*.h' under directory 'lib'
    warning: no files found matching '*.c' under directory 'lib'
    warning: no files found matching '*.cpp' under directory 'lib'
    writing manifest file 'lib/Cartopy.egg-info/SOURCES.txt'
    running build_ext
    building 'cartopy.trace' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include -I./lib/cartopy -I/tmp/pip-build-env-8k461e_i/overlay/lib/python3.6/site-packages/numpy/core/include -I/usr/include -I/usr/include/python3.6m -I/home/stefan/python_environments/mss_dataserver/include/python3.6m -c lib/cartopy/trace.cpp -o build/temp.linux-x86_64-3.6/lib/cartopy/trace.o
    x86_64-linux-gnu-gcc: error: lib/cartopy/trace.cpp: Datei oder Verzeichnis nicht gefunden
    x86_64-linux-gnu-gcc: fatal error: no input files
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/stefan/python_environments/mss_dataserver/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/stefan/01_gtd/04_aktuelleProjekte/mertl-research/macro_shake_net/github_mss/Cartopy-0.19.0/setup.py'"'"'; __file__='"'"'/home/stefan/01_gtd/04_aktuelleProjekte/mertl-research/macro_shake_net/github_mss/Cartopy-0.19.0/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
WARNING: You are using pip version 19.3.1; however, version 21.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

### Operating system
Linux Mint 19 Tara 64-bit

**Comment by inigodelportillo** [comment]
I am finding the same issue.

**Comment by greglucas** [comment]
Hm... This does seem to be broken on sdist installs. I think we need to go down this path:
https://github.com/SciTools/cartopy/blob/4ca93c1eefa86cb85177467407852b4636bb3e70/setup.py#L48-L54

Can you try installing with this command: `FORCE_CYTHON=1 pip install cartopy==0.19.0`?

**Comment by mcquay239** [comment]
> Hm... This does seem to be broken on sdist installs. I think we need to go down this path:
> 
> https://github.com/SciTools/cartopy/blob/4ca93c1eefa86cb85177467407852b4636bb3e70/setup.py#L48-L54
> 
> Can you try installing with this command: `FORCE_CYTHON=1 pip install cartopy==0.19.0`?

This flag fixes the problem on Arch linux

**Comment by felipem775** [comment]
This flag fixes the problem on Linux Mint 20

**Comment by inigodelportillo** [comment]
The flag also fixes the problem on Ubuntu 20.4

**Comment by stefanmaar** [comment]
Using `FORCE_CYTHON=1 pip install cartopy==0.19.0` worked for me as well (Linux Mint 19 Tara 64-bit).

**Comment by paulathomas** [comment]
Can you try installing with this command: FORCE_CYTHON=1 pip install cartopy==0.19.0

Works on Ubuntu 20.10 under WSL too.

**Comment by greglucas** [comment]
Thanks for testing that out everyone. This should be fixed soon (#1769) and a new release tagged that doesn't require that workaround.

**Comment by greglucas** [comment]
The new release is out on PyPI now.
`pip install cartopy` or `pip install cartopy==v0.19.0.post1` should work to get the latest version and avoid the installation issue above.
