### ISSUE TITLE
Installation Failure

### ISSUE THREAD

**Issue by K4Werri** [SciTools/cartopy#1771]
### Description

I'm trying to install cartopy. The installation process is attempting to compile some code and terminates with the following error:

x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DACCEPT_USE_OF_DEPRECATED_PROJ_API_H=1 -I/usr/include -I./lib/cartopy -I/tmp/pip-build-env-bg6ptomt/overlay/lib/python3.8/site-packages/numpy/core/include -I/usr/include -I/home/kevin/Python38/venv/include -I/usr/include/python3.8 -c lib/cartopy/trace.cpp -o build/temp.linux-x86_64-3.8/lib/cartopy/trace.o
  lib/cartopy/trace.cpp:6:10: fatal error: Python.h: No such file or directory
      6 | #include "Python.h"
        |          ^~~~~~~~~~
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for Cartopy
ERROR: Could not build wheels for Cartopy which use PEP 517 and cannot be installed directly

This is an extract from out2.txt appended below.

My reference sources are https://pypi.org/project/Cartopy/ and https://scitools.org.uk/cartopy/docs/v0.13/installing.html# for the dependencies.

The GEOS and PROJ.4 dependencies were installed using the package managers as per the associated install instructions on pages referenced on https://scitools.org.uk/cartopy/docs/v0.13/installing.html#, that is

sudo apt-get install proj-bin
sudo apt-get install libproj-dev
sudo apt-get install libgeos*

The remaining dependencies were installed using pip.

Any advice welcome.

Thanks in advance.

Kevin.

#### Code to reproduce

pip install cartopy

#### Traceback 

See attached files out, out2
[out.txt](https://github.com/SciTools/cartopy/files/6374846/out.txt)
[out2.txt](https://github.com/SciTools/cartopy/files/6374847/out2.txt)

<details>
<summary>Full environment definition</summary>

Python 3.8 (using virtual environment), pip for package installation

### Operating system

Xubuntu 20.04 LTS

### Cartopy version

Attempting to install via pip - uses Cartopy-0.19.0.post1.tar.gz (see file out.txt)

### pip list

See attached file called 
[installed.txt](https://github.com/SciTools/cartopy/files/6374841/installed.txt)

```
```

</details>

**Comment by K4Werri** [comment]
I have since solved this I think. Needed to install python3-dev, that is ...

sudo apt-get install python3-dev

... which leads to an error free cartopy install.

Assuming that it all works when I try to use it anger, this issue can be closed from my perspective.

Kevin.

**Comment by dopplershift** [comment]
I'll go ahead and close out, but feel free to re-open if you encounter further problems.
