### ISSUE TITLE
importing cartopy.crs in Binder fails

### ISSUE THREAD

**Issue by vrx-** [SciTools/cartopy#1778]
I'm trying to load my notebook in binder and I seem to have issues with importing cartopy.crs. I guess this is somehow similar to #1740 but in binder.
I'm using a minimal environment.yml to test this

```
name: test-environment
  -python=3.7
channels:
  - conda-forge
dependencies:
  - numpy=1.20.2
  - matplotlib=3.4.1
  - matplotlib-base=3.4.1
  - pandas=1.2.3
  - cartopy=0.17.0
  - dask=2021.4.0
  - pillow=8.1.2
```

~                 

And this is the error I'm getting:
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-4-57acb5775a36> in <module>
      1 from matplotlib import pyplot as plt
----> 2 import cartopy.crs as ccrs
      3 import cartopy.io.img_tiles as cimgt
      4 # from cartopy.mpl.gridliner import LONGITUDE_FORMATTER, LATITUDE_FORMATTER
      5 # from cmocean import cm as ccmo

/srv/conda/envs/notebook/site-packages/cartopy/__init__.py in <module>
    105 # Commonly used sub-modules. Imported here to provide end-user
    106 # convenience.
--> 107 import cartopy.crs
    108 import cartopy.feature  # noqa: F401  (flake8 = unused import)

/srv/conda/envs/notebook/site-packages/cartopy/crs.py in <module>
     34 import six
     35 
---> 36 from cartopy._crs import CRS, Geodetic, Globe, PROJ4_VERSION
     37 from cartopy._crs import Geocentric  # noqa: F401 (flake8 = unused import)
     38 import cartopy.trace

ModuleNotFoundError: No module named 'cartopy._crs'
```

Is there some specific hidden requirement? I had to add specific versions of pillow because before that I was getting `ImportError: cannot import name _imaging`.

**Comment by dopplershift** [comment]
Doubtful that the order actually changed anything since Conda will install them in the order that resolves the dependencies. Better odds that whatever was causing the problem was fixed by getting an updated version of...something.

**Comment by vrx-** [comment]
It's binder. I did not manually update anything and used the same lines in the yml file. So I do not know what is the answer.

**Comment by dopplershift** [comment]
Oh, I meant that changing the file -> Binder rebuilt environment -> Binder pulled down some new version. Either way, what matters is that it works for you now.
