### ISSUE TITLE
Building fails due to "proj_api.h"

### ISSUE THREAD

**Issue by Finnbm** [SciTools/cartopy#1779]
### Description
I've used cartopy historically, but when I tried installing it in another virtual environment I can't build it with the error: ```fatal error: proj_api.h: No such file or directory```. I tried the solutions in several other similar issues, such as inhttps://stackoverflow.com/questions/40719116/making-proj-api-h-available-for-pip-install-cartopy, but I'm a bit stuck. 

#### Code to reproduce

```
pipenv install cartopy
```

#### Traceback 

```
  copying lib/cartopy/io/srtm.npz -> build/lib.linux-x86_64-3.9/cartopy/io
  warning: build_py: byte-compiling is disabled, skipping.

  running build_ext
  building 'cartopy.trace' extension
  creating build/temp.linux-x86_64-3.9
  creating build/temp.linux-x86_64-3.9/lib
  creating build/temp.linux-x86_64-3.9/lib/cartopy
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fno-semantic-interposition -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fPIC -DACCEPT_USE_OF_DEPRECATED_PROJ_API_H=1 -I/usr/include -I./lib/cartopy -I/tmp/pip-build-env-elbn5ja0/overlay/lib/python3.9/site-packages/numpy/core/include -I/usr/include -I/home/user/.local/share/virtualenvs/wind-gps-data-helpers-STW38_pP/include -I/usr/include/python3.9 -c lib/cartopy/trace.cpp -o build/temp.linux-x86_64-3.9/lib/cartopy/trace.o
  lib/cartopy/trace.cpp:634:10: fatal error: proj_api.h: No such file or directory
    634 | #include "proj_api.h"
        |          ^~~~~~~~~~~~
  compilation terminated.
  error: command '/usr/bin/gcc' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for cartopy
ERROR: Could not build wheels for cartopy which use PEP 517 and cannot be installed directly
```

Thanks for the help!

<details>
Pipenv virtual environment,

Installed (potentially relevant) packages:

```
local/proj 8.0.0-3
    Cartographic Projections library
local/python-pyproj 3.0.1-1
    Python interfaces to PROJ.4 library
```

### Operating system

Arch Linux, hardened kernel

</details>

**Comment by Finnbm** [comment]
Update: I forgot to check dependency versions and the ```proj``` package deprecated the ```proj_api.h``` file. Make sure you have a version less than 7.x installed and it should work.

**Comment by Balinus** [comment]
I'm using proj version 6.3 and I get the same error. I was able to install cartopy previously in my other project, but it fails now. Very strange, I can't pinpoint the problem.

**Comment by AlFontal** [comment]
Just wondering @Balinus, did you ever manage to solve this?

I am on Ubuntu 20.04 LTS with proj version 6.3 too, and find myself unable to install `cartopy` (even when pinning to the 0.19.0.post1 version)
