### ISSUE TITLE
Google Colab Crashes for an unknown reason when I trying to use cartopy.

### ISSUE THREAD

**Issue by tasanyphy01773** [SciTools/cartopy#1788]
### Description

Google Colab Crashes for an unknown reason when I trying to use cartopy. I've checked multiple files but the same problem.

#### Code to reproduce

```#make the figure larger 
fig = plt.figure(figsize=(11, 8.5))
 
# Set the axes using theb specified map projection
ax = plt.axes(projection=ccrs.PlateCarree())
 
ax.contourf(ds_mean['pr'], transform = ccrs.PlateCarree())
ax.coastlines()

```

#### Traceback 

![image](https://user-images.githubusercontent.com/68806666/118125503-e3dc1c00-b418-11eb-8bae-33868d9011e0.png)

<details>
 <summary>Full environment definition</summary>

### Operating system
OS: Linux

### Cartopy version
Requirement already satisfied: cartopy in /usr/local/lib/python3.7/dist-packages (0.19.0.post1)
Requirement already satisfied: pyshp>=2 in /usr/local/lib/python3.7/dist-packages (from cartopy) (2.1.3)
Requirement already satisfied: numpy>=1.13.3 in /usr/local/lib/python3.7/dist-packages (from cartopy) (1.19.5)
Requirement already satisfied: shapely>=1.5.6 in /usr/local/lib/python3.7/dist-packages (from cartopy) (1.7.1)

### conda list

```
```

### pip list

```
```

</details>

**Comment by greglucas** [comment]
Are you sure it is Cartopy producing your problem and not your dataset? We don't know what `ds_mean['pr']` has in it, can you reproduce and send a real traceback with `np.ones((5, 5))`?

**Comment by dopplershift** [comment]
The only other thing I can think of would be a problem with how you've installed Cartopy. In the past, I've needed this for Collab:
```python
!apt-get -qq install libproj-dev libgeos-dev
!pip install shapely --no-binary shapely cartopy
```

But I agree with @greglucas, we really need to see the full traceback.

**Comment by tasanyphy01773** [comment]
#solved 
Thanks a lot for replying. I've installed cartopy just by using `pip install cartopy` that actually created problem. Then I tried,
`!apt-get install libproj-dev proj-data proj-bin
!apt-get install libgeos-dev
!pip install cython
!pip install cartopy`

then this 
`!apt-get -qq install python-cartopy python3-cartopy
!pip uninstall -y shapely    # cartopy and shapely aren't friends (early 2020)
!pip install shapely --no-binary shapely`
after that google colab didn't crashed!

**Comment by QuLogic** [comment]
OK, closing then. This is a long-standing issue mentioned elsewhere.
