### ISSUE TITLE
Make `FeatureArtist` a `ScalarMappable`

### ISSUE THREAD

**Issue by maxnoe** [SciTools/cartopy#1789]
To plot data into features, e.g. color each country according to data, it would be very helpful if `FeatureArtist` would implement the `ScalarMappable` interface: https://matplotlib.org/stable/api/cm_api.html#matplotlib.cm.ScalarMappable 

So having `set_array`, `set_clim`, `set_cmap` etc, so one can directly add the data and a colormap.

As a current workaround, one has to construct a colormap, norm and set the facecolors manually like this:

```
norm = Normalize(vmin=data.min(), vmax=data.max())
cmap = plt.get_cmap('inferno')
sm = ScalarMappable(cmap=cmap, norm=norm)

ax.add_feature(
    feature,
    facecolor=[cmap(norm(v)) for v in data],
)
fig.colorbar(sm, ax=ax)
```

when `FeatureArtist` would be a `ScalarMappable`, this should become a lot easiery, e.g. this should work:

```
artist = ax.add_feature(feature,  array=data,  cmap='inferno')
fig.colorbar(artist, ax=ax)
```

**Comment by greglucas** [comment]
This does seem like it would be a nice extension. I wonder if there would be any gotchas in mapping to different types of geometries (LineString vs Polygons for example). PRs definitely welcome to see what this would look like!
