### ISSUE TITLE
Cartopy with proj version 8

### ISSUE THREAD

**Issue by mcuntz** [SciTools/cartopy#1798]
### Description

Homebrew on macOS updated itself. The default proj version is now 8 (8.0.1 currently). There is no `proj_api.h` anymore but only `proj.h` in the include path. Cartopy uses `proj_api.h` in `lib/cartopy/_proj4.pxd`.

How can I tell the install process to use proj@7 from homebrew? Or how can I tell pip to use proj@7 instead of simply proj, which is proj@8?

`pkg-config --modversion proj` gives 8.0.1.
`PKG_CONFIG_PATH=/usr/local/opt/proj@7/lib/pkgconfig/ pkg-config --modversion proj` gives 7.2.1. However, doing `PKG_CONFIG_PATH=/usr/local/opt/proj@7/lib/pkgconfig/ python -m pip install -ve .` still uses proj 8.

<details>
 <summary>Full environment definition</summary>

### Operating system
macOS 10.15.7
Python 3.8.9

### Cartopy version
latest master

### pip list
```
alabaster==0.7.12
appnope==0.1.2
argon2-cffi==20.1.0
async-generator==1.10
attrs==21.2.0
Babel==2.9.1
backcall==0.2.0
basemap==1.2.2+dev
beautifulsoup4==4.9.3
bleach==3.3.0
Bottleneck==1.3.2
bs4==0.0.1
-e git+git@github.com:SciTools/cartopy.git@de87bee210e3f5edf7626a66de0d19e40970176a#egg=Cartopy
certifi==2021.5.30
cffi==1.14.5
cftime==1.5.0
chardet==4.0.0
coverage==5.5
cycler==0.10.0
Cython==0.29.23
decorator==5.0.9
defusedxml==0.7.1
docutils==0.16
entrypoints==0.3
f90nml==1.3.1
flake8==3.9.2
GDAL==3.3.0
idna==2.10
imagesize==1.2.0
iniconfig==1.1.1
ipykernel==5.5.5
ipython==7.24.1
ipython-genutils==0.2.0
ipywidgets==7.6.3
jedi==0.18.0
Jinja2==3.0.1
joblib==1.0.1
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==6.1.12
jupyter-console==6.4.0
jupyter-core==4.7.1
jupyterlab-pygments==0.1.2
jupyterlab-widgets==1.0.0
kiwisolver==1.3.1
MarkupSafe==2.0.1
matplotlib==3.4.2
matplotlib-inline==0.1.2
mccabe==0.6.1
mistune==0.8.4
nbclient==0.5.3
nbconvert==6.0.7
nbformat==5.1.3
nest-asyncio==1.5.1
netCDF4==1.5.6
notebook==6.4.0
numexpr==2.7.3
numpy==1.20.3
numpydoc==1.1.0
packaging==20.9
pandas==1.2.4
pandocfilters==1.4.3
parso==0.8.2
patsy==0.5.1
pexpect==4.8.0
pickleshare==0.7.5
Pillow==8.2.0
pluggy==0.13.1
prometheus-client==0.11.0
prompt-toolkit==3.0.18
ptyprocess==0.7.0
py==1.10.0
pycodestyle==2.7.0
pycparser==2.20
pyflakes==2.3.1
Pygments==2.9.0
pykdtree==1.3.4
pyparsing==2.4.7
pyproj==3.1.0
pyrsistent==0.17.3
pyshp==2.1.3
pytest==6.2.4
pytest-cov==2.12.1
python-dateutil==2.8.1
pytz==2021.1
pyzmq==22.1.0
qtconsole==5.1.0
QtPy==1.9.0
requests==2.25.1
schwimmbad==0.3.2
scikit-learn==0.24.2
scipy==1.6.3
Send2Trash==1.5.0
Shapely==1.7.1
six==1.16.0
snowballstemmer==2.1.0
soupsieve==2.2.1
Sphinx==4.0.2
sphinx-rtd-theme==0.5.2
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==2.0.0
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.5
statsmodels==0.12.2
terminado==0.10.0
testpath==0.5.0
threadpoolctl==2.1.0
toml==0.10.2
tornado==6.1
tqdm==4.61.0
traitlets==5.0.5
urllib3==1.26.5
wcwidth==0.2.5
webencodings==0.5.1
widgetsnbextension==3.5.1
wxPython==4.1.1
xarray==0.18.2
xlrd==2.0.1
```

</details>

**Comment by greglucas** [comment]
I don't see anything obviously wrong with what you're doing at first glance. Do you have a conda environment somewhere with proj8 as well? It may be grabbing proj from the conda check before ever reaching the pkg-config check in the else below this:
https://github.com/SciTools/cartopy/blob/de87bee210e3f5edf7626a66de0d19e40970176a/setup.py#L187-L188

**Comment by mcuntz** [comment]
The shared libraries were not rebuild with the `python -m pip install -ve .` command. I had to remove the shared libraries first:
`
pip uninstall cartopy -y
 rm lib/cartopy/*.so lib/cartopy/*/*.so
 PKG_CONFIG_PATH=/usr/local/opt/proj@7/lib/pkgconfig/ python -m pip install -ve .
`
Then it worked:
`
cartopy> otool -L lib/cartopy/_crs.cpython-38-darwin.so
lib/cartopy/_crs.cpython-38-darwin.so:
	/usr/local/opt/proj@7/lib/libproj.19.dylib (compatibility version 22.0.0, current version 22.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
`
