### ISSUE TITLE
Longitude labels in LambertConformal at wrong locations

### ISSUE THREAD

**Issue by MiriamSterl** [SciTools/cartopy#1800]
### Description

I want to plot some data in a LambertConformal projection and add labels to the axes. See the example code below. However, now the x-labels show up twice, and both times in the middle of the plot, instead of at its bottom. When instead I set `gl.xlabels_bottom = False` and `gl.xlabels_top = True`, no x-labels are plotted at all. With the y-labels, I do not get this problem; they are just nicely plotted either along the left or right boundary of the plot.
How can I get the x-labels at the right location (at the bottom of the figure)?

![image](https://user-images.githubusercontent.com/42772450/120817541-14176600-c552-11eb-8920-3bad4fc66fb7.png)

#### Code to reproduce

```
import numpy as np
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
 
bounds_lon = [-45,-25]
bounds_lat = [55,65]
lon = np.arange(bounds_lon[0],bounds_lon[1]+0.1,0.1)
lat = np.arange(bounds_lat[0],bounds_lat[1]+0.1,0.1)
Lon, Lat = np.meshgrid(lon,lat)
data = np.ones(np.shape(Lon))

data_crs = ccrs.PlateCarree()
projection = ccrs.LambertConformal(central_longitude=np.mean(bounds_lon),central_latitude=np.mean(bounds_lat),cutoff=bounds_lat[0])

plt.figure(figsize=(4,4))
ax = plt.axes(projection=projection)
ax.coastlines()
ax.contourf(Lon, Lat, data, transform=data_crs)

gl = ax.gridlines(crs=ccrs.PlateCarree(), linewidth=2, color='gray', alpha=0.5, linestyle='--')
gl.xlabels_bottom = True
```

#### Traceback 

```

```

<details>
 <summary>Full environment definition</summary>

### Cartopy version
0.18.0

### conda list

```
```

### pip list

```
```

</details>

**Comment by pgf** [comment]
You just need to add the `x_inline=False` as a parameter to the [`gridlines`](https://scitools.org.uk/cartopy/docs/latest/matplotlib/geoaxes.html#cartopy.mpl.geoaxes.GeoAxes.gridlines) call or as an attribute to the returned [`gridliner`](https://scitools.org.uk/cartopy/docs/latest/matplotlib/gridliner.html#cartopy.mpl.gridliner.Gridliner) object, i.e. `gl.x_inline=False`.
