### ISSUE TITLE
Proj4 version 0.0.0 is installed, but cartopy requires at least version 4.8.0

### ISSUE THREAD

**Issue by T0T4R4** [SciTools/cartopy#1802]
### Description

Cartopy references Proj4 v4.8+ but this  dependency seems to be broken (or has changed).

#### Code to reproduce

```
pip install cartopy
```

#### Traceback 

```
Collecting cartopy
  Using cached Cartopy-0.19.0.post1.tar.gz (12.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\xxx\Documents\_Dev\spotOnSphere\venv\Scripts\python.exe' 'C:\Users\xxx\Documents\_Dev\spotOnSphere\venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' 
get_requires_for_build_wheel 'C:\Users\clert\AppData\Local\Temp\tmpmvxy2j86'
       cwd: C:\Users\xxx\AppData\Local\Temp\pip-install-1mm3d5wz\cartopy_d77d889b8758424f8a81267a0a53c0b7
  Complete output (5 lines):
  setup.py:117: UserWarning: Unable to determine GEOS version. Ensure you have 3.3.3 or later installed, or installation may fail.
    warnings.warn(
  setup.py:166: UserWarning: Unable to determine Proj version. Ensure you have 4.9.0 or later installed, or installation may fail.
    warnings.warn(
  Proj version 0.0.0 is installed, but cartopy requires at least version 4.9.0.
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/ed/ca/524ce33692df3faeaa56852fb6a33b0b410be94cc288417565b96fef3f64/Cartopy-0.19.0.post1.tar.gz#sha256=4b8b4773a98ed7009fe17d9b6ec87ac3ac62b7d14634d7768c190eadc647d576 
(from https://pypi.org/simple/cartopy/) (requires-python:>=3.5). 
Command errored out with exit status 1: 'C:\Users\xxx\Documents\_Dev\spotOnSphere\venv\Scripts\python.exe' 'C:\Users\xxx\Documents\_Dev\spotOnSphere\venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' 
get_requires_for_build_wheel 'C:\Users\xxx\AppData\Local\Temp\tmpmvxy2j86' Check the logs for full command output.

```

<details>
 <summary>Full environment definition</summary>

### Operating system
Windows 10
Python 3.9.4 64bit

### Cartopy version
Latest as available via pip

### conda list

```
Thankfully i am NOT using conda
```

### pip list

```
```

</details>

**Comment by dopplershift** [comment]
CartoPy 0.13 is pretty old. Can you try updating to the latest release?

**Comment by T0T4R4** [comment]
But that is what is retrieved when you pip install. Could you publish a more recent version instead ?

**Comment by mbelotti99** [comment]
Hi!

I had the same issue. I'm on a Mojave MacOS.

I thought it could be something wrong with my proj installation, so I tried to install it in several different ways (through Homebrew, Macports and manual compilation). 

It seems like Cartopy was looking for a file called proj_api.h which no longer exists in the current version of proj. This file was not created in any of the installation methods I tried, and it is not in the current master branch of the proj project. 

Also, @T0T4R4 the proj package you are looking for is not the one in pip. Check out [this link](https://proj.org/install.html#install) for installation instructions.

One more observation: I was able to install Cartopy successfully on Ubuntu 20.04 Focal Fossa yesterday.

**Comment by dopplershift** [comment]
CartoPy does not currently build or work with PROJ >= 8--the older versions have the `proj_api.h`. It'd probably be good to double check what version you have install and roll it back as necessary.

**Comment by T0T4R4** [comment]
So could you update the cartoon requirements so that they specifically quote the right version of proj ?
Ideally we don't want to have to compile the dependencies specifically as it makes the installation of cartopy more complicated.

**Comment by dopplershift** [comment]
@T0T4R4 Are you referring to the web documentation or somewhere else? Also, I'm not sure I see how that relates to compiling the dependencies.

**Comment by T0T4R4** [comment]
What i am saying is that it should be enough to run a pip install , as this would install the requirements. However it's not as we have to do extra step to compile a very specific version of one of cartopy's dependancies (Proj) and that's a pain.

**Comment by QuLogic** [comment]
Proj is not a Python package; we cannot set requirements in `pip` because it doesn't exist on PyPI.

**Comment by dopplershift** [comment]
To elaborate further, we'd really, really, really love for users to be able to "just" `pip install proj`. A full 20% of our support is probably related to either PROJ or GEOS (both non-Python libraries) that have to be managed outside `pip` (not to mention this could solve Shapely conflict issues). Unfortunately, there's no standard for packaging non-Python software for `pip`. That's why we normally recommend using Conda as the "easy" path to getting everything installed.
