### ISSUE TITLE
how to install Cartopy in MacOS ?

### ISSUE THREAD

**Issue by bjkindia** [SciTools/cartopy#1806]
I have been trying to install Cartopy in macOS but below error coming 

```
lib/cartopy/trace.cpp:634:10: fatal error: 'proj_api.h' file not found
  #include "proj_api.h"
           ^~~~~~~~~~~~``
```
I have installed 
**Proj version 8.**

and I unserstand proj version 8 removed proj_api.h' file 

I don't how can proceed with this

**Comment by josephgruber** [comment]
Same issue.

**Comment by dopplershift** [comment]
That depends on how you installed PROJ. If you used Homebrew, try `brew install proj@7`. Another option is to install CartoPy using Conda and avoid this problem altogether.
