### ISSUE TITLE
Central_latitude dont work with negative values 

### ISSUE THREAD

**Issue by rrodrigojrr** [SciTools/cartopy#1822]
Hello,

Whenever I attempt to generate an Orthographic projection with my data for latitudes below +8.84, I get only a blank square and the colorbar.
```
ax = plt.axes(projection=ccrs.Orthographic(central_longitude=0, central_latitude=-90))
```

For the PlateCarrée projection and for the Orthographic projection with latitudes >= +8.84, it works just fine, though.

```
ax = plt.axes(projection=ccrs.Orthographic(central_longitude=0, central_latitude=8.84))
```

Does anyone know how to make it work for lower and negative latitudes?

**Comment by greglucas** [comment]
I can't reproduce this. This works for me:
```python
import matplotlib.pyplot as plt
import cartopy.crs as ccrs

ax = plt.axes(projection=ccrs.Orthographic(central_longitude=0, central_latitude=-90))
ax.coastlines()

plt.show()
```

My guess is it has to do with your data specifically covering the entire plotting region. Can you create a minimal reproducible example and include it here?

**Comment by jsillin** [comment]
I'm having a somewhat similar issue with just a solid-color square appearing when trying to plot in a non-PlateCarree projection.

For me, setting the projection with a negative longitude works fine for the basemap:
```
fig, ax = plt.subplots(1, 1, figsize=(15, 15), subplot_kw={'projection': ccrs.NearsidePerspective(central_longitude=-75,central_latitude=40),'transform':ccrs.PlateCarree()})
ax.add_feature(cfeature.BORDERS,edgecolor='dimgray')
ax.add_feature(cfeature.COASTLINE,edgecolor='dimgray')
ax.add_feature(cfeature.STATES,edgecolor='dimgray')
```
![download (65)](https://user-images.githubusercontent.com/40693187/128536628-915e67a4-9b2a-43fc-8fde-6db139d96d33.png)

but when I go to add my data, I get a blank square:
```
fig, ax = plt.subplots(1, 1, figsize=(15, 15), subplot_kw={'projection': ccrs.NearsidePerspective(central_longitude=-75,central_latitude=40),'transform':ccrs.PlateCarree()})
ax.add_feature(cfeature.BORDERS,edgecolor='dimgray')
ax.add_feature(cfeature.COASTLINE,edgecolor='dimgray')
ax.add_feature(cfeature.STATES,edgecolor='dimgray')

ax.contourf(t8.longitude,t8.latitude,t8,transform=ccrs.PlateCarree())
```

![download (66)](https://user-images.githubusercontent.com/40693187/128536760-8f4921d1-2aac-4fc9-9c88-c83e155bc201.png)

My data are global temperatures defined with lat and lon coordinates: 
![Screenshot_71](https://user-images.githubusercontent.com/40693187/128537035-3bcc3ac8-8f00-4ea1-adc4-4408d1ffe420.png)

There should be data for all points covered here. Unless the pole is causing a problem and there's some trick to working around that? There is data for lat=90.0.

If you want to reproduce using the exact dataset, this netcdf contains the data I used https://storage.googleapis.com/nwp-plots/cartopy_projection_issue_data.nc

**Comment by rcomer** [comment]
I cannot reproduce the example from https://github.com/SciTools/cartopy/issues/1822#issuecomment-894352025 with Cartopy 0.22, so I guess something happened that fixed it.
