### ISSUE TITLE
Backport NaturalEarth url change in release 0.18 and 0.19 ?

### ISSUE THREAD

**Issue by thebaptiste** [SciTools/cartopy#1834]
It should be great, if possible, to backport the change of NaturalEarth url (done in this [commit](https://github.com/SciTools/cartopy/commit/af814c31829002acd7c1c49ba52cee530c6ac19a) ) in at least releases 0.18 (==> 0.18.1) and 0.19 (==> 0.19.1), and of course to release a new version with this change.

**Comment by xylar** [comment]
The conda-forge version of 0.19.0 has just been patched with this fix, https://github.com/conda-forge/cartopy-feedstock/pull/116, and should be available soon.

**Comment by akrherz** [comment]
> And what about the pypi release ?

See #1849 for current discussion
