### ISSUE TITLE
Unable to install cartopy 0.19.0 using conda install

### ISSUE THREAD

**Issue by harshmistry96** [SciTools/cartopy#1846]
I am trying to install the latest version of cartopy(0.19.0) using following command
`conda install -c conda-forge cartopy`

but it installs cartopy(0.18.0). I have attached the screenshot for reference.

OS; Windows 10 (64-bit)
![image](https://user-images.githubusercontent.com/48412770/132578226-d7664731-1f9c-4a4c-b9b3-b352b95005cf.png)

Also, tried using `pip install cartopy==0.19.0.post1`

but i get following error:
![image](https://user-images.githubusercontent.com/48412770/132578458-55664b8b-ece4-459b-a828-59c6eb8b7c42.png)

**Comment by dopplershift** [comment]
For some reason it's still picking from defaults, which is confusing. What does this do:
```
conda install -c conda-forge cartopy=0.19.0.post1
```

**Comment by harshmistry96** [comment]
Hi,

Can this issue be resolved?

**Comment by rcomer** [comment]
@harshmistry96 did you try the suggestion from https://github.com/SciTools/cartopy/issues/1846#issuecomment-915548993?

**Comment by QuLogic** [comment]
You should not install into base. Create a new environment with conda-forge enabled from the start to prevent mismatched dependencies.

**Comment by harshmistry96** [comment]
@QuLogic Thank you for the reply. I was able to download latest version of cartopy(0.19).

But now I am getting some different error.
--------------------------------------------------------------------
URLError: <urlopen error [Errno 11002] getaddrinfo failed>

**Comment by QuLogic** [comment]
That's not enough information to go on, but 0.20.0 is out now; try upgrading to that first.

**Comment by xaviernogueira** [comment]
@harshmistry96 That is because they changed servers, you need to have the new 0.20.0 version. That said i am having trouble downloading it, but now at least you know what is causing the URLerror

**Comment by harshmistry96** [comment]
@QuLogic the latest version (0.20.0) works fine. 
Thanks
