### ISSUE TITLE
Wrong "temperature" variable name in "Block plots" example

### ISSUE THREAD

**Issue by jypeter** [SciTools/cartopy#1862]
I have just executed the example script provided in [Block plots](https://scitools.org.uk/cartopy/docs/latest/matplotlib/advanced_plotting.html#block-plots) (a subsection of the [More advanced mapping with cartopy and matplotlib](https://scitools.org.uk/cartopy/docs/latest/matplotlib/advanced_plotting.html) page)

This page plots a temperature variable, according to the script
```
fname = iris.sample_data_path('rotated_pole.nc')
temperature = iris.load_cube(fname)
```

I have checked the **temperature** range, before playing with the levels, and found out that they were really weird for a temperature variable.
```
>>> type(temperature)
<class 'numpy.ma.core.MaskedArray'>
>>> temperature.min(), temperature.max(),
(98439.0, 102954.0)
>>> v = iris.load_cube(fname)
>>> v
<iris 'Cube' of air_pressure_at_sea_level / (Pa) (grid_latitude: 22; grid_longitude: 36)>
```

Looking more closely it seems that **the input data file provides a Sea Level Pressure** example!
```
        float air_pressure_at_sea_level(grid_latitude, grid_longitude) ;
                air_pressure_at_sea_level:standard_name = "air_pressure_at_sea_l
                air_pressure_at_sea_level:units = "Pa" ;
```

It would probably make more sense to use `slp` or `sea_level_pressure` instead of `temperature` in the example :-)

It's probably worth checking which variable names are used, if this example data is used elsewhere in the cartopy and iris documentation

**Comment by QuLogic** [comment]
The Iris dependency, and that entire example, was removed in #1814.
