### ISSUE TITLE
Using plt.subplots to create mixed Axes and GeoAxes ?

### ISSUE THREAD

**Issue by jypeter** [SciTools/cartopy#1864]
Is there a way to use [plt.subplots](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.subplots.html) to create a **mixed** bunch of Axes and GeoAxes ?

From what I have seen, you can:
- either create axes that are all regular matplotlib axes,
- or add something like `subplot_kw={'projection': ccrs.PlateCarree()}` but then you will only get GeoAxes

You could also create axes that are all of the same type and then use a function to change the the type of some of them, kind of similar to what @rcomer mentioned in #1756

I guess the current workaround is to call [fig.add_subplot](https://matplotlib.org/stable/api/figure_api.html#matplotlib.figure.Figure.add_subplot) as many times as required, and use `projection=` when you need a GeoAxes. But it would be nice to do everything at the same time with `plt.subplots`

**Comment by rcomer** [comment]
Looks like this `matplotlib` issue is relevant https://github.com/matplotlib/matplotlib/issues/20392.  But they decided not to modify the `plt.subplots` API and instead recommended replacing individual axes that you want to change.

**Comment by jypeter** [comment]
Thanks for the pointer!

Well, easily getting a proper page layout can be hard. And there are lots of similar looking options that we don't always know about...

**Comment by dopplershift** [comment]
Either way, there's nothing Cartopy can do about this, since `plt.subplots` is strictly a Matplotlib API, we can't do anything in this repo to change that.
