### ISSUE TITLE
New doc: remove mention of the block plot example, or put it back

### ISSUE THREAD

**Issue by jypeter** [SciTools/cartopy#1870]
@QuLogic mentions removing the dependency to iris and netCDF4 in #1862, which makes perfect sense

This apparently led to **removing the `pcolormesh` Block plots example** (instead of using alternative data from `config["repo_data_dir"]`). Why not! There is still a [last pcolormesh example in the new site](https://2816-5282596-gh.circle-artifacts.com/0/docs/build/html/gallery/miscellanea/animate_surface.html?highlight=pcolormesh) in the new site, even if it uses dummy data

But if you remove the _Block plots_ example, you also have to remove the part of the sentence where it is mentioned at the bottom of the [previous page](https://2816-5282596-gh.circle-artifacts.com/0/docs/build/html/matplotlib/intro.html). It currently states: _In the next section, examples of contouring, **block plotting** and adding geo-located images are provided for more advanced map based visualisations_.

**Comment by dopplershift** [comment]
Always happy to have new examples that demonstrate things that aren't otherwise covered. For now, we've taken the suggestion of removing the inaccurate text (since we're trying to push to a release).
