### ISSUE TITLE
Image not same size as plot

### ISSUE THREAD

**Issue by gersmit** [SciTools/cartopy#1872]
**I save an image with from pyresample.geometry import AreaDefinition :**
local_scn.save_dataset(masked_img[0],
filename='/home/pi/a-satpy-testen/images/'+ file_name + ' transp_scn'+'.png',
overlay={'coast_dir': '/home/pi/a-satpy-testen/GSHHS_DATA_ROOT/',
'overlays': {'grid': grid,
'coasts': coast,
'borders': borders,
'rivers': rivers
}})

**Then i load image:**
fig = plt.figure(figsize=(10, 7.5))

fname = '/home/pi/a-satpy-testen/images/'+ file_name + ' transp_scn'+'.png'
img_extent = (-10, 25, 32, 58) #== lon-, lat-, lon+, lat+ == same coordinate as i save the image
img = plt.imread(fname)

land = cartopy.feature.NaturalEarthFeature('physical', 'land',
'10m', edgecolor='face', facecolor='beige')

ax = plt.axes(projection=ccrs.PlateCarree())
plt.title(file_name + ' satellite\n'
'2012 09/26/2012 20:50 UTC')

ax.add_feature(land, facecolor='green', zorder=1, alpha=0.1)
ax.coastlines(resolution='50m', color='blue', linewidth=1)
ax.add_feature(cfeature.BORDERS.with_scale('50m'))
ax.imshow(img, origin='upper', extent=img_extent, transform=ccrs.PlateCarree())

ax.axis('tight')
plt.savefig('/home/pi/a-satpy-testen/images/'+ file_name + ' transp_background' +'.png', transparent=True)
plt.show()

**Why is the coordinate not the same, there is a diverence between blue and white coastlines, see attachement.
What do i have to do to make the coordinates equal
How do i have to save an image to join later with the plot**
![coordinate not the same JPG](https://user-images.githubusercontent.com/38345229/133623005-31d9529b-3219-4966-bada-d07df7b09e07.jpg)

**Comment by greglucas** [comment]
There is an example in the gallery discussing the issue with using the wrong ellipse for your data.
https://scitools.org.uk/cartopy/docs/latest/gallery/lines_and_polygons/effects_of_the_ellipse.html#sphx-glr-gallery-lines-and-polygons-effects-of-the-ellipse-py

It is a bit complicated, but it boils down to making sure you are using the proper CRSs for your image, which is likely not PlateCarree is my guess... (There may be an `img.crs` attribute that you can use depending on how you have loaded that data)

**Comment by gersmit** [comment]
@greglucas , many thanks for thinking with me.
The problem is solved.
