### ISSUE TITLE
Problems encountered when using cartopy to set the latitude and longitude grid labels

### ISSUE THREAD

**Issue by 19950813** [SciTools/cartopy#1878]
#### Code to reproduce

``` python
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
from cartopy.mpl.gridliner import LONGITUDE_FORMATTER, LATITUDE_FORMATTER
from cartopy.io import img_tiles as cjmt

plt.rcParams['font.sans-serif']=['Microsoft YaHei']
plt.rcParams['axes.unicode_minus'] = False
fig = plt.figure(figsize=(6, 6), dpi=300)
ax = fig.add_axes(
        [0.05, 0, 0.9, 0.9],
        projection=ccrs.LambertConformal(central_longitude=105, standard_parallels=(25, 47))
    )
ax.set_extent([70, 145,10, 60], crs=ccrs.PlateCarree())
request = cjmt.TDT_vec_w()
ax.add_image(request, 5)
gl = ax.gridlines(draw_labels=True, linestyle="--", linewidth=0.1, x_inline=False, y_inline=False, color='k')
gl.rotate_labels = False
gl.bottom_labels = False
gl.right_labels = False
gl.xformatter = LONGITUDE_FORMATTER
gl.yformatter = LATITUDE_FORMATTER
gl.xlabel_style = {'size': 7}
gl.ylabel_style = {'size': 7}
ax.spines['geo'].set_linewidth(
    0.5)
plt.savefig("/temp/test.png", dpi=300, bbox_inches='tight', format='png')

```

#### Traceback 

- When using the defined latitude and longitude label, the label will still appear when the lower label display is turned off
- The specific output picture is as follows:
[![4KxJ8H.png](https://z3.ax1x.com/2021/09/17/4KxJ8H.png)](https://imgtu.com/i/4KxJ8H)

<details>
 <summary>Full environment definition</summary>

### Operating system

MAC

### Cartopy version
0.18.0

### conda list

```
cartopy                   0.18.0
python                    3.7.10
matplotlib-base           3.4.2 
```

### pip list

```
```

</details>

**Comment by stefraynaud** [comment]
This has been fixed by #1530 and should be made available soon with v0.19.
By the way, the longitude and latitude formatters are used automatically if the gridlines projection is platecaree, with is the default.
Note also that `cartopy.mpl.ticker` formatters are better than those of `cartopy.mpl.gridliner` and are used by default.

**Comment by dopplershift** [comment]
I think @stefraynaud meant 0.20. I'm going to close this as fixed in 0.20, but feel free to re-open if you find this is not the case.

**Comment by 19950813** [comment]
@dopplershift @stefraynaud hello,Uh, I think my problem has not been substantively resolved, so I would like to ask you, besides waiting for the release of version 0.20, is there any better solution for my current needs?

**Comment by rcomer** [comment]
@19950813 Cartopy 0.20 was released 18 hours ago, so can give it a try now 👍
