### ISSUE TITLE
Seg fault when drawing 110m coastlines

### ISSUE THREAD

**Issue by sjsmith757** [SciTools/cartopy#1886]
### Description
Hi! I have been working on getting cartopy working on a managed system. I have had to build all of Cartopy's dependencies myself from source, and I'm relatively new at this, so it is very possible this is not specifically a cartopy issue. Still I would appreciate any guidance that might help me identify what the problem is. 

I am able to install cartopy and import its major modules without issues. The only issue I have found so far is when plotting coastlines, it results in a segmentation fault (core dumped). Specifically, this only happens with the 110m coastlines from Natural Earth, and it happens upon the call to `draw()`. Both the 50m and 10m coastlines do not result in a seg fault. Other physical features are also fine, such as 110m ocean and 110m land. I haven't tried an exhaustive list, but 110m coastline is the only issue I have found so far. I have tried removing the shapefiles from cartopy's cache and re-downloading, but this doesn't solve the issue. I'm not really sure what next steps to try from here. I can use 50m coastlines as a work around for the time being, but it would be nice to have 110m for some occasions. 

#### Code to reproduce

```
import cartopy.crs as ccrs
import matplotlib.pyplot as plt
fig, ax = plt.subplots(1,1,subplot_kw={'projection':ccrs.PlateCarree()})
ax.coastlines('110m')
plt.show()
```

 <summary>Full environment definition</summary>

### Operating system
RHEL 8.4 x86-64

### Cartopy version
cartopy==0.20.0

### pip list
Cython==0.29.23
Fiona==1.8.20
flufl.lock==6.0
matplotlib==3.4.1
numpy==1.19.5
pep8==1.7.1
Pillow==8.2.0
pyproj==3.1.0
pyshp==2.1.3
pytest==6.2.5
scipy==1.6.3
Shapely==1.7.1

### other dependencies
libtiff==4.3.0
PROJ==8.1.1
GEOS==3.10.0dev
SQLITE3==3.36.0

</details>

**Comment by greglucas** [comment]
Hm... that definitely shouldn't be happening! That may be a tough one to trace down if it is only happening in a certain situation. You could try using `gdb` to attempt to get a better stack trace to point you to a specific location of the failure. You might also want to install the dependencies with verbose logging on to see if they had any warnings that could be important.

**Comment by QuLogic** [comment]
Did you install Shapely from a binary wheel, or build it against the shared GEOS libraries you already have?

**Comment by sjsmith757** [comment]
Great thought, I believe it would have been a pre-built wheel since I used pip when possible. Let me give it a try building from source and get back to you.

**Comment by sjsmith757** [comment]
That took care of it! Thanks so much!
