### ISSUE TITLE
the resolution of cartopy land is too coarse

### ISSUE THREAD

**Issue by lwk1542** [SciTools/cartopy#1922]
### Description

using cartopy, the coarse resolution of land can not be improved even the scale is "10m". see the figure, the land and islands are so close. How to solve this problem？
![image](https://user-images.githubusercontent.com/16815156/140031061-beacd601-8e32-40d2-a846-c585b691b238.jpeg)

#### Code to reproduce

```
import matplotlib.pyplot as plt
    import cartopy
    
    def spatdistriClass():
    
        size = 10
        plt.rc('font', family='Times New Roman', weight='normal', size=size)
        font = {'family': 'Times New Roman',
                'color': 'black',
                'weight': 'normal',
                'size': size}
    
        pro = cartopy.crs.PlateCarree()
        fig, axes_arr = plt.subplots(nrows=1, ncols=1, figsize=(5.5, 3.3),
                                     subplot_kw={'projection': cartopy.crs.PlateCarree(central_longitude=180)})
        ax1 = axes_arr
        ax1.coastlines('10m', color="grey", linewidth=0.1)
        ax1.add_feature(cartopy.feature.LAND.with_scale('10m'), facecolor='grey')
    
        plt.savefig("image.jpeg", dpi=300, bbox_inches='tight', pad_inches=0.01)
        plt.show()
        plt.close()
        return " "
    
    
    if __name__ == '__main__':
        spatdistriClass() 

```

#### Traceback 

```

```

<details>
 <summary>Full environment definition</summary>

### conda list

```
```

### pip list

```
```

</details>

**Comment by greglucas** [comment]
If you specify `edgecolor='none'` I think you'll get what you're looking for.

Perhaps that should actually be the default for these filled polygons... I'm not sure why they have the edgecolor explicitly set to 'face'.
https://github.com/SciTools/cartopy/blob/313f02f3e90309277209eca65b8b211256a527d5/lib/cartopy/feature/__init__.py#L500-L503
