### ISSUE TITLE
Cannot add my shpfile on Mercator projection images

### ISSUE THREAD

**Issue by haiyangdaozhang** [SciTools/cartopy#1927]
### Description

I used satpy to generate a tif file. And then I want to draw the tif file as a png and overlay a custom coastline. If myarea is a latlong projection, the program is successful. But if myarea is  a Mercator projection, it can createa png image, but thereis no coastlines on the image. I don't know why this problem occurs.

#### myarea:

```
myarea
Out[25]: 
Area ID: MERC30
Description: merc30
Projection ID: MERC30_new
Projection: {'datum': 'WGS84', 'lat_ts': '30', 'lon_0': '0', 'no_defs': 'None', 'proj': 'merc', 'type': 'crs', 'units': 'm', 'x_0': '0', 'y_0': '0'}
Number of columns: 8000
Number of rows: 8000
Area extent: (8517004.5473, -1230740.1737, 12517004.5473, 2769259.8263)
```
#### fail to add shp file to picture

```
crs=myarea.to_cartopy_crs()
shape_feature_latlong = ShapelyFeature(Reader(my_shpfile).geometries(), crs, facecolor=(1, 1, 1, 0),
                             edgecolor=edgecolor, linewidth=linewidth)
plt.clf()
plt.cla()
plotdata = plt.imread(dproduct_file"r")
# dproduct_file is a tiff file which has been resampled by satpy
fig = plt.figure(figsize=(8, 8), dpi=100)
ax = plt.axes((0, 0, 1, 1), projection=crs)
plt.axis("off")
ax.set_global()
ax.add_feature(shape_feature, linestyle=linetype)
fig.savefig("test_merc.png")
```
It works ,but there is no my coastline on the image.

**Comment by haiyangdaozhang** [comment]
If I use ax.coastlines() , it will create default coastlines. But ax.add_feature cannot work.

**Comment by dopplershift** [comment]
What is `crs` above? I see you're passing it to `ShapelyFeature`, which means it matches the coordinate system of the shapefile (which I would have otherwise guessed is lat/lon), but then you're also using it for your axes and plotting data, which means it should be Mercator?

My guess is change `crs` to `ccrs.PlateCarree()` in the creating the `ShapelyFeature`.

**Comment by haiyangdaozhang** [comment]
It works！ Thank you!
