### ISSUE TITLE
Fails to build with matplotlib 3.5

### ISSUE THREAD

**Issue by sebastic** [SciTools/cartopy#1929]
### Description
As reported by Lucas Nussbaum in [Debian Bug #999533](https://bugs.debian.org/999533):
> During a rebuild of all packages in sid, your package failed to build on amd64, using matplotlib 3.5 currently in experimental. This version will soon be uploaded to unstable.
>
> If you have questions about this, please contact Sandro Tosi <morph@debian.org>.
> 
> Relevant part (hopefully):
> ```
> make[1]: Entering directory '/<<PKGBUILDDIR>>'
> xvfb-run -a -n 1 -s "-screen 0 1280x1024x24 -dpi 96" dh_auto_test
> I: pybuild base:232: cd /<<PKGBUILDDIR>>/.pybuild/cpython3_3.9_cartopy/build; python3.9 -m pytest --pyargs -m "not network and not natural_earth"
> ============================= test session starts ==============================
> platform linux -- Python 3.9.7, pytest-6.2.5, py-1.10.0, pluggy-0.13.0
> rootdir: /<<PKGBUILDDIR>>
> collected 0 items / 1 error
> 
> ==================================== ERRORS ====================================
> ________________________ ERROR collecting test session _________________________
> /usr/lib/python3.9/importlib/__init__.py:127: in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
> <frozen importlib._bootstrap>:1030: in _gcd_import
>     ???
> <frozen importlib._bootstrap>:1007: in _find_and_load
>     ???
> <frozen importlib._bootstrap>:972: in _find_and_load_unlocked
>     ???
> <frozen importlib._bootstrap>:228: in _call_with_frames_removed
>     ???
> <frozen importlib._bootstrap>:1030: in _gcd_import
>     ???
> <frozen importlib._bootstrap>:1007: in _find_and_load
>     ???
> <frozen importlib._bootstrap>:986: in _find_and_load_unlocked
>     ???
> <frozen importlib._bootstrap>:680: in _load_unlocked
>     ???
> <frozen importlib._bootstrap_external>:850: in exec_module
>     ???
> <frozen importlib._bootstrap>:228: in _call_with_frames_removed
>     ???
> cartopy/tests/mpl/__init__.py:15: in <module>
>     import matplotlib.pyplot as plt
> /usr/lib/python3/dist-packages/matplotlib/pyplot.py:2226: in <module>
>     switch_backend(rcParams["backend"])
> /usr/lib/python3/dist-packages/matplotlib/pyplot.py:267: in switch_backend
>     class backend_mod(matplotlib.backend_bases._Backend):
> /usr/lib/python3/dist-packages/matplotlib/pyplot.py:268: in backend_mod
>     locals().update(vars(importlib.import_module(backend_name)))
> /usr/lib/python3.9/importlib/__init__.py:127: in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
> /usr/lib/python3/dist-packages/matplotlib/backends/backend_tkagg.py:1: in <module>
>     from . import _backend_tk
> /usr/lib/python3/dist-packages/matplotlib/backends/_backend_tk.py:14: in <module>
>     from PIL import Image, ImageTk
> E   ImportError: cannot import name 'ImageTk' from 'PIL' (/usr/lib/python3/dist-packages/PIL/__init__.py)
> =========================== short test summary info ============================
> ERROR ../../.. - ImportError: cannot import name 'ImageTk' from 'PIL' (/usr/l...
> !!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
> =============================== 1 error in 1.00s ===============================
> E: pybuild pybuild:354: test: plugin distutils failed with: exit code=2: cd /<<PKGBUILDDIR>>/.pybuild/cpython3_3.9_cartopy/build; python3.9 -m pytest --pyargs -m "not network and not natural_earth"
> dh_auto_test: error: pybuild --test -i python{version} -p 3.9 returned exit code 13
> ```
>
> The full build log is available from:
> http://qa-logs.debian.net/http://qa-logs.debian.net/2021/11/numpy-matplotlib/matplotlib-exp/python-cartopy_0.20.1+dfsg-1_unstable_matplotlib-exp.log

### Operating system

Debian unstable amd64

### Cartopy version

0.20.1

**Comment by greglucas** [comment]
That looks like it isn't even trying to import cartopy at that point. It is failing very early on trying to import matplotlib, which then fails importing PIL. Perhaps the installs of matplotlib and PIL aren't compatible on the build systems yet?

Note also that there was another issue in matplotlib-3.5.0rc1 causing cartopy test failures that has been fixed upstream in matplotlib (https://github.com/matplotlib/matplotlib/pull/21293) and won't be in the rc, so some failure is expected currently, just not during the imports.

**Comment by QuLogic** [comment]
That's a bug in Debian packaging. The Tk backend require Tk support from Pillow.
