### ISSUE TITLE
Cant properly install cartopy

### ISSUE THREAD

**Issue by lennuk93** [SciTools/cartopy#1935]
### Description

Hello
I am trying to install cartopy on my Mac. I installed it apparently but now the line below is not running and I have no clue how to fix it.

#### Code to reproduce
Installed with
```
brew install proj geos 
pip3 install cartopy 
```

Then in a python console:
```
import cartopy.crs as ccrs
```

#### Traceback 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cartopy/__init__.py", line 107, in <module>
    import cartopy.crs
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cartopy/crs.py", line 26, in <module>
    import cartopy.trace
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cartopy/trace.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace '_GEOSCoordSeq_create_r'
```

<details>
 <summary>Full environment definition</summary>

### Operating system
- MacOS Monterey 12.0.1 
- Python 3.9

.zshrc added lines
```
export DYLD_LIBRARY_PATH=/opt/homebrew/opt/geos/lib/
export GEOS_DIR=/opt/homebrew/opt/geos/
export PKG_CONFIG_PATH=/opt/homebrew/bin/pkg-config
```

### Cartopy version
Cartopy==0.20.1

### conda list
Not using conda.

### pip list

```
Cartopy==0.20.1
certifi==2021.10.8
cycler==0.11.0
kiwisolver==1.3.2
matplotlib==3.4.3
numpy==1.21.2
Pillow==8.4.0
pyModeS==2.9
pyparsing==3.0.6
pyproj==3.2.1
pyshp==2.1.3
python-dateutil==2.8.2
pyzmq==22.3.0
Shapely==1.8.0
six==1.16.0
```

</details>

**Comment by greglucas** [comment]
Did you follow the instructions about needing to install shapely from source after installing geos?
https://scitools.org.uk/cartopy/docs/latest/installing.html#required-dependencies
```
# shapely needs to be built from source to link to geos. If it is already
# installed, uninstall it by: pip3 uninstall shapely
pip3 install shapely --no-binary shapely
```

Is pkg-config finding and linking the paths properly? `pkg-config --libs geos proj`

You might want to do a verbose install `pip install -v cartopy` to see if anything stands out in the installation logs.

**Comment by greglucas** [comment]
Closing for lack of response and no dependence on PROJ anymore.
