### ISSUE TITLE
v0.20.2 release?

### ISSUE THREAD

**Issue by greglucas** [SciTools/cartopy#1936]
To prevent warnings with the recent shapely deprecations, I propose we make a v0.20.2 release in the very near future. See comment here:
https://github.com/SciTools/cartopy/pull/1914#issuecomment-962574807

All of those issues have been addressed and are in the v0.20.x branch, so I think we are good to go unless anyone has other ideas to add to the release. I think Matplotlib v3.5 will be released soon, so it might be nice to hold off on a patch release until that is out to make sure tests pass and we don't need other patch updates.

Comment here if you have issues with this plan.

**Comment by dopplershift** [comment]
👍 to making a patch release, but waiting on Matplotlib 3.5 first.

**Comment by richli** [comment]
Matplotlib 3.5 [was released on 2021-11-15](https://github.com/matplotlib/matplotlib/releases/tag/v3.5.0)

**Comment by greglucas** [comment]
Yep, v0.20.1 should work with it. Is there something critical we need to get into v0.20.2?

I can't get a PR on the v0.20.x branch to pass, so it is still waiting on that: https://github.com/SciTools/cartopy/pull/1969
Everything passes for me locally, so I have no idea what the issue is with ogc_clients.

**Comment by greglucas** [comment]
Any objections to cutting a v0.20.2 release later today? I lost track of this before now and I think everything is updated for MPL 3.5 now too.
ping: @dopplershift, @QuLogic

**Comment by dopplershift** [comment]
Fine with me.

**Comment by greglucas** [comment]
Version 0.20.2 is now released and available through pypi: `pip install cartopy==0.20.2`
