### ISSUE TITLE
How to get coastline coordinates for geomagnetic transformation

### ISSUE THREAD

**Issue by dinsmoro** [SciTools/cartopy#1945]
### Description

I want to get coordinate points from the cartopy.feature.COASTLINE or ax.coastlines('110m') methods so they can be converted to geomagnetic coordinates and then be replotted (by making a matplotlib Path instance from vertices? guessing how to use them after the best).

Either method doesn't seem to expose any way to access points that make them up (e.g. no .get_path() like described here: [https://stackoverflow.com/a/57500066/2403531](https://stackoverflow.com/a/57500066/2403531)), so I'm not sure how to accomplish this.

Raising an issue since searching through the source code/docs don't expose anything useful to me (though I'm not super savvy with intricate matplotlib/cartopy methods) and these stackoverflow Q's have also gone unanswered: [https://stackoverflow.com/questions/67626751/how-to-use-cartopy-to-plot-data-in-geomagnetic-coordinates](https://stackoverflow.com/questions/67626751/how-to-use-cartopy-to-plot-data-in-geomagnetic-coordinates), [https://stackoverflow.com/questions/70045971/plotting-coastlines-and-other-features-in-magnetic-coordinates-with-cartopy](https://stackoverflow.com/questions/70045971/plotting-coastlines-and-other-features-in-magnetic-coordinates-with-cartopy).

#### Code to reproduce

```
import cartopy
cc = cartopy.feature.COASTLINE;
# ideally a method like cc.get_path() or cc.get_points()
```

**Comment by dopplershift** [comment]
I think the [Hurricane Katrina path](https://scitools.org.uk/cartopy/docs/latest/gallery/lines_and_polygons/hurricane_katrina.html#sphx-glr-gallery-lines-and-polygons-hurricane-katrina-py) example will be your best guide on how to get the geometry out of a feature, and then plot with it somehow.

**Comment by dinsmoro** [comment]
Thanks for the quick reply! But unfortunately I can't figure out the piece of that example that would inform on outputting coordinates from a cartopy method.

something like
```
import cartopy
cc = cartopy.feature.COASTLINE;
cc.geometries();
```

Yields a `<tuple_iterator>` and it doesn't seem to be the `<generator object BasicReader.geometries>` that `shpreader.Reader(states_shp).geometries()` yields in the code.

**Comment by dopplershift** [comment]
This is the beginning of getting the coordinates. I'm not sure what actually to do to convert to geomagnetic coordinates, but should get you started:
```python
import cartopy
cc = cartopy.feature.COASTLINE;
for geom in cc.geometries():
    print(list(geom.coords)[:10])
    break
```
Each of the things returned by iterating over `geometries()` is a Shapely `Geometry` object, so for more info I'd recommend pouring over their [docuementation](https://shapely.readthedocs.io/en/stable/manual.html#geometric-objects).

**Comment by dinsmoro** [comment]
Thanks for that bit of code - that got it going for me!

For posterity (not sure how long these issues exist once closed):
*For something other than geo->mag coords, replace `aacgmv2.convert_latlon_arr` with any other function that adjusts lat/long coords for the specific application*

        import cartopy.feature as cfeature
        cc = cfeature.NaturalEarthFeature('physical', 'coastline', mapper_resolution, color='xkcd:black',zorder=75); #get a feature to mess with
        geom_mag = []; #prep a list
        for geom in cc.geometries():
            geom_mag.append(convert_to_mag(geom, time4mag, alt4mag));
            # geom_mag.append(geom);
            # coords = list(geom.coords);
        #END FOR geom
        cc_mag = cfeature.ShapelyFeature(geom_mag, settings_map['projection'], color='xkcd:black',zorder=75);
        for geom in cc_mag.geometries():
            ax.plot(*geom.coords.xy, color='xkcd:black', linewidth=1.0, zorder=75, transform=ccrs.PlateCarree());
        #END FOR geom

with the function convert_to_mag:

```
def convert_to_mag(geom, time4mag, alt4mag): #based on fabulously thorough code at https://gis.stackexchange.com/a/291293
    import aacgmv2 #install with: pip install aacgmv2 [need buildtools what a pain]
    # from math import isnan as isnan
    if geom.is_empty:
        return geom
    #END IF
    if geom.has_z:
        def convert_to_mag_doer(coords, time4mag, _):
            for long, lat, alt4mag in coords:
                [lat_mag, long_mag, alt_mag] = aacgmv2.convert_latlon(lat, long, alt4mag, time4mag, method_code='G2A'); #converts from geographic to geomagnetic (AACGMv2)
                yield (long_mag, lat_mag, alt_mag)
            #END FOR long, lat, alt_mag
        #END DEF
    else:
        def convert_to_mag_doer(coords, time4mag, alt4mag):
            for long, lat in coords:
                [lat_mag, long_mag, _] = aacgmv2.convert_latlon_arr(lat, long, alt4mag, time4mag, method_code='G2A'); #converts from geographic to geomagnetic (AACGMv2)
                # tryCntr = 0;
                # while( (isnan(long_mag.item()) | isnan(lat_mag.item())) & (tryCntr < 5) ):
                #     #recalc at higher altitude
                #     [long_mag, lat_mag, _] = aacgmv2.convert_latlon_arr(lat, long, alt4mag+200, time4mag, method_code='G2A'); #converts from geographic to geomagnetic (AACGMv2)
                #     tryCntr += 1 #increment
                # #END IF
                yield (long_mag.item(), lat_mag.item())
            #END FOR long, lat
        #END DEF
    #END IF
    # Process coordinates from each supported geometry type
    if geom.type in ('Point', 'LineString', 'LinearRing'):
        return type(geom)(list(convert_to_mag_doer(geom.coords, time4mag, alt4mag)))
    elif geom.type == 'Polygon':
        ring = geom.exterior
        shell = type(ring)(list(convert_to_mag_doer(ring.coords, time4mag, alt4mag)));
        holes = list(geom.interiors);
        for pos, ring in enumerate(holes):
            holes[pos] = type(ring)(list(convert_to_mag_doer(ring.coords, time4mag, alt4mag)));
        #END FOR pos, ring
        return type(geom)(shell, holes)
    elif geom.type.startswith('Multi') or geom.type == 'GeometryCollection':
        # Recursive call
        return type(geom)([convert_to_mag(part, time4mag, alt4mag) for part in geom.geoms])
    else:
        raise ValueError('Type %r not recognized' % geom.type)
    #END IF
#END DEF
```

**Comment by dopplershift** [comment]
Glad you got it working! There's no expiration date for GitHub issues, so this will exist until GitHub goes away for some reason.
