### ISSUE TITLE
Global map cropped with pcolormesh when lats > 90

### ISSUE THREAD

**Issue by fmaussion** [SciTools/cartopy#1947]
Here is a mwe:

```python
import matplotlib
import matplotlib.pyplot as plt
import numpy as np 
import cartopy
import cartopy.crs as ccrs  

print('matplotlib', matplotlib.__version__)
print('cartopy', cartopy.__version__)

lon = np.linspace(-179.625, 179.625, 480)
lat = np.linspace(90, -90, 241)
data, _ = np.meshgrid(lon, lat)

plt.figure()
ax = plt.axes(projection=ccrs.EqualEarth())
plt.pcolormesh(lon, lat, data, transform=ccrs.PlateCarree(), shading='nearest')
ax.coastlines(); ax.gridlines();
```

Which produces:
![image](https://user-images.githubusercontent.com/10050469/143658015-03b38361-98ed-451c-9ff8-ff9f26e446a7.png)

Strangely enough, this does not occur with other coordinates (here in steps of 1):

```python
lon = np.linspace(-180, 180, 361)
lat = np.linspace(90, -90, 181)
data, _ = np.meshgrid(lon, lat)

plt.figure()
ax = plt.axes(projection=ccrs.EqualEarth())
plt.pcolormesh(lon, lat, data, transform=ccrs.PlateCarree(), shading='nearest')
ax.coastlines(); ax.gridlines();
```

![image](https://user-images.githubusercontent.com/10050469/143658094-ea177c60-7e62-4915-9d48-4c9c875e7f40.png)

This is:

```
matplotlib 3.4.3
cartopy 0.20.1
```

**Comment by fmaussion** [comment]
Ok yes, this happens when the bounds [-180, 180] are not included in the coordinates. In my first example above however, if `shading='nearest'` is correctly interpreted, the bounds are actually correct. (note that I come from xarray, where plots that used to work before - previous version unknown -  now have this issue with the latest stable versions)

**Comment by fmaussion** [comment]
I think I have found that the problem reliably occurs when the latitudes are > 90°, which happens in the case above and auto shading. See e.g. with `shading='flat'`: 

```python
lon = np.linspace(-179.625, 179.625, 480)
lat = np.linspace(90.1, -90.1, 241)
data, _ = np.meshgrid(lon[1:], lat[1:])

plt.figure()
ax = plt.axes(projection=ccrs.EqualEarth())
plt.pcolormesh(lon, lat, data, transform=ccrs.PlateCarree(), shading='flat')
ax.coastlines(); ax.gridlines();
```

![image](https://user-images.githubusercontent.com/10050469/143683987-78b6652f-f21d-4bda-9750-8902ad0b60fd.png)

**This problem does not occur with cartopy 0.18.0**.

**Comment by greglucas** [comment]
@fmaussion, I think updating the bounds was missed in the refactor of the pcolormesh code, so we are effectively only updating the bounds based on the wrapped cells and missing the mesh, and depending on the bounds you choose you may or may not get wrapped cells all the way out to the bounds of the projection. I opened #1958 to try and add the bounds check back in, can you try that out and make sure it works as expected for your use-cases?

**Comment by fmaussion** [comment]
@greglucas sorry I haven't followed up on this. yes as far as I can see you fix seem to solve the problems with ERA5 data.

I would very much welcome a new cartopy release soon!
