### ISSUE TITLE
cartopy v 0.20.1 throws various HTTP errors when trying to use cartopy.io.img_tiles

### ISSUE THREAD

**Issue by kovar-ursa** [SciTools/cartopy#1965]
### Description
cartopy v 0.20.1 throws various HTTP errors when trying to use cartopy.io.img_tiles

One of the examples I used to try to implement the capability is:

[Example code used as model](https://notebook.community/lmoresi/docker-web-notebook-server/notebooks/Example%20Working%20with%20on-demand%20mapping%20services)

#### Code to reproduce

```
fig = plt.figure()
mapbox_satellite = cimgt.MapboxTiles(map_id='mapbox.satellite', 
            access_token='pk.ey...qB7AXa40XGWFm_nuyQ')
ax = fig.add_subplot(1, 1, 1, projection=mapbox_satellite.crs)
ax.add_image(mapbox_satellite, 8)
```
OSM also fails in the same manner. Using an invalid mapbox token produces a 401 error rather than a 404.

#### Traceback 

```
There is no traceback other than a very long steam of 404 errors.
```

<details>
 <summary>OSX, python 3.9, Jupyter Lab</summary>

### Operating system
MacOS 12.0.1

### Cartopy version
0.20.1

</details>

**Comment by greglucas** [comment]
Mapbox updated their API endpoints and those were changed in Cartopy 0.20.
See here for the documentation:
https://scitools.org.uk/cartopy/docs/latest/reference/generated/cartopy.io.img_tiles.MapboxTiles.html

And mapbox's API styles: https://docs.mapbox.com/api/maps/styles/

I think the update required in your script is the map-id: `map_id='satellite-v9'`

xref: https://github.com/SciTools/cartopy/pull/1763

**Comment by kovar-ursa** [comment]
If I just do the `add_image` no errors are produced. Once I try to plot anything, I start getting a long series of:

```
<urlopen error [Errno 60] Operation timed out>
<urlopen error [Errno 61] Connection refused>
<urlopen error [Errno 61] Connection refused>
<urlopen error [Errno 61] Connection refused>
<urlopen error [Errno 61] Connection refused>
<urlopen error [Errno 61] Connection refused>
<urlopen error [Errno 61] Connection refused>
<urlopen error [Errno 61] Connection refused>
<urlopen error [Errno 60] Operation timed out>
```
Let me see if I can make a simple reproducible example.

**Comment by kovar-ursa** [comment]
The above now works. I did not change anything, I just waited a few days and tried again.

**Comment by dopplershift** [comment]
Going to blame either spurious network issue or upstream service problem. Either way, not a problem with cartopy.
