### ISSUE TITLE
I Have installed cartopy using conda but still not able to import cartopy.

### ISSUE THREAD

**Issue by Durgaprasad2021** [SciTools/cartopy#1971]
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-a4ba129e3112> in <module>
----> 1 import cartopy

ModuleNotFoundError: No module named 'cartopy'

**Comment by greglucas** [comment]
You probably need to activate your conda environment then. This is a conda issue, not Cartopy if you have successfully installed it.

**Comment by Durgaprasad2021** [comment]
I have tried done that but still not able to import the file

**Comment by dopplershift** [comment]
If `conda install cartopy` succeeded but `import cartopy` says `MduleNotFoundError`, something is wrong with your conda setup--not Cartopy.

Make sure that you're running the Python you think you are, with something like `which python` or `python -c 'import sys;print(sys.prefix)`. Depending on what OS you're running (you haven't mentioned it), one of those should work to point you in the direction.
