### ISSUE TITLE
Broken links to generated documentation of cartopy.crs.CRS methods

### ISSUE THREAD

**Issue by wjbenfold** [SciTools/cartopy#1972]
### Description

Some links are broken in the cartopy documentation (and consequently in documentation linked into it, e.g. Iris)

Example: https://scitools.org.uk/cartopy/docs/latest/whatsnew/v0.7.html

As of 17/12/2021, the link to cartopy.mpl.geoaxes.GeoAxes.gridlines() works fine, but the link to cartopy.crs.CRS.transform_points() is broken. Links to cartopy.crs.CRS itself are fine.

![image](https://user-images.githubusercontent.com/69585101/146535248-08385a6f-33a4-4b91-b842-230565b90369.png)

**Comment by rcomer** [comment]
This appears to be fixed (in my local build at least).  Maybe by #2183?

**Comment by greglucas** [comment]
Closed by #2220
