### ISSUE TITLE
while i was trying to plot my model data then i was getting error raise ValueError("DataArray must be 2d") ValueError: DataArray must be 2d

### ISSUE THREAD

**Issue by haritha1022** [SciTools/cartopy#2000]
my code
import xarray as xr
import cartopy.crs as ccrs
from cartopy import feature as cf
import matplotlib.pyplot as plt
import numpy as np

#Opening and reading data
data=xr.open_dataset("rain33.nc")
print(data)

lon=data.lon[:]
lat=data.lat[:]
rainnc=data.rainnc[0]
#time=data.time[0]
#Margins for the cartopy extent

east = 100
west = 60
north = 38
south = 0
ax = plt.axes(projection=ccrs.PlateCarree())
rainnc.plot.contourf(cmap="jet",ax=ax)
ax.set_extent([west, east, south, north])
ax.coastlines()
ax.add_feature(cf.BORDERS)
#ax.colorbar(cb, pad='2%',label='pa',extend='both',location='right')
#plt.colorbar(cb)
plt.savefig("rain3.jpg")
plt.show()

and my data contains
Dimensions:    (time: 2, bnds: 2, lon: 378, lat: 351, lev_2: 1)
Coordinates:
  * time       (time) datetime64[ns] 2021-12-30T10:30:00 2021-12-31
  * lon        (lon) float64 77.43 77.45 77.46 77.47 ... 81.32 81.33 81.34 81.35
  * lat        (lat) float64 11.14 11.15 11.16 11.17 ... 14.65 14.66 14.67 14.68
  * lev_2      (lev_2) float64 1e+03
Dimensions without coordinates: bnds
Data variables:
    time_bnds  (time, bnds) datetime64[ns] ...
    rainnc     (time, lev_2, lat, lon) float32 ...

**Comment by fischcheng** [comment]
So the data array you are trying to plot is not 2d, which is required by contourf. Try something like isel(time=0, lev_2=0) might work.

**Comment by haritha1022** [comment]
hii sir
i have changed the command sir


import xarray as xr
import cartopy.crs as ccrs
from cartopy import feature as cf
import matplotlib.pyplot as plt
import numpy as np

#Opening and reading data
data=xr.open_dataset("rain33.nc")
print(data)


lon=data.lon[:]
lat=data.lat[:]
#u=data.u[0];
#v=data.v[0,::5,::5]
#z=data.z[0]

#lev_2=data.lev_2[:]

rainnc=data.rainnc[0]
#time=data.time[0]
#Margins for the cartopy extent

east = 100
west = 60
north = 38
south = 0


ax = plt.axes(projection=ccrs.PlateCarree())
c_scheme=plt.pcolor(lat,lon,np.squeeze(rainnc[0,0,:,:]),cmap='jet')
ax.set_extent([west, east, south, north])
ax.coastlines()
ax.add_feature(cf.BORDERS)
#ax.colorbar(cb, pad='2%',label='pa',extend='both',location='right')
plt.savefig("rain3.jpg")
plt.show()


and again the error shows
raise IndexError("too many indices")
IndexError: too many indices

**Comment by dopplershift** [comment]
Please post the full traceback that occurs with the error so we can see what line triggers that.

**Comment by fischcheng** [comment]
I'd just try to use `xarray` to plot (see example here, how it works with Cartopy https://xarray.pydata.org/en/stable/user-guide/plotting.html). `xarray` wrap  a lot of numpy/matplotlib methods. Say, no need to `np.squeeze`, can just be `dataarray.isel()`, I think `isel` will do the squeeze automatically. 

Could you please print `data` and `rainnc`? 
The recommended way to access variable inside a `dataset` would be something like:
`rainnc = data['rain'] `( or whatever variable name)
then select what timestep/level you want to plot
`rainnc.isel(time=0, lev_2=0).plot(**)`
 
BTW, it's also possible to plot `facet` (multiple subplots) directly from xarray.

**Comment by haritha1022** [comment]
thank you so much sir .it works

**Comment by haritha1022** [comment]
Thanks a lot.
