### ISSUE TITLE
Projections not documented anymore

### ISSUE THREAD

**Issue by maxnoe** [SciTools/cartopy#2004]
### Description

Older documentation versions had a nice list and gallery of the different projections available in `cartopy.crs`. The current documentation does not list any of these and seems to e.g. explicitly remove the projections from the documentation here:

https://github.com/SciTools/cartopy/blob/22cdafca511744143c5b673598a1889f169c1e3d/lib/cartopy/crs.py#L36

It would be nice to at least document the projection classes, even better would be bringing back the nice gallery page showing off all the projections.

### Cartopy version

Current release version and dev docs

**Comment by greglucas** [comment]
I think they are all still there?
https://scitools.org.uk/cartopy/docs/latest/reference/crs.html#list-of-projections
https://scitools.org.uk/cartopy/docs/latest/reference/projections.html

Perhaps putting them in an easier place to find?

**Comment by maxnoe** [comment]
Is this page ever linked to from the toplevel?

https://scitools.org.uk/cartopy/docs/latest/reference/projections.html

**Comment by maxnoe** [comment]
Yes, it is, but the link is called `PlateCarree`, not `Projections` or `Gallery of Projections`:

![Screenshot_20220214_161518](https://user-images.githubusercontent.com/5488440/153891180-38ea8277-76dd-484c-80a1-0d36a8bd8cf1.png)

**Comment by maxnoe** [comment]
And the reason I didn't see the list of projections is that google brought me directly here:

https://scitools.org.uk/cartopy/docs/latest/reference/generated/cartopy.crs.CRS.html#cartopy.crs.CRS

**Comment by maxnoe** [comment]
So maybe just fixing the name of the link in the sidebar would have been enough. But why not include all the classes in the auto-generated API docs? Google seems to like referring people to that

**Comment by maxnoe** [comment]
Ok, thanks, indeed that looks ok, sorry for the noise
