### ISSUE TITLE
different results for Geostationary projection example in 0.18

### ISSUE THREAD

**Issue by kcw78** [SciTools/cartopy#2008]
### Description
I am running the Geostationary projection example in the documentation with cartopy 0.18 (with python 3.8.3, matplotlib 3.3.4 and PROJ 7.0.1)
Reference URL:
https://scitools.org.uk/cartopy/docs/v0.15/examples/geostationary.html

When I do, I get a significantly different image than the one posted in the example.
Image attached for reference.
Example was created for 0.15.0. Has something change since then?

#### Code to reproduce
Code is available at reference URL above.
It is included here for completeness (comments clipped).
"""
Reprojecting images from a Geostationary projection
"""
try:
    from urllib2 import urlopen
except ImportError:
    from urllib.request import urlopen
from io import BytesIO

import cartopy.crs as ccrs
import matplotlib.pyplot as plt

def geos_image():
    """
    Return a specific SEVIRI image by retrieving it from a github gist URL.
    """
    url = ('https://gist.github.com/pelson/5871263/raw/'
           'EIDA50_201211061300_clip2.png')
    img_handle = BytesIO(urlopen(url).read())
    img = plt.imread(img_handle)
    img_proj = ccrs.Geostationary(satellite_height=35786000)
    img_extent = (-5500000, 5500000, -5500000, 5500000)
    return img, img_proj, img_extent, 'upper'

def main():
    ax = plt.axes(projection=ccrs.Miller())
    ax.coastlines()
    ax.set_global()
    img, crs, extent, origin = geos_image()
    plt.imshow(img, transform=crs, extent=extent, origin=origin, cmap='gray')
    plt.show()

if __name__ == '__main__':
    main()

#### Traceback 
There is no error or traceback message.
However the generated image is different / wrong.
![Example_Reprojecting_Geostationary_Image](https://user-images.githubusercontent.com/68927141/156808058-10e006f9-a09b-4209-8343-8252e3acdc08.png)

**Comment by greglucas** [comment]
That is odd. It doesn't look like anything changed between those two versions. All of the example galleries look like they produced the proper images:
**Latest:** https://scitools.org.uk/cartopy/docs/latest/gallery/scalar_data/geostationary.html#sphx-glr-gallery-scalar-data-geostationary-py

**v0.18:** https://scitools.org.uk/cartopy/docs/v0.18/gallery/geostationary.html#sphx-glr-gallery-geostationary-py

**Comment by kcw78** [comment]
Yes, that's odd. Looks like the problem is on my system. (That would explain problems I have transforming other Geostationary images.) I installed cartopy with conda from conda-forge channel. Is v0.18 the latest version available at conda-forge? Should I install Proj version 6.x (instead of 7.0.1)?

**Comment by greglucas** [comment]
Oh yes, PROJ versions could very well be the issue as there were some conflicts with PROJ APIs around that version transition. I thought conda-forge made sure the PROJ/Cartopy versions lined up properly though.

Yes, conda-forge should have the latest release available, so upgrading would be recommended if you can.

**Comment by kcw78** [comment]
Problem solved after I ran conda update for cartopy. New versions installed: cartopy v0.20.2 and Proj 8.2.1. That also solved some of the projection problems I was having from Geostationary to Mercator. Now I gotta diagnose the others....LOL

**Comment by QuLogic** [comment]
Seems like we can close this then.
