### ISSUE TITLE
Vendor test decorator from MPL?

### ISSUE THREAD

**Issue by oscargus** [SciTools/cartopy#2020]
### Description

Matplotlib may deprecate the `@cleanup` test decorator https://github.com/matplotlib/matplotlib/pull/22697 as it is no longer used in the Matplotlib code base. It was noted that Cartopy uses it, so my question now is where it should be vendored. To me it seems like creating a new file either `testing.py` or `decorators.py` may be options, possibly in the `mpl` directory. Or just add it to `utils.py`.

Any preferences?

(I can provide a PR, just in case.)

**Comment by dopplershift** [comment]
So it looks like `@cleanup`
1. Sets style (can handle with `pytest-mpl`)
1. Catches warnings
1. Resets the unit registry
1. Resets rcparams

(Did I miss anything?)

I don't know that we need any of that, except *maybe* the warning handling (which actually comes from the stdlib). So I'm wondering if we could just completely remove all uses?

**Comment by greglucas** [comment]
I agree with removing the cleanup decorator if possible. It works for me locally at least, see #2023

**Comment by QuLogic** [comment]
> I don't know that we need any of that, except _maybe_ the warning handling (which actually comes from the stdlib). So I'm wondering if we could just completely remove all uses?

We don't need this either; it's caught by pytest.

**Comment by oscargus** [comment]
Thanks all! Seems like it can work without it then. (The test failures in #2023 seems unrelated, so far.)

(This would then go in MPL 3.6, which is quite some time ahead, so should be plenty of time to get a Cartopy release out, if required. I guess all of you are at least as updated as I am when it comes to MPL releases, but in case someone else happens to see this.)
