### ISSUE TITLE
Shapely throwing an error during map plotting

### ISSUE THREAD

**Issue by Marchesini010126** [SciTools/cartopy#2040]
### Description

Hi everyone,
I am trying to use cartopy to develop a simple ground track calculator, but I have not been able to obtain the ground track as desired. I have defined a simple mock ground track in radiants and then it is converted in degrees inside the groundtrack_generator function. Shapely is the culprit I think, but I am not able to move on from this error. If someone has an idea, it is very much appreciated 

Thank you for your time and attention
Best,

Gregorio Marchesini
#### Code to reproduce

```
import numpy as np
import cartopy 
import numpy as np
from   matplotlib import pyplot as plt

def groundtrack_generator(groundtracks_list :list  = [],
                          labels            :list = [],
                          projection        :str   = "PlateCarree",
                          colors            :list  = [],
                          linewidth         :float = 1 ,
                          grid              :bool  = True,
                          grid_linewidth    :float = 1,
                          grid_color        :str   = "gray",
                          grid_alpha        :float =   0.3) :
    
    """
    Parameters 
    ----------
    
    groundtracks_list (List)  : List of numpy.ndarray[[N,2]] defining the latitude and longitude of each groundtrack
                                col[0] = longitude 
                                col[1] = latitude.
                                Units are radiants.  

    labels            (List ) : label per groundtrack
    projection        (Str  ) : projection to be used (see available projections below)
    colors            (List ) : list of colours per groundtrack
    linewidth         (Float) : linewidth of the groundtracks 
    grid              (Bool ) : activates grid on map, defining latitude and longitude reference
    grid_linewidth    (Float) : grid width
    grid_color        (Str  ) : grid color (refer to https://matplotlib.org/3.5.0/tutorials/colors/colors.html#:~:text=Single%20character%20shorthand%20notation%20for%20some%20basic%20colors. for a list of colors)
    grid_alpha        (Float) : grid alpha

    Returns
    --------
    Returns plot of a given set of ground tracks as definied by the groundtrack_list
    
    Description :
    -------------
    plots a set of ground tracks over a specified map. 
    
    have a look at :
    https://scitools.org.uk/cartopy/docs/v0.15/crs/projections.html
    for all maps projections and types
    
    Maps
    
    1  PlateCarree
    2  Mollweide
    3  AlbersEqualArea
    4  AzimuthalEquidistant
    5  LambertConformal
    6  LambertCylindrical
    7  Mercator
    8  Miller
    9  Mollweide
    10 Orthographic
    11 Robinson
    12 Sinusoidal
    13 Stereographic
    14 TransverseMercator
    15 InterruptedGoodeHomolosine
    16 RotatedPole
    
    
    
    
    """
    try :
        map_projection = getattr(cartopy.crs,projection) 
    except  AttributeError :
        raise ValueError("unknown map type {}.\n Check again the correct name of the map you want to apply".format(projection))
            
    # start defining the figure
    figure        = plt.figure(figsize=(8,6))
    ax            = plt.axes(projection=map_projection())

    rad2deg = 180/np.pi
    if len(colors) == 0 :
        colors = [(.0,.0,.0,.0)*len(groundtracks_list)]
   
    
    for groundtrack,color,label in zip(groundtracks_list,colors,labels) :
        
        # plot start position with bigger width
        plt.plot(groundtrack[:,0]*rad2deg,groundtrack[:,1]*rad2deg,
                    color     =  color,
                    linewidth = linewidth,
                    label     = label,
                    transform=cartopy.crs.Geodetic())

        plt.plot(groundtrack[0,0]*rad2deg,groundtrack[0,1]*rad2deg,
                    linewidth=linewidth*5,
                    color     =  color,
                    transform=cartopy.crs.Geodetic(),
                    marker = "*")
                    
    ax.set_global()
    
    if grid :
       ax.gridlines(color     =grid_color,
                    linestyle ="--",
                    draw_labels=True,
                    linewidth =grid_linewidth,
                    alpha     =grid_alpha)
    
    
    try :
        ax.stock_img()
    except :
        pass
    
    ax.legend()



# divide long/lat info from rotation matrix

line = np.linspace(0,2*np.pi,20)
lat = np.cos(line)[:,np.newaxis]
lon = np.sin(line)[:,np.newaxis]
cooordinates = np.hstack((lon,lat))

groundtracks_list       = [cooordinates]
labels                  = ["sat1"]
color_list              = [(0.,0.,0.,0.)]

test_maps =  ["Sinusoidal",
              "Stereographic",
             "LambertCylindrical",
             "Mercator",
             "Miller",
             "Mollweide",
             "Orthographic"]

for map in test_maps :

    groundtrack_generator(groundtracks_list =groundtracks_list ,
                        labels            = labels     ,
                        projection        = map,
                        colors            = color_list ,
                        linewidth         = 1 ,
                        grid              = True,
                        grid_linewidth    = 1,
                        grid_color        = "gray",
                        grid_alpha        =  0.3)

plt.show()


```

#### Traceback 

```
source /Users/gregorio/anaconda3/bin/activate
conda activate astrodynamic_venv
/Users/gregorio/anaconda3/envs/astrodynamic_venv/bin/python /Users/gregorio/Desktop/astrodyamics_challenges/groundtrack_project_code/bug_test.py
(base) n171-p76 :: Desktop/astrodyamics_challenges/groundtrack_project_code ‹main*› » source /Users/gregorio/anaco
nda3/bin/activate
(base) n171-p76 :: Desktop/astrodyamics_challenges/groundtrack_project_code ‹main*› » conda activate astrodynamic_
venv
(astrodynamic_venv) n171-p76 :: Desktop/astrodyamics_challenges/groundtrack_project_code ‹main*› » /Users/gregorio
/anaconda3/envs/astrodynamic_venv/bin/python /Users/gregorio/Desktop/astrodyamics_challenges/groundtrack_project_c
ode/bug_test.py
Traceback (most recent call last):
  File "/Users/gregorio/Desktop/astrodyamics_challenges/groundtrack_project_code/bug_test.py", line 122, in <module>
    cooordinates = np.hstack(lon,lat)
  File "<__array_function__ internals>", line 179, in hstack
TypeError: _vhstack_dispatcher() takes 1 positional argument but 2 were given
(astrodynamic_venv) n171-p76 :: Desktop/astrodyamics_challenges/groundtrack_project_code ‹main*› » /Users/gregorio
/anaconda3/envs/astrodynamic_venv/bin/python /Users/gregorio/Desktop/astrodyamics_challenges/groundtrack_project_c
ode/bug_test.py
/Users/gregorio/anaconda3/envs/astrodynamic_venv/lib/python3.9/site-packages/cartopy/mpl/gridliner.py:844: ShapelyDeprecationWarning: __len__ for multi-part geometries is deprecated and will be removed in Shapely 2.0. Check the length of the `geoms` property instead to get the  number of parts of a multi-part geometry.
  elif len(intersection) > 4:
/Users/gregorio/anaconda3/envs/astrodynamic_venv/lib/python3.9/site-packages/cartopy/mpl/gridliner.py:850: ShapelyDeprecationWarning: __getitem__ for multi-part geometries is deprecated and will be removed in Shapely 2.0. Use the `geoms` property to access the constituent parts of a multi-part geometry.
  xy = np.append(intersection[0], intersection[-1],
<__array_function__ internals>:180: ShapelyDeprecationWarning: The array interface is deprecated and will no longer work in Shapely 2.0. Convert the '.coords' to a numpy array instead.
/Users/gregorio/anaconda3/envs/astrodynamic_venv/lib/python3.9/site-packages/numpy/lib/function_base.py:5392: ShapelyDeprecationWarning: The array interface is deprecated and will no longer work in Shapely 2.0. Convert the '.coords' to a numpy array instead.
  return concatenate((arr, values), axis=axis)
/Users/gregorio/anaconda3/envs/astrodynamic_venv/lib/python3.9/site-packages/cartopy/mpl/gridliner.py:855: ShapelyDeprecationWarning: Iteration over multi-part geometries is deprecated and will be removed in Shapely 2.0. Use the `geoms` property to access the 
```

<details>
 <summary>Full environment definition</summary>

### Operating system
macOS Monterrey

# conda list
packages in environment at /Users/gregorio/anaconda3/envs/astrodynamic_venv:

Name                    Version                   Build  Channel
ampl-mp                   3.1.0             h2beb688_1006    conda-forge
basemap                   1.2.2            py39h023f496_4    conda-forge
boost-cpp                 1.72.0               h179ae3a_7    conda-forge
brotli                    1.0.9                h5eb16cf_7    conda-forge
brotli-bin                1.0.9                h5eb16cf_7    conda-forge
bzip2                     1.0.8                h0d85af4_4    conda-forge
c-ares                    1.18.1               h0d85af4_0    conda-forge
ca-certificates           2021.10.8            h033912b_0    conda-forge
cartopy                   0.20.0           py39h023f496_0    conda-forge
casadi                    3.5.5            py39h2d4fd04_9    conda-forge
certifi                   2021.10.8        py39h6e9494a_2    conda-forge
cspice-cmake              66                   h20e74f6_4    tudat-team
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
fonttools                 4.33.0           py39h701faf5_0    conda-forge
freetype                  2.10.4               h4cff582_1    conda-forge
geos                      3.9.1                he49afe7_2    conda-forge
giflib                    5.2.1                hbcb3906_2    conda-forge
icu                       70.1                 h96cf925_0    conda-forge
ipopt                     3.14.5               h463af43_0    conda-forge
jbig                      2.1               h0d85af4_2003    conda-forge
jpeg                      9e                   h5eb16cf_1    conda-forge
kiwisolver                1.4.2            py39h7248d28_1    conda-forge
krb5                      1.19.3               hb98e516_0    conda-forge
lcms2                     2.12                 h577c468_0    conda-forge
lerc                      3.0                  he49afe7_0    conda-forge
libblas                   3.9.0           14_osx64_openblas    conda-forge
libbrotlicommon           1.0.9                h5eb16cf_7    conda-forge
libbrotlidec              1.0.9                h5eb16cf_7    conda-forge
libbrotlienc              1.0.9                h5eb16cf_7    conda-forge
libcblas                  3.9.0           14_osx64_openblas    conda-forge
libcurl                   7.82.0               h9dce1e3_0    conda-forge
libcxx                    13.0.1               hc203e6f_0    conda-forge
libdeflate                1.10                 h0d85af4_0    conda-forge
libedit                   3.1.20191231         h0678c8f_2    conda-forge
libev                     4.33                 haf1e3a3_1    conda-forge
libffi                    3.4.2                h0d85af4_5    conda-forge
libgfortran               5.0.0           9_3_0_h6c81a4c_23    conda-forge
libgfortran5              9.3.0               h6c81a4c_23    conda-forge
libiconv                  1.16                 haf1e3a3_0    conda-forge
liblapack                 3.9.0           14_osx64_openblas    conda-forge
libnghttp2                1.47.0               hca56917_0    conda-forge
libopenblas               0.3.20          openmp_hb3cd9ec_0    conda-forge
libosqp                   0.6.2                he49afe7_3    conda-forge
libpng                    1.6.37               h7cec526_2    conda-forge
libssh2                   1.10.0               hd3787cc_2    conda-forge
libtiff                   4.3.0                h17f2ce3_3    conda-forge
libwebp                   1.2.2                h28dabe5_0    conda-forge
libwebp-base              1.2.2                h0d85af4_1    conda-forge
libxcb                    1.13              h0d85af4_1004    conda-forge
libzlib                   1.2.11            h6c3fc93_1014    conda-forge
llvm-openmp               13.0.1               hcb1a161_1    conda-forge
lz4-c                     1.9.3                he49afe7_1    conda-forge
matplotlib                3.5.1            py39h6e9494a_0    conda-forge
matplotlib-base           3.5.1            py39hb07454d_0    conda-forge
metis                     5.1.0             h2e338ed_1006    conda-forge
mumps-include             5.2.1               h694c41f_11    conda-forge
mumps-seq                 5.2.1               hea8e22a_11    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
ncurses                   6.3                  h96cf925_1    conda-forge
nrlmsise-00               0.1                  hbe5fc6d_1    tudat-team
numpy                     1.22.3           py39hf56e92f_2    conda-forge
openjpeg                  2.4.0                h6e7aa92_1    conda-forge
openssl                   3.0.2                h6c3fc93_1    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.4.2            py39hbd61c47_1    conda-forge
pillow                    9.1.0            py39hd2c7aa1_2    conda-forge
pip                       22.0.4             pyhd8ed1ab_0    conda-forge
proj                      8.0.1                h1512c50_0    conda-forge
pthread-stubs             0.4               hc929b4f_1001    conda-forge
pybind11                  2.9.2            py39h7248d28_1    conda-forge
pybind11-global           2.9.2            py39h7248d28_1    conda-forge
pyparsing                 3.0.8              pyhd8ed1ab_0    conda-forge
pyproj                    3.3.0            py39h767ef73_2    conda-forge
pyshp                     2.2.0              pyhd8ed1ab_0    conda-forge
python                    3.9.12          h1cc4136_1_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pytz                      2022.1             pyhd8ed1ab_0    conda-forge
readline                  8.1                  h05e3726_0    conda-forge
scipy                     1.8.0            py39h056f1c0_1    conda-forge
scotch                    6.0.9                h3da7401_2    conda-forge
setuptools                62.1.0           py39h6e9494a_0    conda-forge
shapely                   1.8.0            py39h1d9c377_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sofa-cmake                1.0.0                hc45f8e4_6    tudat-team
sqlite                    3.38.2               hb516253_0    conda-forge
tabulate                  0.8.9              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h5dbffcc_0    conda-forge
tornado                   6.1              py39h63b48b0_3    conda-forge
tudat                     2.10.7               hb7fd799_0    tudat-team
tudat-resources           1.2.0                h37eea90_0    tudat-team
tudatpy                   0.6.3            py39h0f645d4_0    tudat-team
tzdata                    2022a                h191b570_0    conda-forge
unicodedata2              14.0.0           py39h63b48b0_1    conda-forge
unixodbc                  2.3.9                hd863c23_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.9                h35c211d_0    conda-forge
xorg-libxdmcp             1.1.3                h35c211d_0    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
zlib                      1.2.11            h6c3fc93_1014    conda-forge
zstd                      1.5.2                h582d3a0_0    conda-forge

```
```

### pip list

```
```

</details>

**Comment by greglucas** [comment]
The error says:
```
Traceback (most recent call last):
  File "/Users/gregorio/Desktop/astrodyamics_challenges/groundtrack_project_code/bug_test.py", line 122, in <module>
    cooordinates = np.hstack(lon,lat)
  File "<__array_function__ internals>", line 179, in hstack
TypeError: _vhstack_dispatcher() takes 1 positional argument but 2 were given
```
But your example looks right to me with `np.hstack((lon, lat))`.

Additionally, to see the tracks you should update the color_list variable because it currently has 0 alpha, meaning it will be hidden. `color_list = [(0, 0, 0, 1)]`.

I'm going to close as I don't think there is anything wrong here.
