### ISSUE TITLE
Pip not installing the latest version of Cartopy

### ISSUE THREAD

**Issue by Quba1** [SciTools/cartopy#2053]
### Description
When trying to install Cartopy with pip, it fails to install the latest version because there is a mismatch between cartopy and metadata version. Because of that, pip fails to install the latest cartopy version and falls back to version 18, which installation fails because of incompatible proj version (as described in #2047).

The installation messages look like this:

```
$ pip install --user --upgrade cartopy
Collecting cartopy
  Using cached Cartopy-0.20.2.tar.gz (10.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Discarding https://files.pythonhosted.org/packages/f6/55/1e1c737dc9436b320deead73d1c455ddbb74b8b6992081863492f6f6378a/Cartopy-0.20.2.tar.gz#sha256=4d08c198ecaa50a6a6b109d0f14c070e813defc046a83ac5d7ab494f85599e35 (from https://pypi.org/simple/cartopy/) (requires-python:>=3.7): Requested cartopy from https://files.pythonhosted.org/packages/f6/55/1e1c737dc9436b320deead73d1c455ddbb74b8b6992081863492f6f6378a/Cartopy-0.20.2.tar.gz#sha256=4d08c198ecaa50a6a6b109d0f14c070e813defc046a83ac5d7ab494f85599e35 has inconsistent version: filename has '0.20.2', but metadata has '0.0'
  Using cached Cartopy-0.20.1.tar.gz (10.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Discarding https://files.pythonhosted.org/packages/fc/59/aa52698e3838f4cd0e7eaa75bd86837e9e0b05041dbdaee3cda2fffced06/Cartopy-0.20.1.tar.gz#sha256=91f87b130e2574547a20cd634498df97d797abd12dcfd0235bc0cdbcec8b05e3 (from https://pypi.org/simple/cartopy/) (requires-python:>=3.7): Requested cartopy from https://files.pythonhosted.org/packages/fc/59/aa52698e3838f4cd0e7eaa75bd86837e9e0b05041dbdaee3cda2fffced06/Cartopy-0.20.1.tar.gz#sha256=91f87b130e2574547a20cd634498df97d797abd12dcfd0235bc0cdbcec8b05e3 has inconsistent version: filename has '0.20.1', but metadata has '0.0'
  Using cached Cartopy-0.20.0.tar.gz (10.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Discarding https://files.pythonhosted.org/packages/0f/c0/58453b036e79046d211f083880d58dcce787e7e07647ac25dc46c6555099/Cartopy-0.20.0.tar.gz#sha256=eae58aff26806e63cf115b2bce9477cedc4aa9f578c5e477b2c25cfa404f2b7a (from https://pypi.org/simple/cartopy/) (requires-python:>=3.7): Requested cartopy from https://files.pythonhosted.org/packages/0f/c0/58453b036e79046d211f083880d58dcce787e7e07647ac25dc46c6555099/Cartopy-0.20.0.tar.gz#sha256=eae58aff26806e63cf115b2bce9477cedc4aa9f578c5e477b2c25cfa404f2b7a has inconsistent version: filename has '0.20.0', but metadata has '0.0'
  Using cached Cartopy-0.19.0.post1.tar.gz (12.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Discarding https://files.pythonhosted.org/packages/ed/ca/524ce33692df3faeaa56852fb6a33b0b410be94cc288417565b96fef3f64/Cartopy-0.19.0.post1.tar.gz#sha256=4b8b4773a98ed7009fe17d9b6ec87ac3ac62b7d14634d7768c190eadc647d576 (from https://pypi.org/simple/cartopy/) (requires-python:>=3.5): Requested cartopy from https://files.pythonhosted.org/packages/ed/ca/524ce33692df3faeaa56852fb6a33b0b410be94cc288417565b96fef3f64/Cartopy-0.19.0.post1.tar.gz#sha256=4b8b4773a98ed7009fe17d9b6ec87ac3ac62b7d14634d7768c190eadc647d576 has inconsistent version: filename has '0.19.0.post1', but metadata has '0.0'
  Using cached Cartopy-0.18.0.tar.gz (14.4 MB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy>=1.10 in /usr/lib/python3/dist-packages (from cartopy) (1.21.5)
Requirement already satisfied: pyshp>=1.1.4 in ./.local/lib/python3.10/site-packages (from cartopy) (2.3.0)
Requirement already satisfied: setuptools>=0.7.2 in /usr/lib/python3/dist-packages (from cartopy) (59.6.0)
Requirement already satisfied: shapely>=1.5.6 in ./.local/lib/python3.10/site-packages (from cartopy) (1.8.2)
Requirement already satisfied: six>=1.3.0 in /usr/lib/python3/dist-packages (from cartopy) (1.16.0)
Building wheels for collected packages: cartopy
  Building wheel for cartopy (setup.py) ... error

```

I finally managed to install the latest version as suggested by [this SO post](https://stackoverflow.com/a/68126941/10605194). with

```
pip install --upgrade --no-cache-dir --use-deprecated=legacy-resolver --user cartopy
```

But obviously this is just a workaround.

### System configuration

Ubuntu 22.04
Python 3.10.5
pip 22.0.2

**Comment by jules-ch** [comment]
I'm having this issue aswell

**Comment by janpieter-vanparys** [comment]
I think I have the same error
`Step 11/28 : RUN venv/bin/python -m pip install pykdtree scipy cartopy==0.19.0.post1
 ---> Running in 1fc52fdeb493
Collecting pykdtree
  Downloading pykdtree-1.3.5-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (264 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 264.8/264.8 kB 1.8 MB/s eta 0:00:00
Collecting scipy
  Downloading scipy-1.8.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (42.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.2/42.2 MB 2.2 MB/s eta 0:00:00
Collecting cartopy==0.19.0.post1
  Downloading Cartopy-0.19.0.post1.tar.gz (12.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.1/12.1 MB 29.3 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
  WARNING: Requested cartopy==0.19.0.post1 from https://files.pythonhosted.org/packages/ed/ca/524ce33692df3faeaa56852fb6a33b0b410be94cc288417565b96fef3f64/Cartopy-0.19.0.post1.tar.gz#sha256=4b8b4773a98ed7009fe17d9b6ec87ac3ac62b7d14634d7768c190eadc647d576, but installing version 0.0
Discarding https://files.pythonhosted.org/packages/ed/ca/524ce33692df3faeaa56852fb6a33b0b410be94cc288417565b96fef3f64/Cartopy-0.19.0.post1.tar.gz#sha256=4b8b4773a98ed7009fe17d9b6ec87ac3ac62b7d14634d7768c190eadc647d576 (from https://pypi.org/simple/cartopy/) (requires-python:>=3.5): Requested cartopy==0.19.0.post1 from https://files.pythonhosted.org/packages/ed/ca/524ce33692df3faeaa56852fb6a33b0b410be94cc288417565b96fef3f64/Cartopy-0.19.0.post1.tar.gz#sha256=4b8b4773a98ed7009fe17d9b6ec87ac3ac62b7d14634d7768c190eadc647d576 has inconsistent version: filename has '0.19.0.post1', but metadata has '0.0'
ERROR: Could not find a version that satisfies the requirement cartopy==0.19.0.post1 (from versions: 0.11.0, 0.12.0.4, 0.12.0.5, 0.13.0, 0.13.1, 0.14.0, 0.14.2, 0.15.1, 0.16.0, 0.17.0, 0.18.0b1, 0.18.0b2, 0.18.0rc1, 0.18.0, 0.19.0rc1, 0.19.0.post1, 0.20.0, 0.20.1, 0.20.2)
ERROR: No matching distribution found for cartopy==0.19.0.post1
ERROR: Service 'quick-frontend' failed to build: The command '/bin/sh -c venv/bin/python -m pip install pykdtree scipy cartopy==0.19.0.post1' returned a non-zero code: 1`

**Comment by zachsa** [comment]
Hi - following on from the linked thread (pypa/pipenv), is there a reason that updating the `pip` version would result in this?

**Comment by Quba1** [comment]
@zachsa from what I read the issue is that the new resolver is more strict, and I suspect cartopy developers just missed setting a correct version somewhere.

**Comment by matteius** [comment]
I am not sure on the time-frame when this became an issue for you, but I notice some recent setuptools releases that may have affected things, because pip will pull in the latest setuptools.  https://pypi.org/project/setuptools/#history
From what I can tell, there is no version specified in the cartopy setup.py or setup.cfg or anywhere I thought to look in the project space, and that too seems like related to the issue.

**Comment by pffijt** [comment]
This is also happening to my team with cartopy==0.19.0.post1 and latest stable pip version. We used `--use-deprecated=legacy-resolver` as a temporary work around.

**Comment by greglucas** [comment]
I think this has something to do with the git folder not being present and setuptools_scm not being able to get the tagged version to replace somewhere along the line, yet it is present in other places of the build system, so some sort of miscommunication. Another workaround when installing from the downloaded sdist:
`SETUPTOOLS_SCM_PRETEND_VERSION="$(python3 setup.py --version)" pip install .`

My guess is this is an "easy" fix for someone with knowledge of setuptools_scm / build machinery here.

**Comment by jules-ch** [comment]
I suspect we need to add `"setuptools_scm[toml]>=6.2"` with toml support since it fails after adding support for PEP517/518.

**Comment by greglucas** [comment]
Thanks @jules-ch, are you willing to open up a PR removing that and updating the pins?
It does look like the git-archival.txt and that dependency should be removed because it is natively supported by setuptools_scm: https://github.com/Changaco/setuptools_scm_git_archive

**Comment by dopplershift** [comment]
We should be able to make a 0.20.2.post1 if we get that in.

**Comment by dopplershift** [comment]
I went ahead and made a PR with @jules-ch' s fix so we can try to get this out there ASAP. Thanks for identifying @jules-ch!

**Comment by greglucas** [comment]
I was able to `pip install --upgrade cartopy` and get v0.20.3 now. Thanks, @jules-ch and @dopplershift for figuring out the fix and getting a release out so quickly.

**Comment by rbaard1** [comment]
Unfortunately I am still getting the same  error with Cartopy v0.21.0: `expected '0.21.0', but metadata has '0.0.0'`. Should I open a new issue for this?

macOS 12.6
pip v22.3.1
Python 3.10.8

**Comment by dopplershift** [comment]
@rbaard1 Please open a new issue and include the full command you're using to install Cartopy as well as the full output from running that command.
