### ISSUE TITLE
Getting error Proj version 0.0.0 is installed, but cartopy requires at least version 8.0.0 (while trying to install cartopy)

### ISSUE THREAD

**Issue by Barokirving1** [SciTools/cartopy#2063]
### Description
Hello, I was trying to install cartopy so that I can import and use it on jupyter notebook and I am using a windows computer. However, when I try to install it using pip the following error comes. Can anyone please help me to find the best solution to solve this error? Thanks for your help.

#1981 

</details>

C:\Users\barok> pip install cartopy
Collecting cartopy
  Using cached Cartopy-0.20.3.tar.gz (10.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\barok\miniconda3\python.exe' 'C:\Users\barok\miniconda3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' get_requires_for_build_wheel 'C:\Users\barok\AppData\Local\Temp\tmpr6c28j1_'
       cwd: C:\Users\barok\AppData\Local\Temp\pip-install-abtwr2_1\cartopy_61ba9a4cccce421bbb67eada722140b7
  Complete output (3 lines):
  <string>:117: UserWarning: Unable to determine GEOS version. Ensure you have 3.7.2 or later installed, or installation may fail.
  <string>:166: UserWarning: Unable to determine Proj version. Ensure you have 8.0.0 or later installed, or installation may fail.
  Proj version 0.0.0 is installed, but cartopy requires at least version 8.0.0.
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/98/a9/0e4000eabadfcff6373c0fec790863b543b919cbfec18aed60d71ba67d5d/Cartopy-0.20.3.tar.gz#sha256=0d60fa2e2fbd77c4d1f6b1f9d3b588966147f07c1b179d2d34570ac1e1b49006 (from https://pypi.org/simple/cartopy/) (requires-python:>=3.7). Command errored out with exit status 1: 'C:\Users\barok\miniconda3\python.exe' 'C:\Users\barok\miniconda3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' get_requires_for_build_wheel 'C:\Users\barok\AppData\Local\Temp\tmpr6c28j1_' Check the logs for full command output.
  Using cached Cartopy-0.20.2.tar.gz (10.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\barok\miniconda3\python.exe' 'C:\Users\barok\miniconda3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' get_requires_for_build_wheel 'C:\Users\barok\AppData\Local\Temp\tmp76fblfvu'
       cwd: C:\Users\barok\AppData\Local\Temp\pip-install-abtwr2_1\cartopy_72929b0ca95c4775aa3c63cacbbd652e
  Complete output (3 lines):
  <string>:117: UserWarning: Unable to determine GEOS version. Ensure you have 3.7.2 or later installed, or installation may fail.
  <string>:166: UserWarning: Unable to determine Proj version. Ensure you have 8.0.0 or later installed, or installation may fail.
  Proj version 0.0.0 is installed, but cartopy requires at least version 8.0.0.
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/0f/c0/58453b036e79046d211f083880d58dcce787e7e07647ac25dc46c6555099/Cartopy-0.20.0.tar.gz#sha256=eae58aff26806e63cf115b2bce9477cedc4aa9f578c5e477b2c25cfa404f2b7a (from https://pypi.org/simple/cartopy/) (requires-python:>=3.7). Command errored out with exit status 1: 'C:\Users\barok\miniconda3\python.exe' 'C:\Users\barok\miniconda3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' get_requires_for_build_wheel 'C:\Users\barok\AppData\Local\Temp\tmpcc19xy_c' Check the logs for full command output.
  Using cached Cartopy-0.19.0.post1.tar.gz (12.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\barok\miniconda3\python.exe' 'C:\Users\barok\miniconda3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' get_requires_for_build_wheel 'C:\Users\barok\AppData\Local\Temp\tmp606auhag'
       cwd: C:\Users\barok\AppData\Local\Temp\pip-install-abtwr2_1\cartopy_ccec1e993dd44c0d80035dacf2c46fd4
  Complete output (3 lines):
  <string>:117: UserWarning: Unable to determine GEOS version. Ensure you have 3.3.3 or later installed, or installation may fail.
  <string>:166: UserWarning: Unable to determine Proj version. Ensure you have 4.9.0 or later installed, or installation may fail.
  Proj version 0.0.0 is installed, but cartopy requires at least version 4.9.0.
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/ed/ca/524ce33692df3faeaa56852fb6a33b0b410be94cc288417565b96fef3f64/Cartopy-0.19.0.post1.tar.gz#sha256=4b8b4773a98ed7009fe17d9b6ec87ac3ac62b7d14634d7768c190eadc647d576 (from https://pypi.org/simple/cartopy/) (requires-python:>=3.5). Command errored out with exit status 1: 'C:\Users\barok\miniconda3\python.exe' 'C:\Users\barok\miniconda3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' get_requires_for_build_wheel 'C:\Users\barok\AppData\Local\Temp\tmp606auhag' Check the logs for full command output.
  Using cached Cartopy-0.18.0.tar.gz (14.4 MB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\barok\miniconda3\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\barok\\AppData\\Local\\Temp\\pip-install-abtwr2_1\\cartopy_f1e5d9d6f39f4a9caa97e7cc6d1c0c2e\\setup.py'"'"'; __file__='"'"'C:\\Users\\barok\\AppData\\Local\\Temp\\pip-install-abtwr2_1\\cartopy_f1e5d9d6f39f4a9caa97e7cc6d1c0c2e\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\barok\AppData\Local\Temp\pip-pip-egg-info-hwuvi3le'
         cwd: C:\Users\barok\AppData\Local\Temp\pip-install-abtwr2_1\cartopy_f1e5d9d6f39f4a9caa97e7cc6d1c0c2e\
    Complete output (5 lines):
    C:\Users\barok\AppData\Local\Temp\pip-install-abtwr2_1\cartopy_f1e5d9d6f39f4a9caa97e7cc6d1c0c2e\setup.py:104: UserWarning: **Unable to determine GEOS version**. Ensure you have 3.3.3 or later installed, or installation may fail.
      warnings.warn(
    C:\Users\barok\AppData\Local\Temp\pip-install-abtwr2_1\cartopy_f1e5d9d6f39f4a9caa97e7cc6d1c0c2e\setup.py:157: UserWarning: Unable to determine Proj version. Ensure you have 4.9.0 or later installed, or installation may fail.
      warnings.warn(
    **Proj version 0.0.0 is installed**, but cartopy requires at least version 4.9.0.

PS C:\Users\barok> pip show proj
Name: proj
Version: 0.2.0
PS C:\Users\barok> pip show geos
Name: geos
Version: 0.2.3

**Comment by QuLogic** [comment]
Proj and GEOS are C libraries, not the Python `proj`/`geos` you installed.

Is there a reason you aren't using `conda` to install a pre-build Cartopy?

**Comment by Barokirving1** [comment]
> 

Thank you so much for replying. I have also tried to use conda to install Cartopy. 
C:\Users\barok>conda install -c conda-forge cartopy. Then it was installed properly without error. However, when I type:

`import cartopy.crs as ccrs` and 
`from cartopy.mpl.ticker import LongitudeFormatter, LatitudeFormatter` 
 
I will get an error **ModuleNotFoundError: No module named 'cartopy.crs' and ModuleNotFoundError: No module named 'cartopy.mpl'.** Thus, when I get this error I thought this happened because cartopy was not installed properly using conda, and I should use another method. All I am trying to do is import the above and I ended up using pip in case it is better. Can you please tell me if there is any other way to solve this problem? Thank you so much for your help. Much appreciated!

**Comment by QuLogic** [comment]
> (base) C:\Users\barok>conda install -c conda-forge cartopy

You should avoid messing with the base environment and create a new one in which you install everything you need in a self-contained manner.

**Comment by greglucas** [comment]
There is no longer a direct PROJ dependency check with v0.21 that was just released, so that error shouldn't happen anymore. For conda something like this should work to make sure that jupyter and cartopy are using the same python kernels by default:
```bash
conda create -n test cartopy jupyterlab
conda activate cartopy
jupyterlab
...
```
