### ISSUE TITLE
Pip installation failing with python 3.10

### ISSUE THREAD

**Issue by TimurDela** [SciTools/cartopy#2081]
### Description

Following the instruction, I have installed GEOS, Shapely, and pyshp but when I run
```shell
python3.10 -m pip install cartopy
```
I get the following error:

```shell
Collecting cartopy
  Using cached Cartopy-0.21.0.tar.gz (10.9 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [32 lines of output]
      Traceback (most recent call last):
        File "/home/timur/.local/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/home/timur/.local/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/timur/.local/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 147, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 128, in _get_build_requires
          self.run_setup()
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 143, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 206, in <module>
          setup(
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 143, in setup
          _install_setup_requires(attrs)
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 131, in _install_setup_requires
          dist = distutils.core.Distribution(dict(
        File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 447, in __init__
          _Distribution.__init__(self, {
        File "/usr/lib/python3.10/distutils/dist.py", line 292, in __init__
          self.finalize_options()
        File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 740, in finalize_options
          ep.load()(self)
        File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2444, in load
          self.require(*args, **kwargs)
        File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2467, in require
          items = working_set.resolve(reqs, env, installer, extras=self.extras)
        File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 787, in resolve
          raise DistributionNotFound(req, requirers)
      pkg_resources.DistributionNotFound: The 'importlib-metadata; python_version < "3.8"' distribution was not found and is required by the application
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
```

#### Code to reproduce

```

```

#### Traceback 

```

```

<details>
 <summary>Full environment definition</summary>

### Operating system
Ubuntu 20.04.2 LTS

### Cartopy version
Cartopy-0.21.0

### pip list

Package                      Version
---------------------------- --------------------
apturl                       0.5.2
argcomplete                  1.8.1
bcrypt                       3.1.7
beautifulsoup4               4.8.2
blinker                      1.4
Brlapi                       0.7.0
certifi                      2019.11.28
chardet                      3.0.4
click                        8.1.3
colorama                     0.4.3
command-not-found            0.3
cryptography                 2.8
cupshelpers                  1.0
cycler                       0.11.0
dbus-python                  1.2.16
defer                        1.0.6
distro                       1.4.0
distro-info                  0.23ubuntu1
duplicity                    0.8.12.0
entrypoints                  0.3
fasteners                    0.14.1
feedparser                   5.2.1
Flask                        2.2.2
fonttools                    4.37.1
future                       0.18.2
geos                         0.2.3
html5lib                     1.0.1
httplib2                     0.14.0
idna                         2.8
importlib-metadata           4.12.0
itsdangerous                 2.1.2
Jinja2                       3.1.2
keyring                      18.0.1
kiwisolver                   1.4.4
language-selector            0.1
launchpadlib                 1.10.13
lazr.restfulclient           0.14.2
lazr.uri                     1.0.3
lockfile                     0.12.2
louis                        3.12.0
lxml                         4.5.0
macaroonbakery               1.3.1
Mako                         1.1.0
MarkupSafe                   2.1.1
matplotlib                   3.5.3
meld                         3.20.2
monotonic                    1.5
netifaces                    0.10.4
numpy                        1.23.3
oauthlib                     3.1.0
olefile                      0.46
onboard                      1.4.1
packaging                    21.3
padme                        1.1.1
paramiko                     2.6.0
pexpect                      4.6.0
Pillow                       7.0.0
pip                          22.2.2
progressbar                  2.5
protobuf                     3.6.1
pyasn1                       0.4.2
pycairo                      1.16.2
pycups                       1.9.73
pycurl                       7.43.0.2
PyGObject                    3.36.0
PyJWT                        1.7.1
pymacaroons                  0.13.0
PyNaCl                       1.3.0
pyparsing                    2.4.6
pyproj                       3.4.0
pyRFC3339                    1.1
pyshp                        2.3.1
python-apt                   2.0.0+ubuntu0.20.4.4
python-dateutil              2.7.3
python-debian                0.1.36ubuntu1
python-gnupg                 0.4.5
pytz                         2019.3
pyxdg                        0.26
PyYAML                       5.3.1
reportlab                    3.5.34
requests                     2.22.0
requests-unixsocket          0.2.0
SecretStorage                2.3.1
setuptools                   45.2.0
Shapely                      1.6.4
simplejson                   3.16.0
six                          1.14.0
soupsieve                    1.9.5
ssh-import-id                5.10
system-service               0.3
systemd-python               234
ubuntu-advantage-tools       20.3
ubuntu-drivers-common        0.0.0
Ubuntu-Make                  19.6
ufw                          0.36
unattended-upgrades          0.1
unity-scope-calculator       0.1
unity-scope-devhelp          0.1
unity-scope-firefoxbookmarks 0.1
unity-scope-gdrive           0.7
unity-scope-manpages         0.1
unity-scope-tomboy           0.1
unity-scope-virtualbox       0.1
unity-scope-zotero           0.1
urllib3                      1.25.8
usb-creator                  0.3.7
wadllib                      1.3.3
webencodings                 0.5.1
Werkzeug                     2.2.2
wheel                        0.37.1
xdiagnose                    3.8.9
xkit                         0.0.0
XlsxWriter                   1.1.2
zipp                         3.8.1

</details>

**Comment by greglucas** [comment]
That looks like it is leaving your virtual environment and moving into a global python distribution where it finds `setuptools` and uses that, but from an older Python version. Does it help if you `pip install setuptools cartopy` in that venv?

**Comment by TimurDela** [comment]
Thanks for the advice @greglucas but it had no effect, `setuptools` was already installed. I believe I have some problems with too many python versions installed but Cartopy is the only package that raises this problem.

**Comment by TimurDela** [comment]
After removing all versions of python3 and reinstalling only 3.8, installation works but I still suspect that some dependencies are not very well configured which leads to problems when people have several versions of python3 available.
