### ISSUE TITLE
"import cartopy" give me "ProjError: Error creating Transformer from CRS.~"

### ISSUE THREAD

**Issue by yun881201** [SciTools/cartopy#2085]
I just installed cartopy and try to import, but I got the ProjError as follow:
---------------------------------------------------------------------------
ProjError                                 Traceback (most recent call last)
Input In [637], in <cell line: 1>()
----> 1 import cartopy

File ~\anaconda3\envs\specavail\lib\site-packages\cartopy\__init__.py:107, in <module>
    103     pass
    105 # Commonly used sub-modules. Imported here to provide end-user
    106 # convenience.
--> 107 import cartopy.crs  # noqa: E402  module-level imports
    108 import cartopy.feature

File ~\anaconda3\envs\specavail\lib\site-packages\cartopy\crs.py:1680, in <module>
   1676         return self._y_limits
   1679 # Define a specific instance of a Mercator projection, the Google mercator.
-> 1680 Mercator.GOOGLE = Mercator(min_latitude=-85.0511287798066,
   1681                            max_latitude=85.0511287798066,
   1682                            globe=Globe(ellipse=None,
   1683                                        semimajor_axis=WGS84_SEMIMAJOR_AXIS,
   1684                                        semiminor_axis=WGS84_SEMIMAJOR_AXIS,
   1685                                        nadgrids='@null'))
   1686 # Deprecated form
   1687 GOOGLE_MERCATOR = Mercator.GOOGLE

File ~\anaconda3\envs\specavail\lib\site-packages\cartopy\crs.py:1641, in Mercator.__init__(self, central_longitude, min_latitude, max_latitude, globe, latitude_true_scale, false_easting, false_northing, scale_factor)
   1639 # Calculate limits.
   1640 minlon, maxlon = self._determine_longitude_bounds(central_longitude)
-> 1641 limits = self.transform_points(self.as_geodetic(),
   1642                                np.array([minlon, maxlon]),
   1643                                np.array([min_latitude, max_latitude]))
   1644 self._x_limits = tuple(limits[..., 0])
   1645 self._y_limits = tuple(limits[..., 1])

File ~\anaconda3\envs\specavail\lib\site-packages\cartopy\crs.py:408, in CRS.transform_points(self, src_crs, x, y, z, trap)
    405     x[to_180] = (((x[to_180] + 180) % 360) - 180)
    406 try:
    407     result[:, 0], result[:, 1], result[:, 2] = \
--> 408         _safe_pj_transform(src_crs, self, x, y, z, trap=trap)
    409 except ProjError as err:
    410     msg = str(err).lower()

File ~\anaconda3\envs\specavail\lib\site-packages\cartopy\crs.py:49, in _safe_pj_transform(src_crs, tgt_crs, x, y, z, trap)
     48 def _safe_pj_transform(src_crs, tgt_crs, x, y, z=None, trap=True):
---> 49     transformer = _get_transformer_from_crs(src_crs, tgt_crs)
     51     # if a projection is essentially 2d there
     52     # should be no harm in setting its z to 0
     53     if z is None:

File ~\anaconda3\envs\specavail\lib\site-packages\cartopy\crs.py:45, in _get_transformer_from_crs(src_crs, tgt_crs)
     43 @lru_cache
     44 def _get_transformer_from_crs(src_crs, tgt_crs):
---> 45     return Transformer.from_crs(src_crs, tgt_crs, always_xy=True)

File ~\anaconda3\envs\specavail\lib\site-packages\pyproj\transformer.py:310, in from_crs(crs_from, crs_to, skip_equivalent, always_xy, area_of_interest)
    302 class Transformer:
    303     """
    304     The Transformer class is for facilitating re-using
    305     transforms without needing to re-create them. The goal
    306     is to make repeated transforms faster.
    307 
    308     Additionally, it provides multiple methods for initialization.
    309 
--> 310     .. versionadded:: 2.1.0
    311 
    312     """
    314     def __init__(
    315         self,
    316         transformer_maker: Union[TransformerMaker, None] = None,
    317     ) -> None:
    318         if not isinstance(transformer_maker, TransformerMaker):

File pyproj/_transformer.pyx:319, in pyproj._transformer._Transformer.from_crs()

ProjError: Error creating Transformer from CRS.: (Internal Proj Error: proj_create_operations: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name)
-----------------------------------------

Would you help me?

**Comment by dopplershift** [comment]
What versions of Cartopy and pyproj do you have installed? (You can check that with `conda list pyproj` and `conda list cartopy`). On first glance, this looks like a pyproj problem.

**Comment by yun881201** [comment]
> What versions of Cartopy and pyproj do you have installed? (You can check that with `conda list pyproj` and `conda list cartopy`). On first glance, this looks like a pyproj problem.

Thank you for your answer. 
After writing issue post, I created new env, and installed related library one by one. Now , I can import cartopy. Thank you very much.
