### ISSUE TITLE
cartopy crashes with 0.21.0

### ISSUE THREAD

**Issue by PBrockmann** [SciTools/cartopy#2088]
Hi,

The simplest cartopy script crashes when cartopy is installed at 0.21.0 release
with a pip install cartopy==0.21.0

```
import cartopy.crs as ccrs
import matplotlib.pyplot as plt
ax = plt.axes(projection=ccrs.PlateCarree())
ax.coastlines()
plt.show()
```
produces a core.

Concerned installed modules are:
```
python                    3.9.13
matplotlib                3.6.0
Cartopy                   0.21.0
```

**Comment by dopplershift** [comment]
Try re-installing Shapely: `pip install --force-reinstall --no-binary shapely shapely` (yes, repeat `shapely`).

**Comment by PBrockmann** [comment]
Indeed. It has solved the problem.
Thanks
