### ISSUE TITLE
ImportError: DLL load failed: 

### ISSUE THREAD

**Issue by gaonan0902** [SciTools/cartopy#2095]
Traceback (most recent call last):
  File "E:/PROGRAM/Shaylee/coupled_network_causal_of_LAI.py", line 18, in <module>
    import cartopy.crs as ccrs
  File "E:\APP\PYTHON\lib\site-packages\cartopy\__init__.py", line 110, in <module>
    import cartopy.crs
  File "E:\APP\PYTHON\lib\site-packages\cartopy\crs.py", line 27, in <module>
    import cartopy.trace
ImportError: DLL load failed: 找不到指定的模块。
I'm very confused about this question. Python 3.7

**Comment by dopplershift** [comment]
According to Google translate, that says "The specified module could not be found.". I'm guessing something is up with your Python environment. My first guess is to reinstall shapely:
```
pip install shapely --force-reinstall --no-binary shapely
```
If that doesn't fix it, I'd suggest reinstalling your entire Python environment.

**Comment by gaonan0902** [comment]
> According to Google translate, that says "The specified module could not be found.". I'm guessing something is up with your Python environment. My first guess is to reinstall shapely:

Thank you for your kindness!

**Comment by dopplershift** [comment]
If you're still having problems, feel free to re-open.
