### ISSUE TITLE
Cartopy did not work with the previous installation 

### ISSUE THREAD

**Issue by yangyang-studio** [SciTools/cartopy#2098]
![mmexport1667699401273](https://user-images.githubusercontent.com/84533790/200150378-5411572e-9d62-45f9-b583-631d16072608.png)
![mmexport1667699405702](https://user-images.githubusercontent.com/84533790/200150384-e237874f-88a4-4b35-a96b-3cf009214417.png)
Operating platform: WINDOW10 
Version number: 0.18.0

**Comment by dopplershift** [comment]
Please upgrade to CartoPy 0.21 which should solve the _`autoscaleXon` issue.

**Comment by yangyang-studio** [comment]
![mmexport1667930216553](https://user-images.githubusercontent.com/84533790/200640373-660d6f0f-2a98-4594-ab4d-6fc6a06518c4.png)
![mmexport1667930221180](https://user-images.githubusercontent.com/84533790/200640394-df901b04-923d-4711-8572-1ef6b83ece97.png)
Unable to install

**Comment by dopplershift** [comment]
Yes, that's expected based on the line:

> Unable to determine GEOS version. Ensure you have 3.7.2 or later installed, or installation may fail.

Did you install the GEOS library?

I know installing GEOS on Windows can be challenging, which is why we usually recommend installing [using Conda](https://scitools.org.uk/cartopy/docs/latest/installing.html#conda-pre-built-binaries) for Windows users.

**Comment by yangyang-studio** [comment]
![mmexport1667956538319](https://user-images.githubusercontent.com/84533790/200712530-83a19ce7-1eb9-43f7-875e-94bc841e1907.png)
![mmexport1667956542224](https://user-images.githubusercontent.com/84533790/200712533-aaaa0fb7-0fa8-4f8c-9901-e56bf6c54fb7.png)
![mmexport1667956545450](https://user-images.githubusercontent.com/84533790/200712538-ac611535-5b55-43dd-8f30-d83567063cd2.png)
![mmexport1667956550037](https://user-images.githubusercontent.com/84533790/200712542-8e736752-4346-4a4f-90da-f108c34edcd3.png)
GESO has been installed, but carcopy still cannot be installed

**Comment by QuLogic** [comment]
That's an unrelated Python package (Google Earth Overlay Server). GEOS (Geometry Engine - Open Source) is a C++ package that cannot be installed with `pip`. That's why we say you should install it with `conda`.

Also, your prompt shows you are working in the `(base)` environment. That is generally dangerous; it would be better to create a separate conda environment for experimenting.

**Comment by dopplershift** [comment]
Also, if you have conda, go ahead and use conda to install cartopy and don't use `pip`.

**Comment by greglucas** [comment]
We have just released v0.22 which should help with the compatibility between packages and installation much easier. Please open a new issue if you are still having problems.
