### ISSUE TITLE
Mac Deprecation warning

### ISSUE THREAD

**Issue by jzstoller** [SciTools/cartopy#2101]
The [mac installation instructions](https://scitools.org.uk/cartopy/docs/latest/installing.html#macos) still work well but throw a deprecation warning on this step:
pip3 install "shapely<2" --no-binary shapely

The warning is:
DEPRECATION: --no-binary currently disables reading from the cache of locally built wheels. In the future --no-binary will not influence the wheel cache. pip 23.1 will enforce this behaviour change. A possible replacement is to use the --no-cache-dir option. You can use the flag --use-feature=no-binary-enable-wheel-cache to test the upcoming behaviour. Discussion can be found at https://github.com/pypa/pip/issues/11453

**Comment by dopplershift** [comment]
Hopefully #2083 will land well before that deprecation becomes a problem and we won't care about how Shapely is installed any more.

**Comment by greglucas** [comment]
We have just released v0.22 which should help with the compatibility between packages and installation much easier. Please open a new issue if you are still having problems.
