### ISSUE TITLE
Unexpected behaviour when transforming to display units and figure-inches

### ISSUE THREAD

**Issue by rbaard1** [SciTools/cartopy#2107]
### Description

I am trying to create a figure in Matplotlib, where I want to place an object at a specific position in inches ('figure-inches'), relative to a corner of the GeoAxes. To do this, I first get the position of the corner in data coordinates, then transform the coordinates to figure-inches, move it in figure-inches, transform it back into data coordinates and plot it. However, this does not give the expected result, see images below. For comparison, I also recreated this scenario with a regular Axes object, and there it works as expected (set `geo = False` in the code below to reproduce).

**With GeoAxes:** the displacement (see blue dot) is not what I had expected it to be, and the purple dot (which is supposed to be in the corner on top of the red one) does not show up. Even more interesting, the blue and orange dots don't overlap, even though they should be.
![cartopy-issue-geo](https://user-images.githubusercontent.com/116029928/204916902-8ce021b4-913a-4e14-8030-08053005fc7f.png)

**With regular `matplotlib.axes`:**  there is a purple dot on top of the red one. The orange and blue dot overlap, and are at 45 degrees relative to the top-left corner, which is what I was trying to achieve.
![cartopy-issue](https://user-images.githubusercontent.com/116029928/204916891-ac43ffc1-466a-4a5f-98a3-7465c0be806e.png)

I am not sure if I misunderstood something about the transforms, but this feels like a bug to me. Unfortunately I am unable to pinpoint exactly where in the process it goes wrong. One possible hint to understanding what happens is to note that the printed values of the positions are the same, whether using `geo = True` or `geo = False`. Is it possible that `ax.transData` does not work properly when using GeoAxes and `set_extent`?

#### Code to reproduce

```python
import numpy as np
import matplotlib
from matplotlib import pyplot as plt
from cartopy import crs as ccrs

geo = True
print(f'{geo=}')

if geo:
	ax = plt.axes(projection=ccrs.PlateCarree())
	ax.set_extent((0, 5, 50, 53), crs=ccrs.PlateCarree())
	(x0, x1, y0, y1) = ax.get_extent()
	ax.coastlines()

else:
	ax = plt.axes()
	x0, x1, y0, y1 = (0, 5, 50, 53)
	ax.set_xlim(x0, x1)
	ax.set_ylim(y0, y1)

fig = ax.get_figure()

# Start with data coordinates
top_left = (x0, y1)
# Convert to display units
top_left_display = ax.transData.transform_point(top_left)
# Convert to figure-inches
top_left_figure_inches = fig.dpi_scale_trans.inverted().transform_point(top_left_display)
# Adjust in figure-inches
top_left_adjusted_figure_inches = top_left_figure_inches + np.array([1, -1])
# Convert back to data coordinates
top_left_adjusted = (fig.dpi_scale_trans + ax.transData.inverted()).transform_point(top_left_adjusted_figure_inches)

print(f'{top_left=}')
print(f'{top_left_display=}')
print(f'{top_left_figure_inches=}')
print(f'{top_left_adjusted_figure_inches=}')
print(f'{top_left_adjusted=}')
print()

ax.scatter(*top_left, color='red', s=1000)
ax.scatter(*top_left_figure_inches, transform=fig.dpi_scale_trans, color='purple', s=100)
ax.scatter(*top_left_adjusted_figure_inches, transform=fig.dpi_scale_trans, color='blue', s=100)
ax.scatter(*top_left_adjusted, color='orange', s=20)

plt.show()
```

#### Console output 

```python
geo=True
top_left=(0.0, 53.0)
top_left_display=array([160. , 844.8])
top_left_figure_inches=array([0.8  , 4.224])
top_left_adjusted_figure_inches=array([1.8  , 3.224])
top_left_adjusted=array([ 1.00806452, 52.18831169])
```

<details>
 <summary>Full environment definition</summary>

### Operating system
macOS 12.6, M1 Pro chip

### Cartopy version
0.21.0 (shows up as `0.0.0` in `pip list` but that is due to the workaround for [this issue](https://github.com/SciTools/cartopy/issues/2053)

### pip list

```
Package         Version
--------------- -----------
attrs           22.1.0
Cartopy         0.0.0
certifi         2022.9.24
click           8.1.3
click-plugins   1.1.1
cligj           0.7.2
compact-json    1.1.3
contourpy       1.0.5
cycler          0.11.0
et-xmlfile      1.1.0
Fiona           1.8.22
fonttools       4.37.4
GDAL            3.5.3
geopandas       0.11.1
kiwisolver      1.4.4
matplotlib      3.6.1
more-itertools  9.0.0
munch           2.5.0
networkx        2.8.7
numbers-parser  3.7.0
numpy           1.23.4
openpyxl        3.0.10
packaging       21.3
pandas          1.5.0
Pillow          9.2.0
pip             22.3.1
protobuf        4.21.8
pyparsing       3.0.9
pyproj          3.4.0
PyQt6           6.4.0
PyQt6-Qt6       6.4.1
PyQt6-sip       13.4.0
pyshp           2.3.1
python-dateutil 2.8.2
python-snappy   0.6.1
pytz            2022.4
regex           2022.9.13
roman           3.3
scipy           1.9.3
setuptools      65.4.1
Shapely         1.8.5.post1
six             1.16.0
wheel           0.37.1
```

</details>

**Comment by rbaard1** [comment]
Thanks so much for the quick response, and yes, it works now! Thanks, this was driving me nuts. Really happy that the solution is so simple.

For my understanding: when do you need to do such a draw, and why don't you need to perform one when you use `set_xlim` or `set_ylim`? Would it make sense to perform such a draw by default after using `set_extent`, or is it possibly computationally expensive?

**Comment by greglucas** [comment]
`fig.draw_without_rendering()` can definitely be computationally expensive which is why it isn't done until absolutely needed in the general case. Unfortunately, I don't have a great answer for when you need to call this or not. But generally it is whenever you've updated/changed some transform (which GeoAxes is doing under the hood) from the previous iteration. 

Another case this crops up in outside of Cartopy is if you use tight/constrained layout on the plots where there is some moving around of axes and therefore the data points on the screen. So, you need to make sure you walk the draw-tree before getting the coordinates in that case too.
