### ISSUE TITLE
patch filling uncorrect

### ISSUE THREAD

**Issue by PBrockmann** [SciTools/cartopy#2111]
I have noticed that patches are not filled properly. I need this structure because patches can describe polygons with holes.
When you use fill method it is correct but only the exterior of the polygon can be plotted.

![image](https://user-images.githubusercontent.com/5402758/206414310-20b21372-4366-4a5e-89db-766c92920fa4.png)

![image](https://user-images.githubusercontent.com/5402758/206414096-87ff4b3c-20e9-4190-a3aa-1b8a232bf8e5.png)

In red the patch filled uncorrectly.
In blue the polygon filled (only exteriors with no holes).

Here is a simplified test:

```
import matplotlib.pyplot as plt
from matplotlib.path import Path
from matplotlib.patches import PathPatch
from shapely.geometry import Polygon
import cartopy.crs as ccrs

#-----------------------------------------
def polygon2patch(poly, **kwargs):
    path = Path.make_compound_path(
           Path(poly.exterior.coords),
           *[Path(ring.coords) for ring in poly.interiors])
    patch = PathPatch(path, **kwargs)
    return patch

#-----------------------------------------
fig = plt.figure(figsize=(10,5))

map_proj = ccrs.Orthographic(-80, 50)
map_proj._threshold /= 100.  # the default values is bad, users need to set them manually
ax = fig.add_subplot(1, 1, 1, projection=map_proj)

transform = ccrs.Geodetic()

p1 =  Polygon([(20, 20), (80, 20), (100,70), (10, 70)])
p2 =  Polygon([(40, 25), (40, 30), (45, 30), (45, 25)])
p3 =  Polygon([(50, 35), (50, 40), (55, 40)])
polygon = Polygon(p1.exterior.coords, holes=[p2.exterior.coords, p3.exterior.coords])

x = polygon.exterior.coords.xy[0]
y = polygon.exterior.coords.xy[1]
ax.fill(x, y, transform=transform, color="blue", lw=0.5, edgecolor="black", alpha=0.5)

patch = polygon2patch(polygon, transform=transform, facecolor="red", lw=0.5, edgecolor="black")
ax.add_patch(patch)

ax.set_global()
ax.gridlines()
plt.show()
```

Tested with cartopy 0.21.0
Issue relative to https://stackoverflow.com/questions/74710358/how-to-detect-inner-polygons-from-a-multipolygon-shapely-object

**Comment by greglucas** [comment]
Probably an issue with the handling of `is_ccw` within project_polygon:
https://github.com/SciTools/cartopy/blob/4f61922426b2981638f0ce399615c9c57723afeb/lib/cartopy/crs.py#L938-L944
I'm not sure why Geodetic is handled differently with `is_ccw = True` rather than getting it from the Polygon directly...

**Comment by PBrockmann** [comment]
I have investigated more on this problem.
I have found that I need to create closed path with ```Path(poly.exterior.coords, closed=True)```
Then it works better. All polygons are correctly filled.

Except some that are folded despite the use of ```shapely.geometry.polygon.orient```.

I have defined a new test case that puzzles me.

```
import cartopy.crs as ccrs
import matplotlib.pyplot as plt
import matplotlib.patches
import numpy as np

fig = plt.figure(figsize=(10,5))

map_proj = ccrs.Robinson(10)
ax = fig.add_subplot(1, 1, 1, projection=map_proj)

ax.set_global()
ax.gridlines()

transform = ccrs.PlateCarree()

poly =  np.array([
    [-70,  10],
    [-60,  10],
    [-60,  20],
    [-70,  20],
    [-81,  20],
    [-80,  30],
    [-70,  30],
    [-70,  20],
    [-70,  10]
])
polyCode = np.array([ 1, 2, 2, 2, 2, 2, 2, 2, 79])
path =  matplotlib.path.Path(poly, polyCode)

patch = matplotlib.patches.PathPatch(path, facecolor='red', edgecolor='black', transform=transform)
ax.add_patch(patch)

#ax.fill(poly[:,0], poly[:,1], color='blue', edgecolor='black', alpha=0.4, transform=transform)

plt.show()
```

![image](https://user-images.githubusercontent.com/5402758/210416530-4655fc2c-f968-413a-84e8-6f771c4d8f3c.png)
 
but changing the center of the projection ``` ccrs.Robinson(100)``` gives

![image](https://user-images.githubusercontent.com/5402758/210416752-d6b206e6-335c-4ce4-a147-9a2c8f37b832.png)

That because the polygon is not fully oriented counter-clockwise. It is folded.

So my question is how to handle those cases ?

**Comment by greglucas** [comment]
The examples seem to work now with the latest release, so closing. Feel free to reopen and include another example if this isn't fixed yet.
