### ISSUE TITLE
Inquiry about confliction error between cartopy and wrf-python due to Numpy

### ISSUE THREAD

**Issue by chochon** [SciTools/cartopy#2117]
### Description

I didn't install the conda program.
I just tried to install cartopy on Windows cmd (windows + R) using wheel file from the following link.
[https://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy](url)
F.Y.I, python version is 3.9.12.

I also downloaded for wrf_python‑1.3.4.1‑cp39‑cp39‑win_amd64.whl and numpy‑1.22.4+mkl‑cp39‑cp39‑win_amd64.whl and installed from above website.

Now, I succeed to install wrf-python and numpy‑1.22.4+mkl and then python can import the wrf module. However,  my problem that the wrf-python module can not be imported when installing cartopy (Cartopy-0.20.2-cp39-cp39-win_amd64.whl).
I think those are conflicted because of numpy.
wrf-python required numpy-1.22.4+mkl but cartopy requires numpy-1.23.5 version.
I want to use both module at same time. How can I solve this problem?

**Comment by dopplershift** [comment]
Unfortunately, we don't control that site, so I have no idea how the wheels there were built and why there might be a conflict. As such, we can't really offer much support for those wheels--especially when it comes to environment issues. It seems odd, though, that their cartopy package would need numpy 1.23.5 when there are no wheels for that version on that page.

Warning: It is also my understanding that the collection of wheels of is no longer being maintained. (The title says "Archived: Unofficial Windows..."). For instance, the latest numpy there (1.22.4) is out of date by 7 months. You may want to consider using Anaconda/miniconda and using the builds from conda-forge. Support for the conda-forge cartopy packages can then be done over at [their feedstock](https://github.com/conda-forge/cartopy-feedstock).
