### ISSUE TITLE
why not conda default? 

### ISSUE THREAD

**Issue by SpacelySpaceSprockets** [SciTools/cartopy#2119]
Not so much an issue as a question.  

There are businesses and government agencies that currently can't use conda-forge (or can't easily use it) due to security issues.  I don't really know what those issues are, but it's a thing.

So I was just curious why cartopy isn't in the conda default repository. And what would it take to get you to add cartopy to Anaconda default?

**Comment by QuLogic** [comment]
That's not up to us; you should ask the Anaconda people about it.

**Comment by ocefpaf** [comment]
> So I was just curious why cartopy isn't in the conda default repository.

Also, it is: https://anaconda.org/anaconda/cartopy

You can check that with: `conda search --channel defaults cartopy`

**Comment by SpacelySpaceSprockets** [comment]
weird. I have a yml file with cartopy in the installation list and it
didn't find it with just the default channel.  I added conda-forge and it
did.

**Comment by SpacelySpaceSprockets** [comment]
also, that version is a few behind the one on conda-forge, maybe conda
couldn't reconcile the older version
https://anaconda.org/conda-forge/cartopy
