### ISSUE TITLE
 ERROR: Failed building wheel for cartopy

### ISSUE THREAD

**Issue by RoshanPaudyal** [SciTools/cartopy#2124]
### Description

Output exceeds the [size limit](command:workbench.action.openSettings?%5B%22notebook.output.textLineLimit%22%5D). Open the full output data [in a text editor](command:workbench.action.openLargeOutput?af70fc79-d21c-44f1-838c-44c33023a8fd)
Requirement already satisfied: hvplot in c:\users\61415\anaconda3\lib\site-packages (0.8.0)
Collecting geoviews
  Using cached geoviews-1.9.5-py2.py3-none-any.whl (500 kB)
Requirement already satisfied: packaging in c:\users\61415\anaconda3\lib\site-packages (from hvplot) (21.3)
Requirement already satisfied: bokeh>=1.0.0 in c:\users\61415\anaconda3\lib\site-packages (from hvplot) (2.4.3)
Requirement already satisfied: pandas in c:\users\61415\anaconda3\lib\site-packages (from hvplot) (1.4.4)
Requirement already satisfied: holoviews>=1.11.0 in c:\users\61415\anaconda3\lib\site-packages (from hvplot) (1.15.0)
Requirement already satisfied: colorcet>=2 in c:\users\61415\anaconda3\lib\site-packages (from hvplot) (3.0.0)
Requirement already satisfied: numpy>=1.15 in c:\users\61415\anaconda3\lib\site-packages (from hvplot) (1.21.5)
Collecting cartopy>=0.18.0
  Using cached Cartopy-0.21.1.tar.gz (10.9 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: pillow>=7.1.0 in c:\users\61415\anaconda3\lib\site-packages (from bokeh>=1.0.0->hvplot) (9.2.0)
Requirement already satisfied: typing-extensions>=3.10.0 in c:\users\61415\anaconda3\lib\site-packages (from bokeh>=1.0.0->hvplot) (4.3.0)
Requirement already satisfied: tornado>=5.1 in c:\users\61415\anaconda3\lib\site-packages (from bokeh>=1.0.0->hvplot) (6.1)
Requirement already satisfied: Jinja2>=2.9 in c:\users\61415\anaconda3\lib\site-packages (from bokeh>=1.0.0->hvplot) (2.11.3)
Requirement already satisfied: PyYAML>=3.10 in c:\users\61415\anaconda3\lib\site-packages (from bokeh>=1.0.0->hvplot) (6.0)
Collecting pyshp>=2.1
  Using cached pyshp-2.3.1-py2.py3-none-any.whl (46 kB)
Collecting pyproj>=3.0.0
...
  Building wheel for cartopy (pyproject.toml): started
  Building wheel for cartopy (pyproject.toml): finished with status 'error'
Failed to build cartopy
Note: you may need to restart the kernel to use updated packages.
Output exceeds the [size limit](command:workbench.action.openSettings?%5B%22notebook.output.textLineLimit%22%5D). Open the full output data [in a text editor](command:workbench.action.openLargeOutput?6fad590b-5add-4b09-ac0b-e7eda620d7cf)
  error: subprocess-exited-with-error
  
  × Building wheel for cartopy (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [286 lines of output]
      <string>:90: UserWarning: Unable to determine GEOS version. Ensure you have 3.7.2 or later installed, or installation may fail.
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-39
      creating build\lib.win-amd64-cpython-39\cartopy
      copying lib\cartopy\crs.py -> build\lib.win-amd64-cpython-39\cartopy
      copying lib\cartopy\geodesic.py -> build\lib.win-amd64-cpython-39\cartopy
      copying lib\cartopy\img_transform.py -> build\lib.win-amd64-cpython-39\cartopy
      copying lib\cartopy\util.py -> build\lib.win-amd64-cpython-39\cartopy
      copying lib\cartopy\vector_transform.py -> build\lib.win-amd64-cpython-39\cartopy
      copying lib\cartopy\_epsg.py -> build\lib.win-amd64-cpython-39\cartopy
      copying lib\cartopy\_version.py -> build\lib.win-amd64-cpython-39\cartopy
      copying lib\cartopy\__init__.py -> build\lib.win-amd64-cpython-39\cartopy
      creating build\lib.win-amd64-cpython-39\cartopy\feature
      copying lib\cartopy\feature\nightshade.py -> build\lib.win-amd64-cpython-39\cartopy\feature
      copying lib\cartopy\feature\__init__.py -> build\lib.win-amd64-cpython-39\cartopy\feature
      creating build\lib.win-amd64-cpython-39\cartopy\io
      copying lib\cartopy\io\img_nest.py -> build\lib.win-amd64-cpython-39\cartopy\io
...
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cartopy
ERROR: Could not build wheels for cartopy, which is required to install pyproject.toml-based projects

### pip list
pip install hvplot geoviews
```
```

**Comment by QuLogic** [comment]
Lots of output is cropped, and there is not really any indication of the error here.

But since you appear to be using anaconda, it would be better to create a new conda environment, and use conda to install cartopy from conda-forge instead of using pip.

**Comment by greglucas** [comment]
Closing for lack of response. Please see our installation guide for further help: https://scitools.org.uk/cartopy/docs/latest/installing.html
