### ISSUE TITLE
"set_xlabel" or "set_ylabel " is not supported in GeoAxesSubplot of cartopy v0.21.1 ?

### ISSUE THREAD

**Issue by gc13141112** [SciTools/cartopy#2125]
Dear everyone,
I used cartopy v0.21.1 to plot subplots, but "set_xlabel" or "set_ylabel " is not supported in GeoAxesSubplot.
Any recommendations for how to solve this or investigate further?
Thanks!
`fig, axs = plt.subplots(nrows=3,ncols=3,subplot_kw={'projection': background.crs},figsize=(11,8))`
`axs=axs.flatten()`
`axs.set_ylabel('Isoprene')`

**Comment by dopplershift** [comment]
In the code sample you provided, `axs` is a numpy array of `GeoAxesSubplot` instances. If you pull out one of these, with e.g. `axs[0]`, you'll find that `set_xlabel()` and `set_yabel()` work fine, like:

```python
axs[0].set_xlabel()
```

**Comment by gc13141112** [comment]
Thanks.  The below code is set and also does not work.
`axs[0].set_ylabel(''Isoprene'')`
Moreover, I only use `axs[0].text()`

**Comment by QuLogic** [comment]
> nrows=3,ncols=3,

`axs` is a 2D NumPy array, you need to use `axs[0, 0]`, etc. This is explained in the Matplotlib `subplots` docs.
