### ISSUE TITLE
Strange extent behaviour when latitude value too high

### ISSUE THREAD

**Issue by rcomer** [SciTools/cartopy#2128]
### Description

This problem behaviour was triggered by a downstream bug, so I completely understand if you prefer to ignore this issue!  The bug is that my latitude values were generated with `np.arange`, which resulted in my maximum latitude being slightly greater than 90 degrees.

My code creates a contourf and then adds a box to highlight a particular region.  The extent of the resulting plot shrinks to match the box.   If I remove the "problem line" in the below example, the output image is as expected.  The problem also goes away if the axes is instantiated with `projection=SOURCE_PROJ`.

#### Code to reproduce

```python
import matplotlib.pyplot as plt
import numpy as np

import cartopy.crs as ccrs

SOURCE_PROJ = ccrs.PlateCarree()
TARGET_PROJ = ccrs.PlateCarree(central_longitude=200)

def sample_data(shape=(73, 145)):
    """
    Return ``lons``, ``lats`` and ``data`` of some fake data.
    """
    nlats, nlons = shape
    lats1d = np.linspace(-np.pi / 2, np.pi / 2, nlats)
    lons1d = np.linspace(0, 2 * np.pi, nlons)
    lons, lats = np.meshgrid(lons1d, lats1d)
    wave = 0.75 * (np.sin(2 * lats) ** 8) * np.cos(4 * lons)
    mean = 0.5 * np.cos(2 * lats) * ((np.sin(2 * lats)) ** 2 + 2)

    lats1d = np.rad2deg(lats1d)
    lons1d = np.rad2deg(lons1d)
    data = wave + mean

    lats1d[-1] += 0.00001  # <-- PROBLEM LINE

    return lons1d, lats1d, data


def latlon_region_plot(lat_range, lon_range, ax):
    """
    Add a box described by lat_range and lon_range to the geoaxes.
    """
    ax.plot(
        [lon_range[0], lon_range[1], lon_range[1], lon_range[0], lon_range[0]],
        [lat_range[0], lat_range[0], lat_range[1], lat_range[1], lat_range[0]],
        transform=SOURCE_PROJ, color='magenta')


lons, lats, data = sample_data()
fig = plt.figure()
ax = fig.add_subplot(projection=TARGET_PROJ)

cf = ax.contourf(lons, lats, data, transform=SOURCE_PROJ)
ax.coastlines()
latlon_region_plot([-5, 25], [110, 140], ax)

plt.show()
```

#### Actual Result
![extent_box_bad](https://user-images.githubusercontent.com/10599679/214316084-4592fe04-8a3d-48ee-9a3e-5bea695bb8e0.png)

#### Expected Result
![extent_box_good](https://user-images.githubusercontent.com/10599679/214316152-a5c211fd-4ead-490e-ad37-44f78c7eb834.png)

<details>
 <summary>Full environment definition</summary>

### Operating system
RHEL7

### Cartopy version
0.20.3, 0.21.0, 0.21.1

The problem does not appear with 0.19.

### conda list

```
```

### pip list

```
```

</details>

**Comment by rcomer** [comment]
Thanks to @trexfeathers who spotted the latitude point was the problem.

**Comment by greglucas** [comment]
This only seems to be an issue with contours (changing to pcolormesh the auto-scaling is as expected).
I wonder if this is actually an issue in MPL rather than Cartopy...
when adding the collection with `autolim=False`
https://github.com/matplotlib/matplotlib/blob/66f7956984cbfc3647e867c6e5fde889a89c64ef/lib/matplotlib/contour.py#L872-L877

The autoscaling is as expected if autolim is True when adding the collections.
```python
for col in cf.collections:
    ax.add_collection(col, autolim=True)
```

I couldn't boil it down to an easily reproducible MPL-only example, maybe something to do with non-affine transforms on the collections?

**Comment by rcomer** [comment]
For `pcolormesh`, Cartopy has its own call to `update_datalim`, specifically ignoring nans

https://github.com/SciTools/cartopy/blob/a8f62baf12e73921a5910a61f2c7b75d8dfc07fb/lib/cartopy/mpl/geoaxes.py#L1889-L1898

Would it be reasonable to add

```python
self.ignore_existing_data_limits = False
```

after the `contour` and `contourf` limit updates?
https://github.com/SciTools/cartopy/blob/a8f62baf12e73921a5910a61f2c7b75d8dfc07fb/lib/cartopy/mpl/geoaxes.py#L1622
https://github.com/SciTools/cartopy/blob/a8f62baf12e73921a5910a61f2c7b75d8dfc07fb/lib/cartopy/mpl/geoaxes.py#L1670

Or would it be better to do something in Matplotlib?

**Comment by greglucas** [comment]
Aren't we already doing that with the `ignore=False` in the update calls? I think we agree that we should take account of the previous bboxes still and not change those to True (if you add one collection in the western hemisphere and this one is in the eastern hemisphere, we want the full globe not just the eastern hemisphere). But, I think you're proposing to do something else that I'm not following. Maybe a PR/example would be better.

Maybe there is a way to filter out the nans in the paths/bboxes better here? (nanmin used in pcolormesh)

**Comment by rcomer** [comment]
Sorry, I probably shouldn't have posted the above so late in the working day!  I have opened #2129, which hopefully is clearer,
