### ISSUE TITLE
Empty areas at the horizon when using `add_image` to NearsidePerspective

### ISSUE THREAD

**Issue by bratushka** [SciTools/cartopy#2135]
### Description
When plotting `NearsidePerspective` in `cartopy` using `add_image` I get many empty areas (as shown on the image) close to the horizon line.

[![Map with empty areas][1]][1]

#### Code to reproduce

Here's the code to reproduce:

```py
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import cartopy.io.img_tiles as cimgt


plt.figure(figsize=(7, 7), frameon=False)
projection = ccrs.NearsidePerspective(
    central_longitude=-86.055024,
    central_latitude=11.9320027,
    satellite_height=700000,
)
ax = plt.subplot(1, 1, 1, projection=projection)
ax.add_image(cimgt.GoogleTiles(), 7)
ax.set_global()
plt.show()
```

  [1]: https://i.stack.imgur.com/IAnC3.png
<details>
 <summary>Full environment definition</summary>

**Dockerfile** where the environment is defined:

```
FROM jupyter/scipy-notebook:x86_64-python-3.10.9


RUN conda install -c conda-forge cartopy
RUN conda install -c conda-forge gdal

RUN pip3 install countryinfo
RUN pip3 install haversine
RUN pip3 install reverse-geocode
RUN pip3 install pymbtiles

CMD ["start-notebook.sh"]
```

</details>

**Comment by greglucas** [comment]
You can shrink the threshold of the projection, which will sample that region with more points.
`projection.threshold = 1000`

Related to: https://github.com/SciTools/cartopy/issues/1907 and https://github.com/SciTools/cartopy/pull/1951
