### ISSUE TITLE
Add 'test' command to setup.py

### ISSUE THREAD

**Issue by esc24** [SciTools/cartopy#214]
The unit tests for cartopy can be run by calling `nosetests`. However, doing so will cause the the default matplotlib backend to be used. This default varies between platforms, e.g. under OSX it may be 'MacOSX', under linux it may be 'TkAgg'. The differences between these backends causes problems in the unit testing (see #211).

Modify `setup.py` so that one can run the units tests by entering   `python setup.py test`. Doing so should select the 'Agg' matplotlib backend and use the `KnownFailure` plugin. See below for a script that provides the basic functionality outside of `setup.py`:

``` python
#!/usr/bin/env python
#
# This allows running the cartopy tests from the command line: e.g.
# python tests.py -v -d

import matplotlib
matplotlib.use('agg')

import nose
from matplotlib.testing.noseclasses import KnownFailure


def run():
    nose.main(addplugins=[KnownFailure()])


if __name__ == '__main__':
    run()
```

**Comment by QuLogic** [comment]
> The unit tests for cartopy can be run by calling nosetests. However, doing so will cause the the default matplotlib backend to be used. This default varies between platforms, e.g. under OSX it may be 'MacOSX', under linux it may be 'TkAgg'.

This bit is no longer true, BTW (#500).

**Comment by pelson** [comment]
Done.
