### ISSUE TITLE
Aurora data no longer available from NOAA website

### ISSUE THREAD

**Issue by jmgomezpoveda** [SciTools/cartopy#2147]
### Description

The Aurora sample at https://scitools.org.uk/cartopy/docs/v0.18/gallery/aurora_forecast.html can no longer work, since NOAA is no longer providing the Aurora matrix at http://services.swpc.noaa.gov/text/aurora-nowcast-map.txt

**Comment by greglucas** [comment]
It looks like NOAA switched over to JSON for their product now. A PR to update that would be great!
https://services.swpc.noaa.gov/json/ovation_aurora_latest.json

Or they have the N/S split up in text files too: https://services.swpc.noaa.gov/text/ovation_latest_aurora_n.txt
