### ISSUE TITLE
Cannot install cartopy.

### ISSUE THREAD

**Issue by MaxWinter12** [SciTools/cartopy#2162]
Hi everyone.
I'm extremely new to programming, for my task at uni I have to use cartopy. But I have problems with installation.
after:
pip install cartopy

I am getting few errors:
error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cartopy
Failed to build cartopy
ERROR: Could not build wheels for cartopy, which is required to install pyproject.toml-based projects

I don't know how to handle them.

For Visual C++ Redistributable I have downloaded latest version and installed it few times.

I'm using Python 3.11.2 on windows 11.

I assume there's more from me to write here, but not sure what else to add to describe my problem.

Hope someone can help, 

Thanks in advance.

**Comment by greglucas** [comment]
Please see the installation requirements and suggestions. Conda is recommended if you are having problems with getting a compiler working.
https://scitools.org.uk/cartopy/docs/latest/installing.html
You could also try the Windows unofficial binaries listed on that page as well.
