### ISSUE TITLE
AttributeError: 'LineString' object has no attribute 'segmentize'

### ISSUE THREAD

**Issue by jo-caulkins** [SciTools/cartopy#2165]
### Description

I've encountered an error with LineString not having one of its built-in methods that I haven't run into before. I can't add the whole file, but I've added the relevant block. The problem arose when I ran the code in a new environment - specifically IDLE instead of Anaconda. 

#### Code to reproduce

```
def linestringXY(ls, ps): #ls is a LineString, ps is a list of shapely points
        myls = ls.segmentize(cell_size)
        coords = myls.coords
        ps = ps + coords

linestringXY(someLs, [])
```

#### Traceback

```
Traceback (most recent call last):
  File "C:\Users\jcaulkins\OneDrive\Documents\Python Scripts\heatmap.py", line 206, in <module>
    findXY(slice_can_rail, can_rail_ps)
  File "C:\Users\jcaulkins\OneDrive\Documents\Python Scripts\heatmap.py", line 189, in findXY
    linestringXY(geom.iloc[i], ps)
  File "C:\Users\jcaulkins\OneDrive\Python Scripts\heatmap.py", line 156, in linestringXY
    myls = ls.segmentize(cell_size)
AttributeError: 'LineString' object has no attribute 'segmentize'
```

<details>
 <summary>Full environment definition</summary>

### Operating system
Windows 11

### Cartopy version
Cartopy==0.20.2

### conda list

```
```

### pip list

```
geopandas 0.12.2
geoplot 0.5.1
shapely 1.8.2
cartopy 0.20.2
fiona 1.9.1
pyproj 3.3.1
packaging 23.0
rtree 1.0.1
numpy 1.24.2
```

</details>

**Comment by QuLogic** [comment]
This seems to be a question about Shapely, not Cartopy.
