### ISSUE TITLE
Could not build wheels for cartopy

### ISSUE THREAD

**Issue by DarkSky7** [SciTools/cartopy#2178]
### Description
lib/cartopy/trace.cpp(767): fatal error C1083: Cannot open include file: 'geos_c.h': No such file or directory

### 'pip install cartopy' transcript
Collecting cartopy
  Using cached Cartopy-0.21.1.tar.gz (10.9 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: numpy>=1.18 in c:\programs\python311\lib\site-packages (from cartopy) (1.24.3)
Requirement already satisfied: matplotlib>=3.1 in c:\programs\python311\lib\site-packages (from cartopy) (3.7.1)
Requirement already satisfied: shapely>=1.6.4 in c:\programs\python311\lib\site-packages (from cartopy) (2.0.1)
Collecting pyshp>=2.1 (from cartopy)
  Using cached pyshp-2.3.1-py2.py3-none-any.whl (46 kB)
Requirement already satisfied: pyproj>=3.0.0 in c:\programs\python311\lib\site-packages (from cartopy) (3.5.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\programs\python311\lib\site-packages (from matplotlib>=3.1->cartopy) (1.0.7)
Requirement already satisfied: cycler>=0.10 in c:\programs\python311\lib\site-packages (from matplotlib>=3.1->cartopy) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\programs\python311\lib\site-packages (from matplotlib>=3.1->cartopy) (4.39.4)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\programs\python311\lib\site-packages (from matplotlib>=3.1->cartopy) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\user\appdata\roaming\python\python311\site-packages (from matplotlib>=3.1->cartopy) (23.1)
Requirement already satisfied: pillow>=6.2.0 in c:\programs\python311\lib\site-packages (from matplotlib>=3.1->cartopy) (9.5.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\programs\python311\lib\site-packages (from matplotlib>=3.1->cartopy) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\user\appdata\roaming\python\python311\site-packages (from matplotlib>=3.1->cartopy) (2.8.2)
Requirement already satisfied: certifi in c:\programs\python311\lib\site-packages (from pyproj>=3.0.0->cartopy) (2023.5.7)
Requirement already satisfied: six>=1.5 in c:\users\user\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.7->matplotlib>=3.1->cartopy) (1.16.0)
Building wheels for collected packages: cartopy
  Building wheel for cartopy (pyproject.toml): started
  Building wheel for cartopy (pyproject.toml): finished with status 'error'
Failed to build cartopy

### Operating system
Windows-10

### Cartopy version
Cartopy-0.21.1

**Comment by greglucas** [comment]
Did you follow the installation instructions? Specifically, it looks like you have not installed GEOS.
https://scitools.org.uk/cartopy/docs/latest/installing.html

**Comment by DarkSky7** [comment]
Nothing in the installation instructions offers any help (that I've found).  The build depends on a source installation of geos (geos-devel) with geos_c.h configured from geos_c.h_in and the resulting includes folder.  On a Linux machine, the includes and libraries have standard locations.  I'm not sure how that maps into Windows-10 where pip can find it.  I apologize for my ignorance, but I could use guidance on where to put geos-devel so pip can complete the cartopy build.

**Comment by dopplershift** [comment]
@DarkSky7 The lack of availability of pre-built GEOS packages for Windows is why there aren't great install instructions for Windows. In addition to the headers you mentioned, you're going to need the binary libgeos library compiled for Windows. The options I see here are:

1. Build libgeos from source for Windows; requires you having a working compiler stack
2. Install pre-built binaries from e.g. [osgeo4w](https://trac.osgeo.org/osgeo4w/). I know that exists, but have no clue how you necessarily go about building Python packages linking to them.
3. (recommended) Use conda ([miniforge](https://github.com/conda-forge/miniforge/releases/tag/23.1.0-1) is small and straightforward to set up) to install pre-built Windows packages

**Comment by DarkSky7** [comment]
Thanks for the suggestions... I've been cautioned against mixing pip and
conda trees; without better insight into the consequences, I'm avoiding
that.  If I tapped osgeo4w <https://trac.osgeo.org/osgeo4w/>, I'd still
need to find a way around pip install cartopy requiring/finding geos_c.h.
I have geos source and a build stack, but likewise no clue on how to
facilitate pip finding geos_c.h in pip install cartopy.  Mired in bog until
someone posts an informed suggestion or upgrades the build/install process
somehow.

**Comment by rcomer** [comment]
Anaconda has some guidance about how to safely mix conda and pip, and what to avoid.
https://www.anaconda.com/blog/using-pip-in-a-conda-environment

**Comment by DarkSky7** [comment]
Thanks

**Comment by ruierzhao** [comment]
UnsatisfiableError: The following specifications were found to be in conflict:
  - cartopy=0.21 -> pyproj[version='>=3.0.0'] -> proj[version='>=8.2.1,>=8.2.1,<8.2.2.0a0'] -> proj4==999999999999
  - fiona
 
I want to use the latest version, but what if the package conflicts

**Comment by ruierzhao** [comment]
Can I still read the  document of previous version now

**Comment by yucsong** [comment]
> @DarkSky7 The lack of availability of pre-built GEOS packages for Windows is why there aren't great install instructions for Windows. In addition to the headers you mentioned, you're going to need the binary libgeos library compiled for Windows. The options I see here are:
> 
> 1. Build libgeos from source for Windows; requires you having a working compiler stack
> 2. Install pre-built binaries from e.g. [osgeo4w](https://trac.osgeo.org/osgeo4w/). I know that exists, but have no clue how you necessarily go about building Python packages linking to them.
> 3. (recommended) Use conda ([miniforge](https://github.com/conda-forge/miniforge/releases/tag/23.1.0-1) is small and straightforward to set up) to install pre-built Windows packages

If that is the case here, why the instruction didn't mention about that?  People thought conda installation would install/build the GEOS package together.

**Comment by yucsong** [comment]
I suggested GitHub to take this package down ... ask them to rewrite it and come up with better documentation.

**Comment by dopplershift** [comment]
@yucsong Please keep your comments constructive and respectful.

The comments above are specific to building from source, which is what's currently required for users who wish to stick with `pip` and installing packages from PyPI. There is no way within that system to express a dependency on GEOS, and there is a lack of pre-compiled GEOS packages for Windows. If you think that information should be included in the documentation, you are welcome to submit a Pull Request adding it to the installation documentation.

If you install using `conda`, that will install all necessary dependcies, and [as documented](https://scitools.org.uk/cartopy/docs/v0.21/installing.html#conda-pre-built-binaries) it is as straightforward as:
```
conda install -c conda-forge cartopy
```

**Comment by yucsong** [comment]
> @yucsong Please keep your comments constructive and respectful.
> 
> The comments above are specific to building from source, which is what's currently required for users who wish to stick with `pip` and installing packages from PyPI. There is no way within that system to express a dependency on GEOS, and there is a lack of pre-compiled GEOS packages for Windows. If you think that information should be included in the documentation, you are welcome to submit a Pull Request adding it to the installation documentation.
> 
> If you install using `conda`, that will install all necessary dependcies, and [as documented](https://scitools.org.uk/cartopy/docs/v0.21/installing.html#conda-pre-built-binaries) it is as straightforward as:
> 
> ```
> conda install -c conda-forge cartopy
> ```
Thanks, I will try to.  The problem with that is going back many years, cartopy wants to depend on shapely to call the gets, but that never happened. This contributed the whole problems that we are having. Wasted days to figure that out but no solutions.

**Comment by thomas-haslwanter** [comment]
I agree: if cartopy does not work (smoothly) with Windows, it might make sense to take it off GitHub for the momement. Took me quite some time to find this post, and figure out the source of the problem.

**Comment by dopplershift** [comment]
This is a FREE, open-source package developed by a tiny group of volunteers. If you're dissatisfied with what you're getting from the package, you are welcome to:
1. Try to contribute to make it better
2. Move on and use something else

I will also add that continued complaints from people who are doing absolutely nothing to improve the situation is not something that motivates me to put work into the project. Instead, I look at a post like this and decide to spend my limited time on this Earth hanging with my kids or playing Playstation rather than getting frustrated by my open source "hobby".

**Comment by ocefpaf** [comment]
I'd like to add that just a few aggressive complains can take a toll on the devs and, not even the indisputable success of this package can remedy that.

Also, you don't seem to understand how GitHub works. If they start pulling buggy software it will become empty rather quickly. Really, this is not a joke, all software is buggy, you can help out with PRs or constructive comments, or make the devs unwilling to use their free time to work on a software that is used in many countries, by many governments, countless scientists, etc.

**Comment by thomas-haslwanter** [comment]
I think you are right: I have not really thought that comment through, and I would like to apologize. cartopy is a brilliant project - and the occassional problem should lead to a pull request, not to a complaint.
Since I could not find anything where I can make up for my comment with some donation, I will try to see if I can solve on of the open issues, and submit a pull request.

Thanks a lot for the work you have put into cartopy!

**Comment by greglucas** [comment]
We have just released v0.22 which should help with the compatibility between packages and installation much easier. Please open a new issue if you are still having problems.
