### ISSUE TITLE
Plea for a stock_img() alpha

### ISSUE THREAD

**Issue by CommonClimate** [SciTools/cartopy#2179]
### Description
I am delighted that `.add_feature()` now allows for transparency via an `alpha` parameter; this goes a long way to decluttering busy maps. Unfortunately, the same feature is not available for `stock_img()`, and I was wondering why. I am admittedly ignorant of the way the background is implemented in Cartopy, but given that a lot of matplotlib objects have an alpha parameter, I was hoping this would be a matter of exposing it at the API level. Is this thinking too simplistic?

### Proposal
`ax.stock_img(alpha=0.5)` reduces background opacity by 50%, for instance.

**Comment by rcomer** [comment]
`stock_img` passes the image to `imshow`, and `imshow` handles _alpha_.  So it looks to me that it might indeed just be a case of exposing the keyword, though I am certainly no expert here.
https://github.com/SciTools/cartopy/blob/7f132a580c36027ddc4ef70aa70f4a2c0a878a67/lib/cartopy/mpl/geoaxes.py#L1012-L1014

**Comment by dopplershift** [comment]
@rcomer That looks correct to me.
