### ISSUE TITLE
Spines form incomplete junctions with some projections

### ISSUE THREAD

**Issue by kerrycobb** [SciTools/cartopy#2184]
### Description

When using certain projections such as cartopy.crs.AlbersEqualArea or cartopy.crs.Orthographic along with changing the extent such that some of the map is clipped, the spines at one corner do not form a connection or properly align. This is evident if you increase the line width of the spines. The image below shows the result in the affected corner which I have observed to be in both the top right corner as well as the lower left corner. The code below produced the plot this image was taken from.
![Example](https://github.com/SciTools/cartopy/assets/12968902/e7835cee-a936-4aa5-bdb0-9cc041f5300a)

#### Code to reproduce

```
import matplotlib.pyplot as plt
import cartopy.crs as ccrs

fig = plt.figure()
ax = plt.axes(projection=ccrs.Orthographic(0, 0))
ax.set_extent([-10, -11, 10, 11])
ax.spines[:].set_linewidth(3)
plt.savefig("test.pdf")
```

<details>
 <summary>Full environment definition</summary>

### Operating system
macOS 11.3.1

### Versions
Cartopy: 0.21.1
matplotlib: 3.7.1

</details>

**Comment by greglucas** [comment]
It looks like the GeoSpine path isn't closed. @QuLogic do you know if there was a specific reason for not closing the path? It looks like you explicitly set the capstyle to "butt" in https://github.com/SciTools/cartopy/pull/1213
I suppose non-closure makes sense for normal Left/Right/Bottom/Top Spines, but are GeoSpines always loops and therefore closed?

@kerrycobb A workaround for your specific case, but I don't think is general, is to call `ax.spines[:].set_capstyle("projecting")`.

**Comment by kerrycobb** [comment]
Thanks @greglucas for the work around! That's a good solution for my current case. 

I was thinking the same thing about the path not being closed because of the effect that I see if I set the joinstyle  to round `ax.spines[:].set_joinstyle("round")`. It changes the joinstyle of just 3 corners.

**Comment by QuLogic** [comment]
I think that was just to match previous behaviour; the former `PathPatch` uses 'butt' cap style. Matplotlib's spines use 'projecting', so that would likely be more consistent. I would think that not closing the path is an oversight, but since that's used for the background as well, I'm a bit surprised that didn't seem to cause any other issues.
