### ISSUE TITLE
Kernel crashed ... this is a buggy software 

### ISSUE THREAD

**Issue by yucsong** [SciTools/cartopy#2187]
I tend to think this is the MOST difficult package to install on the internet. If you search, a lot of bugs related to this package. 
Is there still a conflict with GEOS and shapely now?

**Comment by yucsong** [comment]
What exactly are needed to have this package work??? Could you please elaborate more clearly???

**Comment by greglucas** [comment]
It is unclear what you have tried or what issues you are having installing Cartopy from your description. Please be courteous when writing your comments.

We have an installation guide here: https://scitools.org.uk/cartopy/docs/latest/installing.html
which lists all of the required software and recommendations for how to install those packages. If you have specific error messages or logs when installing that can often help to diagnose the problem and you can search for other issues and what people did to solve their installation issue.

**Comment by yucsong** [comment]
This is really frustrating - the guide is not very helpful.  What exactly are needed before the installation? Why there are conflict with shaply still exists that killed the kernel?   That guidance is really vague under ubuntu:  
sudo apt -y install libgeos-dev

Is this enough? What about proj4? 

If you don't have these on the system, how would you install them etc.  I found no other packages are like this one, so hard to install  ...
