### ISSUE TITLE
Kernel crashed again... this is a buggy software 

### ISSUE THREAD

**Issue by yucsong** [SciTools/cartopy#2190]
Could you resolve the conflict with shapely now?  Please clearly lay out the steps to make this work on ubuntu:

would Conda install -c  ... carroty be enough to install the GEOS and PROJ4? or do we need to pre-install these two packages?
How to resolve the shaply conflicts?

**Comment by rcomer** [comment]
I use Ubuntu and have no problems installing Cartopy with Conda.  Conda automatically installs all the dependencies so you do not need to worry about that.

**Comment by ocefpaf** [comment]
BTW, if you are having issues with the conda package, consider opening an issue in the package provider upstream. If it is conda-forge the cartopy feedstock, or conda's discourse if it is from the main channel.

**Comment by yucsong** [comment]
> I use Ubuntu and have no problems installing Cartopy with Conda. Conda automatically installs all the dependencies so you do not need to worry about that.

You don't have problems doesn't mean others won't.  https://stackoverflow.com/questions/75983457/unable-to-import-cartopy-importerror-libgeos-c-so-1-cannot-open-shared-object

**Comment by ocefpaf** [comment]
> You don't have problems doesn't mean others won't

Please be courteous and polite. Everybody is trying to help you here. Note that, with the information you reported, all we can is try to install the same way and report back if it worked or not. It also works for my case but I know how to use conda and it's multiple channels, so, if you can follow our advice above and report in the right place or provide more information, we can probably help you further.

**Comment by greglucas** [comment]
We have just released v0.22 which should help with the compatibility between packages and installation much easier. Please open a new issue if you are still having problems.
