### ISSUE TITLE
Stamen watercolor tile requests send back HTTP Error 404

### ISSUE THREAD

**Issue by wckoeppen** [SciTools/cartopy#2198]
### Description
Attempting to use the `cartopy.io.img_tiles.Stamen` tiles with the `watercolor` style sends back an HTTP Error 404: Not Found error.
 
It looks like the Stamen tile urls may have changed slightly? [This code](https://github.com/SciTools/cartopy/blob/main/lib/cartopy/io/img_tiles.py#L360) asks for
```
f'http://tile.stamen.com/{self.style}/{z}/{x}/{y}.png'
```
These requests get redirected to `https://tiles.stadiamaps.com/styles/`, and it looks like the watercolor tiles are only made available there as jpg, not png. (Other tilesets are available in both formats.)

Doesn't work: https://tiles.stadiamaps.com/styles/stamen_watercolor/12/1104/1625.png
Works:             https://tiles.stadiamaps.com/styles/stamen_watercolor/12/1104/1625.jpg

#### Code to reproduce

```
import matplotlib.pyplot as plt
import cartopy.io.img_tiles as cimgt

request = cimgt.Stamen(style='watercolor')

fig = plt.figure()
ax = fig.add_axes([0,0,1,1], projection=request.crs)
ax.set_extent([-83.35, -83.30, 34.85, 34.90])
img = ax.add_image(request, 14)
plt.show()
```
### Operating system
Mac OS Ventura 13.4.1

### Cartopy version
0.21.1

### conda list

```
  - numpy
  - gpxpy
  - python=3.10
  - shapely
  - geopandas
  - matplotlib
  - tqdm
  - cartopy
  - pandas
  - jupyterlab
```

**Comment by lgolston** [comment]
Thanks @wckoeppen for reporting! I don't know if the png version is still available or not, but jpg seems to be the primary version of watercolor so we should look at using that. More broadly, could be handled something like in openlayers: [link](https://github.com/openlayers/openlayers/blob/fe68ca7370bdefe5419cec72fcb910efee250577/src/ol/source/Stamen.js#L22)

**Comment by rcomer** [comment]
I think this one is fixed by #2202?

**Comment by dopplershift** [comment]
I think so. This should be fixed either by running `main` or installing the next release when it becomes available. If you find that's not the case, feel free to re-open.

**Comment by wckoeppen** [comment]
Thanks everyone. Much appreciated!
