### ISSUE TITLE
AttributeError: module 'cartopy' has no attribute 'PlateCarree'

### ISSUE THREAD

**Issue by jiehua-lee** [SciTools/cartopy#2203]
import cartopy as ccrs#坐标系统
import cartopy.feature as cfeature
ccrs.PlateCarree()

lons=360*np.random.rand(100)
lats=180*np.random.rand(100)-90
fig,ax=plt.subplots(1,1,figsize=(6,6),
                    subplot_kw={
                        'projection':ccrs.PlateCarree(central_longitude=70)})
ax.coastlines(linewidth=0.3,color='gray')
ax.add_feature(cfeature.LAND,facecolor=cfeature.COLORS['land'])
ax.scatetr(lons, lats,s=10,color='maroon')
ax.gridelines(linestyle='dotted',linewidth=0.5)
ax.add_feature(cfeature.BORDERS,linewidth=0.3)
ax.set_extent([60,140,10,50]) # west_lon, east_lon, south_lat, north_lat
ax.add_feature(cfeature.OCEAN)
ax.add_feature(cfeature.LAKES)  
ax.add_feature(cfeature.RIVERS)
ax.add_feature(cfeature.STATES,linewidth=0.5)
ax.stock_img()

我试过的方法包括重装包和register_projection，cartopy的依赖包我也都有

**Comment by akrherz** [comment]
Try this
```python
import cartopy.crs as ccrs
```

**Comment by jiehua-lee** [comment]
But new Error appears：
AttributeError: 'GeoAxes' object has no attribute 'scatetr'
0.0

**Comment by akrherz** [comment]
> AttributeError: 'GeoAxes' object has no attribute 'scatetr'

It is just a typo, try `scatter`

**Comment by jiehua-lee** [comment]
> Try this
> 
> ```python
> import cartopy.crs as ccrs
> ```



> 

thank you！
