### ISSUE TITLE
Packaging dependency requirement

### ISSUE THREAD

**Issue by greglucas** [SciTools/cartopy#2216]
### Description

`packaging` is only listed as a test dependency, but we are now version gating in the main importable code section. We should either figure out a different way to do the version checks within the code or add it as a primary dependency.

ping @rcomer it looks like this came in these two PRs: #2213, #2215

**Comment by rcomer** [comment]
I think I started it with #2169, with more in #2166 and I was copying how it was done in the tests.  Before that the version checks were just comparing strings, but I think we need something more sophisticated than that once mpl 3.10 comes out

```
In [1]: "3.10" > "3.4"
Out[1]: False
```

**Comment by rcomer** [comment]
I have to admit it did not cross my mind to think about what type of dependency this is.  Sorry about that.

**Comment by dopplershift** [comment]
I don't think it's a particularly burdensome dependency, but it is definitely should be added to the install list.

**Comment by greglucas** [comment]
> I have to admit it did not cross my mind to think about what type of dependency this is. Sorry about that.
No problem at all @rcomer! I just wanted to make sure we had a plan for addressing this. I'll add this as a dependency in my release PR so we don't have to deal with rebase conflicts when adding it to current main.
