### ISSUE TITLE
problem with import cartopy

### ISSUE THREAD

**Issue by lindbergh153** [SciTools/cartopy#2223]
### Description
Hello, I can't import cartopy.crs

#### Code to reproduce

```
import cartopy.crs as ccrs
```

#### Traceback

```
  File "D:\DWOSM_risk\testing.py", line 26, in <module>
    import cartopy.crs as ccrs
  File "D:\Miniconda3\envs\gnome\lib\site-packages\cartopy\__init__.py", line 107, in <module>
    import cartopy.crs  # noqa: E402  module-level imports
  File "D:\Miniconda3\envs\gnome\lib\site-packages\cartopy\crs.py", line 22, in <module>
    import shapely.geometry as sgeom
  File "D:\Miniconda3\envs\gnome\lib\site-packages\shapely\__init__.py", line 1, in <module>
    from .lib import GEOSException  # NOQA
ImportError: DLL load failed while importing lib: The specified procedure could not be found.
```

<details>
 <summary>Full environment definition</summary>

### Operating system
win10

### Cartopy version
0.21.1

### conda list
# packages in environment at D:\Miniconda3\envs\gnome:
#
# Name                    Version                   Build  Channel
adios-db                  1.0.0b1                  pypi_0    pypi
alabaster                 0.7.13             pyhd8ed1ab_0    conda-forge
altgraph                  0.17.2                   pypi_0    pypi
apptools                  5.2.0                    pypi_0    pypi
argon2-cffi               21.3.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0           py38h91455d4_3    conda-forge
asteval                   0.9.29                   pypi_0    pypi
astroid                   2.13.3           py38haa244fe_0    conda-forge
astropy                   5.2.1                    pypi_0    pypi
asttokens                 2.2.1              pyhd8ed1ab_0    conda-forge
atomicwrites              1.4.1              pyhd8ed1ab_0    conda-forge
attrs                     22.2.0             pyh71513ae_0    conda-forge
awesome-slugify           1.6.5                      py_5    conda-forge
babel                     2.11.0             pyhd8ed1ab_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                pyhd8ed1ab_3    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
basemap                   1.3.6                    pypi_0    pypi
basemap-data              1.3.2              pyhd8ed1ab_1    conda-forge
basemap-data-hires        1.3.2              pyhd8ed1ab_1    conda-forge
beautifulsoup4            4.11.1             pyha770c72_0    conda-forge
bleach                    6.0.0              pyhd8ed1ab_0    conda-forge
bokeh                     2.4.3              pyhd8ed1ab_3    conda-forge
boost-cpp                 1.80.0               h9f4b32c_0    conda-forge
brotli                    1.0.9                hcfcfb64_8    conda-forge
brotli-bin                1.0.9                hcfcfb64_8    conda-forge
brotlipy                  0.7.0           py38h91455d4_1005    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2023.7.22            h56e8100_0    conda-forge
cartopy                   0.21.1           py38hf3113ef_1    conda-forge
cell_tree2d               0.3.0           py38hcc40339_1005    conda-forge
certifi                   2023.7.22          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1           py38h57701bc_3    conda-forge
cftime                    1.6.2            py38hbaf524b_1    conda-forge
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
clangdev                  5.0.0                   flang_3  [flang]  conda-forge
click                     7.1.2                    pypi_0    pypi
click-plugins             1.1.1                    pypi_0    pypi
cligj                     0.7.2                    pypi_0    pypi
cloudpickle               2.2.1                    pypi_0    pypi
cmemsapi                  0.1.17                   pypi_0    pypi
colander                  1.8.3              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
colorcet                  3.0.1              pyhd8ed1ab_0    conda-forge
comm                      0.1.2              pyhd8ed1ab_0    conda-forge
configobj                 5.0.8                    pypi_0    pypi
contourpy                 1.0.7            py38hb1fd069_0    conda-forge
coverage                  7.1.0            py38h91455d4_0    conda-forge
cryptography              39.0.0           py38h086c683_0    conda-forge
curl                      7.87.0               h68f0423_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cython                    0.29.33          py38hd3f51b4_0    conda-forge
dask                      2023.4.1                 pypi_0    pypi
debugpy                   1.6.6            py38hd3f51b4_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
descartes                 1.1.0                    pypi_0    pypi
dill                      0.3.6              pyhd8ed1ab_1    conda-forge
docutils                  0.17.1           py38haa244fe_3    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
envisage                  7.0.1                    pypi_0    pypi
et_xmlfile                1.1.0              pyhd8ed1ab_0    conda-forge
exceptiongroup            1.1.0              pyhd8ed1ab_0    conda-forge
executing                 1.2.0              pyhd8ed1ab_0    conda-forge
expat                     2.5.0                h1537add_0    conda-forge
filemagic                 1.6                      pypi_0    pypi
fiona                     1.9.2                    pypi_0    pypi
fire                      0.5.0                    pypi_0    pypi
flang                     5.0.0           he025d50_20180525    conda-forge
flang_win-64              5.0.0           h13ae965_20180526    conda-forge
flask                     2.2.2              pyhd8ed1ab_0    conda-forge
flit-core                 3.8.0              pyhd8ed1ab_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.2               hbde0cde_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.38.0           py38h91455d4_1    conda-forge
fortran-compiler          1.5.2                h9655429_0    conda-forge
freetype                  2.12.1               h546665d_1    conda-forge
fsspec                    2023.5.0                 pypi_0    pypi
funcy                     2.0                      pypi_0    pypi
future                    0.18.2           py38haa244fe_5    conda-forge
geographiclib             1.52               pyhd8ed1ab_0    conda-forge
geojson                   2.5.0                      py_0    conda-forge
geopandas                 0.12.2                   pypi_0    pypi
geopy                     2.3.0              pyhd8ed1ab_0    conda-forge
geos                      3.11.2               h1537add_0    conda-forge
git                       2.39.0               h57928b3_0    conda-forge
gitdb                     4.0.10             pyhd8ed1ab_0    conda-forge
gitpython                 3.1.27             pyhd8ed1ab_0    conda-forge
gridded                   0.3.4              pyhd8ed1ab_2    conda-forge
gsw                       3.4.0            py38hbdcd294_3    conda-forge
h5py                      3.8.0                    pypi_0    pypi
hdf4                      4.2.15               h1b1b6ef_5    conda-forge
hdf5                      1.12.2          nompi_h2a0e4a3_101    conda-forge
holoviews                 1.15.4             pyhd8ed1ab_0    conda-forge
hvplot                    0.8.2              pyhd8ed1ab_0    conda-forge
icc_rt                    2020.2                intel_254    numba
icu                       70.1                 h0e60522_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
image-registration        0.2.6                    pypi_0    pypi
imageio                   2.26.1                   pypi_0    pypi
imagesize                 1.4.1              pyhd8ed1ab_0    conda-forge
importlib-metadata        6.0.0              pyha770c72_0    conda-forge
importlib_metadata        6.0.0                hd8ed1ab_0    conda-forge
importlib_resources       5.10.2             pyhd8ed1ab_0    conda-forge
imreg-dft                 2.0.0                    pypi_0    pypi
iniconfig                 2.0.0              pyhd8ed1ab_0    conda-forge
intel-openmp              2023.0.0         h57928b3_25922    conda-forge
ipykernel                 6.21.0             pyh025b116_0    conda-forge
ipython                   8.4.0            py38haa244fe_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
iso8601                   1.1.0              pyhd8ed1ab_0    conda-forge
itsdangerous              2.1.2              pyhd8ed1ab_0    conda-forge
jedi                      0.17.2                   pypi_0    pypi
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
joblib                    1.2.0              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h8ffe710_2    conda-forge
jsonschema                4.17.3             pyhd8ed1ab_0    conda-forge
jupyter_client            8.0.1              pyhd8ed1ab_0    conda-forge
jupyter_core              5.2.0            py38haa244fe_0    conda-forge
jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
kiwisolver                1.4.4            py38hb1fd069_1    conda-forge
krb5                      1.20.1               h6609f42_0    conda-forge
lazy-loader               0.2                      pypi_0    pypi
lazy-object-proxy         1.9.0            py38h91455d4_0    conda-forge
lerc                      4.0.0                h63175ca_0    conda-forge
libaec                    1.0.6                h63175ca_1    conda-forge
libblas                   3.9.0              16_win64_mkl    conda-forge
libbrotlicommon           1.0.9                hcfcfb64_8    conda-forge
libbrotlidec              1.0.9                hcfcfb64_8    conda-forge
libbrotlienc              1.0.9                hcfcfb64_8    conda-forge
libcblas                  3.9.0              16_win64_mkl    conda-forge
libcurl                   7.87.0               h68f0423_0    conda-forge
libdeflate                1.14                 hcfcfb64_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libflang                  5.0.0           h6538335_20180525    conda-forge
libgd                     2.3.3                h891f43f_3    conda-forge
libhwloc                  2.8.0                h039e092_1    conda-forge
libiconv                  1.17                 h8ffe710_0    conda-forge
liblapack                 3.9.0              16_win64_mkl    conda-forge
libnetcdf                 4.8.1           nompi_h8c042bf_106    conda-forge
libpng                    1.6.39               h19919ed_0    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libsqlite                 3.40.0               hcfcfb64_0    conda-forge
libssh2                   1.10.0               h680486a_3    conda-forge
libtiff                   4.4.0                hc4f729c_5    conda-forge
libwebp                   1.2.4                hcfcfb64_1    conda-forge
libwebp-base              1.2.4                h8ffe710_0    conda-forge
libxcb                    1.13              hcd874cb_1004    conda-forge
libxml2                   2.10.3               hc3477c8_0    conda-forge
libzip                    1.9.2                hfed4ece_1    conda-forge
libzlib                   1.2.13               hcfcfb64_4    conda-forge
llvm-meta                 5.0.0                         0    conda-forge
llvmlite                  0.39.1           py38h19421c1_1    conda-forge
lmfit                     1.1.0                    pypi_0    pypi
locket                    1.0.0                    pypi_0    pypi
lxml                      4.9.2                    pypi_0    pypi
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
macholib                  1.16.2             pyhd8ed1ab_0    conda-forge
mapbox_earcut             1.0.0            py38hbd9d945_3    conda-forge
markdown                  3.4.1              pyhd8ed1ab_0    conda-forge
markupsafe                2.1.2            py38h91455d4_0    conda-forge
matplotlib-base           3.7.1            py38hf11a4ad_1
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
mayavi                    4.8.1                    pypi_0    pypi
memoization               0.4.0                    pypi_0    pypi
mistune                   2.0.4              pyhd8ed1ab_0    conda-forge
mkl                       2022.1.0           h6a75c08_874    conda-forge
mongodb                   4.0.3                he170510_0
motuclient                1.8.4                    pypi_0    pypi
msys2-conda-epoch         20160418                      1    conda-forge
multiprocess              0.70.14          py38h91455d4_3    conda-forge
munch                     2.5.0                    pypi_0    pypi
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
nbclient                  0.7.2              pyhd8ed1ab_0    conda-forge
nbconvert                 7.2.9              pyhd8ed1ab_0    conda-forge
nbconvert-core            7.2.9              pyhd8ed1ab_0    conda-forge
nbconvert-pandoc          7.2.9              pyhd8ed1ab_0    conda-forge
nbformat                  5.7.3              pyhd8ed1ab_0    conda-forge
nbsphinx                  0.8.9              pyhd8ed1ab_0    conda-forge
netcdf4                   1.5.4                    pypi_0    pypi
networkx                  3.0                      pypi_0    pypi
notebook                  6.4.12             pyha770c72_0    conda-forge
nptdms                    1.6.1                    pypi_0    pypi
numba                     0.56.4                   pypi_0    pypi
numpy                     1.23.5           py38h90ce339_0    conda-forge
oil-library               2.0.1                    pypi_0    pypi
openmp                    5.0.0                    vc14_1    conda-forge
openpyxl                  3.0.9              pyhd8ed1ab_0    conda-forge
openssl                   1.1.1t               hcfcfb64_0    conda-forge
packaging                 23.0               pyhd8ed1ab_0    conda-forge
pandas                    1.5.3            py38h5846ac1_0    conda-forge
pandoc                    2.19.2               h57928b3_1    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
panel                     0.14.3             pyhd8ed1ab_0    conda-forge
param                     1.12.3             pyh1a96a4e_0    conda-forge
parso                     0.7.1                    pypi_0    pypi
partd                     1.4.0                    pypi_0    pypi
pathos                    0.3.0              pyhd8ed1ab_0    conda-forge
patsy                     0.5.3                    pypi_0    pypi
pefile                    2022.5.30                pypi_0    pypi
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    9.3.0            py38hdc2b20a_1
pip                       22.2.2             pyhd8ed1ab_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_0    conda-forge
platformdirs              2.6.2              pyhd8ed1ab_0    conda-forge
pluggy                    1.0.0              pyhd8ed1ab_5    conda-forge
pooch                     1.7.0              pyha770c72_3    conda-forge
pox                       0.3.2              pyhd8ed1ab_0    conda-forge
ppft                      1.7.6.6            pyhd8ed1ab_0    conda-forge
progressbar               2.5                        py_0    conda-forge
proj                      8.2.1                h1cfcee9_0    conda-forge
prometheus_client         0.16.0             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.36             pyha770c72_0    conda-forge
psutil                    5.9.1            py38h294d835_0    conda-forge
pthread-stubs             0.4               hcd874cb_1001    conda-forge
pthreads-win32            2.9.1                hfa6e2cd_3    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
py                        1.11.0             pyh6c4a22f_0    conda-forge
py_gd                     2.0.3            py38h294d835_1    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyct                      0.4.6                      py_0    conda-forge
pyct-core                 0.4.6                      py_0    conda-forge
pyerfa                    2.0.0.2                  pypi_0    pypi
pyface                    7.4.4                    pypi_0    pypi
pygments                  2.14.0             pyhd8ed1ab_0    conda-forge
pygmt                     0.8.0                    pypi_0    pypi
pygnome                   1.1.3                    pypi_0    pypi
pyhdf                     0.10.5           py38h9831fd4_0    conda-forge
pyinstaller               5.3                      pypi_0    pypi
pyinstaller-hooks-contrib 2022.8                   pypi_0    pypi
pymongo                   4.2.0            py38h885f38d_1    conda-forge
pynucos                   3.1.1              pyhd8ed1ab_0    conda-forge
pyopenssl                 23.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyproj                    3.3.0            py38hbc4243d_1    conda-forge
pyrsistent                0.19.3           py38h91455d4_0    conda-forge
pyshp                     2.3.1              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyh0701188_6    conda-forge
pytest                    7.2.1              pyhd8ed1ab_0    conda-forge
pytest-cov                4.0.0              pyhd8ed1ab_0    conda-forge
pytest-timeout            2.1.0              pyhd8ed1ab_0    conda-forge
python                    3.8.15          h0269646_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-dotenv             0.20.0                   pypi_0    pypi
python-fastjsonschema     2.16.2             pyhd8ed1ab_0    conda-forge
python_abi                3.8                      3_cp38    conda-forge
pytz                      2022.7.1           pyhd8ed1ab_0    conda-forge
pyviz_comms               2.2.1              pyhd8ed1ab_1    conda-forge
pywavelets                1.4.1                    pypi_0    pypi
pywin32                   304              py38hd3f51b4_2    conda-forge
pywin32-ctypes            0.2.0           py38haa244fe_1006    conda-forge
pywinpty                  2.0.10           py38hd3f51b4_0    conda-forge
pyyaml                    6.0              py38h91455d4_5    conda-forge
pyzmq                     23.2.1           py38h09162b1_0    conda-forge
regex                     2022.10.31       py38h91455d4_0    conda-forge
requests                  2.28.1             pyhd8ed1ab_0    conda-forge
salib                     1.4.5              pyh6c4a22f_0    conda-forge
scikit-image              0.20.0                   pypi_0    pypi
scikit-learn              1.2.0            py38h69724d7_0    conda-forge
scipy                     1.10.1           py38h0f6ee2a_0    conda-forge
send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
setuptools                67.6.1             pyhd8ed1ab_0    conda-forge
shapely                   2.0.1            py38h49d2d47_1    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
smmap                     3.0.5              pyh44b312d_0    conda-forge
snowballstemmer           2.2.0              pyhd8ed1ab_0    conda-forge
soupsieve                 2.3.2.post1        pyhd8ed1ab_0    conda-forge
sphinx                    5.1.1              pyhd8ed1ab_1    conda-forge
sphinx-autoapi            1.9.0              pyhd8ed1ab_0    conda-forge
sphinx_rtd_theme          1.0.0              pyhd8ed1ab_0    conda-forge
sphinxcontrib-applehelp   1.0.4              pyhd8ed1ab_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-dotnetdomain 0.4                        py_0    conda-forge
sphinxcontrib-golangdomain 0.2.0.dev0                 py_0    conda-forge
sphinxcontrib-htmlhelp    2.0.0              pyhd8ed1ab_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.5              pyhd8ed1ab_2    conda-forge
sqlalchemy                1.3.24           py38h294d835_1    conda-forge
sqlite                    3.40.0               hcfcfb64_0    conda-forge
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
statsmodels               0.13.5                   pypi_0    pypi
tabulate                  0.9.0                    pypi_0    pypi
tamoc                     2.2.0                    pypi_0    pypi
tbb                       2021.7.0             h91493d7_1    conda-forge
tblib                     1.7.0              pyhd8ed1ab_0    conda-forge
termcolor                 2.3.0                    pypi_0    pypi
terminado                 0.17.0             pyh08f2357_0    conda-forge
testfixtures              7.0.0              pyhd8ed1ab_0    conda-forge
threadpoolctl             3.1.0              pyh8a188c0_0    conda-forge
tifffile                  2023.3.21                pypi_0    pypi
tinycss2                  1.2.1              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h8ffe710_0    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
toolz                     0.12.0                   pypi_0    pypi
tornado                   6.2              py38h91455d4_1    conda-forge
tqdm                      4.64.1             pyhd8ed1ab_0    conda-forge
traitlets                 5.9.0              pyhd8ed1ab_0    conda-forge
traits                    6.4.1                    pypi_0    pypi
traitsui                  7.4.3                    pypi_0    pypi
transaction               3.0.1              pyhd8ed1ab_0    conda-forge
translationstring         1.4                pyh9f0ad1d_0    conda-forge
trimesh                   3.13.4             pyh6c4a22f_0    conda-forge
typing-extensions         4.4.0                hd8ed1ab_0    conda-forge
typing_extensions         4.4.0              pyha770c72_0    conda-forge
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
uncertainties             3.1.7                    pypi_0    pypi
unicodedata2              15.0.0           py38h91455d4_0    conda-forge
unidecode                 1.3.6              pyhd8ed1ab_0    conda-forge
urllib3                   1.26.14            pyhd8ed1ab_0    conda-forge
vc                        14.3                hb6edc58_10    conda-forge
vs2015_runtime            14.34.31931         h4c5c07a_10    conda-forge
vtk                       9.2.6                    pypi_0    pypi
wcwidth                   0.2.6              pyhd8ed1ab_0    conda-forge
webencodings              0.5.1                      py_1    conda-forge
werkzeug                  2.2.2              pyhd8ed1ab_0    conda-forge
wheel                     0.38.4             pyhd8ed1ab_0    conda-forge
win_inet_pton             1.1.0              pyhd8ed1ab_6    conda-forge
winpty                    0.4.3                         4    conda-forge
wrapt                     1.14.1           py38h91455d4_1    conda-forge
xarray                    2022.6.0           pyhd8ed1ab_1    conda-forge
xlsxwriter                3.0.3              pyhd8ed1ab_0    conda-forge
xorg-kbproto              1.0.7             hcd874cb_1002    conda-forge
xorg-libice               1.0.10               hcd874cb_0    conda-forge
xorg-libsm                1.2.3             hcd874cb_1000    conda-forge
xorg-libx11               1.7.2                hcd874cb_0    conda-forge
xorg-libxau               1.0.9                hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xorg-libxext              1.3.4                hcd874cb_1    conda-forge
xorg-libxpm               3.5.13               hcd874cb_0    conda-forge
xorg-libxt                1.2.1                hcd874cb_2    conda-forge
xorg-xextproto            7.3.0             hcd874cb_1002    conda-forge
xorg-xproto               7.0.31            hcd874cb_1007    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
yaml                      0.2.5                h8ffe710_2    conda-forge
zeromq                    4.3.4                h0e60522_1    conda-forge
zipp                      3.12.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               hcfcfb64_4    conda-forge
zope.interface            5.5.2            py38h91455d4_0    conda-forge
zope.sqlalchemy           1.1                      py38_0
zstd                      1.5.2                h12be248_6    conda-forge

### pip list

```
```

</details>

**Comment by dopplershift** [comment]
That last line indicates a problem with your installation of shapely, not cartopy.

**Comment by lindbergh153** [comment]
> That last line indicates a problem with your installation of shapely, not cartopy.

Thanks for your help. So I should reinstall shapely?

**Comment by dopplershift** [comment]
I would try reinstalling shapely, maybe even try rebuilding the environment. How did you install shapely?

**Comment by lindbergh153** [comment]
Thanks for your help. The problem is fixed by reinstallation of shapely.
