### ISSUE TITLE
Don't use generic feature_download executable name

### ISSUE THREAD

**Issue by sebastic** [SciTools/cartopy#2227]
### Description

Since 0.22.0 `tools/cartopy_feature_download.py` gets installed as `/usr/bin/feature_download` which is a far too generic name.

The `cartopy_` prefix should be preserved as per this patch:
```diff
Description: Don't use generic feature_download executable name.
Author: Bas Couwenberg <sebastic@debian.org>

--- a/pyproject.toml
+++ b/pyproject.toml
@@ -56,7 +56,7 @@ plotting = ["pillow>=6.1.0", "scipy>=1.3
 test = ["pytest>=5.1.2", "pytest-mpl>=0.11", "pytest-xdist", "pytest-cov", "coveralls"]
 
 [project.scripts]
-feature_download = "tools.cartopy_feature_download.py:__main__"
+cartopy_feature_download = "tools.cartopy_feature_download.py:__main__"
 
 [project.urls]
 documentation='https://scitools.org.uk/cartopy/docs/latest/'
```

### Operating system

Debian unstable

### Cartopy version

0.22.0

</details>

**Comment by greglucas** [comment]
I agree this is not super ideal. More generally, I wonder if we even want to install "cartopy_feature_download" as a script like this at all because I don't think it rises to the level of needing to be site-wide available as a script. Maybe we could move it into a function within the package somehow instead. Any other thoughts on this from anyone?

**Comment by dopplershift** [comment]
An option would be to have it as code in a `__main__` in an appropriate module, so you could run it like `python -m cartopy.feature` ?

**Comment by QuLogic** [comment]
I think it used to be installed as `cartopy_feature_download.py`, so this rename was accidental.

**Comment by sebastic** [comment]
> I think it used to be installed as `cartopy_feature_download.py`, so this rename was accidental.

It was, and installing it without the language extension is better.

**Comment by greglucas** [comment]
I think the current installation is actually broken? So a simple name change won't fix the underlying issue. It looks like setuptools expects scripts to be a part of the package, but we have put the script in a separate directory without an `__init__.py` so the tools directory isn't a module.

```bash
/usr/bin/cartopy_feature_download", line 5, in <module>
    from tools.cartopy_feature_download.py import __main__
ModuleNotFoundError: No module named 'tools'
```

**Comment by QuLogic** [comment]
Oh, that's a good catch; probably should move to `cartopy.feature` somewhere as @dopplershift suggested.
