### ISSUE TITLE
Source code no longer included on PyPI

### ISSUE THREAD

**Issue by xylar** [SciTools/cartopy#2228]
On conda-forge, we're trying to build 0.22.0:
https://github.com/conda-forge/cartopy-feedstock/pull/156

However, we're running into issues because a `.tar.gz` file wasn't included in the PyPI release.  First, our bot was not able to create a PR for the release (see https://github.com/conda-forge/cartopy-feedstock/issues/155).  Then, when I tried to use the source from GitHub instead, `setuptools-scm` complains:
```
      LookupError: setuptools-scm was unable to detect version for /home/conda/feedstock_root/build_artifacts/cartopy_1691225778495/work.
      
      Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.
      
      For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
      [end of output]
```
While there are workarounds that I've used in the past (I'm a little rusty so I'll have to dig them up), it seems like the cleanest solution would be to include the source on PyPI agian.

**Comment by greglucas** [comment]
That was definitely an oversight! It looks like we didn't download the sdist in the upload-to-pypi release step on CI, but it was produced in the artifacts.
https://github.com/SciTools/cartopy/actions/runs/5767791499#artifacts

@dopplershift I think you have a PyPI release token for Cartopy, are you able to download the sdist artifact from that release run and upload it to PyPI?

**Comment by xylar** [comment]
I've bypassed the `setuptools-scm` issue on cond-forge so this is not pressing for us.

**Comment by greglucas** [comment]
Lets actually leave this open until we get the sdist uploaded PyPI for v0.22.

**Comment by dopplershift** [comment]
I just uploaded the Cartopy-0.22.0.tar.gz that was built in that job.
