### ISSUE TITLE
flake8: increase max line length?

### ISSUE THREAD

**Issue by rcomer** [SciTools/cartopy#2253]
### Description

Would Cartopy consider increasing its maximum line length to 88 characters, like Matplotlib did at https://github.com/matplotlib/matplotlib/pull/24893?  I keep finding myself needing to rearrange lines because they are just a few characters over the limit.

**Comment by dopplershift** [comment]
I didn't even realize that would be an increase for us. That sounds fine.

**Comment by greglucas** [comment]
Agreed, should be fine especially if you don't wholesale change the current code with black which did have some pushback: https://github.com/SciTools/cartopy/pull/2152
