### ISSUE TITLE
Change the 'from waves import sample_data' line in the 'Contour labels' and the 'Contour transform options' examples ?

### ISSUE THREAD

**Issue by jypeter** [SciTools/cartopy#2270]
I have visited the [Contour labels](https://scitools.org.uk/cartopy/docs/latest/gallery/scalar_data/contour_labels.html) and the [Contour transform options](https://scitools.org.uk/cartopy/docs/latest/gallery/scalar_data/contour_transforms.html) Gallery pages, and both examples use `from waves import sample_data`

Trouble is that I just get an error if I do that !
```
>>> from waves import sample_data
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'waves'
```

I [searched the cartopy site](https://scitools.org.uk/cartopy/docs/latest/gallery/scalar_data/sg_execution_times.html?highlight=waves) and discovered that `waves` was apparently the example script for the [Filled contours Gallery page](https://scitools.org.uk/cartopy/docs/latest/gallery/scalar_data/waves.html) !!

Having to dig this way to find a dependency is not to great... Can you improve the Gallery examples that need the `sample_data` function to tell the user where to find `waves.py`, or just redefine the `sample_data` function in all the scripts that need it?

**Comment by rcomer** [comment]
Actually it looks like this was done at #2044.

**Comment by jypeter** [comment]
Thanks for having checked that !
