### ISSUE TITLE
Tests fail without scipy

### ISSUE THREAD

**Issue by greglucas** [SciTools/cartopy#2275]
### Description

Doing a clean install of Cartopy with `pip install .[test]` ends up with 5 failures and 3 errors due to missing scipy imports. We could either make these optional tests, or add scipy to the testing optional install. Further, would we want to add the other optional things to the test installation? `test = ["cartopy[ows,plotting,speedups]", ...` i.e. should the testing option be as complete as possible, or should those truly only be if people want to test those branches?

```python
FAILED lib/cartopy/tests/mpl/test_mpl_integration.py::test_quiver_regrid - ImportError: Regridding vectors requires scipy.
FAILED lib/cartopy/tests/mpl/test_mpl_integration.py::test_quiver_regrid_with_extent - ImportError: Regridding vectors requires scipy.
FAILED lib/cartopy/tests/mpl/test_mpl_integration.py::test_barbs_regrid - ImportError: Regridding vectors requires scipy.
FAILED lib/cartopy/tests/mpl/test_mpl_integration.py::test_barbs_regrid_with_extent - ImportError: Regridding vectors requires scipy.
FAILED lib/cartopy/tests/mpl/test_mpl_integration.py::test_streamplot - ImportError: Regridding vectors requires scipy.
ERROR lib/cartopy/tests/test_img_transform.py
ERROR lib/cartopy/tests/test_vector_transform.py
ERROR lib/cartopy/tests/mpl/test_contour.py
```

**Comment by dopplershift** [comment]
If the library can work fully without spicy installed, then I'd mark those tests to skip if the library isn't installed. `pytest.importorskip` is probably helpful here.

**Comment by lgolston** [comment]
I also think skipping the scipy tests is reasonable in this situation, given that: this is what is already done currently with fiona, and the CI test suite runs with the optional dependencies so those tests aren't neglected.
