### ISSUE TITLE
Cartopy Install Fail

### ISSUE THREAD

**Issue by adominious** [SciTools/cartopy#2291]
I am trying to install `cartopy` on a version of Arch Linux (EndeavourOS), whenever I run  `paru -S python-cartopy`, I am met with many errors, none of which I fully understand (I am very new to all of this!)

I attached the output of my terminal when running the command, this is what I was met with. Any help would be much appreciated.

[terminal_output.txt](https://github.com/SciTools/cartopy/files/13428411/terminal_output.txt)

**Comment by rcomer** [comment]
I am not familiar with `paru`, but it seems to be finding an older Cartopy version that was indeed more difficult to install.  Are you able to use `pip` or `conda`?

**Comment by QuLogic** [comment]
If you are installing via the package manager, you need to report this failure to your distribution.

**Comment by adominious** [comment]
Creating a virtual environment and using `pip install cartopy` was successful.

For context, `paru` is just a package manager similar to `yay`. I will report this failure as suggested.
