### ISSUE TITLE
GOOGLE_MERCATOR representation very slow (offline mode)

### ISSUE THREAD

**Issue by robin-cls** [SciTools/cartopy#2292]
### Description

Hi, I am reporting a possible error relating to using cartopy in offline_mode. I am trying to represent the the GOOGLE_MERCATOR projection using the magic method __repr__ but it is very slow (several minutes). I work behind a proxy so I have no internet, so I suspect some web requests are pending but I am not sure of this.

Anyway, setting up the proxy connection gives the normal behavior, and it seems odd to have this difference of behavior because I use cartopy_offlinedata and should not need anything from the web.

Is somebody able to reproduce this behavior ?

#### Code to reproduce

``` python
import cartopy
import time
start = time.time()
cartopy.crs.GOOGLE_MERCATOR.__repr__()
print(f"Done in {time.time() - start:.3f} s")
```

#### Traceback
```
Done in 0.070 s # With internet
Done in 300.860 s # No internet
```

### More details for geoviews users

I found this behavior because the [geoviews](https://github.com/holoviz/geoviews) import took a very long time in our setup (conda environment, no internet). After analysis the import, we found out that setting `param.parameterized.docstring_signature = False` was working around the slow import.

This setting was simply telling the Ipython Pager not to try and fill the docstring for the different Parameterized classes in geoviews. The problematic class was `geoviews.element.geo.WMTS`, which overrides the default crs Param.ClassSelector from PlateCarree() to GOOGLE_MERCATOR. This lead us to looking at the representation methods of the latter projection and we have observed that its `__repr__()` was taking a very long time to execute, explaining the slow geoviews import.

<details>
 <summary>Full environment definition</summary>

### Operating system
Redhat 8

### Versions
cartopy: 0.22.0
cartopy_offlinedata: 0.22.0
proj: 9.3.0
pyproj: 3.6.1

</details>

**Comment by greglucas** [comment]
I'm not able to reproduce this by turning the internet off on my local system.

It might be worth looking at pyproj network settings:
https://pyproj4.github.io/pyproj/dev/api/network.html#network-api
or the transformation grids to see what grids it is trying to download and possibly download those ahead of time if necessary:
https://pyproj4.github.io/pyproj/dev/transformation_grids.html

**Comment by robin-cls** [comment]
You were spot on thanks. I installed the `proj-data` Conda package and it has done the two recommendations for me (PROJ_DATA folder filled with grids and PROJ_NETWORK set to OFF).
Works like a charm so I'll keep in mind that `cartopy_offlinedata` and `proj-data` works in tandem.
