### ISSUE TITLE
UN map is blank on latest docs

### ISSUE THREAD

**Issue by QuLogic** [SciTools/cartopy#2297]
### Description

I was looking at the [UN map example](https://scitools.org.uk/cartopy/docs/latest/gallery/miscellanea/un_flag.html), and it's all white:

![image](https://github.com/SciTools/cartopy/assets/302469/876f23ca-fc83-4a1b-affa-aebf4aa5a554)

**Comment by rcomer** [comment]
This seems to have changed between v0.21.0 and v0.21.1.  If I pin shapely <2 and have latest everything else, the map shows up fine.

**Comment by rcomer** [comment]
I have no idea how, but #2325 appears to have fixed this.
[Circle Docs](https://output.circle-artifacts.com/output/job/5d59515d-9bf7-455a-b8a9-c20441b3388e/artifacts/0/docs/build/html/gallery/miscellanea/un_flag.html#sphx-glr-gallery-miscellanea-un-flag-py)
