### ISSUE TITLE
About Cartopy support Shapely version

### ISSUE THREAD

**Issue by eraevil** [SciTools/cartopy#2300]
Can cartopy support Shapely>2.0? I use a package called transbigdata, but it conflicts with the version Shapely dependency version dependency required by cartopy, which bothers me a lot. At present, I am using python3.8 and cartopy-0.2.0. Do the later versions support Shapely packages with versions greater than 2.0? Looking forward to your reply. Thanks！

**Comment by dopplershift** [comment]
Cartopy >= [0.21.1](https://github.com/SciTools/cartopy/releases/tag/v0.21.1) is compatible with shapely >= 2.0.

**Comment by eraevil** [comment]
thank you very much! I will try it.
