### ISSUE TITLE
`cartopy 0.22.0**  does not exist` for github actions?

### ISSUE THREAD

**Issue by raphaelquast** [SciTools/cartopy#2308]
### Description

While updating unittests for [EOmaps](https://github.com/raphaelquast/EOmaps) to include python 3.11 and 3.12, I ran into the following issue:

First I had `- cartopy >=0.20.0` in the environment and the installation works in `python 3.8 - 3.10` but failed on `python 3.11` and `3.12`.

In the log, I noticed that cartopy didn't resolve to the most recent version, so I tried to force `cartopy=0.22.0`  

This results in the following error (conda-channel is set to `conda-forge`):

```
  Looking for: ['numpy', 'scipy', 'pandas', 'geopandas', "matplotlib[version='>=3.4']", 'descartes', 'mapclassify', 'pyproj', 'cartopy=0.22', 'datashader', 'netcdf4', 'xarray', 'rioxarray', 'owslib', 'requests', 'xmltodict', 'cairosvg', 'nbformat', 'coveralls', 'pytest', 'pytest-cov', 'docutils', 'jupyter', 'nbformat', 'python=3.10']
  
  
  Could not solve for environment specs
  The following package could not be installed
  └─ cartopy 0.22**  does not exist (perhaps a typo or a missing channel).
```

https://github.com/raphaelquast/EOmaps/actions/runs/7366542527/job/20048908647#step:3:679

Any idea why `cartopy 0.22.0` is somehow not available for the github actions (run on `ubuntu-latest`)?
If I try locally (on windows 10), everything installs just fine...

**Comment by akrherz** [comment]
This likely should be reported to [conda-forge/cartopy-feedstock](https://github.com/conda-forge/cartopy-feedstock), what's confusing me at the moment is that your example is showing python=3.10 failing, not 3.11 nor 3.12.  Perhaps try [mamba-org/setup-micromamba](https://github.com/mamba-org/setup-micromamba) to bootstrap your env?

**Comment by raphaelquast** [comment]
thanks for the quick response!

I guess it fails in any python version at the moment... python 3.10 was just the first one to encounter the issue.
(tests are run on 3.9-.312)

I checked using only pyhton 3.11 and 3.12 and the result is the same:
https://github.com/raphaelquast/EOmaps/actions/runs/7366664781/job/20049136881#step:3:535

I'll give micromamba a try!

**Comment by raphaelquast** [comment]
OK, micromamba seems to work just fine on ubuntu! Thanks for the tip!


https://github.com/raphaelquast/EOmaps/actions/runs/7366929322/job/20049632475

but it creates a segmentation-fault on windows

**Comment by akrherz** [comment]
Yeah, your segfault appears to be happening when running your test suite

> tests/test_WMS_capabilities.py::TestWMS::test_ArcGIS_REST_API PASSED     [  0%]
Windows fatal exception: access violation

Likely not a cartopy issue.

**Comment by raphaelquast** [comment]
@akrherz thanks for your comments!  
I'll close this since `micromamba` is perfectly able to locate cartopy 0.22.0 and I've decided to keep using it since it also supports caching environments. Thanks for the tipp!
