### ISSUE TITLE
cannot import name lgeos

### ISSUE THREAD

**Issue by 1996potato** [SciTools/cartopy#2310]
**I am using Python 3.10, I am using GEOS version 0.2.3, and my Cartopy is 0.20.2. My code is**
Import cartopy.crs as ccrs
Import matplotlib.pyplot as plt
Ax=plt. axes (projection=ccrs. Mollweide())
Ax.stock_ Img()
Ax. coastlines()
Plt. show()
**The running result is:**
Traceback (most recent call last):
File "C: \ Users \ ASUS \ PycharmProjects \ pythonProject \ 2024106. py", line 1, in<module>
Import cartopy.crs as ccrs
File "D: \ python310 \ lib \ site packages \ cartopy \ _ init__. py", line 110, in<module>
Import cartopy.crs
File "D: \ python310 \ lib \ site packages \ cartopy \ crs. py", line 27, in<module>
Import cartopy.track
File "trace. pyx", line 77, in init cartopy.trace
ImportError: cannot import name lgeos

**Here is the information in the cartopy package, as well as information on other packages associated with cartopy**
![微信图片_20240107014851](https://github.com/SciTools/cartopy/assets/155841274/97816d69-811b-4ca5-a3c7-aab5b650f01f)
![微信图片_20240107014841](https://github.com/SciTools/cartopy/assets/155841274/28b645cf-7918-4237-86e5-7f284df24fbb)

I want to know how to solve this problem. Thank you!

**Comment by rcomer** [comment]
Hello @1996potato, are you able to upgrade to the latest Cartopy version - 0.22?  Considerable work went into that version to alleviate installation issues.

**Comment by 1996potato** [comment]
> Hello @1996potato, are you able to upgrade to the latest Cartopy version - 0.22? Considerable work went into that version to alleviate installation issues.

I have tried, but it seems difficult to install successfully. I finally found the version that suits me here(https://www.lfd.uci.edu/~gohlke/pythonlibs/#shapely)
![8f9e07f2950bc53c25efd1fa519b678](https://github.com/SciTools/cartopy/assets/155841274/4307e161-c474-4f57-ad39-d48a1fcd0343)
