### ISSUE TITLE
Support pcolormesh set_ methods

### ISSUE THREAD

**Issue by pelson** [SciTools/cartopy#233]
Because of cartopy's cleverness with pcolormesh, it is now no longer possible to use the `set_` family of methods to correctly set pcolormesh properties after instantiation. Wrap the result so these methods can continue to work as expected.

**Comment by philippjfr** [comment]
Any news on this? It would help a lot for quickly animating plots in the [cube-explorer project](https://github.com/CubeBrowser/cube-explorer).

**Comment by pelson** [comment]
> Any news on this?

Afraid not. It isn't a *huge* task, but does get fairly deep into matplotlib-isms and the often unpleasant wrapping of plot methods in cartopy.

> It would help a lot for quickly animating plots in the cube-explorer project.

Agreed. Let's keep that one on the possibilities list - it may be that it would provide sufficient collateral benefit to the cube-explorer project that we tackle it in the near future. From the cube-explorer's perspective it is good to have a simple optimisation in the back-pocket once we have refined the interface itself.

**Comment by greglucas** [comment]
The global_wrap_3 image is currently failing because the boundary is not clipping the polygons on the boundary exactly to produce a black boundary line. Instead, the colors are being aliased out the edges. I think this is related to: https://github.com/matplotlib/matplotlib/issues/15952

**Comment by rcomer** [comment]
Was this addressed by #1496?

**Comment by rcomer** [comment]
> Was this addressed by #1496?

I'm going to assume it was.  If there are other set_ methods that are missing and wanted, someone can always open a more specific issue.
