### ISSUE TITLE
Plotting custom coastline - regression since 0.19

### ISSUE THREAD

**Issue by oliviermarti** [SciTools/cartopy#2335]
### Description
I tried to plot the coastline of my ocean model. The line should be interrupted between continental masses

It's OK with orthographic projection and most polar projection I have tested
It fails with Robinson, Hammer, etc ...

Observed with cartopy 0.22. It works fine with cartopy 0.19

### Code to reproduce
```
# Dataset with position (longitude and latitude) of the coastline of the model
# Between each continental mass, there is a point with lon/lat=nan
# This allow to interrupt the coastline between 1 continents
dc=xr.open_dataset ("https://thredds-su.ipsl.fr/thredds/dodsC/tgcc_thredds/work/p86mart/GRAF/DATA/orca2.3_coastline.nc")

fig = plt.figure(figsize=(12,12))

ProjIn   = ccrs.PlateCarree (central_longitude=0)
ProjPlot = ccrs.Robinson    (central_longitude=0)
#ProjPlot = ccrs.Orthographic    (central_longitude=0)

ax = fig.add_subplot (1, 1, 1, projection=ProjPlot)
ax.coastlines (lw=0.2)
ax.gridlines (draw_labels=True, crs=ProjIn)

# The following is OK with Orthographic projection and most polar projection I have tested
# It fails with Robinson, Hammer, etc ...
# With message : 
#      GEOSException: IllegalArgumentException: CGAlgorithmsDD::orientationIndex encountered NaN/Inf numbers
ax.plot (dc['lon_coast'], dc['lat_coast'], transform=ProjIn)
```

### Software versions
Version python     :  3.11.7 
Version numpy      :  1.26.3
Version xarray     :  2024.1.1
Version Matplotlib :  3.8.2
Version Cartopy    :  0.22.0

**Comment by lgolston** [comment]
Hello @oliviermarti, based on the error, this seems dependent on the behavior of shapely/geos upstream. Since the original dataset does contain nan values, I would suggest splitting the plot on the nan values, e.g.

```
import numpy as np
indices = np.flatnonzero(np.isnan(dc['lon_coast']))

x0 = 0
for ii in range(indices.size):        
    x1 = indices[ii]
    ax.plot(dc['lon_coast'][x0:x1], dc['lat_coast'][x0:x1], 'k', transform=ProjIn)
    x0 = x1 + 1
```

**Comment by oliviermarti** [comment]
Hello @lgolston,

I know there is available workarounds. Mine is base on matplotlib patches.

But,

- Should we consider as normal that a thing that could be done in 1 line with old software now needs 8 ?

- Jumping above nan is a normal and documented behavior of matplotlib plot. 

- The problem is encountered in only a small set of cartopy projection. So the 'normal' behavior off cartopy is still to jump above nan.

So I'm not really happy to have to use a workaround ...

But, I'm a bit distracted guy ... See ticket https://github.com/SciTools/cartopy/pull/2262 from me a few month ago.  The same ... ! If I understand well, the problem should be solved in next version. So  let's use a workaround for a few months :-)

Thank you for caring !

Olivier

PS : my workaround

```
from matplotlib.path import Path
import matplotlib.patches as mpatches

codes = np.where ( np.isnan(lon_coast), Path.MOVETO, Path.LINETO  )
codes[0] = Path.MOVETO
coast_path = Path (np.stack([lon_coast, lat_coast]).T, codes)
ax.add_patch (mpatches.PathPatch (coast_path, facecolor='none', edgecolor='blue', lw=3, transform=ProjIn))
```

**Comment by rcomer** [comment]
Thanks for the pointer to #2262.  I just tried the code from the OP with our `main` development branch and got this:

![image](https://github.com/SciTools/cartopy/assets/10599679/796de80b-be5b-4790-a354-10648878f05e)

So I agree this seems to be fixed for the next release, and so I will close this.  Please say if I've missed something that still needs doing.

**Comment by oliviermarti** [comment]
Perfect ! Thanks again.
