### ISSUE TITLE
Cartopy 0.23 release

### ISSUE THREAD

**Issue by greglucas** [SciTools/cartopy#2339]
### Description

Our last release was in August 2023, which means we haven't released since Python 3.12 has come out which I did not realize 😮 
https://github.com/SciTools/cartopy/releases

I think we should aim for a release soon. Numpy 2.0 is coming out soon as well, so we will for sure need one after that. Should we wait for that, or should we do a release before that pinning to `numpy<2` before that is released and then release another one right after that?

Are there any PRs / issues we need to address before the release?
Two issues in the milestone that aren't really dealbreakers: https://github.com/SciTools/cartopy/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Next+Release%22
There are a few PRs, but all of these have been around for a while at this point so probably not necessary to hold up the release for either: https://github.com/SciTools/cartopy/pulls?q=is%3Aopen+is%3Apr+milestone%3A%22Next+Release%22

**Comment by rcomer** [comment]
Once #2338 is in, would we still need the pin if we release before numpy?

**Comment by rcomer** [comment]
https://github.com/numpy/numpy/issues/24300 recommends releasing shortly after the first 2.0 rc is out.  That appears to be imminent so unless it slips a lot more I'm not sure we gain anything by releasing first.

**Comment by neutrinoceros** [comment]
Numpy 2.0.0rc1 is out now

**Comment by greglucas** [comment]
v0.23 has been released now 🎉 
https://github.com/SciTools/cartopy/releases/tag/v0.23.0
https://pypi.org/project/Cartopy/0.23.0/
