### ISSUE TITLE
The left extent has a boundary when plotting using Cartopy?

### ISSUE THREAD

**Issue by RbHou** [SciTools/cartopy#2359]
Hi, everyone. I am a new user of Cartopy. I came up with a problem when plotting a map with this package. That is the left extent of the figure does not work as expected. Here is my code:

from matplotlib import pyplot as plt
from cartopy import config
import cartopy.crs as ccrs
import cartopy.feature as cfeature

plt.rcParams['font.family'] = 'Times New Roman'

fig = plt.figure(figsize=(10, 10))
data_crs = ccrs.UTM(zone="54")
ax = fig.add_subplot(1, 2, 1, projection=data_crs)

extent1 = (-8590999.50109861663,1175979.2740885501,3318785.3743070965,5139873.132667384)
ax.set_extent(extent1, crs=data_crs)

ax.add_feature(cfeature.LAND)
ax.coastlines(resolution='50m')
ax.gridlines()
gl = ax.gridlines(draw_labels=True)
gl.xlabels_top = False
gl.ylabels_right = False
gl.xlabel_style = {'size': 25}
gl.ylabel_style = {'size': 25}
plt.xlabel('Latitude (deg)', fontsize=20)
plt.ylabel('Longitude (deg)', fontsize=20)

#
ax = fig.add_subplot(1, 2, 2, projection=data_crs)
extent2 = (-3590999.50109861663,1175979.2740885501,3318785.3743070965,5139873.132667384)
ax.set_extent(extent2, crs=data_crs)

ax.add_feature(cfeature.LAND)
ax.coastlines(resolution='50m')
ax.gridlines()
gl = ax.gridlines(draw_labels=True)
gl.xlabels_top = False
gl.ylabels_right = False
gl.xlabel_style = {'size': 25}
gl.ylabel_style = {'size': 25}
plt.xlabel('Latitude (deg)', fontsize=20)
plt.ylabel('Longitude (deg)', fontsize=20)

The variables extent1 and extent2 define different left boundaries. However, the plotting results are the same. I used ax.get_extent() to find the left boundary coordination and get the results of -249999.64635181264. If I continuously make the left boundary move right to a value larger than -249999.64635181264, it works on the map. 

So what is the reason? 

Here is my device:  Operating system Win11, Cartopy version 0.22.0,  python 3.11.8

Any suggestion would be appreciated.
![fig](https://github.com/SciTools/cartopy/assets/39408664/4f6d088a-088c-401c-899c-5cfc147bc93e)

Ruibin Hou

**Comment by QuLogic** [comment]
UTM zones are generally only 6° longitude wide. That being said, it appears that the boundaries are fairly hard-coded:
https://github.com/SciTools/cartopy/blob/75ec0fadf0078256e2f87944d147e1b5e8f93fc1/lib/cartopy/crs.py#L1544-L1561
That probably won't work well for non-Earth globes, for example, though I'm not sure how often one would use UTM on other planets.

**Comment by RbHou** [comment]
> UTM zones are generally only 6° longitude wide. That being said, it appears that the boundaries are fairly hard-coded:
> 
> https://github.com/SciTools/cartopy/blob/75ec0fadf0078256e2f87944d147e1b5e8f93fc1/lib/cartopy/crs.py#L1544-L1561
> 
> 
> That probably won't work well for non-Earth globes, for example, though I'm not sure how often one would use UTM on other planets.

Dear [QuLogic](https://github.com/QuLogic), thanks for your answer, which clearly explained the reason. Maybe I should use zone=53 as projection. I will try it.
