### ISSUE TITLE
figsize is not affecting the actual figure size of a matplotlib figure when a cartopy projection is applied

### ISSUE THREAD

**Issue by habtie-phys** [SciTools/cartopy#2374]
consider the following script that gives grids of matplotlib axes with a cartopy projection
```
proj = ccrs.LambertAzimuthalEqualArea(central_latitude = clat, central_longitude = clon)
fig,axes = plt.subplots(1,3, figsize=(10,10),subplot_kw={'projection':proj})
```

changing the figsize parameter is not affecting the actual fig size when a cartopy projection is applied. In addition, even though the given width and heights of the fig are equal, the result figure doesn't show that.  However, this issue is not the case when the number of axes in the subplot is 1
![cartopy_fig](https://github.com/SciTools/cartopy/assets/37933681/0cf9db60-e5d6-4554-8388-cec523bd04c4)

**Comment by QuLogic** [comment]
Are you running in a notebook or a script? Please provide a complete example.

**Comment by habtie-phys** [comment]
thanks for the reply. I run the code from VScode Jupyter notebook. 

Here is the complete code. The plot parameters can be obtained from the  attached json file
[plot_params.json](https://github.com/SciTools/cartopy/files/15089905/plot_params.json)

`
import json
from matplotlib import pyplot as plt
import cartopy.crs as ccrs

with open('plot_params.json', 'r') as f:
    plot_params = json.load(f)
# 
glon_e3d = plot_params['glon_e3d']
gclat_e3d = plot_params['gclat_e3d']
glon_test = plot_params['glon_test']
gclat_test = plot_params['gclat_test']
lon_secs = plot_params['lon_secs']
lat_secs = plot_params['lat_secs']
# 
proj = ccrs.LambertAzimuthalEqualArea(central_latitude = clat, central_longitude = clon)
fig,axes = plt.subplots(1,3, figsize=(10,10),subplot_kw={'projection':proj})
axs = axes.ravel()
# 
extent = [205, 225, 65, 69]
ax = axs[0]
ax.gridlines()
ax.set_extent(extent, crs=ccrs.PlateCarree())
ax.scatter(glon_e3d, gclat_e3d, transform = ccrs.Geodetic(), c = 'k', marker = '.', label = 'data points', s=10)
# 
ax = axs[1]
ax.gridlines()
ax.set_extent(extent, crs=ccrs.PlateCarree())
ax.scatter(glon_test, gclat_test, transform = ccrs.Geodetic(), c = 'k', marker = '.', label = 'data points', s=10)
# 
ax = axs[2]
ax.gridlines()
ax.set_extent(extent, crs=ccrs.PlateCarree())
ax.scatter(lon_secs, lat_secs, transform = ccrs.Geodetic(), c = 'k', marker = '.', label = 'data points', s=10)

plt.show()`

when the number of axes in the subplots is 1, the figsize parameter affects the actual size of the figure without changing extent of the axis. However, this is not the case when the number of the axes is higher than 1

**Comment by rcomer** [comment]
Cartopy's axes all have fixed aspect ratios so will not fill up the figure when arranged like this.  The default backend used by Jupyter always resizes the figure to fit around the artists on it.  I suspect you will see consistent behaviour if you do a more simple plot without Cartopy:

```python
import matplotlib.pyplot as plt

fig, ax_arr = plt.subplots(1,3, figsize=(10,10))

for ax in ax_arr:
    ax.set_aspect('equal')
```

**Comment by habtie-phys** [comment]
thanks for the reply. you right, I got the same issue with the above code also. I will leave open the issue in case some one suggests a general solution

**Comment by dopplershift** [comment]
@habtie-phys Right, `ax.set_aspect('equal')` is equivalent to what _every_ Cartopy-based plot is doing due to the nature of plotting on geographic projections.

There isn't a general solution to this problem currently given that Matplotlib doesn't have a dynamic layout engine for Axes. Instead Matplotlib provides various APIs for carving out rectangles from a figure, which Axes are then free to adjust within to suit their needs.

Closing since at best anything addressing this would have to happen in Matplotlib itself.

**Comment by habtie-phys** [comment]
@dopplershift thank you for the reply. Now I understand that this is not the right place for the issue to remain open.
