### ISSUE TITLE
pcolormesh does not conform to country and state boundaries

### ISSUE THREAD

**Issue by AgilentGCMS** [SciTools/cartopy#2425]
### Description
I am trying to plot some simple country masks on top of country and state borders with cartopy. I have verified that the masks are correct, but do not correspond to country and state borders drawn by cartopy. The problem is best illustrated with a continental US country mask [here](https://drive.google.com/file/d/1VQErvmabC4o2sqKc2ZBa9L_spsJhVjFr/view?usp=sharing).

#### Code to reproduce
First, let's check that the country mask is actually correct. The US-Canada border between 121 W and 98 W runs exactly along 49 N, which makes checking the mask along that part of the border easy.
```python
from netCDF4 import Dataset
with Dataset('us_mask.nc', 'r') as fid:
    cmask = fid.variables['us_mask'][:] # 0.1x0.1 country mask

cmask[1389,590:820] # the row just south of 49N between 121W and 98W, should be all 1s
cmask[1390,590:820] # the row just north of 49N between 121W and 98W, should be all 0s
```
Now let's try to plot on a couple of different projections
```python
from netCDF4 import Dataset
import numpy as np
import cartopy.crs as ccrs
import cartopy.feature as cfeature
from matplotlib import pyplot as plt

# read the mask
with Dataset('us_mask.nc', 'r') as fid:
    us_mask = fid.variables['us_mask'][:]

# common plotting parameters
lat_edges = np.linspace(-90., 90., 1801)
lon_edges = np.linspace(-180., 180., 3601)
data_proj = ccrs.PlateCarree(central_longitude=0.0)
coast_width = 0.7

# try plotting on Robinson projection
map_proj = ccrs.Robinson(central_longitude=0.0)
aspect = (map_proj.x_limits[1]-map_proj.x_limits[0])/(map_proj.y_limits[1]-map_proj.y_limits[0])
fig = plt.figure(figsize=(5*aspect, 5))
ax = plt.axes([0, 0, 1, 1], projection=map_proj)
ax.add_feature(cfeature.LAKES.with_scale('50m'), linewidth=0.5, edgecolor='k', facecolor='none')
ax.add_feature(cfeature.BORDERS.with_scale('50m'), linewidth=0.5*coast_width, edgecolor='0.25')
ax.add_feature(cfeature.COASTLINE.with_scale('50m'), linewidth=coast_width, edgecolor='k')

img = ax.pcolormesh(lon_edges, lat_edges, us_mask, transform=data_proj, cmap=plt.cm.Reds, vmin=0, vmax=1, edgecolors='face', shading='flat')

# now with nearsided perspective
map_proj = ccrs.NearsidePerspective(central_longitude=-98.5, central_latitude=39.8, satellite_height=3.0E6)
aspect = (map_proj.x_limits[1]-map_proj.x_limits[0])/(map_proj.y_limits[1]-map_proj.y_limits[0])
fig = plt.figure(figsize=(5*aspect, 5))
ax = plt.axes([0, 0, 1, 1], projection=map_proj)
ax.add_feature(cfeature.LAKES.with_scale('50m'), linewidth=0.5, edgecolor='k', facecolor='none')
ax.add_feature(cfeature.BORDERS.with_scale('50m'), linewidth=0.5*coast_width, edgecolor='0.25')
ax.add_feature(cfeature.COASTLINE.with_scale('50m'), linewidth=coast_width, edgecolor='k')

img = ax.pcolormesh(lon_edges, lat_edges, us_mask, transform=data_proj, cmap=plt.cm.Reds, vmin=0, vmax=1, edgecolors='face', shading='flat')
```

#### Output
Both the nearside perspective projection
![Screenshot 2024-08-20 at 3 07 54 PM](https://github.com/user-attachments/assets/20f3a0c4-c0df-45f6-934c-64301fcf672b)
and the Robinson projection
![Screenshot 2024-08-20 at 3 08 01 PM](https://github.com/user-attachments/assets/c8d206b4-98c9-4d0c-bc5f-544ad4f565ef)
shows a thin empty space between the mask and the 49th parallel. If I zoom in that space disappears
![Screenshot 2024-08-20 at 3 09 46 PM](https://github.com/user-attachments/assets/ab59f980-2044-448d-acd0-2ad94cfb1997)
And if I save to a PNG file that space disappears also. So this is a problem with rendering on the screen and not necessarily the underlying data.

<details>
 <summary>Full environment definition</summary>

### Operating system
MacOS Sonoma 14.6.1

### Cartopy version
0.21.1

### pip list
```
Package                   Version
------------------------- ---------------
anyio                     4.3.0
arrow                     1.3.0
asttokens                 2.4.1
attrs                     23.2.0
Brotli                    1.1.0
build                     1.0.3
cached-property           1.5.2
Cartopy                   0.21.1
certifi                   2024.7.4
cffi                      1.16.0
cftime                    1.6.3
charset-normalizer        3.3.2
contourpy                 1.2.1
cycler                    0.12.1
Cython                    3.0.10
decorator                 5.1.1
eccodes                   1.7.0
editables                 0.5
exceptiongroup            1.2.0
executing                 2.0.1
fastjsonschema            2.19.1
findlibs                  0.0.5
flit_core                 3.9.0
fonttools                 4.53.1
fortls                    2.13.0
fqdn                      1.5.1
gast                      0.5.2
GDAL                      3.9.1
h11                       0.13.0
h2                        4.1.0
h5py                      3.11.0
hpack                     4.0.0
hyperframe                6.0.1
idna                      3.7
installer                 0.7.0
ipython                   8.23.0
isoduration               20.11.0
jedi                      0.19.1
json5                     0.9.14
jsonpointer               2.4
jsonschema                4.21.1
jsonschema-specifications 2023.12.1
jupyter_core              5.7.2
kiwisolver                1.4.5
linkify-it-py             2.0.3
lxml                      5.2.2
markdown-it-py            3.0.0
matplotlib                3.8.4
matplotlib-inline         0.1.7
mdit-py-plugins           0.4.0
mdurl                     0.1.2
meson                     1.4.0
meson-python              0.16.0
mpldatacursor             0.7.1
mypy                      1.11.1
mypy_extensions           1.0.0
netCDF4                   1.6.5
numpy                     1.26.4
oldest-supported-numpy    0.1
olefile                   0.47
OWSLib                    0.31.0
packaging                 24.1
pandas                    2.2.2
parso                     0.8.4
pathspec                  0.12.1
pexpect                   4.9.0
Pillow                    9.5.0
pip                       24.0
pkgconfig                 1.5.5
platformdirs              4.2.2
pluggy                    1.4.0
prompt_toolkit            3.0.43
ptyprocess                0.7.0
pure_eval                 0.2.2
pybind11                  2.12.0
pycairo                   1.26.1
pycparser                 2.22
pyepsg                    0.4.0
Pygments                  2.17.2
pyparsing                 3.1.2
pyproj                    3.6.1
pyproject_hooks           1.1.0
pyproject-metadata        0.8.0
pyshp                     2.1.3
python-dateutil           2.8.2
pytz                      2024.1
PyYAML                    6.0.1
pyzmq                     25.1.2
rdata                     0.11.2
referencing               0.34.0
requests                  2.32.3
rfc3339_validator         0.1.4
rfc3986_validator         0.1.1
rpds-py                   0.18.0
SciPy                     1.11.4
setuptools                72.2.0
shapely                   2.0.2
six                       1.16.0
sniffio                   1.2.0
socksio                   1.0.0
stack_data                0.6.3
threadpoolctl             3.5.0
tornado                   6.4
tqdm                      4.66.4
traitlets                 5.14.3
trove-classifiers         2024.5.17
types-psutil              5.9.5.20240106
types-python-dateutil     2.9.0.20240316
types-setuptools          69.1.0.20240223
typing_extensions         4.12.2
tzdata                    2024.1
uc-micro-py               1.0.3
unicodedata2              15.1.0
uri-template              1.3.0
urllib3                   1.26.18
wcwidth                   0.2.13
webcolors                 1.13
webencodings              0.5.1
wheel                     0.44.0
xarray                    2024.5.0
zopfli                    0.2.3
```

</details>

**Comment by dopplershift** [comment]
Where's that `us_mask.nc` from? I'm curious if the edges you're calculating are exactly correct.

**Comment by AgilentGCMS** [comment]
> Where's that `us_mask.nc` from? I'm curious if the edges you're calculating are exactly correct.

They are. That was the point of giving the example of the US-Canada border, which between ~123W and ~95W is **exactly** along 49N. For a 0.1x0.1 mask starting at 90S and 180W, longitude indices 590 to 820 is the longitude range 121W to 98W, and latitude index 1389 is the row just south of 49N while 1390 is the row just north of 49N. Therefore, if the mask is correct, `[1389,590:820]` should be all 1s while `[1390,590:820]` should be all zeros, which they are. This is the **one** place where the US border runs exactly along an integer latitude, and therefore will show which one -- the mask or the plot -- is wrong.

**Comment by AgilentGCMS** [comment]
> Where's that `us_mask.nc` from? I'm curious if the edges you're calculating are exactly correct.

Here's another demonstration that the problem is with `pcolormesh` and not the data. Add the following lines to the code above to plot the exact same mask but with `contourf`.
```python
map_proj = ccrs.NearsidePerspective(central_longitude=-98.5, central_latitude=39.8, satellite_height=3.0E6)
aspect = (map_proj.x_limits[1]-map_proj.x_limits[0])/(map_proj.y_limits[1]-map_proj.y_limits[0])
fig = plt.figure(figsize=(5*aspect, 5))
ax = plt.axes([0, 0, 1, 1], projection=map_proj)
ax.add_feature(cfeature.LAKES.with_scale('50m'), linewidth=0.5, edgecolor='k', facecolor='none')
ax.add_feature(cfeature.BORDERS.with_scale('50m'), linewidth=0.5*coast_width, edgecolor='0.25')
ax.add_feature(cfeature.COASTLINE.with_scale('50m'), linewidth=coast_width, edgecolor='k')

lat_centers = 0.5*(lat_edges[1:]+lat_edges[:-1])
lon_centers = 0.5*(lon_edges[1:]+lon_edges[:-1])

img = ax.contourf(lon_centers, lat_centers, us_mask, transform=data_proj, cmap=plt.cm.Reds, vmin=0, vmax=1)
```
This will produce the plot below, where the mask extends all the way to the 49th parallel.
![Screenshot 2024-08-20 at 11 17 12 PM](https://github.com/user-attachments/assets/ee44f5ad-7d15-4345-a00e-976b11b11dab)

**Comment by greglucas** [comment]
A few thoughts to try:

* Does a resize of the window or pan cause that gap to be filled? (One of the artist draws may not be getting triggered early enough)
* Does increasing the DPI affect the output? You are plotting 3600 values into a potentially small number of pixels, so there might be some edge case of 2-3 data bins getting mapped to a single pixel and some form of aliasing going on.
* Does this also manifest itself with a rectangular projection like PlateCarree or is it only when objects are transformed?

**Comment by AgilentGCMS** [comment]
> * Does a resize of the window or pan cause that gap to be filled? (One of the artist draws may not be getting triggered early enough)
No.

> * Does increasing the DPI affect the output? You are plotting 3600 values into a potentially small number of pixels, so there might be some edge case of 2-3 data bins getting mapped to a single pixel and some form of aliasing going on.
How do I increase the DPI of the plot on the screen? You mean increasing the global matplotlib DPI?

> * Does this also manifest itself with a rectangular projection like PlateCarree or is it only when objects are transformed?
See screenshot of PlateCarree. The gap is still there.
![Screenshot 2024-08-21 at 10 42 04 AM](https://github.com/user-attachments/assets/b9c371e3-1d54-4da1-813b-a6d3233ec823)

**Comment by AgilentGCMS** [comment]
I found [this issue](https://bairdlangenbrunner.github.io/python-for-climate-scientists/matplotlib/pcolormesh-grid-fix.html) on the internet, and my problem might be close but it's not identical because I'm providing the lat/lon edges and not the centers. So `cartopy` shouldn't __need__ to interpolate.

**Comment by greglucas** [comment]
I _think_ it actually has to do with your use of `edgecolors="face"`. My guess is that the Canadian edge might be stamping on top of the US edge and trying to blend together. I don't see the artifacts if you remove edgecolors, or if you set the linewidth to something small like 0.1.

**Comment by AgilentGCMS** [comment]
> I _think_ it actually has to do with your use of `edgecolors="face"`. My guess is that the Canadian edge might be stamping on top of the US edge and trying to blend together. I don't see the artifacts if you remove edgecolors, or if you set the linewidth to something small like 0.1.

That was exactly it, thank you! I'm almost positive I had put that `edgecolors="face"` because in some earlier version of cartopy **not** doing that resulted in some default edge color obscuring face colors, but that seems to no longer be the case.
