### ISSUE TITLE
Planning for next release

### ISSUE THREAD

**Issue by greglucas** [SciTools/cartopy#2429]
@raphaelquast would like the feature he added in a new release: https://github.com/SciTools/cartopy/pull/2362#issuecomment-2316096926

We haven't been getting a lot of new PRs/updates lately, so I'm wondering if anyone has any specific items they want to get in or looked at before our next release. We haven't had a formal release timeframe as far as I know, so I'd be happy making a new release sometime soon since it has been a few months.

**Comment by rcomer** [comment]
Python 3.13 is due out on October 1st.  It might be nice to have a release soon after that with 3.13 wheels, unless you were thinking sooner?

**Comment by greglucas** [comment]
That seems reasonable to me! I have not tested on 3.13 yet, but we should probably add an entry to CI for that. We should also be able to build wheels before that if desired since cibuildwheel already support 3.13 https://github.com/pypa/cibuildwheel

**Comment by QuLogic** [comment]
3.13rc1 is out already; we don't need to wait for 3.13, as that is already ABI stable.

**Comment by rcomer** [comment]
> we should probably add an entry to CI for that

Looks like we need to wait for pyproj?
https://github.com/rcomer/cartopy/actions/runs/10653310243/job/29528256784#step:7:43

**Comment by dopplershift** [comment]
Strong +1 for having a 3.13-supporting release out the door.

**Comment by rcomer** [comment]
We still need to publish docs for this.  I had a go but got myself confused.  What commit/doc-build should be used?  I tried with [this build](https://app.circleci.com/pipelines/github/SciTools/cartopy/1882/workflows/07a92d34-d9a9-4320-b927-321508928c98/jobs/3884) which AFAICT comes from the last commit in the v0.24.1 tag, but it displays the version as [0.24.1.dev2+g1c704d1e](https://output.circle-artifacts.com/output/job/8daa2dee-1f11-459d-8514-05013033dc08/artifacts/0/docs/build/html/reference/index.html)
