### ISSUE TITLE
Consider using Fiona for reading Shapefiles

### ISSUE THREAD

**Issue by rsignell-usgs** [SciTools/cartopy#250]
For reading shapefiles, I used to use pyshp, but switched to Fiona 
http://toblerity.github.com/fiona/
based on recommendations from my opensource GIS buddies.  It's pretty cool.

Fiona is also part of the Enthought Python Distribution, which is handy -- one less step for folks trying to build Cartopy.

Just a thought.

**Comment by dopplershift** [comment]
Was this fixed by #1000?

**Comment by QuLogic** [comment]
I think so; I'm going to close.
