### ISSUE TITLE
Python3 compatibility

### ISSUE THREAD

**Issue by pelson** [SciTools/cartopy#289]
Update Cartopy to support Python 3.

@esc24 has already done much of the hard work.

**Comment by QuLogic** [comment]
It's 2015; does your code run on Python 3?
(Hint: The answer _should_ be yes.)

**Comment by pelson** [comment]
I have manually built pyshp for Python 3 and uploaded to the scitools binstar.org channel. Hopefully that allows #499 to move forwards.
