### ISSUE TITLE
clip lambert

### ISSUE THREAD

**Issue by bblay** [SciTools/cartopy#301]
The image [here] (https://github.com/SciTools/cartopy/pull/292#issuecomment-20187920) shows it might be nice to clip the plots to the lambert bounds.

**Comment by QuLogic** [comment]
This doesn't seem to be a problem for me (in an admittedly simple test). @esc24 Could you check as well, (since there was no script for your earlier comment to verify)?

**Comment by pelson** [comment]
> This doesn't seem to be a problem for me (in an admittedly simple test).

I added clipping some time ago - I suspect that has fixed it.

See also #372 and #230.
