### ISSUE TITLE
Orthographic projection broken for Contour plots. 

### ISSUE THREAD

**Issue by mikewalker92** [SciTools/cartopy#318]
Using the orthographic projection with Contour plots returns nonsense for plots covering large potions of the globe. 

Trying this with the cubes from Iris Sample Data, none of the global data sets plotted correctly, and neither did any of the plots of North America or space wesather.

The following code attempts an orthographic contour plot of air_temp.pp

```python
import iris
import cartopy
import matplotlib.pyplot as plt
import iris.quickplot as qplt
import cartopy.crs as ccrs

cube = iris.load_cube(iris.sample_data_path('air_temp.pp'))

plt.axes(projection=ccrs.Orthographic())

qplt.contour(cube, 25)

plt.show()
```

The resulting image is as follows;

![brokenorthoglobal](https://f.cloud.github.com/assets/4940023/1035265/ff44db06-0f27-11e3-96e3-a8f19197a407.png)

On other occassions, such as this plot of A1B_north_america.nc, the following style of result is obtained;

![brokenorthousa](https://f.cloud.github.com/assets/4940023/1035277/3a963d26-0f28-11e3-9617-ab9f137690a3.png)

Source Code: 
```python
cube = iris.load_cube(iris.sample_data_path('A1B_north_america.nc'))
sub_cube = cube[0,:,:]

plt.axes(projection=ccrs.Orthographic())

qplt.contour(sub_cube, 25)

plt.gca().coastlines()

plt.show()
```

However, the size of the area of the earth plotted seemed to have an effect. All of the smallest sections of the globe plotted as expected, with this image of hybrid_height.nc being an example of this. 

![brokenorthosmall](https://f.cloud.github.com/assets/4940023/1035288/6bd67838-0f28-11e3-86f4-3429aeaa9de3.png)

Source Code:
```python
cube = iris.load_cube(iris.sample_data_path('hybrid_height.nc'))
sub_cube = cube[0,0,:,:]

plt.axes(projection=ccrs.Orthographic())

qplt.contour(sub_cube, 25)

plt.gca().coastlines()

plt.show()
```

**Comment by pelson** [comment]
If there is a remaining issue with this in v0.12.0, I'd consider it a bug. The remaining problem that *may* be encountered is an error along the lines of:

```
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
ValueError: need at least one array to concatenate
```

which is a bug with matplotlib (https://github.com/matplotlib/matplotlib/pull/4107) - though a workaround could be found if that is necessary.
