### ISSUE TITLE
Incorrect Cursor Coordinates for Transverse Mercator

### ISSUE THREAD

**Issue by mikewalker92** [SciTools/cartopy#320]
``` python
import cartopy.crs as ccrs
import matplotlib.pyplot as plt

plt.axes(projection=ccrs.TransverseMercator())
plt.gca().coastlines()
plt.show()
```

Moving the cursor towards any of the corners produces very large numbers for the latitude reading, quickly giving results which are orders of magnitude away from the correct value. 

Longitude values do seem to remain within 180 E and 180 W, but on closer inspection do not give the correct position. For example, values will vary wildly in parts of South America.

**Comment by QuLogic** [comment]
If you have a look at the [comments in proj4](https://trac.osgeo.org/proj/browser/trunk/proj/src/PJ_tmerc.c#L25), it appears the Transverse Mercator implementation is only good for about 90° from the central meridian. That being said, I'm a bit surprised that the coastlines don't appear to be unreasonable.

**Comment by QuLogic** [comment]
A comment on the [proj4 ticket](https://trac.osgeo.org/proj/ticket/5#comment:11) mentions an "extended" version of Transverse Mercator. The result is quite reasonable (though the stock image is clearly not high enough resolution for that distortion at the edges):
![etmerc](https://cloud.githubusercontent.com/assets/302469/6437355/d22641b6-c08b-11e4-863e-0077eae58150.png)
but as noted, it is noticeably slower.

I guess a reasonable way forward might be to limit the default extent for Transverse Mercator to be smaller, maybe ±90° or even less, and then add an `extended` argument that could enable this projection instead.

**Comment by pelson** [comment]
>  add an extended argument that could enable this projection instead

Or consider them to be two separate Projections altogether? Thanks for finding this out @QuLogic - I hadn't seen that note about the extended functionality.

**Comment by QuLogic** [comment]
It looks like upstream is going to make this change for us: https://github.com/OSGeo/proj.4/pull/1234
