### ISSUE TITLE
Setting the extent of plots

### ISSUE THREAD

**Issue by mikewalker92** [SciTools/cartopy#321]
``` python
import iris
import cartopy
import matplotlib.pyplot as plt
import iris.quickplot as qplt
import cartopy.crs as ccrs


cube = iris.load_cube(iris.sample_data_path('air_temp.pp'))

plt.axes(projection=ccrs.NorthPolarStereo())

qplt.contourf(cube)

plt.show()
```

![novisibleplot](https://f.cloud.github.com/assets/4940023/1041283/c10c9b94-0fcc-11e3-8faf-7d49570e9729.png)

Obviously, this code has made the plot very small. This can be worked around either by zooming in, or by using the set_global command, but it would be nice not to have to, especially as for some cubes and projections, (such as Stereographic for this cube) there is no visible plot at all. 

I have found this issue to occur for Stereographic, Gnomonic, North and South Polar Stereo and to a lesser extent, Mercator.

Would a check to see if the extents of the plot are larger than the size of the projection be simple a way to improve the ease of use of these projections?

**Comment by ajdawson** [comment]
The example given doesn't produce a sensible plot, however I can't reproduce this in cartopy alone.

Taking the provided example and adding the following results in a correctly drawn plot with sensible extents:

```python
lons = cube.coord('longitude').points
lats = cube.coord('latitude').points
data = cube.data

ax = plt.axes(projection=ccrs.NorthPolarStereo())
ax.contourf(lons, lats, data, transform=ccrs.PlateCarree())
plt.show()
```

It also produces a sensible plot if cyclic point is added:

```python
lons = cube.coord('longitude').points
lats = cube.coord('latitude').points
data = cube.data
cdata, clons = cartopy.util.add_cyclic_point(data, coord=lons)

ax = plt.axes(projection=ccrs.NorthPolarStereo())
ax.contourf(clons, lats, cdata, transform=ccrs.PlateCarree())
plt.show()
```

This leads me to believe that this problem is actually in iris's plot wrappers and not in cartopy.

**Comment by pelson** [comment]
At some point this was resolved. The original code now produces the following:

![figure_1](https://user-images.githubusercontent.com/810663/50780759-ab9dff00-129b-11e9-8005-ba470d8fb14d.png)


This is with:

```
>>> iris.__version__
>>> matplotlib.__version__
'3.0.1'
```

**Comment by pelson** [comment]
54... #321 now this bug is gone. 🤷‍♂️

**Comment by QuLogic** [comment]
This even works with Cartopy 0.16.0; maybe it was fixed in Iris or Matplotlib somehow?
