### ISSUE TITLE
Infinite Loops in Mollweide and Interrupted Goode Homolosine projections

### ISSUE THREAD

**Issue by mikewalker92** [SciTools/cartopy#325]
```
import cartopy.crs as ccrs
import shapely.geometry as sgeom


coords = [(0.0, 89.99998474121094), (356.2499084472656, 89.99998474121094), (356.2499084472656, 88.59124172525557), (0.0, 88.49668475350418)]

geom = sgeom.Polygon(coords)

source = ccrs.PlateCarree()
target = ccrs.InterruptedGoodeHomolosine()
print 'projecting'
target.project_geometry(geom, source)
print 'done'
```

The polygon specified in coords causes this code to never get to the print 'done' command. 

The same polygon will also cause an infinite loop with the Mollweide projection. 

The effect is that currently, Mollweide and Interrupted Goode Homolosine projection frequently get stuck on global and polar data, in both pcolormesh and contourf plots, and, less frequently, also break for countour plots. Hopefully this is all due to the issue represented by this polygon.

**Comment by pelson** [comment]
Closed thanks to @QuLogic's #567.
