### ISSUE TITLE
Ticks going beyond the extent of the graph

### ISSUE THREAD

**Issue by mikewalker92** [SciTools/cartopy#333]
![toomanyticks](https://f.cloud.github.com/assets/4940023/1086881/2a102498-1609-11e3-9792-e5810e01bea7.png)

After having used gridlines(draw_labels=True) on a plot, if you then zoom in onto a smaller area of the plot, the ticks mark points that are now beyond the  extent of the plot, as shown above.

**Comment by pelson** [comment]
Gridliner hasn't currently been designed to update with pan/zoom. Obviously desirable functionality though.

Thanks @mikewalker92.
