### ISSUE TITLE
MODIS 

### ISSUE THREAD

**Issue by rhattersley** [SciTools/cartopy#344]
As [described by Thomas Lecoq](https://groups.google.com/d/msg/scitools-iris/NccdsbrSYdA/w_ZxVUUGBnkJ):

> include a feature-getter to MODIS satellite imagery: http://pymodis.fem-environment.eu/

**Comment by pelson** [comment]
Looks like this amounts to updating the gallery to include the example from Rich's notebook 👍

**Comment by pelson** [comment]
Actually, this is already in the cartopy docs...http://scitools.org.uk/cartopy/docs/latest/examples/wmts_time.html 🎉
