### ISSUE TITLE
Support Swiss projection/tile standards

### ISSUE THREAD

**Issue by rhattersley** [SciTools/cartopy#350]
EPSG:21781 - "Oblique Mercator"

See:
- http://map.geo.admin.ch/
- http://www.swisstopo.admin.ch/

The tile zoom levels are different from powers-of-two.

Add a tile server example?

**Comment by pelson** [comment]
There are examples in the cartopy codebase of other tile schemes - for example https://github.com/SciTools/cartopy/blob/v0.17.0/lib/cartopy/io/img_tiles.py#L410-L497.

Given this, and the ease at which one can now create a raster source, I'm going to close this one. Happy to accept relatively small PRs that would add this capability, but on the whole this would be quite specialist functionality for cartopy to have to maintain - it may be best as a standalone library that follows cartopy standards.
