### ISSUE TITLE
gridlines and rotated grids - latitude lines not in natural position?

### ISSUE THREAD

**Issue by xadder2** [SciTools/cartopy#364]
Should a simple call to gridlines produce lines in "natural" positions, e.g. 50,55,60N for Europe? It doesn't - the hard-coded (ax.plot) 50N line does not coincide with the lines produced by ax.gridlines.

I can fix with this mticker, ylocator etc., but that seems heavy.

Thanks!

Code:

``` python
#!/usr/bin/env python
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import cartopy.crs as ccrs
from cartopy.mpl.gridliner import LONGITUDE_FORMATTER,LATITUDE_FORMATTER

projLonLat=ccrs.PlateCarree() 
projrot=ccrs.RotatedPole(pole_longitude=180+18,pole_latitude=39.25,globe=None)

ax = plt.axes(projection=projrot)
ax.coastlines(resolution='10m')

# Plot a line along 10 degrees E
ax.plot( [10.0, 10.0], [40.0, 65.0], "k--", lw=2,transform=projLonLat)

# Plot a rough line along 50 degrees N
ax.plot( [-10.0,0,10,20,30, 40.0], [50.,50.,50.,50.,50.,50.], "k", lw=3,transform=projLonLat) # ccrs.plateCarree )

gl=ax.gridlines(crs=projLonLat,
                  linewidth=2, color='green', alpha=0.5, linestyle='--')

plt.show()
```

**Comment by greglucas** [comment]
When I run the example code on latest master the tick locations are all reasonable as expected and line up with the dark expected line. So, I believe this is now fixed to more reasonable default values for the locators. Please reopen if you are still having issues.

**Comment by QuLogic** [comment]
My guess is this was fixed by https://github.com/SciTools/cartopy/commit/6061b2c3a711cf7e706ca3b37103bf7c4c52f2b6
