### ISSUE TITLE
Add examples & tutorials

### ISSUE THREAD

**Issue by ThomasLecocq** [SciTools/cartopy#388]
Hi Guys,

Whenever you don't have time, it would be cool to add new examples and tutorials. I should be able to provide a notebook with the tutorial I gave in Brussels last summer, but it needs tweaking. Bill showed also a few nice examples during his presentation there, those were really cool !

And in tutorials: some like "how to create a map with a Belgian Lamber 72 (pyproj string is known)", etc... :-)

**Comment by Khalilsqu** [comment]
@ThomasLecocq Thanks for the examples, they are really great
