### ISSUE TITLE
Extra license file

### ISSUE THREAD

**Issue by QuLogic** [SciTools/cartopy#458]
There are two licenses in the source: [COPYING](../blob/master/COPYING) and [COPYING.LESSER](../blob/master/COPYING.LESSER). One is GPLv3, the other is LGPLv3, but if I've understood the CLA correctly, cartopy should be definitively LGPL and the COPYING file is superfluous.

**Comment by ssalonen** [comment]
@ajdawson Is on the backlog to update the GSHHS dataset to a newer version which would LGPL licensed as mentioned by @QuLogic? If I understood correctly, the dataset bundled with cartopy is GPL licensed still.

**Comment by pelson** [comment]
> Is [it] on the backlog to update the GSHHS dataset to a newer version which would [be] LGPL licensed as mentioned by @QuLogic?

There is nothing lined up to do so, but if that is of value, it is should be easy enough to do.

**Comment by ssalonen** [comment]
Thanks for the fast response! Definitely I think it would be useful to have a non-GPL python library that can be used in a commercial setting "safely". Basemap is not usable as they declare quite clearly that data is under GPL.

Unfortunately upon closer inspection I noticed some other licenses with the data
- HadISST1: [cartopy readme](https://github.com/SciTools/cartopy/blob/master/lib/cartopy/data/netcdf/HadISST1_SST_update.README.txt), [source terms and conditions](http://www.metoffice.gov.uk/hadobs/hadisst/terms_and_conditions.html)
- raster/** license unclear?

Have you got some special license for the HadISST1 or raster images?

**Comment by pelson** [comment]
>  Basemap is not usable as they declare quite clearly that data is under GPL.

IANAL :cop: but have you checked your assertion with somebody who is? I admit the GPL interpretation is gray, but if you are a consumer of the GSSH data, not making derivatives of it, there are a lot of freedoms granted. For instance, both the Linux kernel and GCC are GPL, yet they are used everyday in commercially situations without complexity.

On the other hand, I have experienced first hand the deep intake of breath when the GPL license is discussed with legal-folk, so I do agree with the sentiment of moving towards the LGPL provisioned GSSH.

**Comment by ssalonen** [comment]
Yes you are definitely right that the license might allow it...but indeed a lawyer is needed to be 100% sure :) 

GCC has special runtime library exception so that makes it a bit different, and even Linux has [some exceptions when it comes to modules].  But certainly data in a python library is gray area...

I think the minimum should be that we document the licenses of different datasets bundled (see my previous post listing some concerns regarding other data). If we can update data to make them use more liberal license, even better!

**Comment by pelson** [comment]
> If we can update data to make them use more liberal license, even better!

:+1: 

> see my previous post listing some concerns regarding other data

>> HadISST1: cartopy readme, source terms and conditions

The license wasn't clear on this data. @marqh - do you know if this is under the Open Government License?

>> raster/** license unclear?

In there is Natural Earth data (http://www.naturalearthdata.com/about/terms-of-use/) and a piece of sample data from http://lance-modis.eosdis.nasa.gov. I haven't looked, but I'm sure the latter has a license associated with the data.

Cartopy intentionally ships with very little data, and functions without any of it (unless you want coastlines, which necessarily does need some data). The raster and GSSH data can be removed from the deployed cartopy, if that is a concern.

Are you happy to take this forwards @ssalonen - this requires somebody to take a little bit of thought on how to document the licenses appropriately, and it sounds like you may have some experience in this matter.

Thanks!

**Comment by marqh** [comment]
> The license wasn't clear on this data. @marqh - do you know if this is under the Open Government License?

I'm afraid I don't, the data owners would need to be contacted to find out more about this
