### ISSUE TITLE
Update srtm.py to get hole-filled product

### ISSUE THREAD

**Issue by scottyhq** [SciTools/cartopy#480]
I noticed the srtm.py fetches data from "http://dds.cr.usgs.gov/srtm/version2_1/SRTM3/". There are then ways to fill the holes and shade (#396). 

Since 11/2013, A newer version of void-filled SRTM was [made available](https://earthdata.nasa.gov/about-eosdis/news/nasa-shuttle-radar-topography-mission-srtm-v30-product-release-lpdaac) via NASA/USGS [LPDAAC](https://lpdaac.usgs.gov/data_access/data_pool).

The server url is new, but the syntax is similar to before (without region subfolders):

"http://e4ftl01.cr.usgs.gov/SRTM/$type.003/2000.02.11/$file" 
Where $type is either 'SRTMUS1' for 30m data over the US, or 'SRTMGL3' for 90m data over the rest of the world. And $file is essentially the same naming scheme (e.g. N18E145.SRTMGL3.hgt.zip). Also, there is other imagery available via the same server, which might be of interest to users.

I could take a stab at a pull request for getting the new data, but am pretty new to pull requests...

**Comment by QuLogic** [comment]
This will be fixed by #690.
