### ISSUE TITLE
import fails due to unchecked dependency failure

### ISSUE THREAD

**Issue by WeatherGod** [SciTools/cartopy#483]
Originally was https://github.com/SciTools/iris/issues/1338

A fresh install of cartopy on a CentOS6 system was successful through "pip install cartopy". Since I was focusing on getting Iris installed and cartopy was only installed as a dependency, I didn't notice the requirement of proj4 version 4.8.0, and the install of cartopy failed to check this. Matplotlib is capable of checking versions of non-python dependencies on build, perhaps code from there could be borrowed? Just need to run "proj" and you get a version string back.

**Comment by QuLogic** [comment]
Odd, I'd have thought the extension would fail to compile without it.
