### ISSUE TITLE
Enable UTM Tick Labels

### ISSUE THREAD

**Issue by scottyhq** [SciTools/cartopy#491]
Hello, I recently came across the frustration of trying to add custom tick labels to a cartopy plot. I'm trying to make a plot of a small area in UTM coordinates, so in this case the default ticks generated by matplotlib should be fine. If I try to use `gridliner` or `set_xticks` I get errors regarding no support for `non-rectangular` coordinate systems. I tried a simple fix below to show default matplotlib ticks, but I'm not able to get tick labels to appear, and in this case not sure what I'm doing incorrectly:

```
plt.figure(figsize=(10,10))
mapproj = ccrs.UTM(55, southern_hemisphere=False) 
ax = plt.axes(projection=mapproj)
ax.set_extent((145.67, 145.84, 18.03, 18.18), crs=ccrs.Geodetic()) 
ax.coastlines(resolution='10m', color='k', linewidth=1)
ax = plt.axes(projection=mapproj)

# default tick divisions seem ok in UTM coords:
print ax.get_xticks()

# Failed Attempt to add custom tick-labels:
for val,label in zip(ax.get_xticks(), ax.get_xticklabels()):
    label.set_text(str(val))
    label.set_position((val,0))  

for val,label in zip(ax.get_yticks(), ax.get_yticklabels()):   
    label.set_text(str(val))
    label.set_position((0,val))  

# make sure they're visible
plt.tick_params(bottom=True,top=True,left=True,right=True,
                labelbottom=True,labeltop=False,labelleft=True,labelright=False)

plt.show()
# Plot still shows no ticks or labels...
```

I would think there is a simple work around for this?

**Comment by pelson** [comment]
```GeoAxes.set_xticks``` and ```GeoAxes.set_yticks```provide interfaces to re-enable the matplotlib ticks, which will work in some limited cases (such as a limited area UTM map). A general solution has not yet been developed to use the gridliner machinery for labelling all map types.
