### ISSUE TITLE
Polygon filling issue with orthographic projection

### ISSUE THREAD

**Issue by krischer** [SciTools/cartopy#492]
Hi all,

I noticed that polygons are not filled correctly at times (not always) when using the orthographic projection. I am using the latest master.

```python
import matplotlib.pylab as plt
import cartopy
import cartopy.crs as ccrs

plt.figure(figsize=(12, 8))

scale="110m"

ax = plt.axes(projection=ccrs.Orthographic(0, -75))
ax.set_global()

ax.add_feature(cartopy.feature.NaturalEarthFeature(
    "physical", "ocean", scale, edgecolor="None",
    facecolor="#CCCCCC"))
ax.coastlines(resolution=scale, color="#222222")

plt.show()
```

![screen shot 2014-10-08 at 11 55 24](https://cloud.githubusercontent.com/assets/800487/4557235/48d0b7ec-4ed1-11e4-81fb-47eb1ce9a31c.png)

But just adjusting the projection slightly results in a correct plot.

```python
ax = plt.axes(projection=ccrs.Orthographic(0, -80))
```

![screen shot 2014-10-08 at 11 55 14](https://cloud.githubusercontent.com/assets/800487/4557239/52a43640-4ed1-11e4-9685-116f2fa82d8e.png)

If somebody gives me some hints on how to investigate this I can also try to fix it.

**Comment by pelson** [comment]
Fixed on v0.12.x and master:

![figure_1](https://cloud.githubusercontent.com/assets/810663/6327356/0c27e4ca-bb53-11e4-9e02-23dbe4f91912.png)

This will be in the forthcoming v0.12.x release.

@krischer - we didn't re-write the algorithm in the end, instead, we adjusted some of the sub-algorithms. There is still a question of improving performance with a different algorithm, but I think the transformation has become a whole lot more robust. I don't have the code to produce that cool multiple globe plot you have, if you still have it, would you mind running and letting us know how you get on (perhaps in a new issue if it is bad)?
