### ISSUE TITLE
Setting Projection Limits and Borders

### ISSUE THREAD

**Issue by digitalvapor** [SciTools/cartopy#527]
About cutting projections or specifying borders - Is it possible to cut along latitude and longitude lines of Stereographic and Lambert Conformal projections? In the Lambert Conformal projection, I see we can alter the secant line intersections with the globe, and set the lower latitude from the north pole with `cutoff`, but what I am looking for is specifying max and min latitudes and longitudes.

![conformal](https://cloud.githubusercontent.com/assets/2218331/5586147/4f3eb56e-9078-11e4-8b08-83cb0bf76693.png)

Is it possible to cut the border along a shapefile, polygon, circle, etc?

**Comment by pelson** [comment]
> Is it possible to cut the border along a shapefile, polygon, circle, etc?

Yes - but it hasn't been made easy just yet. The key method for how the background & outline patches are created is at https://github.com/SciTools/cartopy/blob/master/lib/cartopy/mpl/geoaxes.py#L902. There is no reason that this couldn't be any arbitrarily shaped matplotlib patch.

I've thrown together an example. This functionality would make an excellent addition to cartopy's API :wink:.

```
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import matplotlib.patches as mpatches
import matplotlib.path as mpath

fig = plt.figure()
ax1 = plt.subplot(2, 1, 1, projection=ccrs.PlateCarree())
ax2 = plt.subplot(2, 1, 2, projection=ccrs.PlateCarree())

ax1.coastlines(); ax2.coastlines()


def update_boundary(ax, path):
    """Modifies the boundary of a given axes."""
    background = mpatches.PathPatch(path, edgecolor='none', facecolor='white',
                                    zorder=-1, clip_on=False, transform=ax.transData)
    background.orig_path = path
    background.reclip = True
    ax.background_patch.remove()
    ax.background_patch = background
    ax.patch = background

    outline = mpatches.PathPatch(path, facecolor='none', edgecolor='k',
                                 zorder=2.5, clip_on=False,
                                 transform=ax.transData)
    outline.orig_path = path
    outline.reclip = True
    ax.outline_patch.remove()
    ax.outline_patch = outline

    with ax.hold_limits():
        ax.add_patch(outline)
        ax.add_patch(background)


star_path = mpath.Path.unit_regular_star(5, 0.5)
star_path = mpath.Path(star_path.vertices.copy() * 80,
                       star_path.codes.copy())
update_boundary(ax2, star_path)

plt.show()
```

![figure_1](https://cloud.githubusercontent.com/assets/810663/5626700/ee7b1862-9586-11e4-9fd7-c8082deb9a96.png)

**Comment by digitalvapor** [comment]
Okay! I'd like to help add that. Since I'm new to contributing to Cartopy, is there a certain way you like pull requests/tests/examples done? I added your example. 

Where should I place the method?

**Comment by pelson** [comment]
On the [GeoAxes](https://github.com/SciTools/cartopy/blob/master/lib/cartopy/mpl/geoaxes.py#L208) I think. It would be good if ``_boundaries()`` made use of the method too (i.e. it just defines a path, then calls the new method).

I'm going to go ahead and close this issue, and we can iterate in the PR (#529).

**Comment by digitalvapor** [comment]
Okay, cool.

**Comment by pelson** [comment]
This PR can be updated to simply use the new set_boundary method on the geoaxes. Works a treat! :wink:
