### ISSUE TITLE
Incorrect 0.11.x version numbers

### ISSUE THREAD

**Issue by rhattersley** [SciTools/cartopy#533]
`cartopy.__version__` for the 0.11.1 and 0.11.2 releases are both set to "0.11.x". Hence this is also what you get when installing from binstar.

**Comment by pelson** [comment]
> Hence this is also what you get when installing from binstar.

So it does too. We need to create a v0.11.3 anyway, so good timing!

**Comment by QuLogic** [comment]
It doesn't appear to be on binstar or PyPI, but the tagged commit does have the correct version, so I expect it will trickle down eventually.
