### ISSUE TITLE
Update PEP8 version

### ISSUE THREAD

**Issue by pelson** [SciTools/cartopy#550]
The latest version of PEP8 triggers some errors. Update the travis.yml and fix any outstanding issues.

**Comment by QuLogic** [comment]
New PEP8 adds the rather annoying `E402 module level import not at top of file`, which prevents code like:
```
import six

if six.PY3:
    from urllib.request import urlopen
else:
    from urllib2 import urlopen

from cartopy import config
```
i.e., any imports after some conditional import. What do you think about ignoring this warning?

**Comment by pelson** [comment]
> What do you think about ignoring this warning?

We know what good code should look like - I'd be happy if this PEP8 warning was disabled.
