### ISSUE TITLE
Unspecified shapefile dependency

### ISSUE THREAD

**Issue by sgillies** [SciTools/cartopy#576]
Cartopy requires shapefile (or pyshp?) (https://github.com/SciTools/cartopy/blob/608df4fc69b32ff4bf231b6456cb67f33949ba67/lib/cartopy/io/shapereader.py#L52) but this isn't specified in setup.py, so pip doesn't fetch shapefile.

**Comment by QuLogic** [comment]
The `setup.py` does not (yet) list _any_ requirements. For the time being, you can find them listed in the `INSTALL` file.

**Comment by QuLogic** [comment]
Thanks; I'll try and get this in before the next release.
