### ISSUE TITLE
Some MPL tests are not side-effect free

### ISSUE THREAD

**Issue by QuLogic** [SciTools/cartopy#578]
Run every mpl suite individually via:
```bash
for t in axes caching crs examples features gridliner images img_transform mpl_integration \
        patch pseudo_color set_extent shapely_to_mpl ticker ticks; do
    echo -n "$t "
    nosetests -sv cartopy.tests.mpl.test_$t &> /dev/null && echo OK || echo FAIL
done
```
and you will find that `test_gridliner.test_gridliner`, `test_img_transform.test_regrid_image`, `shapely_to_mpl.test_contour_interiors`, and most of `test_ticks` fail.

However, if you add `cartopy.tests.mpl.test_axes` or `cartopy.tests.mpl.set_extent` first, then all tests magically pass.

**Comment by QuLogic** [comment]
Some testing points to the `matplotlib.testing.decorators.cleanup` decorator. Evidently, it cleans up to a state "cleaner" than the default setup...

**Comment by QuLogic** [comment]
I think the problem is that the `cleanup` decorator calls `matplotlib.tests.setup` on exit, which messes around with font settings:
```python
    # These settings *must* be hardcoded for running the comparison
    # tests and are not necessarily the default values as specified in
    # rcsetup.py
    rcdefaults()  # Start with all defaults
    rcParams['font.family'] = 'Bitstream Vera Sans'
    rcParams['text.hinting'] = False
    rcParams['text.hinting_factor'] = 8
```

Since most other tests do not do this setup if called individually, they don't plot exactly the same.

Should we add the same font settings to the `ImageTesting` decorator, or just avoid calling matplotlib's `cleanup` decorator?

**Comment by pelson** [comment]
Thanks for finding this @QuLogic. I think we should do a pre-clean up of matplotlib whenever using it, so putting it with the ImageTesting decorator makes sense.
