### ISSUE TITLE
How to use get_wms  with a specified CRS?

### ISSUE THREAD

**Issue by rsignell-usgs** [SciTools/cartopy#585]
I'd like to use Cartopy to access the Digital Coast WMS endpoint at:

url='http://coast.noaa.gov/arcgis/services/CCAP/All_Change_0106/MapServer/WMSServer?request=GetCapabilities&service=WMS'

I can successfully issue a manually-constructed `getMap` request, but when I try using Cartopy, I'm getting a blank map.  

How do I specify the CRS I want to use to Cartopy?

Here's my notebook illustrating the issue:
http://nbviewer.ipython.org/gist/rsignell-usgs/f14beafaba6181246cde

**Comment by rsignell-usgs** [comment]
Here's a notebook by @ocefpaf showing access to the same WMS endpoint using folium:
http://nbviewer.ipython.org/gist/ocefpaf/a3e8bfdfed81beed99ec
(you just need to interactively select the layer by clicking on the layer icon and selecting the northeast layer)

When you zoom in, you can see detail like this:
![3-6-2015 2-06-02 pm](https://cloud.githubusercontent.com/assets/1872600/6532635/c60368d0-c40c-11e4-9b67-f09f210515e0.png)

So I'm still interested in how one would do this in Cartopy.

**Comment by ajdawson** [comment]
@rsignell-usgs - you have the lats/lons swapped in the set_extent method. Just use `ax.set_extent((-80, -70.0, 34, 46))` and you should be good to go:

![wms](https://cloud.githubusercontent.com/assets/390602/6534759/ed980254-c437-11e4-9e5b-04bbca246808.png)

**Comment by ocefpaf** [comment]
And the `bbox` vs `x0,x1,y0,y1` attacks again!  BTW: @rsignell-usgs in my cartopy example earlier I did not used the `ax.set_extent`, that is why I got a global blank map.  Now that I see the data that I realize that it was correct.

**Comment by rsignell-usgs** [comment]
Thanks @ajdawson !  Closing this "issue".  :flushed:
