### ISSUE TITLE
binstar channels

### ISSUE THREAD

**Issue by rhattersley** [SciTools/cartopy#592]
What builds should go in what channels?

For a simple getting-things-started proposal, how about:
- Final releases in "main" - e.g. 0.12.0, 0.12.1
- Other stuff in "dev" - e.g. 0.12.3.dev, 0.13.0alpha2, 0.13.0rc1

**Comment by rhattersley** [comment]
> a simple getting-things-started proposal

It was my understanding that we'd already agreed to this, but @pelson doesn't agree. :wink:

**Comment by pelson** [comment]
This is really an issue for conda-recipes-scitools, but it'll do here.

I'm happy to define main however we want, but we have to accept that a lot of the time Iris will be making use of the ``dev`` channel.

Though it shows that something else is amiss, it is also worth noting that cartopy has been sitting on a dev version (on main) as there was no released version which didn't 404 on Natural Earth.

Finally (and this is the reason it is a conda-recipes-scitools issue), currently there is no mechanism to indicate what should be in "dev" and what should be in "main", so the only thing that gets built there is on "main".

**Comment by pelson** [comment]
conda-forge FTW
