### ISSUE TITLE
conda failure on OS X 10.10.2

### ISSUE THREAD

**Issue by jsboyle** [SciTools/cartopy#593]
I am on OS X 10.10.2. Anaconda installation 64 bit, python 2.7.9
When I give the command that is listed on the installation guide:
conda install -c scitools cartopy
I get:
Error: No packages found in current osx-64 channels matching: cartopy

The installation guide says that this is for ALL packages - is there something I am missing?

**Comment by rsignell-usgs** [comment]
If you go to:
https://binstar.org/SciTools/cartopy
it says "non-standard channels are being used".

So if you click on channels:
https://binstar.org/SciTools/cartopy/channels

and then on `main` or `dev`, you can see how to install:

```
conda install -c https://conda.binstar.org/scitools/channel/main cartopy
```
or 
```
conda install -c https://conda.binstar.org/scitools/channel/main cartopy
```

**Comment by jsboyle** [comment]
Rich,
Thanks for the very quick response.
The procedure outlined in the email  is not obvious from the installation guide ( http://scitools.org.uk/cartopy/docs/latest/installing.html#installing <http://scitools.org.uk/cartopy/docs/latest/installing.html#installing> ).

I went to https://conda.binstar.org/scitools/channel/dev <https://conda.binstar.org/scitools/channel/dev> and used the command indicated there:
conda install -c https://conda.binstar.org/scitools/channel/dev <https://conda.binstar.org/scitools/channel/dev> cartopy
the result:
Error: No packages found in current osx-64 channels matching owslib

I have not used binstar very much so there may be something else I need to do.

—Jim

**Comment by pelson** [comment]
Thanks for raising @jsboyle (and identifying @rsignell-usgs). I put the blame squarely on @rhattersley who did some channel shenanigans a week ago :wink:. 

I've now fixed the channels so that you should be able to do

``conda install cartopy -c scitools``

again.

Thanks @jsboyle

**Comment by rhattersley** [comment]
> I put the blame squarely on @rhattersley who did some channel shenanigans a week ago :wink:.

Cartopy really could do with a proper 0.11.3 release suitable for the "main" channel, instead of having to kludge it with hodge-podge of 0.11.2.dev and 0.11.3.dev. :wink:
