### ISSUE TITLE
Python 3.4 conflicts with conda install of cartopy

### ISSUE THREAD

**Issue by jhamman** [SciTools/cartopy#596]
According to the current [installation documentation](http://scitools.org.uk/cartopy/docs/latest/installing.html#installing), "Cartopy requires Python 2.7 or later." When installing `cartopy` using [Anaconda](https://store.continuum.io/cshop/anaconda/) and Python 3.[3, 4], this does not seem to be the case.

```bash
Joes-iMac:~/workdir$ conda install -c scitools cartopy
Fetching package metadata: ......
Solving package specifications: ..
Error: Unsatisfiable package specifications.
Generating hint: 
[      COMPLETE      ] |###############################################| 100%


Hint: the following combinations of packages create a conflict with the
remaining packages:
  - python 3.4*
  - cartopy
```
In the event that I have done something wrong (always a possibility), a bit of direction would be appreciated.  Otherwise, there are two courses of action:

1. Update the documentation to state that the cartopy/conda build is only for python2.7, or
2. Fix the conda build for python 3*.

**Comment by ajdawson** [comment]
Cartopy is compatible with Python 3.4, there just isn't a conda package for available it at the moment, it would be good to provide one though. However, for users installing from source the description in the documentation is entirely accurate so the documentation does not need to be changed.

Perhaps @pelson can figure out having the packages built for 3.4 also?

**Comment by jhamman** [comment]
Thanks @ajdawson .  

@pelson - I'm happy to test out the 3.4 build once its ready.

**Comment by jclark754** [comment]
Hey @ajdawson and @pelson, I believe @dopplershift has created a conda recipe for 3.4. You can `conda config --add channels http://conda.binstar.org/unidata` and then `conda install cartopy`. Perhaps he can get it over to the main conda-recipes repo.

**Comment by pelson** [comment]
Cool. Thanks @jclark754 - @dopplershift and I were talking about this earlier this week, that's awesome! I'm really keen to automate the build process as much as possible, and I'm actually sprinting on that concept right now, so fingers crossed, in the next few months we will have a scalable community driven mechanism for doing this.

**Comment by QuLogic** [comment]
I thought ObvCI does all that uploading stuff for you? Or at the very least, the stuff for Cartopy _releases_ on _SciTools binstar_.

**Comment by pelson** [comment]
> I thought ObvCI does all that uploading stuff for you?

Not so well if you want to support multiple Python and/or numpy versions. The concept of a build matrix cannot be applied as there are some recipes for which it wouldn't be applicable (proj4 doesn't care which numpy version we are building with, for example).

ObviousCI does do a lot of the good bits, but there is a more scalable model which I'm interested in pursuing.

**Comment by ocefpaf** [comment]
@pelson and @QuLogic I believe this issue is solved, right?
