### ISSUE TITLE
Build fails on OS X 10.10.3

### ISSUE THREAD

**Issue by fonnesbeck** [SciTools/cartopy#601]
I am unable to build cartopy on OS X 10.10.3 following the install instructions. Running Python 3.4 (homebrew) and attempting to build from cartopy's master branch. Issue with the Xcode command line tools?

    clang -Wno-unused-result -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/include -I./lib/cartopy -I-I/usr/local/Cellar/proj/4.8.0/include -I/usr/local/Cellar/geos/3.4.2/include -I/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/include/python3.4m -c lib/cartopy/trace.cpp -o build/temp.macosx-10.10-x86_64-3.4/lib/cartopy/trace.o

    In file included from lib/cartopy/trace.cpp:238:

    In file included from ./lib/cartopy/_trace.h:24:

    In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/iostream:38:

    In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/ios:216:

    In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/__locale:15:

    In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/string:439:

    In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/algorithm:628:

    In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/memory:604:

    /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/iterator:341:10: fatal error: '__debug' file not found

    #include <__debug>

             ^

    1 error generated.

    error: command 'clang' failed with exit status 1

**Comment by pelson** [comment]
I've not seen this before. The traceback points to https://github.com/SciTools/cartopy/blob/master/lib/cartopy/_trace.h#L24 which is simply including ```iostream```...

To be clear, are you using ```setup.py```? We recently changed it to identify all of its dependencies up front, and it is possible we've introduced a problem.

Our [automated build for conda](https://github.com/SciTools/conda-recipes-scitools/pull/58), available through the ``scitools`` channel, builds cartopy on OSX using [gcc](https://travis-ci.org/SciTools/conda-recipes-scitools/jobs/53941531) and I confess I haven't tried compiling with clang recently.

As you say, this could equally be a command line tools problem with xcode. The accepted answer on http://stackoverflow.com/questions/29529455/missing-c-header-debug-after-updating-osx-command-line-tools-6-3 suggests a re-install may yield some success.

**Comment by fonnesbeck** [comment]
Yes, the re-install of the command line tools did the trick. Clearly not a Cartopy issue, so closing. Thanks.

**Comment by QuLogic** [comment]
> builds cartopy on OSX using gcc

On OS X, `gcc` is an alias for `clang`:
```
$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin13.4.0
Thread model: posix
```

**Comment by erikwestlund** [comment]
Reinstalling command line tools fixed this for me.
