### ISSUE TITLE
shapefile download URL no longer valid

### ISSUE THREAD

**Issue by mhagdorn** [SciTools/cartopy#602]
Hi there,
I have packaged cartopy to be used on a multiuser system. The URLs for downloading shapefiles is no longer current in the version I have packaged (v 0.8.0). I would also prefer if the shapefiles could be managed in some way, ie downloaded (or packaged) and installed in a central location.

So my questions are
- are there plans to configure location of shapefiles?
- what files get downloaded?

**Comment by pelson** [comment]
Hi @mhagdorn.

Configuration can be done as per http://scitools.org.uk/cartopy/docs/latest/cartopy.html#cartopy.config.
The latest version of cartopy (v0.12.0) has fixed the download location - #532 relates. There is also a workaround in #472 for older versions of cartopy.

Finally, there is a script in https://github.com/SciTools/cartopy/blob/master/tools/download.py which can be used to pre-download much of the data if that is what is needed for your packaging. This is what I do at my organisation, where there are hundreds of people all sharing a common (local) shapefile source.

HTH

**Comment by mhagdorn** [comment]
Hi @pelson,
ah that's very helpful. Got it downloading the shapefiles, although I am hitting another issue where plotting them takes ages (I think I saw a bug report about that elsewhere). It would be handy if you could just download the files without having to plot them. That way I could also get it to work in a non-graphical shell.

**Comment by pelson** [comment]
I agree. I didn't write that script, and would have done the same (remove the use of matplotlib).

I'd try removing https://github.com/SciTools/cartopy/blob/master/tools/download.py#L95-101 with:

```
for feature in features:
    list(feature.geometries())
```

In fact, I went ahead and did this in #603. Would you mind checking it out and seeing that it is what you were expecting?

**Comment by mhagdorn** [comment]
Thanks a lot, that is working for me now. It still takes surprising long to download the files.

Thinking some more about how the packaging could work, it would be really useful if there was a dry option to the download.py program that just reports the URLs it would download. That way the data files could be downloaded elsewhere.

**Comment by pelson** [comment]
I jsut merged #603. It is much quicker than it was, but still downloads (and loads the data, hence it being fairly slow). I've added a ```--dry-run``` which allows you to see the URLs of the files that would otherwise be downloaded.

Hope that helps,
