### ISSUE TITLE
Subplot sizing, what is the best way?

### ISSUE THREAD

**Issue by guziy** [SciTools/cartopy#608]
Hi:

This is not really a bug. The thing I've encountered with basemap as well and always lived with it by tweaking image sizes... 

Matplotlib provides a very good way to do subplots using GridSpec as follows:

```python
gs = GridSpec(3, 2, width_ratios=[1, 1], height_ratios=[1, 1, 0.05], wspace=0.1, hspace=0.1)
```

where one can constrain the widths and heights of different axes to be the same or to differ in some particular way. I have a problem making it work with a mixture of map and line plots..The map plots always come out a bit shorter or lower... Please see the example notebook here (the relevant cartopy related code is in the last cell):

http://nbviewer.ipython.org/github/guziy/PyNotebooks/blob/master/plot_lake_fractions.ipynb

You can see that I have played with the figure size to make the subplots look similar. So my question is: Is there a better way to do this?

Cheers

**Comment by pelson** [comment]
Possibly. Take a look at #9 and the relevant SO question http://stackoverflow.com/questions/15480113/force-aspect-ratio-for-a-map. I can try putting together an example if it doesn't make sense / doesn't help in this situation.

**Comment by guziy** [comment]
Thank you Phil:

I'll check this out.

Cheers
