### ISSUE TITLE
Caching tiles

### ISSUE THREAD

**Issue by ThomasLecocq** [SciTools/cartopy#609]
Hi,

Would it be complicated to add cache capabilty for the tiles? I'm testing some maps, but having to redownload the tiles everytime is not really efficient...

I'm mostly using Google tiles (street or terrain)

Cheers

tom

**Comment by pelson** [comment]
Hi Tom,

There is nothing currently. The magic lines are https://github.com/SciTools/cartopy/blob/master/lib/cartopy/io/img_tiles.py#L192-194, and I imagine it would be doable to create a ``cartopy.io.Downloader`` which can handle this for us. I wrote a generic downloader a few months ago which could be used for this purpose - I'll try to dig it out and see if it is a quick win.

Cheers,

**Comment by ThomasLecocq** [comment]
:+1:  :-)

**Comment by pelson** [comment]
I've answered the question in #732 so will close this one.
