### ISSUE TITLE
Plotting formatted grids

### ISSUE THREAD

**Issue by JoyMonteiro** [SciTools/cartopy#611]
Hello,

I have been trying to plot grids on my maps, and the default works just fine. But notice
the overlap between -180,180

![plain](https://cloud.githubusercontent.com/assets/7300413/7384301/e7a926b2-ee4d-11e4-95f1-b4fd2a1d429d.png)

I wanted lat/long formatting, so I used the following code and removed 180 E to prevent
overlap

```python
plotLons = [-180,-120,-60,0,60,120]
plotLats = [-60,-30,0,30,60]
gl.xlocator = mticker.FixedLocator(plotLons)
gl.ylocator = mticker.FixedLocator(plotLats)
    
gl.xformatter = LONGITUDE_FORMATTER
gl.yformatter = LATITUDE_FORMATTER
```
where gl is a gridline instance returned by ax.gridlines()
and mticker is matplotlib.ticker

Now, some the -180,180 overlap is not there, but the gridlines
stop unexpectedly

![withlatformatting](https://cloud.githubusercontent.com/assets/7300413/7384343/8240572c-ee4e-11e4-9aae-24c362c84cd4.png)

I finally had to run

```python
temp = gl.xlabel_artists[0]
if '180' in temp.get_text():
    temp.set_visible(False) 
```

to get the desired result

![final](https://cloud.githubusercontent.com/assets/7300413/7384349/adfe628c-ee4e-11e4-9bb6-64507005cf48.png)

While I don't mind doing all this, I would like to know if there is a simpler way to do this.
moreover, such an approach only works if **plt.ion()** is enabled. It seems like
gl.xlabel_artists is populated only after **plt.show()** is called, and it I try to script this
figure drawing without **plt.ion()** or if I try to use IPython notebook, I cannot use this
approach.

I was trying to develop a tutorial using an IPython notebook, and ran into this issue.

TIA,
Joy

**Comment by pelson** [comment]
@ajdawson added some functionality which might be more helpful in the PlateCaree case. See the what's new at http://scitools.org.uk/cartopy/docs/latest/whats_new.html#what-s-new-in-cartopy-0-11.

Please feel free to ask any question you have here.

**Comment by JoyMonteiro** [comment]
sorry for the delay in replying, have been a little caught up.

Thanks, will test this and get back with the results!

**Comment by pelson** [comment]
Thanks @JoyMonteiro - I'll close this issue. If you have any questions, feel free to comment on here, re-open, or simply ask on StackOverflow. Thanks!
