### ISSUE TITLE
Update minimum geos version required in cartopy docs

### ISSUE THREAD

**Issue by shoyer** [SciTools/cartopy#612]
The cartopy docs state that the minimum required geos version is 3.3.3: http://scitools.org.uk/cartopy/docs/latest/installing.html#installing

But in practice, that version of geos doesn't seem to work (e.g., you need 3.4.2). This discrepancy should be noted in the docs.

**Comment by pelson** [comment]
> But in practice, that version of geos doesn't seem to work

Are there compilation issues? I haven't tested GEOS 3.3.3 for some time now.

If you are happy to do so, interested in submitting the fixing PR?

**Comment by pelson** [comment]
> If you are happy to do so, interested in submitting the fixing PR?

That is, unless the problem is trivial, just update https://github.com/SciTools/cartopy/blob/master/INSTALL#L64

**Comment by QuLogic** [comment]
You need to update [setup.py](https://github.com/SciTools/cartopy/blob/master/setup.py#L51) too.

**Comment by shoyer** [comment]
The problem doesn't appear on compilation, but when I try to use geos 3.3.3 (e.g., the one supplied with conda), I get error messages like the following when trying to run [some example code](https://github.com/TheClimateCorporation/conda-recipes/blob/master/cartopy/run_test.py): 
`Assertion failed: (0 != cs), function GEOSCoordSeq_getSize_r, file geos_ts_c.cpp, line 3612.`

We found that updating to geos to 3.4.2 fixed this issued. Some slightly older versions of geos might also work -- I haven't tested them.

**Comment by ocefpaf** [comment]
I have seen this before when conda refuses to use latest geos:

https://travis-ci.org/ioos/conda-recipes/builds/60733895#L5291

The error above is also with geos 3.3.3.

**Comment by pelson** [comment]
@shoyer are you describing https://github.com/Toblerity/Shapely/issues/177? It seems to me that the problem wasn't the GEOS version, as much as that ``find_library`` is behaving differently to the library resolution being determined at setup and/or Cython compile time? I haven't seen these issues since fixing shapely in https://github.com/SciTools/conda-recipes-scitools/tree/master/shapely.

**Comment by shoyer** [comment]
@pelson Nope, I'm pretty sure this is independent of that shapely problem.

**Comment by ocefpaf** [comment]
@shoyer I am not that sure.  Are you using conda?  Are you installing cartopy from the ioos or the scitools channels?  If so, can you check if the shapely that your conda is downloading is the one from the channel  you are using or the default anaconda channel?

I am saying this because Continuum just updated their shapely to 1.5.8, compiled against geos-3.3.3, and that shapely gets installed instead of the patched shapely from ioos/scitools 1.5.8dev0.

**Comment by shoyer** [comment]
Are you guys saying it *does* all work using geos-3.3.3 if I configure things properly?

@ocefpaf maybe it would be better if you described what I *should* try. I'm pretty sure I've installed things wrong every possible way before :). And yes, we use conda.

**Comment by ocefpaf** [comment]
> Are you guys saying it does all work using geos-3.3.3 if I configure things properly?

That is my guess, but I do not own a Mac to test it.

>  Maybe it would be better if you described what I should try.

Not sure if it is worth the effort, but if you want to be sure you would need to compile latest shapely (1.5.8) against geos-3.3.3 and try using those with cartopy.  (You'll probably need to update the patches.)

However, we just fixed our shapely (https://github.com/ioos/conda-recipes/pull/216 and https://github.com/SciTools/conda-recipes-scitools/pull/74).  Ideally we should push both shapely and geos to default anaconda to avoid all this redundancy.

**Comment by guziy** [comment]
I see this error on my Mac with 

```
$ geos-config --version
3.5.0
```

The failing code is below:
```python

from netCDF4 import Dataset
import matplotlib.pyplot as plt
from mpl_toolkits.basemap import Basemap, cm
import numpy as np
import matplotlib.pyplot as plt
import cartopy.crs as ccrs


bmap_params = {'llcrnrlat': 39.004303137858841,
               'urcrnrlat': 62.443077596938053,
               'projection': 'rotpole',
               'llcrnrlon': -86.99883217016388,
               'urcrnrlon': -40.221671371989302,
               'lon_0': -73.350000000000009,
               'o_lat_p': 37.878708451507158,
               'resolution': 'l',
               'o_lon_p': 176.70918638372871}


#set extent using projection coordinates
plt.figure(figsize=(6, 5))


rpole_crs = ccrs.RotatedPole(pole_longitude=bmap_params["lon_0"] + 180,
                             pole_latitude=bmap_params["o_lat_p"])

ax = plt.axes(projection=rpole_crs)
ax.coastlines(resolution='50m')

ax.gridlines()
xll, yll = rpole_crs.transform_point(bmap_params["llcrnrlon"], bmap_params["llcrnrlat"], ccrs.Geodetic())
xur, yur = rpole_crs.transform_point(bmap_params["urcrnrlon"], bmap_params["urcrnrlat"], ccrs.Geodetic())
ax.set_extent([xll, xur, yll, yur], crs=rpole_crs)

print(xll, xur, yll, yur)
```
Cheers

**Comment by QuLogic** [comment]
#1856 bumps minimum GEOS to 3.7.2; I assume that is enough.
