### ISSUE TITLE
Savefig speed Cartopy 0.11.0 vs. 0.12.0 and 0.12.0rc1

### ISSUE THREAD

**Issue by ingmeimau** [SciTools/cartopy#614]
I am experiencing quite different processing times of plotting and savefig depending on which Cartopy version I am using. I came across this issue because I need to plot quite "granular" maps, i.e. they are highly spatially inhomogenous. 

Here is an artificial example of what I mean:

    import cartopy.crs as ccrs
    import matplotlib.pyplot as plt
    import numpy as np
    import time 
    from mpl_toolkits.basemap import Basemap
    
    def main():
        
        nx = 700
        ny = 400    
        lon = np.linspace(-5, 5, nx)
        lat = np.linspace(46,50, ny)
        lon,lat = np.meshgrid(lon,lat)    
        a=0;b=120
        data = (b - a) * np.random.random((ny,nx)) + a
        clevs = np.linspace(a,b,18)
        
        do_n_runs = 3
        cart_fig=[];cart_sav=[]
        base_fig=[];base_sav=[]
        for n in xrange(do_n_runs):
            i,j = cartopy_plot(lon, lat, data, clevs)
            cart_fig.append(i); cart_sav.append(j)
            
            i,j = basemap_plot(lon,lat,data,clevs)
            base_fig.append(i); base_sav.append(j)
        
        print 'Cartopy figure plotting: ',np.mean(cart_fig) , "seconds"
        print 'Cartopy savefig        : ',np.mean(cart_sav) , "seconds"
        print 'Basemap figure plotting: ',np.mean(base_fig) , "seconds"
        print 'Basemap savefig        : ',np.mean(base_sav) , "seconds"
        
    def cartopy_plot(lon,lat,data,clevs):
        
        te = time.time()
        fig, ax = plt.subplots(1, 1, figsize=(10,5),
                               subplot_kw={'projection': ccrs.GOOGLE_MERCATOR})
            
        im=ax.contourf(lon, lat, data, clevels=clevs, transform=ccrs.GOOGLE_MERCATOR)
        plt.colorbar(im)
        c_tf = time.time() - te
        
        te = time.time()
        plt.savefig('cartopy_randdat.png',type='png',dpi=200)
        c_ts = time.time() - te
        plt.close()
        return c_tf,c_ts
        
    def basemap_plot(lon,lat,data,clevs):
        te = time.time()
        fig, ax = plt.subplots(1, 1, figsize=(10,5))
        m = Basemap(projection='merc', llcrnrlat=lat[0,0],urcrnrlat=lat[-1,-1],\
                        llcrnrlon=lon[0,0],urcrnrlon=lon[-1,-1],lat_ts=20, resolution='h', ax=ax)
        x,y = m(lon,lat)
         
        im=ax.contourf(x, y, data, clevels=clevs)
        plt.colorbar(im)
        b_tf = time.time() - te
         
        te = time.time()
        plt.savefig('basemap_randdat.png',type='png',dpi=200)
        b_ts = time.time() - te
        plt.close()
        return b_tf, b_ts
    
    if __name__ == '__main__': main()

As a reference, I have also included basemap in this example which always yields about:
Basemap figure plotting:  16.3559799194 seconds
Basemap savefig        :  3.72710172335 seconds

Now Cartopy:
Virtualenv installation python 2.7, Cartopy 0.11.0:
Cartopy figure plotting:  17.7351046403 seconds
Cartopy savefig        :  8.65319832166 seconds
Which is comparable to the Basemap result and okish.

But then:
Anaconda python 2.7, Cartopy 0.12.0rc1 (binstar/scitools):
Cartopy figure plotting:  6.78139209747 seconds
Cartopy savefig        :  18.1392699877 seconds
Anaconda python 2.7, Cartopy 0.12.0 (binstar/ioos):
Cartopy figure plotting:  6.41563336054 seconds
Cartopy savefig        :  18.7613488833 seconds

Can this result be reproduced by anyone? Is there an explanation for this?
Ideally, I would like to have the plotting speed of Cartopy 0.12... and the savefig speed of Cartopy 0.11.0 (or even better, Basemap).
I need to add, that I was struggling a bit with the conda installation of Cartopy, in terms of geoss, shapely and cartopy version mismatch (that's why I came across the different binstar installs).

**Comment by QuLogic** [comment]
It seems that Basemap spends most of its time reading and calculating intersections of the boundary data:
![basemap](https://cloud.githubusercontent.com/assets/302469/7553257/9023b3be-f6bb-11e4-9a09-8af9b35bbd88.png)

Instead, Cartopy spends a whole bunch of time transforming a million paths:
![cartopy](https://cloud.githubusercontent.com/assets/302469/7553278/3e352928-f6bd-11e4-9236-efad4c8798de.png)

If these million calls could be reduced into fewer NumPy arrays, maybe that stage could be sped up a bit...

**Comment by ingmeimau** [comment]
Thanks for this interesting graph!
Still I don't understand why different Cartopy versions spend very different amounts of time in plotting/saving.

**Comment by pelson** [comment]
Just checking, the total execution time is ``figure plotting + savefig``, right? Is it just the case that the work has moved around, so v0.11 has gone from ~26s to ~25s in v0.12? 

The major change for v0.12 comes under:

> Some improvements were made to the geometry transformation algorithm to improve the stability of geometry winding. Several cases of geometries being incorrectly inverted when transformed have now been resolved. (PR #545)

This PR would potentially explain the move of where work is being done. There haven't been any optimisations done recently to cartopy, so I imagine there is some space for improvement in that regard.

**Comment by ingmeimau** [comment]
Correct, total time (plotting+savefig) has decreased by around 1 sec. from v0.11 to v0.12. 
It really seems that work has shifted from plotting to savefig and some optimisation is needed.
I guess this can be closed then.

**Comment by pelson** [comment]
Thanks @ingmeimau - optimisation of full rendering stack is certainly something like like to investigate.
