### ISSUE TITLE
Exploring cartopy

### ISSUE THREAD

**Issue by mhearne-usgs** [SciTools/cartopy#620]
I'm looking at Canopy to replace Basemap, but I'm running into three major (potentially showstopping) issues.  I was wondering if other users had experienced similar problems in general, and if not, whether I should try to try to extract these issues into reproducible code for the developers.

1) Depending on what projection I choose, images displayed with imshow() may or may not be rendered.
2) Images using imshow() render when saved to PNG format, but not to PDF.
3) I cannot get ocean and/or coastline data to render at 10m scale in any kind of time frame I have the patience for.

So far I cannot reproduce these issues with simple examples, so it will take quite a bit of work to boil them down to small snippets of code.

**Comment by pelson** [comment]
> 1) Depending on what projection I choose, images displayed with imshow() may or may not be rendered.

Sounds like either a bug, or a problem with your code. My suspicion, if you are new to cartopy, is that you may not be specifying the transform (projection) of your *image*.

> 2) Images using imshow() render when saved to PNG format, but not to PDF.

I've not experienced this myself, but we don't test PDF creation. A short example would be of value. (perhaps take http://scitools.org.uk/cartopy/docs/latest/examples/geostationary.html)

> 3) I cannot get ocean and/or coastline data to render at 10m scale in any kind of time frame I have the patience for.

Performance is, anecdotally, slightly slower than Basemap at present. The two approaches are very different, with cartopy having to do more work as it does some smarts about figuring out things like crossing the antimeridian. There is room for improvement, but I confess we have been less focused on this than I would have liked.
