### ISSUE TITLE
Bug: Mercator central longitude

### ISSUE THREAD

**Issue by dkillick** [SciTools/cartopy#624]
When making a plot using a Mercator projection with a non-zero central longitude as the plot's projection, the plot fails to draw. See below for a code snippet and result to demonstrate this further.

This also appears to impact on setting a plot extent that crosses the 180deg longitude line:
 * if no central longitude is set then the resultant extent of the plot extends between the specified latitudes but the longitudes run between -180 <= 180 degrees, or
 * if a central longitude is specified, the call to `geoaxes.set_extent` does not reproject the geometry.

Code to demonstrate the central longitude problem:
```python
import matplotlib.pyplot as plt
import cartopy.crs as ccrs

proj = ccrs.Mercator(central_longitude=0.1)
ax = plt.axes(projection=proj)
ax.coastlines()
plt.show()
```

If coastlines are drawn, the plot is accompanied by the following warning:
  `/../cartopy/lib/cartopy/mpl/feature_artist.py:105: UserWarning: Unable to determine extent. Defaulting to global.
  warnings.warn('Unable to determine extent. Defaulting to global.')`

The plot that results is:

![mercator_central_longitude](https://cloud.githubusercontent.com/assets/3473068/8079788/ea09687c-0f5e-11e5-8485-09100ccd68a1.png)

**Comment by pelson** [comment]
Any idea if this used to work in older versions?

**Comment by dkillick** [comment]
This is my fault :scream: Running a git bisect indicated that #324 introduced this problem...

**Comment by pelson** [comment]
Woops. Should be an easy fix :wink:
