### ISSUE TITLE
Import cartopy error

### ISSUE THREAD

**Issue by BeebBenjamin** [SciTools/cartopy#626]
Hi I am running Ubuntu 15.04 and python2.7 64bit.

I have cloned the repository and installed cartopy.

I get the following error when I try to import cartopy.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/Cartopy-0.13.dev0-py2.7-linux-i686.egg/cartopy/__init__.py", line 110, in <module>
    import cartopy.crs
  File "/usr/local/lib/python2.7/dist-packages/Cartopy-0.13.dev0-py2.7-linux-i686.egg/cartopy/crs.py", line 37, in <module>
    from cartopy._crs import CRS, Geocentric, Geodetic, Globe, PROJ4_RELEASE
ImportError: /usr/local/lib/python2.7/dist-packages/Cartopy-0.13.dev0-py2.7-linux-i686.egg/cartopy/_crs.so: wrong ELF class: ELFCLASS32

I think this is because the default build is 32bit.

Any idea how to fix this?  I've successfully installed cartopy in the past on a 64bit machine and wonder why this is now an issue.

**Comment by ajdawson** [comment]
This looks like you have got a 32-bit build of Cartopy and are trying to import it in a 64-bit Python interpreter. The question is how you ended up with the wrong one. If you could post a few details about how you installed and your Python environment it would really help, in particular which python interpreter you are using or expecting to use (system default in /usr/bin/python, [anaconda](https://store.continuum.io/cshop/anaconda/), [canopy](https://www.enthought.com/products/canopy/) etc.) , and how you installed cartopy including exact commands used if possible.

**Comment by QuLogic** [comment]
@BeebBenjamin Did you resolve this issue? I am going to close it if we don't get a response soon.

**Comment by BeebBenjamin** [comment]
I can't remember how I fixed this.  So go ahead and close the issue.
