### ISSUE TITLE
Error:shapely.geos: with first example code

### ISSUE THREAD

**Issue by oceanEngineer** [SciTools/cartopy#636]
Hi, I recently installed cartopy and it looks pretty neat. However, I can't get even the first example code to work.
```python
%matplotlib inline
import cartopy.crs as ccrs
import matplotlib.pyplot as plt

ax = plt.axes(projection=ccrs.PlateCarree())
ax.coastlines()

plt.show()

ERROR:shapely.geos:Geometry must be a Point or LineString
```
I am using python 3.4 and ipython3 notebook. Any help would be appreciated.

**Comment by QuLogic** [comment]
It looks like you're on OSX using homebrew. Can you try re-installing shapely without the wheel like in #615?

**Comment by oceanEngineer** [comment]
You are right about OSX and homebrew. As per suggestion,

pip uninstall shapely && pip install --no-use-wheel shapely

fixed the issue. Thanks
