### ISSUE TITLE
streamplotting for arbitrary input grids

### ISSUE THREAD

**Issue by DamienIrving** [SciTools/cartopy#644]
For input data where the longitude values span -180 to 180, the following works fine for any output projection:
```
import matplotlib.pyplot as plt
import cartopy.crs as ccrs

input_projection = ccrs.PlateCarree()
ax = plt.subplot(nrows, ncols, plotnum, projection=output_projection)
ax.streamplot(x, y, u, v, transform=input_projection)
```

I've found that problems start to arise, however, as soon as the input projection isn't `ccrs.PlateCarree()` (i.e. when the longitude values aren't -180 to 180). For instance, if the input data has longitude values from 0 to 360 and I set `input_projection = ccrs.PlateCarree(central_longitude=180.0)`, the resulting streamline plot is shifted 180 degrees from the correct location (and if I try to set `output_projection = ccrs.PlateCarree(central_longitude=180.0)` only the western hemisphere shows data).

I got around this problem by using `new_cube = cube.intersection(longitude=(-180, 180, False, True))` to convert my input data to -180 to 180, however I thought I'd flag this issue as I'm assuming it was the intention to be able to draw streamlines for any arbitrary input projection.

**Comment by DamienIrving** [comment]
I can confirm that this problem is not unique to `ax.streamplot`. It happens whenever the `transform` option is used (e.g. I get the same issue with `ax.contourf`).

**Comment by rhattersley** [comment]
> if the input data has longitude values from 0 to 360 and I set input_projection = ccrs.PlateCarree(central_longitude=180.0), the resulting streamline plot is shifted 180 degrees from the correct location

If your input values are latitudes and longitudes then you should always set your input CRS as either `PlateCarree()` or `Geodetic()`. The range of the longitudes doesn't matter - you never want to modify the central_longitude. (This is a common confusion made worse by the fact that the `PlateCarree` projection pretends to work with degrees, when really it should be projection metres like the other projections.)

For example, the [waves](http://scitools.org.uk/cartopy/docs/latest/examples/waves.html) example in the documentation supplies longitudes in the range 0 to 360.

So... assuming you still have a problem, could you modify something like the waves example do demonstrate it?

**Comment by DamienIrving** [comment]
@rhattersley Ah, it seems I've fallen for this common confusion. I was changing the `central_longitude` for cases where the longitude axis was 0 to 360, when I should have just used `PlateCarree()`. Thanks for clearing this up for me - when I use `PlateCarree()` everything works fine.
