### ISSUE TITLE
Make use of pj_get_spheroid_defn and pj_get_def from proj_api.h

### ISSUE THREAD

**Issue by pelson** [SciTools/cartopy#649]
With these we can get major & eccentricity information, and a canonical proj4 string respectively.

Unfortunately, when I tried to use these, I have all sorts of problems (thoughts @QuLogic?). My noddy example:

```
#include <proj_api.h>
#include <stdio.h>


int main()
{
  double m, e;
  const char * defn = "+proj=rob +ellps=WGS84";

  projPJ pj = pj_init_plus(defn);

  pj_get_spheroid_defn(&defn, &m, &e);
  printf(" %f %f\n", m, e);

  char * expanded = malloc(sizeof(char) * 1024);
  expanded = pj_get_def(&defn, 0);
  printf(" %s\n", expanded);

  return 0;
}
```

Gives:

```
 0.000000 0.000000
Memory fault(coredump)
```

I confess, I don't really understand what the second argument for pj_get_def does (see https://github.com/OSGeo/proj.4/blob/4.9/src/pj_pr_list.c#L55).

**Comment by ajdawson** [comment]
You need to pass `pj` as the first argument to `pj_get_spheroid` rather than `&defn`, same for `pj_get_def`. It still doesn't work though, but it does work with `+proj=merc` in the definition... Not sure about that problem.

**Comment by QuLogic** [comment]
@ajdawson is correct; you need to use `pj` for both `pj_get_spheroid_defn` and `pj_get_def`. It doesn't work when you do that though, because I think you meant `robin`, not `rob`.

```
 6378137.000000 0.000000
  +proj=robin +ellps=WGS84
```

**Comment by pelson** [comment]
Ah, ok. Thanks guys. I confess, I was hacking around in a bit of a rush on Monday - this is a really interesting option for #330 though.

**Comment by pelson** [comment]
Wow. Looking back - it really doesn't do to try to figure this stuff out in <20mns :wink:.
So I got this working, thanks @ajdawson and @QuLogic.

Pretty surprised by the first result though:
```
  +proj=robin +ellps=WGS84
 6378137.000000 0.000000
```
compared with the expected result from latlong:

```
 6378137.000000 0.006694
  +proj=latlong +ellps=WGS84
```

I expect this is my lack of proj4 foo more than anything else though.

**Comment by pelson** [comment]
The ``pj_latlong_from_proj(pj)`` function can probably help with that though.

What's also interesting is that if I specify the projection incorrectly proj4 just coredumps on me. (e.g. ```+ellps=WGS84```). Hmmm - not quite the silver bullet I was hoping this would prove to be...

**Comment by QuLogic** [comment]
If you're using the code from above, you also need to check whether `pj` is `NULL`, which should indicate an invalid projection string.

**Comment by greglucas** [comment]
We are now relying on pyproj, so don't need to make use of PROJ headers anymore.
