### ISSUE TITLE
Adding a sinusoidal projection

### ISSUE THREAD

**Issue by raj-kesavan** [SciTools/cartopy#650]
I need to work with MODIS data and it would be nice to have a sinusoidal projection CRS native to Cartopy. Is this possible?

I can try adding it myself as well.

**Comment by pelson** [comment]
Yep, this is feasible. If you want to give it a shot, that would be awesome! Figuring out the native coordinate extents is about the most complex part of defining a new projection - take a look at the stereographic projection for a recently up-to-date projection: https://github.com/SciTools/cartopy/blob/master/lib/cartopy/crs.py#L1226
