### ISSUE TITLE
Plate Carree: degrees vs metres

### ISSUE THREAD

**Issue by rhattersley** [SciTools/cartopy#653]
The Plate Carree projection has the strange behaviour that it defaults to "degrees" until you specify a globe, in which case it reverts to metres. Suddenly your coordinates have changed by 4 orders of magnitude!

One solution would be to split the behaviour into two different projections. For example, PlateCarree would always operate in degrees, and EquiRectangular would always operate in metres.

**Comment by pelson** [comment]
If only we had Geodetic contouring then most of the time, we wouldn't be using PlateCarree anyway.
I'm going to close this one, as I don't think there is anything we are likely to do about it in the near future.
