### ISSUE TITLE
`cartopy` failing to install in conda environment

### ISSUE THREAD

**Issue by darribas** [SciTools/cartopy#660]
I create a new conda environment to install anaconda like this:

```
conda create -n testenv ipython
```

Then activate it:

```
source activate testenv
```

And install `cartopy` as suggested in the documentation:

```
conda install -c scitools cartopy
```

If I try to import it, it seems to fail:

```
ipython
```

```%python
In [1]: import cartopy
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-8327782196fd> in <module>()
----> 1 import cartopy

/Users/dani/anaconda/envs/testenv/lib/python2.7/site-packages/cartopy/__init__.py in <module>()
    108 # Commonly used sub-modules. Imported here to provide end-user
    109 # convenience.
--> 110 import cartopy.crs
    111 import cartopy.feature

/Users/dani/anaconda/envs/testenv/lib/python2.7/site-packages/cartopy/crs.py in <module>()
     36
     37 from cartopy._crs import CRS, Geocentric, Geodetic, Globe, PROJ4_RELEASE
---> 38 import cartopy.trace
     39
     40

ImportError: dlopen(/Users/dani/anaconda/envs/testenv/lib/python2.7/site-packages/cartopy/trace.so, 2): Library not loaded: @rpath/libgeos_c.1.dylib
  Referenced from: /Users/dani/anaconda/envs/testenv/lib/python2.7/site-packages/cartopy/trace.so
  Reason: Incompatible library version: trace.so requires version 10.0.0 or later, but libgeos_c.1.dylib provides version 9.0.0

In [2]:
```

I'm on Yosemite 10.10.4 using conda 3.16.0.

Thank you very much in advance,

]d[

**Comment by darribas** [comment]
@ocefpaf asked:
Maybe you have another geos installed. Can you make sure you got geos from the scitools channel as well? What is the output of `conda list | grep geos`?

```
(reprojs2)kokopelli:Desktop dani$ conda list | grep geos
geos                      3.3.3                         0
(reprojs2)kokopelli:Desktop dani$
```

Wouldn't cartopy check that and install a different geos for the environment?

**Comment by ocefpaf** [comment]
`geos 3.3.3` seems to be the default channel one.  Scitools (and IOOS) use [geos 3.4.2](https://github.com/SciTools/conda-recipes-scitools/blob/master/geos/meta.yaml#L3).

Try to install scitools geos too: `conda install -c scitools geos`, but bare in mind that the default channel geos can get installed again in the future if you install another package that depends on version 3.3.3!

> Wouldn't cartopy check that and install a different geos for the environment?

Not really.  Cartopy can check the version, and in this case both versions are OK, but cartopy cannot check if all the dependencies were compiled against the same library (which is the problem here).

If you add the scitools channel to your `.condarc` file ( `conda config --add channels scitools`) you will also get the right geos after an update (`conda update --all`).

**Comment by pelson** [comment]
@ocefpaf - perhaps we should be adding ```geos 3.*``` to our conda recipes to bake the GEOS version. (i.e. here https://github.com/SciTools/conda-recipes-scitools/blob/master/shapely/meta.yaml#L18)

**Comment by ocefpaf** [comment]
Makes sense... I would rather see our `geos` on the default channel though.

**Comment by clarkfitzg** [comment]
@ocefpaf here's what I see:

```
(cartopy)testimage ~ $ conda config --add channels scitools
(cartopy)testimage ~ $ conda update --all
Fetching package metadata: ......
Solving package specifications: .
Package plan for installation in environment /Users/clark.fitzgerald/anaconda/envs/cartopy:

The following packages will be DOWNGRADED:

    geos: 3.4.2-2 --> 3.3.3-0

Proceed ([y]/n)?

(cartopy)testimage ~ $ cat ~/.condarc
channels:
  - scitools
  - defaults
```

It gets installed if I conda install geos after cartopy.

**Comment by pelson** [comment]
Thanks @clarkfitzg. It doesn't make any sense that geos would be downgraded unless there is a package in there which is baking the GEOS version. Can you do a ```conda list``` to give us the packages which are installed in your environment? Id love there to be a command which allowed us to do a ```conda deps require geos```, but alas, I don't think such a thing exists...

**Comment by clarkfitzg** [comment]
```
~/scratch $ conda list
# packages in environment at /Users/clark.fitzgerald/anaconda/envs/cartopy:
#
cartopy                   0.13.0               np19py27_0
decorator                 4.0.2                    py27_0
freetype                  2.5.2                         2
funcsigs                  0.4                      py27_0
geos                      3.4.2                         2
ipython                   4.0.0                    py27_0
ipython-genutils          0.1.0                     <pip>
ipython_genutils          0.1.0                    py27_0
jpeg                      8d                            1
libpng                    1.6.17                        0
libtiff                   4.0.2                         1
matplotlib                1.4.3                np19py27_3
mock                      1.3.0                    py27_0
nose                      1.3.7                    py27_0
numpy                     1.9.2                    py27_0
openssl                   1.0.1k                        1
owslib                    0.9.0                    py27_0
pandas                    0.16.2               np19py27_0
path.py                   7.6                      py27_0
pbr                       1.3.0                    py27_0
pexpect                   3.3                      py27_0
pickleshare               0.5                      py27_0
pillow                    2.9.0                    py27_0
pip                       7.1.2                    py27_0
proj4                     4.9.1                         0
pyepsg                    0.2.0                    py27_0
pyparsing                 2.0.3                    py27_0
pyqt                      4.11.3                   py27_0
pyshp                     1.2.1                    py27_0
python                    2.7.10                        0
python-dateutil           2.4.2                    py27_0
python.app                1.2                      py27_4
pytz                      2015.4                   py27_0
qt                        4.8.6                         3
readline                  6.2                           2
requests                  2.7.0                    py27_0
scipy                     0.16.0               np19py27_1
setuptools                18.1                     py27_0
shapely                   1.5.11                   py27_0
simplegeneric             0.8.1                    py27_0
sip                       4.16.5                   py27_0
six                       1.9.0                    py27_0
sqlite                    3.8.4.1                       1
tk                        8.5.18                        0
traitlets                 4.0.0                    py27_0
wheel                     0.24.0                   py27_0
xray                      0.6.0                    py27_0
zlib                      1.2.8                         0
```

**Comment by pelson** [comment]
Ah, I remember @ocefpaf mentioning that anaconda have a newer shapely, and that pins against an older GEOS. I've been meaning to fix this, so I'll take a look now. I'll ping you when there is a fix available (a few hours).

**Comment by clarkfitzg** [comment]
@pelson Great, thanks!

**Comment by pelson** [comment]
Hmmm. That has taken longer than I thought. I was working on https://github.com/SciTools/conda-recipes-scitools/pull/103, but appear to be having problems.

A workaround would be to pin the version of GEOS. I'm not hugely familiar with it, but pinning would look something like:

```
echo "geos 3.4.2" > ~/anaconda/envs/cartopy/conda-meta/pinned
```

I don't know how well the solver will deal with that, so you may also need to pin the shapely:

```
echo "shapely 1.5.8" >> ~/anaconda/envs/cartopy/conda-meta/pinned
```

**Comment by michaelaye** [comment]
I'm having the same problem and so far only the version of the `ioos` channel works fine, all other workaround have the dylib not found problem.
Concerning the dependency searching in anaconda, that does exist:
`conda search --reverse-dependency package_name`
After that one can do `conda info dependent_p_name` to see how exactly it depends on it (often authors hard-code a specific patch version dependency which usually is not required.)

Back to my problem: I have everything running, but I want to add a new stockfile image so I forked cartopy and install via 'python setup.py develop' and it stops working! So, it works with what I get from the ioos binstar channel, and then the only change I make is to do `p setup.py develop` and BOOM, the error of not finding the proj library is back:
```python
ImportError: dlopen(/Users/klay6683/Dropbox/src/cartopy/lib/cartopy/_crs.so, 2): Library not loaded: @rpath/./libproj.9.dylib
  Referenced from: /Users/klay6683/Dropbox/src/cartopy/lib/cartopy/_crs.so
  Reason: image not found
```

**Comment by rsignell-usgs** [comment]
I know that @ocefpaf worked hard to get the IOOS channel working correctly.  It totally saved me during a python training class I was teaching a few weeks ago....

**Comment by ocefpaf** [comment]
@michaelaye The scitools channel is the big brother of the ioos channel.   We copied the technology and workflow that @pelson developed for scitools.  The only difference is that I have more free time than the scitools  devs to keep the recipes up-to-date.

I am saying this because soon we will have the best of both worlds.  [conda-forge](https://github.com/conda-forge) is an effort to to aggregate all these recipes in a community conda channel.  The ioos and scitools channel will still exist, but the packages in them would be copies from the conda-forge channel.

As soon as we work some kinks out I plan to "transfer" the bulk of the ioos channel to conda-forge.  Stay tunned.

**Comment by BKJackson** [comment]
I have been having similar problems.  Ripping out (sudo rm -rf ...) old macports and fink directories and updating conda (conda update --all) seems to have finally done the trick.

**Comment by pelson** [comment]
I think this should be all working now. Regardng @michaelaye 's issue, I'm finding that when developing in a conda environment, I have to ```python setup.py develop``` *then* ```conda develop cartopy_clone_location``` to get the appropriate rpath magic on my Mac. Might be a useful tip...

If there are any more issues with cartopy installations with conda and the scitools channel, please feel free to raise as another issue (either here, or conda-recipes-scitools).
