### ISSUE TITLE
Map footnote / copyright note example/docs

### ISSUE THREAD

**Issue by timmie** [SciTools/cartopy#664]
Is it possible to add a small inset to the maps explaining the source & copyright?

This applies especially to GoogleTiles / OSM.

**Comment by ajdawson** [comment]
You can use matplotlib's many text/annotation features to do this. There are probably lots of different ways to do it, depending on specifically what you want. For example, you could use the `AnchoredText` object like this:

```python
import cartopy.crs as ccrs
import cartopy.feature as cfeature
import matplotlib.pyplot as plt
from mpl_toolkits.axes_grid.anchored_artists import AnchoredText


# Create basic map for illustration.
ax = plt.axes(projection=ccrs.NorthPolarStereo())
ax.add_feature(cfeature.OCEAN)
ax.add_feature(cfeature.LAND)

# Add a text annotation in the bottom right corner.
ax.set_extent([-180, 180, 30, 90], crs=ccrs.PlateCarree())
text = AnchoredText("Source: the source; copyright whoever", loc=4,
                    prop={'size': 10}, frameon=True)
ax.add_artist(text)

plt.show()
```

Which will give you something like this:
![cannot](https://cloud.githubusercontent.com/assets/390602/9679099/658b65d2-52e3-11e5-9d6f-31798604a047.png)

The matplotlib documentation has lots of examples, perhaps start here: http://matplotlib.org/users/annotations_guide.html#plotting-guide-annotation. It would be fair to say there is a lot of flexibility in how you can do this and what the result will look like!

**Comment by timmie** [comment]
@ajdawson 
Thanks for the swift reply and nice example.
Since providers are usually quite picky about this, maybe even an item for the docs?

**Comment by ajdawson** [comment]
>Since providers are usually quite picky about this, maybe even an item for the docs?

Could be yes, perhaps an example in the gallery. Thanks for flagging it up.

**Comment by timmie** [comment]
OK, so you may reopen and flag it as DOC.

**Comment by rcomer** [comment]
This became part of the [feature creation example](https://scitools.org.uk/cartopy/docs/latest/gallery/lines_and_polygons/feature_creation.html#sphx-glr-gallery-lines-and-polygons-feature-creation-py).
