### ISSUE TITLE
proj version 4.9 really required?

### ISSUE THREAD

**Issue by timmie** [SciTools/cartopy#665]
Hello,
the version of proj 4.9 will only be in the next version of ubuntu (current development beta / not released)

Is this really required?

**Comment by ajdawson** [comment]
For the currently released version (0.13) Proj4.8 is the requirement. For the next version (0.14) the requirement will change to 4.9 I think due to some new code that relies on it, I'm not sure if this will be optional or not. @pelson @scmc72?

**Comment by timmie** [comment]
optional would be great!

**Comment by scmc72** [comment]
I agree - if proj4.9 is not available or difficult for some users to obtain, then I imagine it would be a good idea to make it optional! @Jozhogg

**Comment by pelson** [comment]
The easy solution would be to print a message (on setup.py) and skip the build of the geodetic module. Not keen to implement stub modules though - it would be a straight up ImportError if you haven't got proj 4.9 and wanted the Geodetic stuff.

Thanks for the suggestion @timmie - it makes a lot of sense.

**Comment by vesnikos** [comment]
Also having a homebrew proj4 in a non standard location doesn't solve the problem. You need to hack setup.py to point it to the right location?

**Comment by QuLogic** [comment]
If `proj4` is installed to a non-standard location, you should ensure that the `proj` binary and the include/linker paths returned by `pkg-config` are consistent with that location.

**Comment by vesnikos** [comment]
Hmmm I think that there might be an issue here. For ubuntu OSGeos' package for proj4 (from unstable-gis ppa) doesn't come with the .pc 

If you compile proj4 from source and install it in userspace (having the proj.pc) and exporting the correct PKG_CONFIG_PATH, setup,py's  find_executable() precedes  pkg-config search as it lock with systems proj4

**Comment by QuLogic** [comment]
> For ubuntu OSGeos' package for proj4 (from unstable-gis ppa) doesn't come with the .pc

Did you install the `-dev` package as well?

> If you compile proj4 from source and install it in userspace (having the proj.pc) and exporting the correct PKG_CONFIG_PATH, setup,py's find_executable() precedes pkg-config search as it lock with systems proj4

The `proj` executable is used to find the version; if the non-standard one doesn't show up in the path before the system one, then your installation is incomplete.

**Comment by vesnikos** [comment]
> Did you install the -dev package as well?
- yes

>The proj executable is used to find the version; if the non-standard one doesn't show up in the path before the system one, then your installation is incomplete.

That would work; but to come back to the original issue enforcing v4.9 complicate things in the installation procedure.

**Comment by akrherz** [comment]
Just curious of the current status of this issue?  I got caught in an ugly 'dll' hell attempting to get proj-4.9 working on RHEL7.

**Comment by pelson** [comment]
Hi @akrherz - there hasn't really been any change to the situation. There is still a hard check in the setup.py: https://github.com/SciTools/cartopy/blob/master/setup.py#L58

I don't want to force any one particular solution on anybody, but personally I have found conda to have hugely simplified the installation process for many packages, including cartopy. I fully accept that conda isn't a silver bullet though, and that sometimes, you just want to use the system packages (through yum, apt etc.).

**Comment by markelg** [comment]
Conda is nice, but many people use pip instead, and currently "pip install cartopy" does not work in ubuntu 14 because the proj-4.9 dependency. Also, in many places is common to work with workstations without access to the root, and the tech people may not be willing to compile manually the last proj4 in the /usr folder. Personally, I have been using basemap instead of cartopy for a long time, because of this issue. I only was able to use cartopy once my workstation was upgraded to ubuntu 14 a few months ago.
