### ISSUE TITLE
Mapping Challenge

### ISSUE THREAD

**Issue by ThomasLecocq** [SciTools/cartopy#667]
For your gallery:

http://kottke.org/13/12/wind-map-of-the-earth :-)

**Comment by pelson** [comment]
Hi Thom,

Nice. Reminds me of the [LineIntegralConvolution (LIC)](http://wiki.scipy.org/Cookbook/LineIntegralConvolution) implementation in Python. I'd also love to see an animated [OLIC](http://graphics.cs.ucdavis.edu/~lfeng/sig/tensor/papers/Animating%20Flow%20Fields%20Rendering%20of%20Oriented%20Line%20Integral%20Convolution.pdf) implementation (maybe one for the cold dark nights of the winter). 

I actually did some LIC stuff the other day for a colleague. The challenge in this case was dealing with the masked data and the fact that the data was in PlateCarree, and was wanted on North Polar Stereographic. Here was the output:

![flow](https://cloud.githubusercontent.com/assets/810663/9718794/e4678742-5576-11e5-9436-8b5d8ed8b612.png)

**Comment by ThomasLecocq** [comment]
:+1: wow !

**Comment by pelson** [comment]
Closing this out as there isn't really anything that needs to be done in cartopy. Always welcome new functionality to do LIC / some other form of vector visualisation, but this issue won't help us track that.
