### ISSUE TITLE
FAIL: cartopy.tests.mpl.test_images.test_web_tiles

### ISSUE THREAD

**Issue by timmie** [SciTools/cartopy#669]
The travis builds fail 
https://travis-ci.org/SciTools/cartopy/jobs/79013794#L784

**Comment by pelson** [comment]
I suspect the web tiles have changed (again). We could do with reducing our dependency on what those tiles look like, but for now, it is appropriate to just update the test image. Interested @timmie?

**Comment by timmie** [comment]
MMh, no time this week.

And I am still very new to the package.

**Comment by pelson** [comment]
Ok, no worries @timmie. Thanks for raising.
