### ISSUE TITLE
1D quiver in non-PlateCarree projections

### ISSUE THREAD

**Issue by ocefpaf** [SciTools/cartopy#672]
Using quiver with 1D arrays of `x`, `y`, `u`, `v` works just fine with `ccrs.PlateCarree()`, but raises a `ValueError` with any other projection:

```python
ValueError: x, y, u and v arrays must be the same shape
```

Using `np.atleast_2d` fixes this, and the quiver docs do say: `Plot a 2-D field of arrows`.

However, I wonder if the `atleast2d` should be inside Cartopy, or if the 1D case should raise an error in PlateCarree too.

(See http://nbviewer.ipython.org/gist/ocefpaf/b2f79fe0f96fa1776b97 for a SSCCE.)

**Comment by ocefpaf** [comment]
BTW:  This bug was found by a student @rafacsantana during our Python course here.  Hopefully the students  will be sending PRs of their own soon :wink:

**Comment by pelson** [comment]
:+1: - let's fix it.

**Comment by pelson** [comment]
Ping @scmc72 / @Jozhogg if you're interested.

**Comment by Jozhogg** [comment]
Taking a look now :+1:

**Comment by ocefpaf** [comment]
@Jozhogg take a look at:

https://github.com/SciTools/cartopy/pull/674

**Comment by Jozhogg** [comment]
Thanks @ocefpaf . Didn't spot your PR at first but I just made that same change myself! It certainly makes sense to me - `transform_vectors` is ok with everything being 1D so I feel like it makes sense to have that capability available in `quiver`. Opinions on that fix @pelson ?

**Comment by pelson** [comment]
Apologies to @ocefpaf and @Jozhogg. I hadn't seen the PR (or at least, hadn't linked the two).
Looks like #674 will do the trick. :+1:

**Comment by ocefpaf** [comment]
> Apologies to @ocefpaf and @Jozhogg.

My bad.  I sent this after a long day and forgot to cross-reference issue/PR.
