### ISSUE TITLE
OverflowError with GeoAxes.set_extent

### ISSUE THREAD

**Issue by BrenBarn** [SciTools/cartopy#680]
In some situations, when using the cartopy GeoAxes to plot maps with matplotlib, I get this error:

```
Traceback (most recent call last):
  File "<pyshell#315>", line 1, in <module>
    ax.set_extent([bounds.X1.min(), bounds.X2.max(), bounds.Y1.min(), bounds.Y2.max()], cartopy.crs.AlbersEqualArea())
  File "C:\FakeProgs\Python27\lib\site-packages\cartopy\mpl\geoaxes.py", line 587, in set_extent
    projected = self.projection.project_geometry(domain_in_crs, crs)
  File "C:\FakeProgs\Python27\lib\site-packages\cartopy\crs.py", line 172, in project_geometry
    return getattr(self, method_name)(geometry, src_crs)
  File "C:\FakeProgs\Python27\lib\site-packages\cartopy\crs.py", line 178, in _project_line_string
    return cartopy.trace.project_linear(geometry, src_crs, self)
  File "lib\cartopy\trace.pyx", line 109, in cartopy.trace.project_linear (lib/cartopy\trace.cpp:1135)
  File "lib\cartopy\trace.pyx", line 71, in cartopy.trace.geos_from_shapely (lib/cartopy\trace.cpp:838)
OverflowError: Python int too large to convert to C long
```

The error is not reliably reproducible; it seems to happen randomly sometimes when creating a new GeoAxes and calling `set_extent` on it.

The line that seems to be raising the error is in `trace.pyx`:

    cdef ptr geos_geom = shapely_geom._geom

From [this old commit](https://github.com/olt/shapely/commit/5cce26429a80f1ff944b5deb1e9095df3eba3188) which I found was made in response to a similar problem discussed on [some mailing list](https://groups.google.com/forum/#!msg/imposm/QWEKSw-zBJA/CqFb1faijZwJ) I gather that similar problems existed in the past, on 32-bit systems, when these `_geom` pointers (whatever they are) got too big to fit into a C datatype.

But I'm on 64-bit Python (2.7.8).  This is on Windows 7 64-bit.  I've installed Cartopy 0.13 and Shapely 1.5.12 using the 64-bit wheels from [Christoph Gohlke's site](http://www.lfd.uci.edu/~gohlke/pythonlibs/).

I'm not sure what's going on here, but it seems that somewhere in the innards Cartopy is still relying on some values being able to fit into a C long, and it's failing when that's not the case.  I'm guessing that the random nature of the problem is because a new `_geom` is created every time I create a new GeoAxes (or maybe every time I call `set_extent`), so sometimes it happens to create one that's too big, and sometimes it doesn't.

**Comment by pelson** [comment]
Thanks @BrenBarn. The stochastic nature of the issue will make this a little bit of trial and error, but hopefully we can use our intuition and find a solution pretty quickly.

If you were able to produce a for loop which after a while was able to guarantee a failure, and are comfortable getting cartopy from source, I'd be changing https://github.com/SciTools/cartopy/blob/master/lib/cartopy/trace.pyx#L59 to an ``unsigned long``.

Is there any way you could provide a SSCCE example which, given n attempts, would cause the issue? I don't have a 64-bit Windows machine conveniently available, so will find this hard to reproduce. To my knowledge, I don't know of anybody else who has seen this issue before - but equally, I'm unaware of how many people use Cartopy on Windows either.

Thanks!

**Comment by BrenBarn** [comment]
Unfortunately, so far I haven't been able to set up specific conditions that reliably reproduce the error.  I am working with a set of census shapefiles and encounter the error off and on.

As for your suggested fix, I can't try it out, because I was not able to find a way to compile cartopy from source on Windows, at least not without more pain than I am willing to undergo.  I do have Visual Studio installed and am able to compile some Python extensions, but Cartopy's dependencies on various geospatial libraries tripped me up.

**Comment by pelson** [comment]
> I do have Visual Studio installed and am able to compile some Python extensions, but Cartopy's dependencies on various geospatial libraries tripped me up.

If you use conda, that pain is pretty light-weight. One option would be to install cartopy's dependencies with conda (as defined in the [conda-recipes-scitools recipe](https://github.com/SciTools/conda-recipes-scitools/blob/master/cartopy/meta.yaml)) and then ``python setup.py install`` the cartopy source.

I appreciate you taking the time to raise the issue, and am tempted to include the proposed change into cartopy anyway, but obviously that does not guarantee that we have found the solution to the problem. I'd certainly be happy to help you get setup if that is the route you want to go to see if it fixed the problem for you.

Cheers!

**Comment by QuLogic** [comment]
Ohh, I though `ptr` came from Cython, so I was wondering how it could get confused about its own types, but it looks like that's defined in the file. The correct fix would be to get rid of `ptr`.

The problem is the mix with `ctypes`. Does anyone know how to create a `ctypes.c_void_p` from within the Cython file?
