### ISSUE TITLE
PlateCarree projection span 180°

### ISSUE THREAD

**Issue by wqshen** [SciTools/cartopy#706]
when i want to plot the south pacific with a PlateCarree projection, i write code list below

ax = plt.subplot(projection=ccrs.PlateCarree())
ax.coastlines('50m')
ax.set_extent([135, -150, -60, 0], ccrs.PlateCarree())
plt.show()

But i get the wrong map plot, see attachment, how to fix it ?
![south_pacific](https://cloud.githubusercontent.com/assets/12339722/12015590/8f573b8e-ad79-11e5-996b-6e7397013bed.png)

**Comment by rhattersley** [comment]
Coordinates in a PlateCaree projection are "dumb" Cartesian coordinates - they do not wrap around. So the main problem is you need to change the central longitude of your PlateCaree projection. Once you've done that you can adjust the extent:

```python
ax = plt.subplot(projection=ccrs.PlateCarree(180))
ax.coastlines('50m')
ax.set_extent([135, 210, -60, 0], ccrs.PlateCarree())
plt.show()
```

![south_pacific](https://cloud.githubusercontent.com/assets/917914/12032040/a98712da-ae0b-11e5-862f-b517663f3e01.png)

**Comment by wqshen** [comment]
Thanks

**Comment by pelson** [comment]
See also http://stackoverflow.com/questions/13856123/setting-up-a-map-which-crosses-the-dateline-in-cartopy.

Cheers,
