### ISSUE TITLE
Release v0.14

### ISSUE THREAD

**Issue by pelson** [SciTools/cartopy#716]
Just a heads up @SciTools/cartopy-devs that we are long overdue a v0.14. I'll be triaging and will work towards cutting a release in the next 2-3 weeks.

**Comment by QuLogic** [comment]
So I think 2-3 weeks have gone by...

**Comment by pelson** [comment]
> Probably everything left on the milestone are bump-able.

That is true and sensibly pragmatic. I'll cut a release of v0.14 today. :+1:

**Comment by QuLogic** [comment]
Can close as soon as #733 is handled.

**Comment by pelson** [comment]
Thanks @QuLogic - sorry for the slow-ish turnaround. Let's not leave it so long next time :wink:
