### ISSUE TITLE
Add support for latitude of true scale to Mercator

### ISSUE THREAD

**Issue by bladwig1** [SciTools/cartopy#728]
While most Mercator projections use 0 deg as the latitude of true scale (default), it is possible to modify this latitude using the "+lat_ts" parameter in Proj4.  This parameter currently isn't supported in the Mercator projection class.

**Comment by pelson** [comment]
Sure. If you're interested in submitting a PR (and following https://github.com/SciTools/cartopy/blob/master/CONTRIBUTING.md) I can't see a reason why it shouldn't be accepted. There may be some complexity in the domain calculation - https://github.com/SciTools/cartopy/blob/master/lib/cartopy/crs.py#L963 - but shouldn't be anything insurmountable.

Cheers!
