### ISSUE TITLE
0.13.1 is not on PyPI

### ISSUE THREAD

**Issue by dopplershift** [SciTools/cartopy#733]
Any reason for this?

**Comment by pelson** [comment]
> Any reason for this?

Only lack of motivation :smile: - I've burnt :fire: too much time in the past to use pypi for anything compiled. It is a trivial task though, so if it is useful to you, I'd happily do it.

**Comment by dopplershift** [comment]
My CI setup is building wheels and caching them on S3, using only pip. Without the 0.13.1 tarball, all I get is 0.13.0 (which still has the annoying shapely problem).

**Comment by pelson** [comment]
@dopplershift - I fully intend to push this as part of the v0.14 release, but can't do this until I have the credentials that are sitting on my office machine - unfortunately, I won't be able to do this for 8 days. Hope that isn't too much trouble?

**Comment by dopplershift** [comment]
To be truly lazy, you could add a deploy step to the `.travis.yml` and have it do it automatically (only on tags of course)

**Comment by pelson** [comment]
I've just uploaded v0.14.0 and v0.13.1. https://pypi.python.org/pypi/Cartopy/0.14.0

Not the first time that a pypi package has been requested (#524).

Let me know if there are any problems @dopplershift.

Thanks!

**Comment by dopplershift** [comment]
Thanks! (Now I have to worry about Proj4 4.9, but that's my own fault for trying to use wheels....)

**Comment by pelson** [comment]
> Thanks! (Now I have to worry about Proj4 4.9, but that's my own fault for trying to use wheels....)

https://github.com/conda-forge/proj.4-feedstock :stuck_out_tongue_winking_eye:
