### ISSUE TITLE
Add new Natural Earth shapefiles manually and use as a feature

### ISSUE THREAD

**Issue by ispmarin** [SciTools/cartopy#734]
I tried to download more shapefiles from Natural Earth directly and put on the cache folder, renaming them, and cartopy is not capable of finding them. For example, a physical shapefile with 10m resolution would be named 10m_geographic_locations.shp, with the other files, and I would try to plot using a feature like

NaturalEarthFeature(category='physical', scale='10m', facecolor='none',
                         name='geographic_locations')
with no luck.

**Comment by QuLogic** [comment]
Where exactly did you put the files?

**Comment by ispmarin** [comment]
where cartopy.config said that the cache was. In my system, on `.local/share/cartopy/natural_earth/shapefiles/physical`, for example.

**Comment by ajdawson** [comment]
On my system these are stored in `~/.local/share/cartopy/shapefiles/natural_earth/physical`. Note the order of `shapefiles` and `natural_earth` are swapped. Can you double check the location is correct?

**Comment by ispmarin** [comment]
Sure, sorry about that.

    {'data_dir': '/home/user/.local/share/cartopy',
    'downloaders': {('shapefiles',
   'gshhs'): <cartopy.io.shapereader.GSHHSShpDownloader at 0x7f3602119a10>,
  ('shapefiles',
   'natural_earth'): <cartopy.io.shapereader.NEShpDownloader at 0x7f3602119950>},
 'pre_existing_data_dir': '',
 'repo_data_dir': '/home/user/bin/virtualenvs/mobi/local/lib/python2.7/site-packages/cartopy/data'}

**Comment by ajdawson** [comment]
I'm not able to reproduce this issue. I downloaded the shapefiles and places them in my cache directory (`~/.local/share/cartopy/shapefiles/natural_earth/physical`) and cartopy found them.

You stated that your cache directory was `~/.local/share/cartopy/natural_earth/shapefiles/physical`, which would be **incorrect**. If this is really where you are putting them then you need to move them to `~/.local/share/cartopy/shapefiles/natural_earth/physical`. Can you confirm for us whether or not the directory you are placing the downloaded files/symlinks in is the correct path?

**Comment by ispmarin** [comment]
I confirmed on the post above that my path is the same as yours and posted the `cartopy.config` to show. Sorry about the noise.

What format and how did you put them there? What are the filenames and what do you put on the `name` variable on the features? 

Thanks!

**Comment by ajdawson** [comment]
Sorry I didn't see anywhere that you confirmed the full path, you only showed the value of `cartopy.config`, which doesn't tell me the files are in the correct place, I shall now assume that `ls ~/.local/share/cartopy/shapefiles/natural_earth/physical` prints a list of your files and symbolic links you made to them with corrected names.

I placed symlinks to the downloaded files in `~/.local/share/cartopy/shapefiles/natural_earth/physical` and named them without the preceeding `ne_` exactly as you specified. I used the name "geographic_lines" to construct the feature, again as you specified.

**Comment by ispmarin** [comment]
Could you please show the cartopy code for the Feature?

**Comment by ajdawson** [comment]
Identical to yours I'm afraid:

```python
cfeature.NaturalEarthFeature(
        category="physical",
        name="geographic_lines",
        scale="10m",
        facecolor="none")
```

**Comment by ispmarin** [comment]
Got it. The `name` parameter must match exactly the name of the files, without the scale in front. It works now. 

Thanks!

**Comment by pelson** [comment]
Thanks @ispmarin, and especially big thanks to @ajdawson for supporting @ispmarin. :+1:
