### ISSUE TITLE
Correct SRTM DEM shading

### ISSUE THREAD

**Issue by scottyhq** [SciTools/cartopy#752]
The example [srtm_shading.py](http://scitools.org.uk/cartopy/docs/latest/examples/srtm_shading.html) has an issue with scaling. The function shade() in srtm.py should have an option for a horizontal scale factor since SRTM files have units (degrees, degrees, meters). And the function expects constant x,y,z units. I've changed the function to match output from the GDAL tool [gdaldem hillshade](http://www.gdal.org/gdaldem.html), which has an option for horizontal scale and vertical exaggeration. A comparison of the example before and after the correction is below:

![shade_new](https://cloud.githubusercontent.com/assets/3924836/14295200/4bf86e08-fb3a-11e5-9316-b765304bcf76.png)
![shade_old](https://cloud.githubusercontent.com/assets/3924836/14295201/4c1c7898-fb3a-11e5-99d5-2ec2c620d6bd.png)

I'll try to submit a pull request for this, but haven't contributed before...

**Comment by pelson** [comment]
Closed by #754.
