### ISSUE TITLE
Projection = Orthographic not allowing the addition of markers using plt.plot

### ISSUE THREAD

**Issue by pearseb** [SciTools/cartopy#765]
Hi there,

I've been trying to add some location markers to an Orthographic projection with a central latitude over -90 degrees (i.e. over Antarctica). I do this using the plt.plot function usually when I am using the PlateCarree projection and it works perfectly. However, this time, cartopy places my markers on the central latitude. To place my markers on the correct lat and lon coordinates, I have to use the central_latitude and central_longitude arguments within the transform=ccrs.Orthographic() command.

My code is like so:

```python
# make Southern Ocean plots
fig = plt.figure(figsize=(10,10), facecolor='w')
ax1 = plt.axes(projection=ccrs.Orthographic(central_latitude=-90.0))
ax1.coastlines(resolution='110m')
ax1.gridlines()
ax1.add_feature(cartopy.feature.LAND, zorder=1, 
                edgecolor='black',facecolor=cartopy.feature.COLORS['land_alt1'])
iplt.pcolormesh(mixCNRM_ave, cmap='bone_r', vmin=0,vmax=1000, zorder=0)
cbar = plt.colorbar(orientation='horizontal').set_label(
    label='depth of convective mixing (m)',size=15, family='serif')

# add markers of density changes
scaled = (Rho_d) / ((0-Rho_d.min())*2)
colors = cm.coolwarm(Rho_d)

for num,let in enumerate(CNRMouts):
    sc = scatter(0, 0, marker='o', c=colors, s=100,
                 transform=ccrs.Orthographic(central_latitude=CNRMouts[let][5],
                                             central_longitude=CNRMouts[let][6]))
```

You can see that I have to iterate over the locations where I want to put markers down. This is very annoying, because it makes it very difficult to then add a colorbar to the markers that I add, which has proved difficult.

Hopefully someone has some experience with this or some advice?

Very best,
Pearse

**Comment by ajdawson** [comment]
I think you probably have some confusion about the meaning of the transform keyword. The transform keyword should indicate the coordinate system the data you wish to plot are defined in. Your points must be represented as latitude/longitude because you afre using them to set central latitude/longitude, so the appropriate transform is likely `ccrs.PlateCarree()`. Something like this works fine for plotting multiple points:

```python
fig = plt.figure(figsize=(10,10), facecolor='w')
ax1 = plt.axes(projection=ccrs.Orthographic(central_latitude=-90.0))
ax1.coastlines(resolution='110m')
ax1.gridlines()
ax1.add_feature(cartopy.feature.LAND, zorder=1, edgecolor='black')
ax1.set_global()

lons = [36.2, 55.8, 109.2]
lats = [-62, -81, -78]
ax1.scatter(lons, lats, marker='o', transform=ccrs.PlateCarree(), zorder=2)
```

Note I used `PlateCarree()` for the transform since I am passing in points represented as latitudes and longitudes. (I also set the zorder=2 since some of my points are over the land you wanted to plot with zorder=2, this may not be needed for your case)

**Comment by pearseb** [comment]
Hi Andrew,

Thank you very much for your solution. I didn’t realise that the transform needed to be PlateCarree. Is this the case with all projections if we are adding markers to them?

Best,
Pearse

**Comment by ajdawson** [comment]
The value passed with the transform keyword is independent of the projection you are plotting on, so if you always plot points in lat/lon then you should always pass `PlateCarree`.

**Comment by pearseb** [comment]
Ahh. Thanks for that!
Pearse

**Comment by QuLogic** [comment]
This looks like it's not an issue, so I'm going to close it.
