### ISSUE TITLE
LPDAAC downtime warning

### ISSUE THREAD

**Issue by jsignell** [SciTools/cartopy#769]
I was struggling for a while yesterday to get a different source of SRTM3 rasters because [LPDAAC](https://lpdaac.usgs.gov/data_access/data_pool) was down. It would be nice if the downloader could at least throw this warning from the website: Please note weekly maintenance is every Wednesday 0800-1200 Central Time. Even better would be a direction of how to use another source.

**Comment by QuLogic** [comment]
Well, that's annoying. Ping @scottyhq who suggested this change to see if he has any suggestions as well.

**Comment by scottyhq** [comment]
Perhaps it'd be easy to add a Base URL option to the SRTM downloader? But the other servers I know provide 90m hole-filled datasets, not 30m...

In the meantime you can make you own hillshade and then add it to a figure with ax.imshow()

Here is another source I know of for 90m: http://srtm.csi.cgiar.org/index.asp
And a cool interface http://dwtkns.com/srtm/

The interface for 30m dems I believe uses the same LPDAAC server:
http://dwtkns.com/srtm30m/

Or you can download 90m hole-filled scenes (generated differently) through this website:
http://earthexplorer.usgs.gov

Some more information here:
https://lpdaac.usgs.gov/sites/default/files/public/measures/docs/SRTM%20Quick%20Guide.pdf

**Comment by jsignell** [comment]
Thanks! Can you point me to any examples of opening raster data? I have been having a hard time figuring it out.

**Comment by vincentschut** [comment]
ESA has a srtmgl1 (30m) mirror: http://step.esa.int/auxdata/dem/SRTMGL1/
No idea how 'official' this is.
