### ISSUE TITLE
weird hexbin

### ISSUE THREAD

**Issue by wqshen** [SciTools/cartopy#770]
when i plot a hexbin, something is wrong, please help me
## Code

``` python
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import numpy as np
lons = np.asarray('''128.6  142.6  144.7  160.8  118.4  123.   112.6  122.2  131.9  134.2
                    127.9  148.1  113.8  110.3  155.   138.7  127.1  153.3  136.9  131.9
                    129.4  127.5  168.7  119.1  125.1  119.9  143.3  130.8  130.3  131.2
                    129.9  129.2  130.3  120.7  119.5  112.8  130.2  144.9  151.9  137.4
                    151.2  143.5  141.7  142.6  142.3  158.6  144.9  127.9  126.4  117.4
                    117.1  124.   129.5  129.1  129.2  137.1  137.1  136.7  114.   133.1
                    130.3  149.8  166.4  131.6  147.4  114.6  136.8  128.5  158.4  143.4
                    132.6  126.5  116.1  138.8  155.8  150.4  162.4  170.1  133.   132.8
                    130.9  130.9  133.4  126.8  112.7  137.5  128.4  130.2  131.8  142.7
                    140.6  124.6  151.9  129.4  111.6  145.8  146.3  117.1  140.1  147.3
                    113.   123.3  122.9  147.1  128.7  120.6  134.5  126.7  127.6  111.4
                    113.8  145.   119.5  130.   132.3  129.4  114.2  124.6  140.6  112.9
                    111.9  116.2  115.6  116.5  153.7  123.8  128.8  138.7  128.8  119.
                    156.1  141.7  142.4  143.3  116.4  119.   121.   132.5  150.3  150.1
                    141.   140.9  160.3  170.8  142.6  111.3  121.5  112.3  144.   120.1
                    116.9  165.   141.6  130.4  162.7  119.7  129.8  115.6  125.   138.9
                    160.6  130.1  142.7  119.9  129.8  114.1  152.7  132.   158.   170.9
                    119.2  118.   157.9  158.3  132.5  155.4  170.3  121.7  111.4  130.2
                    122.8  118.8  149.1  125.6  120.5  126.1  156.2  161.4  132.9  118.4
                    135.7  115.2  159.3  136.   134.3  124.   131.3  113.8  157.5  130.6
                    116.5  126.8  127.   116.2  116.8  120.6  120.1  154.5  132.6  149.1
                    130.2  112.8  161.9  124.7  119.   131.2  131.3  139.2'''.split(), 'f4')
lats = np.asarray('''28.5  15.9  27.9  13.8  12.2  21.5  12.7  19.3  23.3  30.5  14.4  26.6
                     17.9  18.6  17.   18.1  23.7  35.6  21.8  22.5  28.1  16.6  18.8  19.5
                     23.4  26.3  13.6  12.2  11.9  21.8  21.   25.9  27.4  15.1  26.3  16.8
                     27.8  27.7  30.4  19.2  19.5  20.1  18.1  22.9  22.5  20.4  20.9  18.1
                     18.   21.9  21.7  27.7  23.7  24.7  25.2  19.3  19.6  20.4  19.4  26.
                     12.9  13.9  26.3  13.9   8.4  15.6  11.   12.5   4.    9.2  18.   26.7
                     20.4  42.6  16.3  49.3  25.3   9.5  31.6  31.6  23.3  23.2  11.1  27.7
                     16.2  12.6  18.4  18.1  18.2   6.4   8.3  15.6   7.2  32.3  17.9  17.3
                     26.8  10.3  23.2  21.5  20.9  28.5  28.5  18.1  16.9  14.8  20.8  21.
                     13.8  17.4  13.   12.   12.   23.4  24.4  16.6  17.6  18.4   9.1   8.8
                      7.5  18.5  14.1  15.4  14.1  18.9  14.9   9.4  17.8  18.2  18.7  22.1
                     22.   21.8  15.6  19.4  20.   16.    6.4  15.   14.7  20.8  28.6  18.8
                     31.2  15.7  23.1  13.9   7.7  20.1  18.6   4.7   5.6  13.6   4.1  16.2
                     16.1  19.7  34.2  23.3  31.4  16.9  30.1  19.2  20.3   7.9  26.6  25.8
                     27.4  25.9  19.2  19.9   8.6   7.6  35.9  23.2   7.8  29.5  15.7  20.1
                     12.2  19.8  39.3  25.7  11.5  26.6   5.7   5.8  22.1  16.3  16.3  17.2
                     25.6  14.5  16.5  15.2  14.   12.3  20.2  17.9  18.6  20.   19.9  15.5
                     17.8  18.8  19.3  22.   14.1  20.6  25.6   9.8  23.3  17.7  21.7  22.5
                     22.7  32.1'''.split(), 'f4')
ax = plt.subplot(projection=ccrs.PlateCarree(180))
ax.coastlines('50m')
ax.set_extent([110, 200, 0, 60], ccrs.PlateCarree())
ax.hexbin(lons, lats, mincnt=1, gridsize=10, cmap=plt.cm.Blues, transform=ccrs.PlateCarree())
plt.show()
```
## figure

![weirdhexbin](https://cloud.githubusercontent.com/assets/12339722/15633906/9d30aa30-25ea-11e6-889b-847fd5a156cc.png)

**Comment by Yefee** [comment]
'''javascript
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import numpy as np
lons = np.asarray('''128.6  142.6  144.7  160.8  118.4  123.   112.6  122.2  131.9  134.2
                    127.9  148.1  113.8  110.3  155.   138.7  127.1  153.3  136.9  131.9
                    129.4  127.5  168.7  119.1  125.1  119.9  143.3  130.8  130.3  131.2
                    129.9  129.2  130.3  120.7  119.5  112.8  130.2  144.9  151.9  137.4
                    151.2  143.5  141.7  142.6  142.3  158.6  144.9  127.9  126.4  117.4
                    117.1  124.   129.5  129.1  129.2  137.1  137.1  136.7  114.   133.1
                    130.3  149.8  166.4  131.6  147.4  114.6  136.8  128.5  158.4  143.4
                    132.6  126.5  116.1  138.8  155.8  150.4  162.4  170.1  133.   132.8
                    130.9  130.9  133.4  126.8  112.7  137.5  128.4  130.2  131.8  142.7
                    140.6  124.6  151.9  129.4  111.6  145.8  146.3  117.1  140.1  147.3
                    113.   123.3  122.9  147.1  128.7  120.6  134.5  126.7  127.6  111.4
                    113.8  145.   119.5  130.   132.3  129.4  114.2  124.6  140.6  112.9
                    111.9  116.2  115.6  116.5  153.7  123.8  128.8  138.7  128.8  119.
                    156.1  141.7  142.4  143.3  116.4  119.   121.   132.5  150.3  150.1
                    141.   140.9  160.3  170.8  142.6  111.3  121.5  112.3  144.   120.1
                    116.9  165.   141.6  130.4  162.7  119.7  129.8  115.6  125.   138.9
                    160.6  130.1  142.7  119.9  129.8  114.1  152.7  132.   158.   170.9
                    119.2  118.   157.9  158.3  132.5  155.4  170.3  121.7  111.4  130.2
                    122.8  118.8  149.1  125.6  120.5  126.1  156.2  161.4  132.9  118.4
                    135.7  115.2  159.3  136.   134.3  124.   131.3  113.8  157.5  130.6
                    116.5  126.8  127.   116.2  116.8  120.6  120.1  154.5  132.6  149.1
                    130.2  112.8  161.9  124.7  119.   131.2  131.3  139.2'''.split(), 'f4')
lats = np.asarray('''28.5  15.9  27.9  13.8  12.2  21.5  12.7  19.3  23.3  30.5  14.4  26.6
                     17.9  18.6  17.   18.1  23.7  35.6  21.8  22.5  28.1  16.6  18.8  19.5
                     23.4  26.3  13.6  12.2  11.9  21.8  21.   25.9  27.4  15.1  26.3  16.8
                     27.8  27.7  30.4  19.2  19.5  20.1  18.1  22.9  22.5  20.4  20.9  18.1
                     18.   21.9  21.7  27.7  23.7  24.7  25.2  19.3  19.6  20.4  19.4  26.
                     12.9  13.9  26.3  13.9   8.4  15.6  11.   12.5   4.    9.2  18.   26.7
                     20.4  42.6  16.3  49.3  25.3   9.5  31.6  31.6  23.3  23.2  11.1  27.7
                     16.2  12.6  18.4  18.1  18.2   6.4   8.3  15.6   7.2  32.3  17.9  17.3
                     26.8  10.3  23.2  21.5  20.9  28.5  28.5  18.1  16.9  14.8  20.8  21.
                     13.8  17.4  13.   12.   12.   23.4  24.4  16.6  17.6  18.4   9.1   8.8
                      7.5  18.5  14.1  15.4  14.1  18.9  14.9   9.4  17.8  18.2  18.7  22.1
                     22.   21.8  15.6  19.4  20.   16.    6.4  15.   14.7  20.8  28.6  18.8
                     31.2  15.7  23.1  13.9   7.7  20.1  18.6   4.7   5.6  13.6   4.1  16.2
                     16.1  19.7  34.2  23.3  31.4  16.9  30.1  19.2  20.3   7.9  26.6  25.8
                     27.4  25.9  19.2  19.9   8.6   7.6  35.9  23.2   7.8  29.5  15.7  20.1
                     12.2  19.8  39.3  25.7  11.5  26.6   5.7   5.8  22.1  16.3  16.3  17.2
                     25.6  14.5  16.5  15.2  14.   12.3  20.2  17.9  18.6  20.   19.9  15.5
                     17.8  18.8  19.3  22.   14.1  20.6  25.6   9.8  23.3  17.7  21.7  22.5
                     22.7  32.1'''.split(), 'f4')
ax = plt.subplot(projection=ccrs.PlateCarree(120))
ax.coastlines('50m')
ax.set_extent([110, 200, 0, 60], ccrs.PlateCarree())
ax.hexbin(lons, lats, mincnt=1, gridsize=10,
          cmap=plt.cm.Blues, transform=ccrs.PlateCarree())
plt.show()
'''

**Comment by wqshen** [comment]
thank you, seems the cen_lon is the key
