### ISSUE TITLE
Conda install basemap and cartopy have confilict

### ISSUE THREAD

**Issue by qingkaikong** [SciTools/cartopy#771]
I am using conda to install cartopy, which seems require geos 3.4.2. It works fine with geos 3.4.2, but when I use conda to install basemap, the geos will be downgrade to 3.3.3, which makes the cartopy not working with the following error:

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-6-383365a20073> in <module>()
----> 1 import cartopy.crs as ccrs
      2 import cartopy.feature as cfeature
      3 
      4 def make_cartopy(projection=ccrs.Robinson(), figsize=(10, 5), resolution='110m'):
      5     fig, ax = plt.subplots(figsize=figsize, subplot_kw=dict(projection=projection))

/Users/qingkaikong/miniconda2/lib/python2.7/site-packages/cartopy/__init__.py in <module>()
    108 # Commonly used sub-modules. Imported here to provide end-user
    109 # convenience.
--> 110 import cartopy.crs
    111 import cartopy.feature

/Users/qingkaikong/miniconda2/lib/python2.7/site-packages/cartopy/crs.py in <module>()
     36 
     37 from cartopy._crs import CRS, Geocentric, Geodetic, Globe, PROJ4_RELEASE
---> 38 import cartopy.trace
     39 
     40 

ImportError: dlopen(/Users/qingkaikong/miniconda2/lib/python2.7/site-packages/cartopy/trace.so, 2): Library not loaded: @rpath/./libgeos_c.1.dylib
  Referenced from: /Users/qingkaikong/miniconda2/lib/python2.7/site-packages/cartopy/trace.so
  Reason: Incompatible library version: trace.so requires version 10.0.0 or later, but libgeos_c.dylib provides version 9.0.0

**Comment by ocefpaf** [comment]
@qingkaikong that conflict exists only in the `default` channel `basemap`. (I am not sure where/how you are installing you `cartopy`.)

Try the conda-forge channel:

```shell
 conda install -c conda-forge basemap cartopy
```

**Comment by qingkaikong** [comment]
Great, thanks, using the conda-forge channel works! I was using the default channel to install basemap!

**Comment by envhyf** [comment]
I have met the same issue while installing cartopy package. Then I tried the command 

       conda install -c conda-forge basemap cartopy

The output shows like:      

      # All requested packages already installed.
      # packages in environment at /Users/HYF/anaconda:
      #
      basemap                   1.1.0                    py27_3    conda-forge
      cartopy                   0.15.1                   py27_5    conda-forge

But the problem is not fixed.

**Comment by ajdawson** [comment]
I tried installing both cartopy and basemap from conda-forge using Python 2.7 (on linux-64), which provided geos 3.6.2 and both basemap and cartopy are functioning correctly.

Which platform are you on? Can you try updating geos?
