### ISSUE TITLE
Additional options for the stock image

### ISSUE THREAD

**Issue by malcolmbrooks** [SciTools/cartopy#786]
The current stock_img() call has a single image available to it (a downscaled Natrual Earth 1). It would be good to be able to choose a higher resolution image (x2 and x4 for instance), and from the Grey Earth and Hypsometric Tints images.

**Comment by ajdawson** [comment]
The `stock_img()` method draw a pre-downloaded (actually shipped with cartopy) image, as you say downsampled from Natural Earth 1. I'm not in favour of extending `stock_img()` to do anything more, as its purpose is for quick-and-easy display of a basemap, and including higher resolution data would swell the size of the cartopy repository to beyond reasonable in my opinion.

However, your point about accessing these other rasters is a good one. I'm not sure our `NaturalEarthFeature` system is capable of obtaining the rasters right now, but this is the place to extend if any as it would allow users to choose arbitrary style and resolution from the full range of Natural Earth rasters.

**Comment by malcolmbrooks** [comment]
That sounds interesting. Is there the option to cache the images that the NaturalEarthFeature has produced?

Without caching, then the background image would be a bottleneck for a job plotting a large number of forecast fields, in parallel, over multuiple regions. That is an advantage of preprocessed/downscaled images.

**Comment by ajdawson** [comment]
I think there is automatic caching already for the Natural Earth sources we support.

**Comment by malcolmbrooks** [comment]
This has come up again, and it would be really useful for me to be able to add the grey earth with shaded relief images in the next couple of weeks. I'm happy to do this myself locally, as a temporary measure, via stock image. 

Whether or not that would get merged in is another matter. I suspect that it would be quite a popular feature with users and the increase in the data file size wouldn't be that large.

Malcolm

**Comment by pelson** [comment]
Fixed by #815.
