### ISSUE TITLE
setup.py install ignores previous built_ext -I arguments

### ISSUE THREAD

**Issue by yggdr** [SciTools/cartopy#790]
Had to compile current proj myself, now installing cartopy fails with setup.py install not finding proj's header files.
The initial setup.py build_ext --inplace -I$HOME/local/include -L$HOME/local/lib works, but the -I flag cannot be passed to setup.py install in any way I have found. Now install tries to run this:
    lib/cartopy/trace.cpp -o build/temp.freebsd-10.3-RELEASE-p4-amd64-3.5/lib/cartopy/trace.o
which of course errors out:
    lib/cartopy/trace.cpp:282:10: fatal error: 'proj_api.h' file not found
Manually running this with a proper -I added works, but setup.py install nevertheless tries to compile it again without -I

**Comment by ajdawson** [comment]
If you use the `--inplace` option you will build extension modules alongside the source, which is great if you are doing development, but no good if you want to install the library. Re-run the `build_ext` command without the `--inplace` flag and it should find what it needs. You can even do it all in one command:

    python setup.py build_ext -I$HOME/local/include -L$HOME/local/lib install

**Comment by yggdr** [comment]
Thank you. I propose that
http://scitools.org.uk/cartopy/docs/latest/installing.html#installing
should be changed or appended to reflect this information.

**Comment by ajdawson** [comment]
I agree with @yggdr - the `--inplace` form is not useful for users who aren't doing development on the project.

**Comment by ajdawson** [comment]
Addressed in #793
