### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by darribas** [SciTools/cartopy#792]
Hi,

I'm working on some code to pull down tiles and part of it relies on some of the machinery in `cartopy`. It is really just one function ([`_merge_tiles`](https://github.com/SciTools/cartopy/blob/master/lib/cartopy/io/img_tiles.py#L381)), but it's quite handy. Right now, I have `cartopy` as a dependency but, thinking of making the library leaner, I was thinking of copying the function (of course with due attribution) and dropping the dependency. Would it be possible for me then to license my library (with the function copied) under a BSD-like license? I think so as it's **L**GPL, but I thought I'd check to be completely sure. Thanks!

**Comment by darribas** [comment]
The package is now [`contextily`](https://github.com/darribas/contextily) and it depends on `cartopy`. However, I'd be keen to make it more lightweight if possible. Any chance anyone could chip in on this? Thank you very much in advance.

**Comment by ghisvail** [comment]
> thinking of making the library leaner

You mean "self-contained" right?

> I was thinking of copying the function (of course with due attribution) and dropping the dependency.

Is it trivial enough to be somehow rewritten in your case? 

> I think so as it's LGPL, but I thought I'd check to be completely sure.

LGPL is [difficult](http://stackoverflow.com/questions/8580223/using-python-module-on-lgpl-license-in-commercial-product) to define outside of dynamic libraries. The minimum would be to isolate this function in its own module (licensed under LGPL, with attribution et al.) and import the module where needed. The rest of the library could then remain permissively licensed.

**Comment by pelson** [comment]
@darribas - at this point, I think you'd need to explicitly state that the function was LGPL and retain the copyright information.
Relevant line is at https://github.com/SciTools/cartopy/blob/master/COPYING.LESSER#L47-L61.


Contextly looks awesome - I wish I'd had it when I was writing the tiler stuff in cartopy! I wouldn't rule out cartopy [optionally] depending on it in the future 😉 

Closing this out, as I think you have everything you need, but do remember that INAL.

**Comment by darribas** [comment]
Thanks for the pointer! I think I'll just leave for now with the `cartopy` dependency. To be honest, it's so much easier to install since `conda-forge` and I haven't had complains that a lighter `contextily` is needed. Plus, once they have it installed, they might discover the beauty `cartopy` is ;)
