### ISSUE TITLE
Consider marking tests requiring network access

### ISSUE THREAD

**Issue by ghisvail** [SciTools/cartopy#797]
The testsuite in version `0.14.2` cannot be fully executed without network access. This is an issue in environments such as the Debian builders, whereby remote fetching of resources is forbidden. Testing is still possible via the non-network test cases, but the procedure requires selective feeding of test files to `nosetests` which is not elegant and far from ideal.

Since you guys are apparently planning to [move away](https://github.com/SciTools/cartopy/pull/758) from `nose` in favour of `pytest`, please consider tagging such network dependent tests with a common [marker](http://doc.pytest.org/en/latest/example/markers.html), so they can be easily excluded from the command line.

Cheers,

**Comment by ghisvail** [comment]
ping @marqh for opinion

Right now, I can only run a restricted set of the tests for the Debian build of `cartopy` due to the lack of network connectivity in the builders. It would really help us out if the tests were made agnostic to the environment and skip tests whenever a resource (such as the network) or an optional dependency (such as matplotlib) is not available. I believe this is possible with both `nose` and `pytest`.

Thanks for considering this issue.

**Comment by marqh** [comment]
Hi @ghisvail 

I agree that there should be the ability to run tests in a range of environments and that implementing skip patterns to handle these cases is a good pattern.  

I believe I also have a requirement to have this delivered for another reason.
I will try to ensure that this is a critical path activity for the next release

thank you

**Comment by QuLogic** [comment]
With pytest, all network-using tests should be marked with the `network` marker now.
