### ISSUE TITLE
Consider shipping the source of the docs in the PyPI tarball 

### ISSUE THREAD

**Issue by ghisvail** [SciTools/cartopy#798]
Most Linux distributions feed the source of their Python packages from PyPI. Currently, the tarball of version `0.14.2` is missing the source of the Sphinx documentation which would be required to build a documentation package for `cartopy`.

Please consider updating the manifest to include the documentation source. Appending `recursive-include docs *` to `MANIFEST.in` should normally suffice.

Cheers,

**Comment by pelson** [comment]
Closed in #913.
