### ISSUE TITLE
Allow interpolation between grid points as opposed to plotting projected pixels.

### ISSUE THREAD

**Issue by MarkWieczorek** [SciTools/cartopy#800]
I would like to project and plot the data in a numpy geographic array. This works, but cartopy plots each individual point as a projected cartesian pixel. This is probably the best approach to use with image data, but with geophysical data (magnetic field, gravity field, topography, etc.) what should be done is plot the data point at the grid node and then smoothly interpolate between the projected nodes. 

I tried doing this using the interpolation option of imshow, but this had no effect (see image below)

```
ax.imshow(data, interpolation="bicubic", transform=ccrs.PlateCarree())
```

Is there a simple way to do this in cartopy, and if not, could this be added as a feature request?

![figure_1](https://cloud.githubusercontent.com/assets/8697285/18779353/f4d4a84c-8178-11e6-8997-2e699dfd88f7.png)

**Comment by QuLogic** [comment]
This seems like something that `ax.contourf` would do (by specifying a relatively large number of contours)?

**Comment by pelson** [comment]
Agreed. This does sound like ``contourf``.
