### ISSUE TITLE
imshow optimisation

### ISSUE THREAD

**Issue by duncanwp** [SciTools/cartopy#808]
Having run into #772 I noticed that imshow is performing a full regrid on my data despite the fact that they have the same projection. I think the problem is that the central-longitude differs. 

Once #722 is fixed it won't make a huge amount of difference except for high-res images, but it might be worth adding an extra set of logic for simple translations to save the full regrid.

**Comment by pelson** [comment]
pykdtree has optimised this problem so much that I think we would see very little return on having such a short circuit. The current implementation handles wrap-arounds, poles and cuts, and getting this right in special cases would take some care that is probably not worth the effort.

Closing this out.
