### ISSUE TITLE
master build failing

### ISSUE THREAD

**Issue by marqh** [SciTools/cartopy#810]
the tests on cartopy master are failing 

mapquest have moved some images used in testing and I cannot find where the images are able to be sourced from

tests such as
cartopy.tests.mpl.test_web_tiles are failing

issues seem to be in
cartopy.io.img_tiles

in

class MapQuestOSM(GoogleTiles):

class MapQuestOpenAerial(GoogleTiles):

**Comment by ajdawson** [comment]
See #781 for MapQuest.

**Comment by QuLogic** [comment]
Build was fixed by #758. Other issues exist to track restoring any skipped functionality.
