### ISSUE TITLE
Unexpected behavior of set_extent

### ISSUE THREAD

**Issue by ResidentMario** [SciTools/cartopy#826]
This *feels* like a bug, but it might also be my not understanding something. It may be a duplicate of just-closed #811, the corrective commit for which has not yet been released.

I have a `GeoAxes` instance named `ax`, which I'm trying to `set_extent` on. It didn't work as expected; here's a debugger session printout:

```
> /Users/Honors/Desktop/geoplot/geoplot/geoplot.py(388)polyplot()
-> if extent:
(Pdb) ax.get_extent()
(-180.0, 180.0, -90.0, 90.0)
(Pdb) n
> /Users/Honors/Desktop/geoplot/geoplot/geoplot.py(391)polyplot()
-> ax.set_extent((x_min_coord, x_max_coord, y_min_coord, y_max_coord), crs=ccrs.PlateCarree())
(Pdb) (x_min_coord, x_max_coord, y_min_coord, y_max_coord)
(-74.255591363152149, -73.700009063871221, 40.496115395170342, 40.91553277700519)
(Pdb) n
> /Users/Honors/Desktop/geoplot/geoplot/geoplot.py(394)polyplot()
-> _set_optional_parameters(ax, stock_image, coastlines, gridlines)
(Pdb) ax.get_extent()
(-0.30517198682779595, 0.25041031245313994, 40.49611539517034, 40.91553277700519)
(Pdb) q
```

As you can see, trying to set extent to `(-74.255591363152149, -73.700009063871221, 40.496115395170342, 40.91553277700519)` sets it to `(-0.30517198682779595, 0.25041031245313994, 40.49611539517034, 40.91553277700519)` instead.

What's more, the number the first two of these gets set to seems to depend on the initial extent.

**Comment by ajdawson** [comment]
Hi @ResidentMario, can you give us a bit more information about the axes object you have created, speecifically what projection you used when you made it (e.g. `ax = plt.axes(projection=ccrs.PlateCarree())`).

**Comment by ResidentMario** [comment]
I pulled out the library code and [put together a notebook demonstrating the issue](https://github.com/ResidentMario/geoplot/blob/master/notebooks/extents-issue.ipynb).

**Comment by ajdawson** [comment]
Thanks @ResidentMario. I think you are seeing the expected behaviour here. The reason is that your projection is `PlateCarree(central_longitude=-73.9266090152)`, and although you may find this surprising, the extents of this projection in projection coordinates is -180 to 180. When you call `get_extent` it is telling you the extent in native projection coordinates, which will be shifted by `73.9266090152` because you set the extent in a different CRS (`PlateCarree(central_longitude=0)`). You can use the optional `crs` keyword to `get_extent` and you should see that same values you put in to `set_extent`:

    ax.get_extent(crs=ccrs.PlateCarree())

**Comment by ResidentMario** [comment]
Ok...help me unwind this.

1. Suppose the following mock method:

```
def do_stuff(df, projection):
    ax = plt.subplot(111, projection=projection)
    x_min_coord, x_max_coord, y_min_coord, y_max_coord = _get_envelopes_min_maxes(
        df.geometry.envelope.exterior
    )
    ax.set_extent((x_min_coord, x_max_coord, y_min_coord, y_max_coord), crs=ccrs.PlateCarree())    
    for geom in df.geometry:
        features = ShapelyFeature([geom], ccrs.PlateCarree())
        ax.add_feature(features, facecolor=facecolor, **kwargs)
    return ax
```

This works as I expect it to: asking for ax.get_extent(crs=projection) nets me `(-0.30517198682779595, 0.25041031245313994, 40.49611539517034, 40.91553277700519)`. Is this syntactically correct, however?

2. Suppose I also have another mock method which does this: 

```
def kde(df, ax):
    import seaborn as sns
    sns.reset_orig()
    sns.kdeplot(pd.Series([p.x for p in df.geometry]), pd.Series([p.y for p in df.geometry]), ax=ax)
```

Since this is a `seaborn` method and not a `cartopy` one, it results in a plot which isn't transformed in any way. Is there a way of transforming the result so that e.g. the following:

```
    ax = do_stuff(df, ccrs.AlbersEqualArea())
    kde(df, ax)
```

Would produce the expected result: one plot on top of the other one?

**Comment by ResidentMario** [comment]
Never mind, I've worked it out on my own. Thanks.
