### ISSUE TITLE
New AxesGrid subclass

### ISSUE THREAD

**Issue by dennissergeev** [SciTools/cartopy#835]
It is possible to use cartopy with matplotlib's `AxesGrid`, as shown in #801.

But it may be even more convenient to have a new cartopy instance as a subclass of `AxesGrid`:
```python
class GeoAxesGrid(AxesGrid):
    def __init__(self, fig, rect, nrows_ncols, projection, **axesgrid_kw):
        axes_class = (GeoAxes, dict(map_projection=projection))
        axesgrid_kw['label_mode'] = ''
        super(GeoAxesGrid, self).__init__(fig, rect, nrows_ncols,
                                          axes_class=axes_class, **axesgrid_kw)
```

**Comment by QuLogic** [comment]
Perhaps you could open a PR with something along those lines?

**Comment by dennissergeev** [comment]
Closing as out-of-scope (see #909)

**Comment by QuLogic** [comment]
Sorry for sending you down a bit of a rabbit hole.
