### ISSUE TITLE
Importing LONGITUDE_FORMATTER or LATITUDE_FORMATTER from cartopy.mpl.gridliner raises warning

### ISSUE THREAD

**Issue by mhearne-usgs** [SciTools/cartopy#839]
OS: Mac OS 10.10.5
Python:  3.5.2 | packaged by conda-forge
Matplotlib version: '2.0.0'
Cartopy version: '0.14.3'

Behavior:
from cartopy.mpl.gridliner import LONGITUDE_FORMATTER

prints this:
.../matplotlib/ticker.py:1693: UserWarning: Steps argument should be a sequence of numbers
increasing from 1 to 10, inclusive. Behavior with
values outside this range is undefined, and will
raise a ValueError in future versions of mpl.
  warnings.warn('Steps argument should be a sequence of numbers\n'

**Comment by QuLogic** [comment]
This is a known bug that will eventually be fixed by #773.

**Comment by QuLogic** [comment]
Fixed by #773.
