### ISSUE TITLE
CRS.transform_vectors() requires Projection object as src_crs argument

### ISSUE THREAD

**Issue by djkirkham** [SciTools/cartopy#845]
The function uses `src_crs.x_limits` and `y_limits`, but these are properties of the Projection class.

**Comment by corinnebosley** [comment]
I'm confused.  This seems like we need to make a change in CRS.transform_vectors(), but @pelson has put a 'Type: Documentation' label on the ticket.

What exactly needs to be done here?

**Comment by pp-mo** [comment]
> 'Type: Documentation' label on the ticket.
>> What exactly needs to be done here?

IMHO : just document the restriction in the docstring.
I.E. first argument needs renaming + docstring states it is a Projection, not a (more general) CRS.
This is all just fine as we haven't released a v1.0 😉

**Comment by corinnebosley** [comment]
Alright then I'm on it.  Can't assign myself though.
