### ISSUE TITLE
Investigate gallery thumbnail for wmts_time example

### ISSUE THREAD

**Issue by lbdreyer** [SciTools/cartopy#851]
The gallery thumbnail for the wmts_time example is not being rendered correctly.

See [Cartopy Gallery](http://scitools.org.uk/cartopy/docs/latest/gallery.html#web-services)

The actual page of the example is fine though:
http://scitools.org.uk/cartopy/docs/latest/examples/wmts_time.html

This needs fixing.

**Comment by pelson** [comment]
Probably because the figure size is squashed for gallery generation.

**Comment by QuLogic** [comment]
This looks fine to me on current docs.
