### ISSUE TITLE
version_switch.js

### ISSUE THREAD

**Issue by bjlittle** [SciTools/cartopy#852]
For context, see #838 

As part of building the documentation process (particularly for a release), perhaps it would be wise to automate the state of the `version_switch.js` [all_versions](https://github.com/SciTools/cartopy/blob/master/docs/source/_static/version_switch.js#L7) variable to include the latest build version, rather than the developer having to remember to do this manually.

**Comment by pelson** [comment]
Documented in https://github.com/SciTools/cartopy/wiki/Release-checklist.
