### ISSUE TITLE
Gnomonic Projection - to include "central_longitude" aka proj4 "+lon_0"

### ISSUE THREAD

**Issue by cvelascof** [SciTools/cartopy#854]
cartopy's Gnomonic Projection accepts "central_latitude" as parameter but "central_longitude" currently missing.
`class cartopy.crs.Gnomonic(central_latitude=0.0, globe=None)
`
however proj4=gnom projection accepts 'lon_0' too
`+proj=gnom +lat_0=51 +lon_0=7`

**Comment by MaxNoe** [comment]
Yes please!

**Comment by ajdawson** [comment]
@cvelascof already implemented this in the master branch, it will be included in the next release.

**Comment by dkillick** [comment]
@ajdawson et al funny you should mention that - I'm working on 0.15.1 right now, which will include that change.

**Comment by ajdawson** [comment]
Really? I thought the 0.15.x branch was cut before this went on master.

**Comment by dkillick** [comment]
@lbdreyer, @bjlittle and I just discussed this - we're going to update v0.15.x from master and then release v0.15.1 from there.
