### ISSUE TITLE
Cartopy fills shapely MultiLineStrings

### ISSUE THREAD

**Issue by coolum001** [SciTools/cartopy#856]
In the program below, a MultiLineString has been constructed, with a 2 point line, and a 3 point line.

Unexpectedly to me, the 3 point line is filled as if it was a Polygon.

This arose in trying to plot a shapefile of pipeline data, where the intent is for a MultiLineString to NOT be filled.

Note that there is a work-around.  Iterate through the true multi-point lines, generating a list of 2 point lines (that join nose-to-tail), and create a shapely MultiLineString from this list.

Environment:

python version : 3.5.2 |Anaconda custom (64-bit)| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)]
python environment : root
pandas version : 0.18.1
current wkg dir: C:\Users\donrc\Documents\JupyterNotebooks\CartopyNotebookProject\develop
Notebook run at: 2017-02-12 16:45:08.010413 local time
Notebook run at: 2017-02-12 06:45:08.010413 UTC
Notebook run on: Windows-10-10.0.14393-SP0
Cartopy Version: 0.15.0

Example program:

```python
from shapely.geometry import MultiLineString

lines = MultiLineString([((0, 0), (10, 10)), ((0, 20),  (10, 15), (15, 10), (20, 0))])
print(lines)


fig = plt.figure(figsize=(10,10))
ax = plt.axes(projection=ccrs.PlateCarree(central_longitude=140))
ax.set_extent((-10, 20, -10, 30))


ax.add_feature(cartopy.feature.LAND)
ax.add_feature(cartopy.feature.OCEAN)



ax.add_geometries([lines], ccrs.PlateCarree(),\
                          edgecolor='green', facecolor=None, alpha = 0.8, linewidth=2)

plt.show()
```

The code for the work-around is shown below (lines is a shapely MultiLineString)

```python
line_good=[]
for l in lines:
    print(l)
    print(list(l.coords))
    start_pt = list(l.coords)[0]
    for i in range(1,len(l.coords)):
        end_pt = list(l.coords)[i]
        simple_line = (start_pt, end_pt)
        line_good.append(simple_line)
        start_pt = end_pt
    #end for
#end for

print(line_good)
lines = MultiLineString(line_good)
```

Happy to supply any more info if needed

**Comment by QuLogic** [comment]
In Matplotlib, `facecolor=None` means to use the default; you want `facecolor='none'` to disable the fill colour entirely.
