### ISSUE TITLE
GeomAxes.tissot says `radius_km` but seems to be in meters

### ISSUE THREAD

**Issue by MaxNoe** [SciTools/cartopy#858]
The keyword argument for the `tissot` frunction is called `radius_km`, but actually seems to be in meters, not kilometers.

Also, it would be nice to be able to set the radius as angle, not just km.

**Comment by QuLogic** [comment]
This would be fixed by #794, but the contributor seems to have disappeared.

**Comment by pelson** [comment]
Thanks for fixing this in #904 @QuLogic! Will be in 0.16.
