### ISSUE TITLE
Mac Anaconda Installation 

### ISSUE THREAD

**Issue by jdossgollin** [SciTools/cartopy#859]
For some reason I'm not able to install anymore on OSX. After uninstalling everything, I run
```
brew cask install anaconda
```
then
```
export PATH=~/anaconda3/bin:"$PATH"
```
Then
```
conda install -c scitools cartopy
```
This gives me the following error message:
```
Fetching package metadata ...........
Solving package specifications: .


UnsatisfiableError: The following specifications were found to be in conflict:
  - cartopy -> numpy 1.8* -> python 2.6* -> openssl 1.0.1*
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.
```
This is clearly a dependency issue, but since the installation instructions say using `conda` is the easiest way, I'm stumped here

**Comment by QuLogic** [comment]
Try `-c conda-forge` instead of `scitools`. Why that channel still exists publicly is a mystery to me...

**Comment by jdossgollin** [comment]
Wow, that did it... may I recommend updating the instructions on [http://scitools.org.uk/cartopy/docs/latest/installing.html](http://scitools.org.uk/cartopy/docs/latest/installing.html)
Thanks
