### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by roshni-b** [SciTools/cartopy#865]
C:\Users\Roshni>conda install -c scitools cartopy
Fetching package metadata .............
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - cartopy -> python 3.4*
  - python 3.5*
Use "conda info <package>" to see the dependencies for each package.

**Comment by ajdawson** [comment]
There is no Python 3.5 version of cartopy in the scitools channel.

**Comment by lbdreyer** [comment]
We're have some trouble uploading to the scitools channel right now which is stopping us from adding the windows python 3.5 version of cartopy.

Whilst you wait for this to be fixed, you could get cartopy from the conda-forge channel:
`conda install -c conda-forge cartopy`

**Comment by QuLogic** [comment]
FYI, the scitools channel is deprecated, so use conda-forge in the future.
