### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by zoezhchen** [SciTools/cartopy#866]
I use conda to install it
```
conda install -c scitools cartopy=0.15.0
Fetching package metadata: ........
Solving package specifications: .....................................
Package plan for installation in environment .conda/envs/myenv:
The following packages will be DOWNGRADED:
    cartopy: 0.15.1-np112py27_0 --> 0.15.0-np112py27_0
Proceed ([y]/n)? y
Unlinking packages ...
[      COMPLETE      ]|###################################################| 100%
Linking packages ...
[      COMPLETE      ]|###################################################| 100%
```
(I have tested conda install -c scitools cartopy, cartopy-0.15.1 is installed without error.,but import with the same error "No module named cartopy")

 I use conda list to check, it is installed
...
cartopy                   0.15.0              np112py27_0

```
ipython
Python 2.7.10 |Anaconda 2.3.0 (64-bit)| (default, May 28 2015, 17:02:03)
Type "copyright", "credits" or "license" for more information.
IPython 3.2.0 -- An enhanced Interactive Python.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
In [1]: import cartopy
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-8327782196fd> in <module>()
----> 1 import cartopy
ImportError: No module named cartopy
```

**Comment by ajdawson** [comment]
Have you also installed ipython with conda. Sometimes this problem comes up because ipython is using your system python, whereas cartopy is installed in conda's python.  You should see ipython in the output of `conda list` (along with cartopy). If you don't, try doing `conda install ipython`.

**Comment by zoezhchen** [comment]
conda install ipython
Fetching package metadata: ......
Solving package specifications: .
Package plan for installation in environment .conda/envs/myenv:

The following NEW packages will be INSTALLED:

    backports.shutil_get_terminal_size: 1.0.0-py27_1
    ipython:                            5.3.0-py27_0

The following packages will be UPDATED:

    pexpect:                            3.3-py27_0    --> 4.2.1-py27_0
    prompt_toolkit:                     1.0.13-py35_0 --> 1.0.13-py27_0
    ptyprocess:                         0.5.1-py35_0  --> 0.5.1-py27_0
    pygments:                           2.2.0-py35_0  --> 2.2.0-py27_0
    python:                             2.7.12-2      --> 2.7.13-0
    wcwidth:                            0.1.7-py35_0  --> 0.1.7-py27_0

The following packages will be DOWNGRADED:

    tk:                                 8.5.19-1      --> 8.5.18-0      (soft-link)
Proceed ([y]/n)? y
Unlinking packages ...
[      COMPLETE      ]|##############################################################| 100%
Linking packages ...
[      COMPLETE      ]|##############################################################| 100%
conda list
ipython                   5.3.0                    py27_0
but when i input ipython
Python 2.7.10 |Anaconda 2.3.0 (64-bit)| (default, May 28 2015, 17:02:03)
Type "copyright", "credits" or "license" for more information.

IPython 3.2.0 -- An enhanced Interactive Python.
 I am still using ipython 3.2.0
In fact i have just installed ipython 5.3.0

**Comment by zoezhchen** [comment]
Thanks for your reply.
if i install ipython 4.0.0 and cartopy, then python downgraded to 2.7.12-2
 then ipython doesnot work.
 when I installed python2.7.13 and ipython 4.0.0, cartopy does not work.
 conda list
cartopy                   0.15.1              np112py27_0
ipython                   4.0.0                    py27_0
python                    2.7.13                        0

import cartopy
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-1-8327782196fd> in <module>()
----> 1 import cartopy

.conda/envs/myenv/lib/python2.7/site-packages/cartopy/__init__.py in <module>()
     22
     23 # Enable shapely performance enhancements
---> 24 import shapely.speedups
     25 if shapely.speedups.available:
     26     shapely.speedups.enable()

.conda/envs/myenv/lib/python2.7/site-packages/shapely/speedups/__init__.py in <module>()
      1 import warnings
      2
----> 3 from shapely.geometry import linestring, polygon
      4 from shapely import coords
      5 import shapely.affinity

.conda/envs/myenv/lib/python2.7/site-packages/shapely/geometry/__init__.py in <module>()
      2 """
      3
----> 4 from .base import CAP_STYLE, JOIN_STYLE
      5 from .geo import box, shape, asShape, mapping
      6 from .point import Point, asPoint

.conda/envs/myenv/lib/python2.7/site-packages/shapely/geometry/base.py in <module>()
      7 from ctypes import pointer, c_size_t, c_char_p, c_void_p
      8
----> 9 from shapely.coords import CoordinateSequence
     10 from shapely.ftools import wraps
     11 from shapely.geos import lgeos, ReadingError

.conda/envs/myenv/lib/python2.7/site-packages/shapely/coords.py in <module>()
      6 from ctypes import byref, c_double, c_uint
 7
----> 8 from shapely.geos import lgeos
      9 from shapely.topology import Validating
     10

.conda/envs/myenv/lib/python2.7/site-packages/shapely/geos.py in <module>()
     64
     65 if sys.platform.startswith('linux'):
---> 66     _lgeos = CDLL(os.path.join(sys.prefix, 'lib', 'libgeos_c.so'))
     67     free = load_dll('c').free
     68     free.argtypes = [c_void_p]

.conda/envs/myenv/lib/python2.7/ctypes/__init__.pyc in __init__(self, name, mode, handle, use_errno, use_last_error)
    360
    361         if handle is None:
--> 362             self._handle = _dlopen(self._name, mode)
    363         else:
    364             self._handle = handle

OSError:.conda/envs/myenv/lib/libgeos_c.so: ELF file OS ABI invalid

**Comment by pelson** [comment]
I think this is another manifestation of #805.
In this case, ipython wasn't installed originally, as identified correctly by **ajdawson**.
Unfortunately, installing ipython also meant compromising on other versions, thus pulling in the xrefed issue. Closing this in favour of the other issue.
