### ISSUE TITLE
UTM Projection created by espg() call has only positive Y extent

### ISSUE THREAD

**Issue by coolum001** [SciTools/cartopy#867]
Creating a UTM projection two different ways gives projections with different Y extents

```
import pandas as pd


import matplotlib.pyplot as plt
import gdal
import osr

import cartopy.crs as ccrs

# get projection EPSG:32656. WGS 84 / UTM zone 56N in two ways

zone = 56
projection = ccrs.UTM(zone, southern_hemisphere=False)

print(projection)
print(projection.x_limits)
print(projection.y_limits)


projection = ccrs.epsg('32656')

print(projection)
print(projection.x_limits)
print(projection.y_limits)
```

gives:

```
<cartopy.crs.UTM object at 0x00000270D2910468>
(-250000.0, 1250000.0)
(-10000000.0, 25000000.0)
_EPSGProjection(32656)
(166021.44308054051, 833978.55691945949)
(0.0, 9329005.1824474372)
```

Note the 0 value for the minimum y_limits for the latter projection.

This is a bug for me, because in processing LANDSAT8 geotiff files, of scenes in the southern hemisphere, negative Y coordinates are used in the geotiff scene limits.

I am processing the LANDSAT data at 

https://s3-us-west-2.amazonaws.com/landsat-pds/L8/089/079/LC80890792016366LGN00/index.html

and the band is LC80890792016366LGN00_B2.tif

with Origin = ( 413685.0 , -2917485.0 )

Creating a projection with the epsg() call, then causes problems in trying to set explicit extents with the 
scene extents, as it appears to be outside the projection y limits.  This then causes subsequent problems with (eg) coastline() calls.

Now I can understand why the EPSG:32656. WGS 84 / UTM zone 56N ends at the equator: us folks in the Southern Hemisphere should be using  a EPSG:32756. WGS 84 / UTM zone 56S projection.  Sadly, NASA did not.  The work around of creating the UTM Zone by hand seems to work OK, but renders the code slightly less general purpose.

Happy to provide more details 

Environment is:

```
python version : 3.5.2 |Anaconda custom (64-bit)| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)]
python environment : root
pandas version : 0.19.2
catopy version : 0.15.0
current wkg dir: C:\Users\donrc\Documents\JupyterNotebooks\LandsatNotebookProject\develop
Notebook name: 2017-03-09-dc-LandsatNotebook
Notebook run at: 2017-03-10 06:57:18.051919 local time
Notebook run at: 2017-03-09 20:57:18.051919 UTC
Notebook run on: Windows-10-10.0.14393-SP0
```

**Comment by marqh** [comment]
this looks like a bug to me, I will try to write a test case to confirm this and report back

**Comment by QuLogic** [comment]
[EPSG 32656](https://epsg.io/32656) is only defined for positive latitudes, so is this really a bug? Cartopy just downloads and uses whatever EPSG gives it.

**Comment by coolum001** [comment]
I have some sympathy for the comment by QuLogic;  the real bug is NASA using EPSG 32656 for South Hemisphere scenes  (however, I suspect NASA goes some way to define industry standard practice).  

Maybe the way forward is to allow people who know what they are doing, to be able to reset the projection limits.  After all, the T in UTM (transverse) means that the projection is largely distortion free along the nominated line of latitude (just as Mercator is distortion free along the equator).  I must admit, that I don't know why EPSG defines a South and North Hemisphere UTM  for a given Zone (maybe, because the ellipsoid is  subtly different in the two hemispheres?)

However, the additional complexity of checking for which projections this made sense, might make projection limits reset hard to implement.  

The easiest answer could be  documentation that explained that EPSG projections, and Cartopy projections that might be expected to be identical, may have different properties, due to implementation details.  I certainly don't want the Cartopy UTM projection to be limited to +ve y, as then my work around won't be valid any more :)

thanks for your time!

**Comment by pelson** [comment]
Closing this out, as there isn't anything cartopy should do about the issue AFAICS. There *is* potentially scope for a feature enhancement that allows custom limits, but that can already be achieved with a custom projection class (though it is more complex when using the ``epsg`` function.

Please feel free to re-open if there is a tangible & simple thing that cartopy could/should do here.

Thanks for raising. 👍
