### ISSUE TITLE
Cannot import cartopy on ubuntu 14.04

### ISSUE THREAD

**Issue by Rumbles** [SciTools/cartopy#871]
I was asked to set up cartopy for someone, I set it up on their laptop (openSUSE 42.2) without issue, but now they want it installing on one of our big servers running ubuntu 14.04. We don't use conda and we use salt to manage config. I was try to install it manually on one of the machines , so I can then write a salt state the reproduce the install method. But I hit issues just getting this installed correctly, I am unsure of the cause.

I installed libgeos-dev (3.4.2-4ubuntu1), python-numpy (1.8.2-0ubuntu0.1) from apt and pyshp, Cython and shapely from pip. At this point cartopy installs with pip (for python 3.5), but when I try to import cartopy in the python console I receive:

```
$ python3.5
Python 3.5.2 (default, Jul 17 2016, 00:00:00) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cartopy
python3.5: geos_ts_c.cpp:3657: int GEOSCoordSeq_setOrdinate_r(GEOSContextHandle_t, geos::geom::CoordinateSequence*, unsigned int, unsigned int, double): Assertion `0 != cs' failed.
Aborted (core dumped)
```

I had some issues installing proj4 initially, the version available in apt for 14.04 is too old, I tried a version for a later version of ubuntu, as well as building from source after uninstalling the old one and that didn't help at all.

From the message it implies there is something amiss with geos, but I am unsure what is the issue - as far as I can tell I am above the minimum version so I'm not sure what else could be wrong. I got the core dump info from apport-retrace, but it doesn't help me understand what the issue is, I hope it could help someone else.

[python-trace.txt](https://github.com/SciTools/cartopy/files/854482/python-trace.txt)

Thanks

**Comment by Rumbles** [comment]
I managed to get this working by replacing the geos installed from apt and replacing it with geos I built from source. Not sure if that would be considered an issue with geos or an issue here as the install notes say 3.3.3 and above should work, but didn't in this case

**Comment by dopplershift** [comment]
How was shapely installed/built?

**Comment by Rumbles** [comment]
Pip installed

**Comment by dopplershift** [comment]
So with the latest version (1.5.17.post1), they have pre-built wheels. For that to work, then CartoPy needs to be built with the same version of GEOS.  (See #805) The most reliable option for your case is to ensure that you build both shapely and cartopy against the installed copy of GEOS.

**Comment by QuLogic** [comment]
To do that, use `pip install --no-binary shapely shapely`.

**Comment by Rumbles** [comment]
Thanks for the help, I will try this and reopen if I get stuck again

**Comment by fpeos** [comment]
#The following did not work for me:

pip install shapely --no-binary shapely
Requirement already satisfied: shapely in /Users/militzer/opt/anaconda3/lib/python3.7/site-packages (1.6.4.post1)

#but this line worked

pip install shapely --upgrade --force-reinstall --no-binary  shapely

# Thanks everyone!

**Comment by JonnoB** [comment]
With the removal of the Proj dependency issues, it would be helpful to update the pip install intructions to be clear that shapely needs the no binary installation. installing cartopy without conda is a nightmare but the solution of appears relatively simple. 

The below simple docker can run cartopy without problems 

```
FROM python:3.11-bullseye

RUN apt-get update && apt-get install -y --no-install-recommends \
   libgeos-dev \
   && rm -rf /var/lib/apt/lists/*

RUN pip3 install --upgrade pip

COPY requirements.txt ./
RUN pip3 install --no-cache-dir -r requirements.txt

ENTRYPOINT [ "python" ]
```

The docker can run the following python script successfully
```
import cartopy
import cartopy.crs as ccrs
import matplotlib.pyplot as plt

ax = plt.axes(projection=ccrs.PlateCarree())
ax.set_extent([0, 5, 30,  60])
ax.add_feature(cartopy.feature.OCEAN)
plt.savefig('world_map.png')
print("I have not crashed")
```

without installing libgeos and then shapely the code will only run sucessfully if the set_extent is commented out. The kernel will crash if set_extent is used or anyother projection or the central longitude is changed. I assume becuase this calls shapely.

Adding in a bit more for those not using conda would be really helpful.
Fantastic library thanks for all your work

Jonno
