### ISSUE TITLE
Gridlines slow rendering plot

### ISSUE THREAD

**Issue by djkirkham** [SciTools/cartopy#872]
Grid lines make updating the plot slower and slower as you zoom in. The problem can be reproduced with the below code:
```
import cartopy.crs as ccrs
import matplotlib.pylab as plt
import matplotlib

transform=ccrs.PlateCarree(central_longitude=0)
ax = plt.axes(projection=transform)
ax.coastlines(resolution='110m')
gridlines=ax.gridlines()

plt.show()
```
If I remove the “gridlines” line and it updates the figure at the same speed no matter how far you zoom in. The issue occurs even if they are outside the visible area.

**Comment by djkirkham** [comment]
@marq

**Comment by QuLogic** [comment]
Is it just zooming in that does this? Just adding gridlines doesn't _appear_ slow, but over 100 runs of creating a figure and saving it, it's about 75% extra time. Most of this time is spent in `Gridliner._axes_domain`.

**Comment by QuLogic** [comment]
BTW, I think you might have mean to mention @marqh there.

**Comment by djkirkham** [comment]
@QuLogic You have to zoom in quite far to see the effect. At normal zoom they don't appear to make any difference.

**Comment by QuLogic** [comment]
Well, I tried this:
```python
import time
import cartopy.crs as ccrs
import matplotlib.pylab as plt

lim = 1e-4

transform = ccrs.PlateCarree(central_longitude=0)
fig0 = plt.figure()
ax = plt.axes(projection=transform)
ax.coastlines(resolution='110m')
gridlines = ax.gridlines()
plt.gcf().canvas.draw()
ax.set_xlim(-lim, lim)
ax.set_ylim(-lim, lim)

transform = ccrs.PlateCarree(central_longitude=0)
fig1 = plt.figure()
ax = plt.axes(projection=transform)
ax.coastlines(resolution='110m')
plt.gcf().canvas.draw()
ax.set_xlim(-lim, lim)
ax.set_ylim(-lim, lim)


t0 = time.time()
fig0.savefig('test.png')
print(time.time() - t0)

t0 = time.time()
fig1.savefig('test.png')
print(time.time() - t0)
```
and it seems to be roughly the same ratio as if I don't call `set_[xy]lim`.

**Comment by pelson** [comment]
I can't reproduce this either. There is nothing in the ``coastlines`` that would trigger a slowdown AFICT in this release. Ironically, the newer cartopy version *may* cause a slowdown as it *can* be adaptive in the dataset it chooses to show.
