### ISSUE TITLE
Conda installation fail

### ISSUE THREAD

**Issue by Marston** [SciTools/cartopy#874]
Hi I would like to install and use cartopy. I've installed conda and created a python3.6.1 environment and then tried to install cartopy as such:

cospmw) [sm ~]$ conda install -c scitools cartopy
Fetching package metadata ...........
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - cartopy -> numpy 1.8* -> python 2.6* -> openssl 1.0.1*
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.

If I'm reading this correctly, it is saying that cartopy requires a python 2.6 environment, as well as an older numpy and openssl packages? 
If so, this is in conflict with the cartopy homepage which say python2.7 or higher......

Is there a way to install cartopy in a python 3 environment?

**Comment by QuLogic** [comment]
Use the `conda-forge` channel instead; `conda install -c conda-forge cartopy`.

**Comment by Marston** [comment]
Thank you :-)
