### ISSUE TITLE
Cartopy install error in Windows

### ISSUE THREAD

**Issue by jstepansky** [SciTools/cartopy#875]
I'm not sure if this is the same issue referenced previously. I've installed numerous Python packages (Numpy, Matplotlib, etc.) with no difficulty. Until Cartopy. Here's the error message I get:

"CondaOSError: OS error: failed to link <src='C:\\Users\\Joe\\Miniconda3\\pkgs\\matplotlib-2.0.0-np111py36_3\\Lib/site-packages/matplotlib/mp1-data/fonts/ttf/DejaVuSans.ttf', dst='C:\\Users\Joe\\Miniconda3\\Lib/site-packages/matplotlib/mp1-data/fonts/ttf/DejaVuSans.ttf', type=1, error=CondaOSError: OS error: win32 hard link failed"

I have no idea what most of that (other than my folder reference) means? Anybody know where I go from here? Again, Cartopy is the only package (so far) that has acted like this.

**Comment by QuLogic** [comment]
This is a problem with the Matplotlib package, not Cartopy. Was this message copied and pasted or typed by hand? Did it really say `mp1`, not `mpl`?

**Comment by jstepansky** [comment]
I apologize, I had to type the message as I couldn't cut/paste from the command prompt. The message did indeed reference mpl. The funny thing is that I had originally installed Matplotlib without issue, and now I get this message. OK, guess I'll ask about Matplotlib creating the error. Thanks!
