### ISSUE TITLE
pip install cartopy -- canot open source file "geodesic.h"

### ISSUE THREAD

**Issue by raybellwaves** [SciTools/cartopy#876]
I am installing cartopy using 'pip install cartopy' .

Originally I had an issue picking up Proj4 as there is a python module named proj. Setup.py was therefore picking up this proj in /nethome/rxb826/PYTHON3/myenv/bin instead of proj in /nethome/rxb826/local/bin. After I deleted proj in /nethome/rxb826/PYTHON3/myenv/bin it worked ok.

Now it is failing at lib/cartopy/geodesic/_geodesic.c
    lib/cartopy/geodesic/_geodesic.c(437): catastrophic error: cannot open source file "geodesic.h"
      #include "geodesic.h"
                           ^
    
    compilation aborted for lib/cartopy/geodesic/_geodesic.c (code 4)
    error: command 'icc' failed with exit status 4
    
    ----------------------------------------
Command "/nethome/rxb826/PYTHON3/myenv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-3czgq1zx/cartopy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-_98th0u4-record/install-record.txt --single-version-externally-managed --compile --install-headers /nethome/rxb826/PYTHON3/myenv/include/site/python3.6/cartopy" failed with error code 1 in /tmp/pip-build-3czgq1zx/cartopy

I have this file available in /nethome/rxb826/local/include/geodesic.h

I've attached my full output
pip install cartopy > out.txt
[out.txt](https://github.com/SciTools/cartopy/files/926693/out.txt)

Cheers,
Ray

**Comment by QuLogic** [comment]
You need Proj 4.9 for the geodesic API; the setup should have checked for this though...

**Comment by pelson** [comment]
It may be you need to build the cartopy extensions with the appropriate flags. In using ``setup.py`` that looks like:

```
python setup.py build_ext -I/path/to/include -L/path/to/lib
python setup.py install
```

But with pip, I'm not certain how to do that.

Closing this, as I don't think it will require a cartopy change.

**Comment by raybellwaves** [comment]
Apologies. Should have closed it myself a while ago.
Was installing on our HPC which had python already installed but I was able to install my own version of python via anaconda therefore used `conda install...`
