### ISSUE TITLE
Support matplotlib hexbin()

### ISSUE THREAD

**Issue by akrherz** [SciTools/cartopy#884]
Current cartopy does not seem to provide `hexbin` support.  I assume this isn't a simple implementation like how `geoaxes.scatter` works or else it would have been done by now?  I will take a swing at this and see how "bad" things look on the various projections!

**Comment by ajdawson** [comment]
xref #770

**Comment by akrherz** [comment]
The simple implementation did not work :(  I wonder if it is related to the troubles I am having getting `PatchCollections` to work, so will keep after it!

**Comment by akrherz** [comment]
Here's an initial implementation for `mpl/geoaxis.py` for your feedback
```python
    def hexbin(self, x, y, *args, **kwargs):
        """
        Reprojects data, if necessary, and calls
        :func:`~matplotlib.pyplot.hexbin'.

        Extra kwargs:

            transform - a :class:`~cartopy.crs.Projection`.

        """
        # exclude Geodetic as a vaild source CS
        if (isinstance(kwargs.get('transform', None),
                       InterProjectionTransform) and
                kwargs['transform'].source_projection.is_geodetic()):
            raise ValueError('Cartopy cannot currently do spherical '
                             'hexbin. The source CRS cannot be a '
                             'geodetic, consider using the cyllindrical form '
                             '(PlateCarree or RotatedPole).')

        t = kwargs.get('transform', None)
        if t is not None and t != self.projection:
            pairs = self.projection.transform_points(t,
                                                     np.asarray(x),
                                                     np.asarray(y))
            x = pairs[:, 0]
            y = pairs[:, 1]
            # remove prior to sending to matplotlib.hexbin
            kwargs.pop('transform')

        result = matplotlib.axes.Axes.hexbin(self, x, y, *args, **kwargs)
        self.autoscale_view()
        return result
```

As I think about this, the concept of doing hexbin in a different crs than the axes is likely not what the user wants (or even what I want :)).  Instead, the user expects the provided point data to be reprojected first, if necessary, and then `hexbin` done in the crs of the axes?

The above is basically a no-op when either:
 - no `transform` is provided 
 - `transform` equals the axes projection

I am only a week into cartopy and likely need to send more time understanding how `pcolormesh` handles this situation.  Sorry to be making noise otherwise!

**Comment by rabernat** [comment]
I would definitely use this feature if it existed.

**Comment by rabernat** [comment]
I would still love to see this feature implemented. Are there any plans by the Cartopy devs to try to turn @akrherz's prototype into a supported feature? Thanks to all the volunteers who maintain this great library.

**Comment by greglucas** [comment]
That looks reasonable to me as well. @akrherz, do you want to open up a PR with your proposed change?

**Comment by akrherz** [comment]
I took a swing at such an [implemention](https://github.com/akrherz/cartopy/commit/0429103154dfa4e6729ab19b53341d8e12f0d7ed), but got a strange resulting plot after adding a test that was more-or-less a contrl-c of the scatter test.

![example](https://user-images.githubusercontent.com/210858/80356131-a53fe780-883e-11ea-80f6-a940f47fc676.png)

I would not have expected it to look like that?

**Comment by akrherz** [comment]
Thanks for the review/response @greglucas!  I just control-c the scatter tests and am unsure what to make of all of this :( It appears I should spend some time understanding how matplotlib computes `gridsize` as it appears to be defaulting to 100.  Additionally, the plot extent does not make sense to me either as it appears to be only from 0 to 180 and not global.

**Comment by greglucas** [comment]
Actually, @akrherz, I think you've basically got it!

The problem is with the data, which is why gridsize is important here. So, all of those gaps you're seeing are actually just empty hexes.
linspace has a default of 50, so the current grid is 50x50. Adding in: `x, y = np.meshgrid(np.linspace(0, 360, 200), np.linspace(-90, 90, 200))`
Makes the plot look much nicer. So, for a test I'd suggest adding some more points and setting the gridsize equal to a smaller number.

The reason you're only seeing 0-180 is because the code currently is short-circuiting your points transformation if the axes and data projection are the same. So there are extra hexes located off the map to the right, rather than wrapped around.

**Comment by akrherz** [comment]
If I set the longitude values to range from -180 to 180 and use 200 linspace values, I then get a global map as I'd expect.

![example](https://user-images.githubusercontent.com/210858/80587286-e3bed900-89db-11ea-9b4e-0c472cba2da4.png)

Shall I proceed with those values in the test instead of 0-360 like the scatter test has?

**Comment by greglucas** [comment]
Want to create the PR and then we can discuss there on your code?

We should try and handle the wrap, so you should probably have a single image like you've shown. Then have two tests, one with -180-180 and one from 0-360 and show that they produce the same image. I don't think that picture is the greatest, so it'd be good to manually set some options to make less hexes and use less data in the tests.
