### ISSUE TITLE
Map Feature Improvements

### ISSUE THREAD

**Issue by dopplershift** [SciTools/cartopy#888]
Two things I'd like to see, and I'll submit a PR if there's interest:

1. A feature for states/provinces
1. The ability to more easily take, say `RIVERS` and get a higher resolution version

**Comment by QuLogic** [comment]
There are two examples of states/provinces in the gallery: [for USA](http://scitools.org.uk/cartopy/docs/latest/examples/hurricane_katrina.html) and [for Australia](http://scitools.org.uk/cartopy/docs/latest/examples/feature_creation.html).

Higher resolution rivers can be had by copying the line out of the source and changing the resolution; I thought there was another issue asking for an easier method, but I can't seem to find it.

**Comment by dopplershift** [comment]
So the point in adding a states/provinces feature would be to avoid having to show the learners I'm training this:
```
'admin_1_states_provinces_lakes'
```
And try to explain how they're supposed to identify that string on their own on the Natural Earth site. For our uses, it stands in stark contrast to the ease of doing `cartopy.feature.LAKES`.

As far as the resolution yes, I can do that. Again, I would like not to stand in front of a room of novice to intermediate Python users and try to suggest that that's their best course of action.

What I'm asking for (really, what I'm asking to create and have merged) is nothing that can't be done, but it would make it easier to do, easier to teach, and shorten my training materials. I can put these in MetPy, but it seems better to have these upstream.

**Comment by jrleeman** [comment]
Agreed. Adding state outlines would greatly simplify the workflow of a lot of map making and seems like it would be a good addition to cartopy vs. metpy.

**Comment by ajdawson** [comment]
Don't wait for more discussion here, go forth and submit PRs @dopplershift

**Comment by dopplershift** [comment]
I think #387 relates to the ease of changing scale.
