### ISSUE TITLE
Fix failing build: pyshp error, http 503 error

### ISSUE THREAD

**Issue by lbdreyer** [SciTools/cartopy#889]
The current build of the master branch is failing due to two errors:
* pyshp: There seems to have been a change in pyshp between versions 1.2.10 and 1.2.11 which changes the printout of a record from a shapefile (see [relevant comment](https://github.com/SciTools/cartopy/pull/780#issuecomment-307054268)). This is causing cartopy.tests.test_shapereader.TestRivers.test_record to fail
* http Error 503: During the build we are getting two `HTTPError: HTTP Error 503: Service Unavailable`

**Comment by ajdawson** [comment]
>http Error 503: During the build we are getting two HTTPError: HTTP Error 503: Service Unavailable

Looks like #781. Previously we have removed the offending tests (#818; @marqh).

**Comment by marqh** [comment]
there are issues with
http://oatile1.mqcdn.com/tiles/1.0.0/sat/0/0/0.jpg

I have made a small change to the code to see what is not resolving
https://github.com/marqh/cartopy/pull/2/commits/9299e830f040225c908f01b394ce86acffaaac2c
https://travis-ci.org/marqh/cartopy/jobs/243683742

the whole subdomain returns a HTTP 503
http://oatile1.mqcdn.com/

I agree with @ajdawson we can remove the test and this data source but my branch doesn't fix this and I am out of time (sorry)

**Comment by ajdawson** [comment]
The integration of #758 has removed the remaining test failures (by setting them as expected fails). This is still a sticky plaster and not a fix for the API, but the tests run green now and this tracking issue can be closed.
