### ISSUE TITLE
Replace dependency pep8 with pycodestyle

### ISSUE THREAD

**Issue by petrrr** [SciTools/cartopy#905]
The package was renamed in `pycodestyle`:

https://pypi.python.org/pypi/pycodestyle/2.3.1
https://github.com/PyCQA/pycodestyle

**Comment by pelson** [comment]
Even better - let's remove it as a dependency altogether, and let https://stickler-ci.com/docs do its magic.

@SciTools/cartopy-devs - any objections?

**Comment by ajdawson** [comment]
Looks like a reasonable choice. I think there is value in treating coding style as different from the tests, it is nicer for contributors not to see failing tests for style problems. That said, there may be some value in being able to run the style check locally before pushing a PR?

**Comment by pelson** [comment]
> That said, there may be some value in being able to run the style check locally before pushing a PR?

Definitely. I'm not convinced it should show a failing test though. ``pycodestyle cartopy`` is a reasonable thing for the conscientious developer to remember (and if they don't, stickler will...).

Given the feedback, let's give it a shot and see how it goes. If it hasn't been done by that point, I'll enable stickler next time I get some significant cartopy development time.

**Comment by pelson** [comment]
Stickler was enabled. We haven't yet removed pep8 as a dependency though. That is the remaining work for this issue.
