### ISSUE TITLE
matplotlib 2.0 adding blank pad

### ISSUE THREAD

**Issue by cvelascof** [SciTools/cartopy#907]
One of the changes in matplotlib 2.0 is "plot layout" where the new default sets the view limits to 5% wider than the data range.  https://matplotlib.org/2.0.2/users/dflt_style_changes.html#plot-layout

This by default add a padding area of nodata around the map (well at least when using plt.pcolormesh)  if you do not set your Axis xmargin and ymargin to zero 
        ax.set_xmargin(0)
        ax.set_ymargin(0)

It is not a Cartopy problem, but still good to know.

More discussion here
https://stackoverflow.com/questions/41748543/matplotlib-rcparams-autolimit-mode-for-single-figure

**Comment by ajdawson** [comment]
This was noted in the Matplotlib 2 compatibility PR also: https://github.com/SciTools/cartopy/pull/773#issuecomment-286778081. Is there really anything we need to do about this in cartopy?

**Comment by pelson** [comment]
It could be something we want to remove in the future, but for now I'm OK with it.
Happy to re-open / re-raise if it comes up often enough. (Perhaps future googlers can 👍 the original description to give a sense of impact)
