### ISSUE TITLE
0.16 release?

### ISSUE THREAD

**Issue by QuLogic** [SciTools/cartopy#915]
`master` supports Matplotlib 2 and 0.15.1 does not. I think that alone is sufficient reason for a new release, but there are several other changes on `master` as well. There's nothing tagged for 0.16 and 10 issues tagged for 0.15, but they've been open a long time and likely can be bumped.

Of the PRs with no milestone, I think we should try to get in #908 and maybe #910 if possible.

**Comment by ajdawson** [comment]
Agreed, we should do a release ASAP. We can wait for #908 and #910 but I don't think releasing without them would  would be a problem if that proves difficult.

We should also make sure the uploaded docs use Matplotlib 2, see #917.

**Comment by ghisvail** [comment]
> We should also make sure the uploaded docs use Matplotlib 2, see #917.

+1 for matplotlib v2.x support. Most Linux distros now have this version in there respective repository.

**Comment by pelson** [comment]
I'm 👍 on this. I've updated the v0.16 milestone to have a deadline of tomorrow (21/11/17). There will be plenty more work on cartopy over the coming weeks, but there is no reason to hold back on a new release before then too.

**Comment by davidh-ssec** [comment]
Any idea when this release will move forward? Really looking forward to the `sweep` parameter fix.

**Comment by dopplershift** [comment]
It looks like there's only one open item on the milestone...that I just added. 😁 That PR should be clean to merge--just want to make sure it doesn't get forgotten. Otherwise, I wouldn't protest having a new release so I don't have to continue to live with things I've already fixed. 😁

**Comment by QuLogic** [comment]
There's nothing on the milestone now; let's have a release.

**Comment by pelson** [comment]
I just tagged v0.16.0 (look ma, no need to make a ```__version__``` shuffle commit! 😄).

Thanks for all the hard work that went into this release. Turns out there was a huge amount of stuff, and I'm glad it is out there. I'm not intending on waiting quite so long for ```v0.17``` - I'm confident I will cut it before SciPy if my cartopy tutorial abstract is accepted 😉
