### ISSUE TITLE
CI is not running for new PRs

### ISSUE THREAD

**Issue by ajdawson** [SciTools/cartopy#919]
The two most recent open PRs have not triggered CI builds. Has the configuration been modified?

**Comment by pelson** [comment]
I did tweak some of the perms on the SciTools org. I'll double check now.

**Comment by pelson** [comment]
Confirmed. I enabled finer controls on the application permissions (they were pretty worryingly liberal before), and that seems to have prevented Travis from synching the scitools repos. I've now granted that permission to the travis-ci App (yay to having explicit grant of permissions)

**Comment by pelson** [comment]
Should all be back up and running. Please ping me if there are any other issues.

**Comment by dopplershift** [comment]
@pelson Where'd you find that? I can't for the life of me figure out how to do so.

**Comment by pelson** [comment]
Org settings:

![screen shot 2017-08-21 at 17 03 20](https://user-images.githubusercontent.com/810663/29528193-15408ae0-8693-11e7-8410-0849f4e5f2bd.png)
