### ISSUE TITLE
Add plt.savefig to "Using cartopy with matplotlib"?

### ISSUE THREAD

**Issue by jypeter** [SciTools/cartopy#922]
The [Using cartopy with matplotlib ](http://scitools.org.uk/cartopy/docs/latest/matplotlib/intro.html) page provides nice examples on how to _display_ maps, but not how to **save** them

This may seem easy to most users, but it's not the case for beginning matplotlib users, or even casual users like me. Would it be possible to add, at least to the first example of the intro page, something like
```
# Save the plot by calling plt.savefig BEFORE plt.show()
plt.savefig('coastlines.pdf')
plt.savefig('coastlines.png')

plt.show()
```
And you could also add a link to http://scitools.org.uk/iris/docs/v1.9.1/userguide/plotting_a_cube.html#saving-a-plot in the _iris_ section. I found this iris link with Google, but nothing similar in the cartopy section

**Comment by pelson** [comment]
Seems sensible. Not keen to document other packages, but a sensible sentence that links to the appropriate matplotlib documentation would be helpful, I agree.

**Comment by jypeter** [comment]
@pelson I won't have time to contribute, unfortunately, and I don't use cartopy enough (yet?)

Best thing I can do is create issues to report the problems or missing things when I see them. I figure if it's a problem for me, it might be for others

**Comment by corinnebosley** [comment]
@jypeter I am not really sure what you mean when you suggest adding a link (http://scitools.org.uk/iris/docs/v1.9.1/userguide/plotting_a_cube.html#saving-a-plot) to the iris section.

What link do you mean, and to what section are you suggesting it needs adding?

**Comment by jypeter** [comment]
It's just that in iris, you have a [6.1.2. Saving a plot](http://scitools.org.uk/iris/docs/v1.9.1/userguide/plotting_a_cube.html#saving-a-plot) section that can be useful for cartopy users who are not familiar with matplotlib (and iris). So you can either replicate this iris section in cartopy, or link to it from cartopy

Actually, the whole [6.1. Matplotlib’s pyplot basics](http://scitools.org.uk/iris/docs/v1.9.1/userguide/plotting_a_cube.html#matplotlib-s-pyplot-basics) is useful!

6.1.2 does not mention that `plt.savefig` needs to be called before `plt.show`, but I'm not 100% sure about that. I confess I'm still not comfortable with the whole _interactive/non-interactive/offline+backends_ business of matplotlib :/
