### ISSUE TITLE
can I update webpage docs for gallery?

### ISSUE THREAD

**Issue by raybellwaves** [SciTools/cartopy#925]
Is there a file which contains the input for the webpage example docs? Is it these? 
https://github.com/SciTools/cartopy/tree/master/lib/cartopy/examples
I would like to suggest some edits.

I was following the example of http://scitools.org.uk/cartopy/docs/v0.15/examples/barbs.html and plotting my own domain. I then realized that cartopy was producing an map outside of the area I was requesting. I was scratching my head for a while and was going to see if this had been answered on stackoverflow. I then realized I had asked this question on April 18th and it was answered by @ajdawson ... (https://stackoverflow.com/questions/43470238/cartopy-set-extent-extending-requested-boundary) I forget to add the `crs=ccrs.PlateCarree()` with `set_extent`. As ajdawson says it's good practice to add `crs=ccrs.PlateCarree()` with `set_extent`. 

I would be happy to add `crs=ccrs.PlateCarree()` to `set_extent` for the cases in http://scitools.org.uk/cartopy/docs/v0.15/gallery.html so it doesn't catch me out (again) or other users. Whilst the examples work as they are the `crs=` input makes it easy to edit the examples for other purposes.

**Comment by ajdawson** [comment]
Yes that is the right place, and yes please go ahead and fix them! That would be a very useful action.

**Comment by pelson** [comment]
Also xrefing this with #645, which would change the default projection for this kind of method.

**Comment by corinnebosley** [comment]
https://github.com/SciTools/cartopy/pull/927
