### ISSUE TITLE
Accidental weird error: ValueError: RGBA values should be within 0-1 range

### ISSUE THREAD

**Issue by secsilm** [SciTools/cartopy#932]
### Bug report

**Bug summary**

I use matplotlib and cartopy to plot a map with animation. But the result is unstable. While Sometimes it's fine, sometimes it's broken.

**Code for reproduction**

```python
#-*-coding:utf-8-*-
from matplotlib.patches import Circle
import matplotlib.pyplot as plt
import xlrd
from matplotlib.animation import FuncAnimation
import matplotlib.ticker as mticker
import cartopy.crs as ccrs
from cartopy.mpl.gridliner import LONGITUDE_FORMATTER, LATITUDE_FORMATTER
import time

fig=plt.figure()
ax = plt.axes(projection=ccrs.PlateCarree())
ax.coastlines()
gl = ax.gridlines(crs=ccrs.PlateCarree(), draw_labels=True,
                  linewidth=2, color='gray', alpha=15, linestyle='--')
gl.xlabels_top = False
gl.ylabels_left = False
gl.xlines = False
gl.xlocator = mticker.FixedLocator([-180, -45, 0, 45, 180])
gl.xformatter = LONGITUDE_FORMATTER
gl.yformatter = LATITUDE_FORMATTER
gl.xlabel_style = {'size': 15, 'color': 'gray'}
gl.xlabel_style = {'color': 'red', 'weight': 'bold'}

start = time.time()
lats  = []
lons  = []
data=xlrd.open_workbook("D:\ChromeDownload\sd.xlsx")
table=data.sheets()[0]
ncols=table.ncols
nrows=table.nrows
for i in range(nrows):
    cir1=Circle(xy=(float(table.col(0)[i].value),float(table.col(1)[i].value)),radius=2,alpha=0.5,transform=ccrs.PlateCarree())
    lons.append(cir1)
    ax.add_artist(lons[i])


def update(framedata):
    if time.time() - start < 8:
        for i in range(nrows):
            lons[i].radius+=1
            if lons[i].radius==15:
                lons[i].radius=2
        return lons
    else:
        for i in range(nrows):
            lons[i].radius = 0
        return lons


animation = FuncAnimation(fig, update, interval=50)
plt.show()
```

This  is the file using in code: `sd.xlsx` .

[sd.xlsx](https://github.com/matplotlib/matplotlib/files/1305140/sd.xlsx)

**Actual outcome**

```
Traceback (most recent call last):
  File "C:\Users\secsi\Anaconda3\lib\site-packages\matplotlib\backends\backend_qt5agg.py", line 197, in __draw_idle_agg
    FigureCanvasAgg.draw(self)
  File "C:\Users\secsi\Anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py", line 464, in draw
    self.figure.draw(self.renderer)
  File "C:\Users\secsi\Anaconda3\lib\site-packages\matplotlib\artist.py", line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "C:\Users\secsi\Anaconda3\lib\site-packages\matplotlib\figure.py", line 1143, in draw
    renderer, self, dsu, self.suppressComposite)
  File "C:\Users\secsi\Anaconda3\lib\site-packages\matplotlib\image.py", line 139, in _draw_list_compositing_images
    a.draw(renderer)
  File "C:\Users\secsi\Anaconda3\lib\site-packages\matplotlib\artist.py", line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "C:\Users\secsi\Anaconda3\lib\site-packages\cartopy\mpl\geoaxes.py", line 356, in draw
    gl._draw_gridliner(background_patch=self.background_patch)
  File "C:\Users\secsi\Anaconda3\lib\site-packages\cartopy\mpl\gridliner.py", line 344, in _draw_gridliner
    y_lc = mcollections.LineCollection(lines, **collection_kwargs)
  File "C:\Users\secsi\Anaconda3\lib\site-packages\matplotlib\collections.py", line 1208, in __init__
    **kwargs)
  File "C:\Users\secsi\Anaconda3\lib\site-packages\matplotlib\collections.py", line 162, in __init__
    self.update(kwargs)
  File "C:\Users\secsi\Anaconda3\lib\site-packages\matplotlib\artist.py", line 885, in update
    for k, v in props.items()]
  File "C:\Users\secsi\Anaconda3\lib\site-packages\matplotlib\artist.py", line 885, in <listcomp>
    for k, v in props.items()]
  File "C:\Users\secsi\Anaconda3\lib\site-packages\matplotlib\artist.py", line 879, in _update_property
    return func(v)
  File "C:\Users\secsi\Anaconda3\lib\site-packages\matplotlib\collections.py", line 749, in set_alpha
    self._set_edgecolor(self._original_edgecolor)
  File "C:\Users\secsi\Anaconda3\lib\site-packages\matplotlib\collections.py", line 712, in _set_edgecolor
    self._edgecolors = mcolors.to_rgba_array(c, self._alpha)
  File "C:\Users\secsi\Anaconda3\lib\site-packages\matplotlib\colors.py", line 232, in to_rgba_array
    raise ValueError("RGBA values should be within 0-1 range")
ValueError: RGBA values should be within 0-1 range
```

**Expected outcome**

![Expected outcome](https://user-images.githubusercontent.com/8894643/30464033-b678f330-9a01-11e7-821b-96ecb1f4d5f1.gif)

**Version**

  * Operating System: `Windows 10`
  * Matplotlib Version: `2.0.0`
  * Python Version: `Python 3.5.2 :: Anaconda custom (64-bit)`
  * Cartopy Version: `0.15.1`

**Comment by LukeC92** [comment]
Hi secslim
I've looked into this and removing the "alpha" keyword from your gridlines seems to make the plot run perfectly every single time (or at least it looks identical to your example image). This seems to be an incompatibility issue with the current matplotlib. I'm going to look into why this error occurs but for now would removing the alpha keyword be an acceptable workaround?

**Comment by ajdawson** [comment]
Should alpha values be between 0 and 1? Would changing to `alpha=0.15` do the right thing?

**Comment by dopplershift** [comment]
Alpha *should* be between 0 and 1...which is what the error is telling us. How did I not notice that before?

Curious that it only *sometimes* causes an error...

**Comment by secsilm** [comment]
Yes, changing `alpha` to be between 0 and 1 worked. But still don't know why it is accidental.

**Comment by LukeC92** [comment]
This is an interesting problem @secsilm . If anyone is wants in exploring it further the error can be replicated using these 6 lines of code:

`import matplotlib.pyplot as plt`
`import cartopy.crs as ccrs`
`fig=plt.figure()`
`ax = plt.axes(projection=ccrs.PlateCarree())`
`gl = ax.gridlines(alpha=15)`
`plt.show()`

Half of the times when the excerpt above is run it will produce a plot of the gridlines. However all the other times it is run it will produce the same errors that secslim encountered.

It is worth noting that even though `alpha=15` is meaningless matplotlib is able to accept that value (it just treats it as `alpha=1`). This can be seen in the following code examples.

`import matplotlib.pyplot as plt`
`fig=plt.figure()`
`plt.plot([1,2,3,4], alpha=15)`
`plt.show()`

and

`import matplotlib.pyplot as plt`
`from matplotlib.lines import Line2D`
`fig = plt.figure()`
`ax = fig.add_subplot(111)`
`x = [0,0.92]`
`y= [0,0.85]`
`line = Line2D(x, y, alpha=15)`
`ax.add_line(line)`
`plt.show()`

The commenters above have already explained that this issue can be entirely avoided by using an appropriate alpha value. However, it could be useful to know why this error only occurs some of the time.

**Comment by QuLogic** [comment]
Well, I tried this by running @LukeC92's code 10 times with 0.16.0 and with `master`, and it never worked.

So I don't see any point in keeping this open.

**Comment by ianjoyce** [comment]
I had the same error.  the label values I was using to color the data were cast as a string for some reason. using '  labels.astype(int) ' corrected the error
