### ISSUE TITLE
A very weird mismatch file of cartopy package in conda-forge

### ISSUE THREAD

**Issue by gepcel** [SciTools/cartopy#937]
Inside the cartopy package at conda-forge [https://anaconda.org/conda-forge/cartopy/0.15.1/download/win-64/cartopy-0.15.1-py36_4.tar.bz2](),
There is  a `Line 111`  in file `Lib/site-packages/cartopy/mpl/feature_artist.py`  :
```python
100        self.set_zorder(1)
111  self._kwargs.setdefault('linewidth', 1.0)
113  self._feature = feature
```
But `Line 111` is not in the [master repository](https://github.com/SciTools/cartopy/blob/master/lib/cartopy/mpl/feature_artist.py#L110:L113), and the `feature_artist.py` was last modified 2 years ago. I couldn't even find the commit that delete or add this line.

Not quite understand the conda-forge mechanism, so file an issue here, hoping someone might take a look at that.

**Comment by ajdawson** [comment]
It is a patch applied by conda-forge during the production of the package, see: https://github.com/conda-forge/cartopy-feedstock/blob/master/recipe/matplotlib2.patch

**Comment by gepcel** [comment]
Oh, but that line will make cartopy ignore the `linewidth=0.5` arg in `ax.add_geometries(..., linewidth=0.5`, and make the `linewidth` always be `1.0`.

```python
%matplotlib inline
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
from cartopy.io.shapereader import Reader
import cartopy.io.shapereader as shpreader

shpfilename = shpreader.natural_earth(resolution='110m',
                                      category='cultural',
                                      name='admin_0_countries')
shp = Reader(shpfilename)
fig, [ax1, ax2] = plt.subplots(1, 2, figsize=(8,3),
                               subplot_kw={'projection': ccrs.PlateCarree()})
ax1.add_geometries(shp.geometries(), crs=ccrs.PlateCarree(),
                 linewidth=0.1, edgecolor='k')
ax1.set(title='linewidth = 0.1')
ax2.add_geometries(shp.geometries(), crs=ccrs.PlateCarree(),
                 linewidth=10, edgecolor='k')
ax2.set(title='linewidth = 10')
plt.tight_layout()
plt.show()
```
The result is:
![linewidth](https://user-images.githubusercontent.com/4179106/31042775-4cd2457a-a5e2-11e7-9c2b-f7724b46ef87.png)

As the line of code, I don't quite understand, because it seems to only to set linewidth to 1.0 if linewidth is not specified. Not sure what's wrong. Removing this line works as expected, got the following result:
![linewidth2](https://user-images.githubusercontent.com/4179106/31042810-c49d4e92-a5e2-11e7-9e6f-7d1225c77732.png)

**Comment by ajdawson** [comment]
I suggest raising an issue on the [conda-forge/cartopy-feedstock](https://github.com/conda-forge/cartopy-feedstock) respository.

**Comment by pelson** [comment]
Thanks for finding, reporting and fixing this.
