### ISSUE TITLE
Google authentification with API key

### ISSUE THREAD

**Issue by ThomasMannschott** [SciTools/cartopy#938]
Hi,

Is there a way to add a Google API authentification key to cartopy in order to get GoogleTiles without a limit restriction?

Best,
Thomas

**Comment by pelson** [comment]
Nothing explicitly. You can configure the tiler to inject your API key into the URL:

https://github.com/SciTools/cartopy/blob/master/lib/cartopy/io/img_tiles.py#L49

In pseudo-code:

```
tiler = cartopy.io.img_tiles.GoogleTiles()
tiler.url += '&API=<my_key>'
ax.add_image(tiler)
```

Please follow-up with success / further issues.

Thanks!
