### ISSUE TITLE
Getting "L" shaped ticklabels when using cartopy + AxesGrid

### ISSUE THREAD

**Issue by spencerahill** [SciTools/cartopy#939]
I am attempting to modify the ticklabels of Axes that use cartopy + AxesGrid, following the example shown in the cartopy docs [here](http://scitools.org.uk/cartopy/docs/v0.15/examples/axes_grid_basic.html).  But unlike the example, I only want ticklabels in an "L" shape, i.e. vertical ticklabels on the leftmost column and horizontal ticklabels on the bottom row.  

I can't manage to accomplish this.  When I edit the horizontal ticklabels of any ax, the horizontal ticklabels of all axes in that column get changed with it.  And likewise for vertical ticklabels and all axes in that row.  (This is true w/ AxesGrid with or without cartopy, but in the latter case I can just set `label_mode='L'` and not have to bother with changing them manually.)

I created a MWE in this [gist](https://gist.github.com/anonymous/968c0dc2a400dc838446731b2661c1a5).  I'm pretty new to both cartopy and AxesGrid, so apologies in advance if I'm missing something obvious.  Thanks!

**Comment by spencerahill** [comment]
Following up on this.  Any help would be extremely useful, so thanks in advance.

**Comment by spencerkclark** [comment]
@spencerahill I recently stumbled upon a workaround for this.  I too would be in support of it being possible to use `label_mode='L'` with `cartopy` and `AxesGrid`; what's in [this gist](https://gist.github.com/spencerkclark/16302dfde457df4c1be2b1b28ac953bc) though should work in the meantime.

**Comment by spencerahill** [comment]
Thanks @spencerkclark!  That's super helpful.

**Comment by pelson** [comment]
Thanks for the detail in your question, and the MWE. It looks like you have a workaround thanks to @spencerkclark. Before we go too far down that path, I should point out my hesitation to build upon axesgrid within cartopy, as highlighted in https://github.com/SciTools/cartopy/pull/909#issuecomment-319284352.

If there is anything that cartopy is doing to actively prohibit axesgrid interoperability I'm supportive of removing that barrier, but in general I'm not in favour of building cartopy on top of the axesgrid functionality.

In the interests of the effectiveness of the cartopy issue tracker, as well as making it easier for users  to find solutions to questions in Google, Q&A is generally best done with StackOverflow.

@spencerahill - would you be willing to convert this issue into a StackOverflow question (and perhaps add an answer based on @spencerkclark's suggestion?). I'm reluctant to move you around like this, but given there are (now at least 2!) users of cartopy with axesgrid, it makes sense to start building a public body of knowledge on StackOverflow for it.

Thanks in advance!

**Comment by spencerahill** [comment]
@pelson thanks for your input.  I understand your reticence -- I am learning for myself that AxesGrid is quite rickety.  

No problem re: StackOverflow: https://stackoverflow.com/questions/48088669/how-to-get-l-shaped-ticklabels-when-using-cartopy-and-axesgrid

Feel free to close this.
