### ISSUE TITLE
Missing contour values remain even after adding cyclic, but only for some fields

### ISSUE THREAD

**Issue by spencerahill** [SciTools/cartopy#940]
I'm using `add_cyclic_point` for contour/contourf plots of data spanning the equator.  In the attached figure, notice that some -- but not all -- of the panels have missing ~~equatorial~~ longitude=0/360 values.  But I have in fact called `add_cyclic_lon` on all of them; the repr of the resulting lon array is `[-179.5 -178.5 -177.5 ...,  178.5  179.5  180.5]`.  They also were all interpolated to an identical lat-lon grid prior to calling `add_cyclic_lon`.  I have tried adding a cyclic point to the left instead of the right, adding multiple cyclic points to the right, adding cyclic points to both ends, but none of those have fixed the problem.  

Interestingly, the only two panels that "work" after adding the cyclic longitude -- namely panels (b) and (e) -- are from models who were already at high resolution, i.e. close to the 1x1 degree to which all were interpolated.  The others are on coarser grids, mostly 2x2.5 degrees.  Also, I have found that interpolating to a coarser grid, e.g. 5x5 degrees, causes the behavior to go away in some -- but not all -- of the cases.  So I wonder if it's the nature of the data after it has been interpolated that is somehow to blame, although frankly it's not clear to me why that would be.

Hopefully this image can suffice to start troubleshooting; I suspect it could be difficult to generate a proper MWE.  Thanks!

![cyclic_bug](https://user-images.githubusercontent.com/6200806/31925040-5b8ae018-b875-11e7-8a12-95d21ca9bcd1.png)

**Comment by ajdawson** [comment]
Did you try not adding any cyclic point at all?

**Comment by spencerahill** [comment]
Yes, should have mentioned that.  That was my first attempt.  Wouldn't have bothered adding a cyclic at all if they worked without.

Also, note that my use of "equatorial" in the original title and description were a mistake.  I meant the prime meridian values, i.e. where longitude=0.  The gap occurs at all latitudes along the prime meridian.

**Comment by spencerahill** [comment]
Extremely sorry, upon further inspection the bug was in the regridding step, not the plotting.  Specifically, I needed to shift my longitudes from [0, 360] to [-180, 180].
