### ISSUE TITLE
import cartopy results in "ImportError: No module named 'shapefile'"

### ISSUE THREAD

**Issue by Timothy-W-Hilton** [SciTools/cartopy#941]
I installed cartopy in a freshly created conda environment for python 3.6:

`conda install -c condo-forge cartopy`

The installation seemed successful, but when I try to import cartopy I get:

```
Python 3.6.1 |Anaconda 4.4.0 (64-bit)| (default, May 11 2017, 13:09:58)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cartopy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/global/homes/t/twhilton/.conda/envs/Tim_py36/lib/python3.6/site-packages/cartopy/__init__.py", line 111, in <module>
    import cartopy.feature
  File "/global/homes/t/twhilton/.conda/envs/Tim_py36/lib/python3.6/site-packages/cartopy/feature.py", line 32, in <module>
    import cartopy.io.shapereader as shapereader
  File "/global/homes/t/twhilton/.conda/envs/Tim_py36/lib/python3.6/site-packages/cartopy/io/shapereader.py", line 52, in <module>
    import shapefile
ModuleNotFoundError: No module named 'shapefile'
```

This seems similar to #610.

**Comment by dopplershift** [comment]
Hmmm....I don't have any such problems with a fresh environment on Mac. Can you open an issue on the conda-forge feedstock for cartopy: https://github.com/conda-forge/cartopy-feedstock ?

Go ahead an include the output of `conda list`. I don't think it's a problem with CartoPy itself, but with the conda package.

**Comment by Timothy-W-Hilton** [comment]
Thanks for having a look.  Speaking with my sys admin I learned that there is an updated conda available on the system.  Using the updated conda this goes away.  For what it's worth, I get the above error using conda 4.1.11. conda 4.3.27 installs and imports cartopy successfully.

**Comment by guytcc** [comment]
I can second that I had to update my conda version (to 4.3.33 in this case), nuke my old environment and recreate. It now works.
