### ISSUE TITLE
Installation failed with conda-forge

### ISSUE THREAD

**Issue by ruggerod** [SciTools/cartopy#943]
Tried to install cartopy on a Mac (OS Sierra 10.12.6) with

`conda install -c conda-forge cartopy`

In python, I get this error when I try to` import cartopy `

OSError: Could not find lib geos_c or load any of its variants ['/Library/Frameworks/GEOS.framework/Versions/Current/GEOS', '/opt/local/lib/libgeos_c.dylib'].

**Comment by dkillick** [comment]
@AlexHilson were you also getting this error?

**Comment by AlexHilson** [comment]
This isn't the error we discussed (that was about compiling PyKE rules iirc). I've seen this error before, I believe it can be solved by installing geos (e.g. ```brew install geos```).

**Comment by dkillick** [comment]
Thanks @AlexHilson. 

As geos is a dependency of shapely, which is a dependency of cartopy, it should be installed automatically as part of the dependency resolution step, which suggests the install is not working correctly.

@ruggerod I just tried installing cartopy on MacOS 10.12.6 and it worked fine for me. Could you try updating your conda (with `conda update --all`) and then installing cartopy into its own env; that is, by running the following commands in the terminal:

```
conda create -n cartopy-test python
source activate cartopy-test
conda install -c conda-forge cartopy
```

I just ran exactly these commands and cartopy imports fine for me.

**Comment by ruggerod** [comment]
Thanks @dkillick and everyone, 

A `conda update --all` worked just fine. 
The following packages have been SUPERSEDED by a higher-priority channel:

    conda-env:          2.6.0-0               conda-forge --> 2.6.0-h36134e3_0      
    pyproj:             1.9.5.1-py27_0        conda-forge --> 1.9.5.1-py27_0        
    shapely:            1.6.1-py27_1          conda-forge --> 1.5.16-py27_0

After that, I was able to import cartopy.

**Comment by dkillick** [comment]
@ruggerod great news! Glad it's working again now :+1:
