### ISSUE TITLE
Display all 60 zones of UTM projection in projection list

### ISSUE THREAD

**Issue by kaedonkers** [SciTools/cartopy#986]
PR #954 adds an example of how to display all 60 zones from the UTM projection.

It would be good to add this to the docs in the Projection List as well as the Gallery.

**Comment by pelson** [comment]
#954 was merged.

**Comment by kaedonkers** [comment]
#954 only added an example to `lib/cartopy/examples/lines_and_polygons` (which in turn should be displayed in the Gallery).

This issue is requesting that all 60 UTM zone also be displayed in the Projection List of the documentation, rather than just the single projection which is currently displayed.

In order to achieve this changes must be made to `docs/make_projection.py`.

**Comment by pelson** [comment]
Right you are. 😄

**Comment by kannes** [comment]
Mind the silly https://en.wikipedia.org/wiki/Universal_Transverse_Mercator_coordinate_system#Exceptions !

**Comment by kaedonkers** [comment]
This issue was addressed by PR #1103, so can be closed.
