### ISSUE TITLE
Remove pcolormesh patched?

### ISSUE THREAD

**Issue by corinnebosley** [SciTools/cartopy#992]
This is what the docstring for `cartopy.mpl.geoaxes.GeoAxes._pcolormesh_patched` says:

```
A temporary, modified duplicate of
:func:`~matplotlib.pyplot.pcolormesh'.

This function contains a workaround for a Matplotlib issue
and will be removed once the issue has been resolved.
https://github.com/matplotlib/matplotlib/pull/1314
```

That link says that the PR was merged 5 years ago.  Surely we can take this out now?

**Comment by pelson** [comment]
Unfortunately it has moved on since then. I don't think we will ever be able to reconcile the two...

See also: https://github.com/SciTools/cartopy/blob/master/lib/cartopy/mpl/geoaxes.py#L1462-L1480

Perhaps we should just remove the comment.
