### ISSUE TITLE
import cartopy.crs error

### ISSUE THREAD

**Issue by raybellwaves** [SciTools/cartopy#997]
I don't suppose somebody would be kind enough to try a fresh installation of cartopy on their mac? (perhaps with version control in case you also have trouble re-installing it)

I got myself in a pickle trying to install `rasterio` using `brew` and `pip` and it fudged up my cartopy installation. Unfortunately, my cartopy installation no longer works. I documented the error on SO https://stackoverflow.com/questions/48139742/cartopy-import-cartopy-crs-error and it's most likely at my end. However, I wanted to double check that it has nothing to do with a recent cartopy/conda installation method. 

Perhaps you could try
`conda remove cartopy geos shapely pyshp proj4 gdal`
`conda install -c conda-forge cartopy`

If this works with no issues then you can go ahead and close this.

**Comment by pelson** [comment]
Thanks for documenting this on StackOverflow @raybellwaves. Glad you found a solution.
